### ISSUE TITLE
可以使用自己的数据微调吗

### ISSUE THREAD

**Issue by Malestudents** [THUDM/ChatGLM-6B#10]

**Comment by yaleimeng** [comment]
是否可参考 #3   ？

**Comment by chenyiwan** [comment]
可以的吧，我也是参考别人修改的微调，做了一个，把数据放进去，处理成要的格式不就行了吗？

https://github.com/chenyiwan/chatglm-6b-fine-tuning

**Comment by duzx16** [comment]
已经实现了基于量化和ptuning的微调https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning，最低只需要7GB显存

**Comment by EasyLuck** [comment]
这个对于数据集中数据长度有要求吗

**Comment by EasyLuck** [comment]
> 可以的吧，我也是参考别人修改的微调，做了一个，把数据放进去，处理成要的格式不就行了吗？
> 
> https://github.com/chenyiwan/chatglm-6b-fine-tuning

这个对于数据集中数据长度有要求吗
