### ISSUE TITLE
[BUG/Help] 请问会开源论文嘛？

### ISSUE THREAD

**Issue by hijkzzz** [THUDM/ChatGLM-6B#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

好奇 SFT 和 RLHF 的数据怎样收集到的
个人猜测是利用了 OpenAI ChatGPT 的输出对 GLM 做 SFT，试了好多问题 和 ChatGPT 的回答非常相似。
但 RLHF 这块不太能猜出来怎么做的，毕竟 rank 数据不容易拿到。

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Anything else?

N/A

**Comment by duzx16** [comment]
关于模型的技术细节不在本仓库的讨论范围内。相关的issue将会被关闭。

**Comment by zbLiuLiu** [comment]
开源论文可还行……
