### ISSUE TITLE
[BUG/Help] has no attribute 'ChatGLMForConditionalGeneration'

### ISSUE THREAD

**Issue by LYMDLUT** [THUDM/ChatGLM-6B#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/mnt/d/ChatGLM-6B/llam.py", line 3, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 148, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.THUDM.chatglm-6b.220f772e9a2d7a55701d9b49bf2efc618acc3b56.modeling_chatglm' has no attribute 'ChatGLMForConditionalGeneration'

### Expected Behavior

e

### Steps To Reproduce

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/mnt/d/ChatGLM-6B/llam.py", line 3, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/lym/miniconda3/envs/lab/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 148, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.THUDM.chatglm-6b.220f772e9a2d7a55701d9b49bf2efc618acc3b56.modeling_chatglm' has no attribute 'ChatGLMForConditionalGeneration'

### Environment

```markdown
- OS:ubuntu
- Python:3.8
- Transformers:4.26.1
- PyTorch:1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

no

**Comment by wujohns** [comment]
和你的问题类似，但是报错是：
module 'transformers_modules.THUDM.chatglm-6b.1b54948bb28de5258b55b893e193c3046a0b0484.tokenization_chatglm' has no attribute 'ChatGLMTokenizer'

**Comment by wujohns** [comment]
这个问题貌似和 hugging face transformers 的缓存机制有关，在后来采用了直接 git clone hugging face上对应的model仓库，放在本地工程的 model 目录中，然后采用如下的方法实现 tokenizer 和 model 的初始化：
```py
tokenizer = AutoTokenizer.from_pretrained(
    # "THUDM/chatglm-6b",
    pretrained_model_name_or_path=getAbsPath('./models/chatglm-6b-int4/'),
    trust_remote_code=True
)
model = AutoModel.from_pretrained(
    # "THUDM/chatglm-6b",
    pretrained_model_name_or_path=getAbsPath('./models/chatglm-6b-int4/'),
    trust_remote_code=True
).half().cuda()
```

**Comment by SWHL** [comment]
I have met the same problem.

**Comment by OneiroXL** [comment]
删除 ~/.cache/huggingface 这个文件夹即可解决这个问题

Deleting the folder  ‘~/.cache/huggingface’ can solve this problem

**Comment by hongge831** [comment]
请问这个问题解决了吗？@OneiroXL 删掉还是会自动创建

**Comment by hongge831** [comment]
> Any solutions? My error is "AttributeError: module 'transformers_modules.local.tokenization_chatglm' has no attribute 'ChatGLMTokenizer'"

请问这个问题解决了吗？ 我也遇到相同的问题

**Comment by SWHL** [comment]
我这里解决了，猜测是代码bug，解决方案给大家参考。
1. 首先确定一下训练后的目录中下面列的文件是否有内容：（以我自己的为例）
   ```text
   output/adgen-chatglm-6b-pt-8-1e-2/checkpoint-7000
   ├── configuration_chatglm.py
   ├── modeling_chatglm.py
   ├── quantization.py
   └──tokenization_chatglm.py
   ```
     - 我这里保存的文件内容都是空的，遇到这个问题的小伙伴，估计也都是空的。
2. 将预训练中对应文件复制到里面即可。因为微调最多换了数据集，其他代码都是一样的。
   ```text
   chatglm-6b
   ├── configuration_chatglm.py
   ├── modeling_chatglm.py
   ├── quantization.py
   └──tokenization_chatglm.py
   ```
3. 重新推理即可。

希望可以帮助到大家。

**Comment by eziohzy** [comment]
> 我这里解决了，猜测是代码bug，解决方案给大家参考。
> 
> 1. 首先确定一下训练后的目录中下面列的文件是否有内容：（以我自己的为例）
>    ```
>    output/adgen-chatglm-6b-pt-8-1e-2/checkpoint-7000
>    ├── configuration_chatglm.py
>    ├── modeling_chatglm.py
>    ├── quantization.py
>    └──tokenization_chatglm.py
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    * 我这里保存的文件内容都是空的，遇到这个问题的小伙伴，估计也都是空的。
> 2. 将预训练中对应文件复制到里面即可。因为微调最多换了数据集，其他代码都是一样的。
>    ```
>    chatglm-6b
>    ├── configuration_chatglm.py
>    ├── modeling_chatglm.py
>    ├── quantization.py
>    └──tokenization_chatglm.py
>    ```
> 3. 重新推理即可。
> 
> 希望可以帮助到大家。

你意思是把这些个文件拷贝到output里面去？  感觉这操作应该没用呀

**Comment by SWHL** [comment]
试试就知道了

**Comment by eziohzy** [comment]
> 试试就知道了

不行；
