### ISSUE TITLE
[BUG/Help] <title>No compiled kernel found

### ISSUE THREAD

**Issue by qihangf** [THUDM/ChatGLM-6B#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 8
Using quantization cache
Applying quantization to glm layers
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
START /usr/bin/chromium-browser "http://127.0.0.1:7860/"
[15356:15356:0515/173606.067595:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
xdg-open: no method available for opening 'http://127.0.0.1:7860/'

### Steps To Reproduce

在尝试int4版本时遇到的问题

### Environment

```markdown
- OS:centos
- Python:3.7
- Transformers:4.26.1
- PyTorch: 1.10.1
- CUDA Support True
```

**Comment by qihangf** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision. Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. No compiled kernel found. Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so Load kernel : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so Setting CPU quantization kernel threads to 8 Using quantization cache Applying quantization to glm layers Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. START /usr/bin/chromium-browser "http://127.0.0.1:7860/" [15356:15356:0515/173606.067595:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. xdg-open: no method available for opening 'http://127.0.0.1:7860/'
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> 在尝试int4版本时遇到的问题
> 
> ### Environment
> ```gfm
> - OS:centos
> - Python:3.7
> - Transformers:4.26.1
> - PyTorch: 1.10.1
> - CUDA Support True
> ```
> 
> ### Anything else?
> _No response_
已经解决了

**Comment by hiber-niu** [comment]
@qihangf 怎么解决的呢？

**Comment by nanqiaoshichuang** [comment]
> @qihangf 怎么解决的呢？

参考  https://github.com/THUDM/ChatGLM-6B#%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
