### ISSUE TITLE
[BUG/Help] ModuleNotFoundError: No module named 'transformers_modules.chatglm-6b-v1'

### ISSUE THREAD

**Issue by MaiziXiao** [THUDM/ChatGLM-6B#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

把最新的 v1.1 ChatGLM版本pull到本地后，用AutoModel.from_pretrained读取的时候报了ModuleNotFoundError: No module named 'transformers_modules.chatglm-6b-v1'这个错。
![image](https://github.com/THUDM/ChatGLM-6B/assets/24979986/4160dc04-a035-42ad-94ca-11dab6c22690)
![image](https://github.com/THUDM/ChatGLM-6B/assets/24979986/43be89d0-0913-41ac-ac4e-b560931caf37)

### Steps To Reproduce

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("models/chatglm-6b-v1.1",  trust_remote_code=True)
model = AutoModel.from_pretrained("models/chatglm-6b-v1.1", trust_remote_code=True).half().cuda()

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by wheatfox** [comment]
本地路径里是不是有类似"chatglm-6b-v1.1"这样的？本地路径的文件夹名称里不能有“.”

**Comment by MaiziXiao** [comment]
> 

是的。。感谢

**Comment by MaiziXiao** [comment]
> 本地路径里是不是有类似"chatglm-6b-v1.1"这样的？本地路径的文件夹名称里不能有“.”

是的。。。感谢

**Comment by 471417367** [comment]
> 本地路径里是不是有类似"chatglm-6b-v1.1"这样的？本地路径的文件夹名称里不能有“.”

tokenizer = AutoTokenizer.from_pretrained("my_model/chatglm2-6b", trust_remote_code=True)
ModuleNotFoundError: No module named 'transformers_modules.my_model/chatglm2-6b'

为什么我这样会报错呢。
