### ISSUE TITLE
[BUG/Help]有没有大佬帮我看看这个报错，在运行示例代码的时候报的错

### ISSUE THREAD

**Issue by ayisun1024** [THUDM/ChatGLM-6B#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

报错信息：
python3.8 chatglm.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.35it/s]
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "chatglm.py", line 5, in <module>
    response, history = model.chat(tokenizer, "Hello", history=[])
  File "/usr/local/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py", line 1285, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/usr/local/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_chatglm.py", line 463, in forward
    q1, k1 = apply_rotary_pos_emb_index(q1, k1, cos, sin, position_ids)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Error in dlopen for library libnvrtc.so.11.2and libnvrtc-d833c4f3.so.11.2

### Steps To Reproduce

chatglm.py的内容是：

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("/data/release/model", trust_remote_code=True)
model = AutoModel.from_pretrained("/data/release/model", trust_remote_code=True).half().cuda()
model = model.eval()
response, history = model.chat(tokenizer, "Hello", history=[])
print(response)

### Environment

```markdown
OS:Linux version 5.4.32-1-tlinux4-0001 (root@3c7067f9a859) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Tue Jul 21 14:24:37 CST 2020
Python:3.8
本机依赖包是：
pip3.8 list
Package                  Version
------------------------ ----------
accelerate               0.19.0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   5.0.0
anyio                    3.6.2
async-timeout            4.0.2
attrs                    23.1.0
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
contourpy                1.0.7
cpm-kernels              1.0.11
cycler                   0.11.0
fastapi                  0.95.1
ffmpy                    0.3.0
filelock                 3.12.0
fonttools                4.39.4
frozenlist               1.3.3
fsspec                   2023.5.0
gradio                   3.30.0
gradio_client            0.2.4
h11                      0.14.0
httpcore                 0.17.0
httpx                    0.24.0
huggingface-hub          0.14.1
idna                     3.4
importlib-metadata       6.6.0
importlib-resources      5.12.0
Jinja2                   3.1.2
jsonschema               4.17.3
kiwisolver               1.4.4
latex2mathml             3.75.2
linkify-it-py            2.0.2
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
mdit-py-plugins          0.3.3
mdtex2html               1.2.0
mdurl                    0.1.2
multidict                6.0.4
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
orjson                   3.8.12
packaging                23.1
pandas                   2.0.1
Pillow                   9.5.0
pip                      23.1.2
pkgutil_resolve_name     1.3.10
protobuf                 4.23.0
psutil                   5.9.5
pydantic                 1.10.7
pydub                    0.25.1
Pygments                 2.15.1
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2023.3
PyYAML                   6.0
regex                    2023.5.5
requests                 2.30.0
semantic-version         2.10.0
sentencepiece            0.1.99
setuptools               41.6.0
six                      1.16.0
sniffio                  1.3.0
starlette                0.26.1
tokenizers               0.13.3
toolz                    0.12.0
torch                    1.13.0
tqdm                     4.65.0
transformers             4.27.1
typing_extensions        4.5.0
tzdata                   2023.3
uc-micro-py              1.0.2
urllib3                  2.0.2
uvicorn                  0.22.0
websockets               11.0.3
wheel                    0.40.0
yarl                     1.9.2
zipp                     3.15.0
```

**Comment by ayisun1024** [comment]
已解决

**Comment by 2408576095** [comment]
> 已解决

您好,您是如何解决的

**Comment by sliontc** [comment]
怎么解决的？
