### ISSUE TITLE
[BUG/Help] 全量微调后推理速度相比chatglm慢了3倍左右

### ISSUE THREAD

**Issue by Sunxxlo** [THUDM/ChatGLM-6B#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好，用deepspeed全量微调后的checkpoint进行推理，速度比chatglm原始参数推理速度慢了3倍左右，decoding出来的长度相差不大，请问是什么原因呢？

### Steps To Reproduce

无

### Environment

```markdown
- OS:Ubuntu
- Python:3.11
- Transformers:4.29.1
- PyTorch:1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
Yes
```

**Comment by Sunxxlo** [comment]
已解决

**Comment by wuzixiaoer** [comment]
为什么呢？

**Comment by Macvh** [comment]
@Sunxxlo 你好，请问你是怎么解决这个问题的，我用deepspeed zero3全量微调后慢了好多
