### ISSUE TITLE
[BUG/Help]32核纯CPU推理时，只占用了一半CPU的核心数，有哪里可以设置参数么？

### ISSUE THREAD

**Issue by zdevc** [THUDM/ChatGLM-6B#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

32核纯CPU推理时，一直只占满了一半CPU的核心数，有哪里可以设置参数么？
![image](https://github.com/THUDM/ChatGLM-6B/assets/40593221/d76ac52c-080b-4ce9-a0ed-e113ae3fa54b)

### Expected Behavior

占更多核心数

### Steps To Reproduce

32核纯CPU推理，htop查看CPU占用情况

### Environment

```markdown
- OS:RHEL7.8
- Python:3.11.2
- Transformers:4.26.1
- PyTorch:1.12
- CUDA Support:False
```

**Comment by AolKleinZ** [comment]
同样的问题，32核只用了一半

**Comment by zdevc** [comment]
> 同样的问题，32核只用了一半

以下代码可以提高CPU占用
import os
import torch

cpu_num = 24 # 这里设置成你想运行的CPU个数
torch.set_num_threads(cpu_num)
os.environ ['OMP_NUM_THREADS'] = str(cpu_num)
os.environ ['MKL_NUM_THREADS'] = str(cpu_num)
os.environ ['OPENBLAS_NUM_THREADS'] = str(cpu_num)
os.environ ['VECLIB_MAXIMUM_THREADS'] = str(cpu_num)
os.environ ['NUMEXPR_NUM_THREADS'] = str(cpu_num)

实测效果最明显的是
- torch.set_num_threads(cpu_num)
