### ISSUE TITLE
[BUG/Help] <title>不懂就问，怎么更新模型版本

### ISSUE THREAD

**Issue by qihangf** [THUDM/ChatGLM-6B#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

只能重新clone吗

### Steps To Reproduce

同上

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by chenyiwan** [comment]
你下载下来不就完了。。

**Comment by 1praiseThesun** [comment]
> 你下载下来不就完了。。

那已经训练好的怎么整合进去呢？
