### ISSUE TITLE
[BUG/Help] 从自然语言中提取专业实体信息

### ISSUE THREAD

**Issue by wenChingzhou** [THUDM/ChatGLM-6B#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

比如从自然语言中：现舱： 上海——芝加哥120GP 5月29号HPL的船 5月25号截单（限重15吨） 上海-纽约 120GP6月2号HPL的船 上海-休斯顿 2*20GP6月7号HPL的船
提取出
[{"type": "求舱", "route": "?", "shippingCompany": "?", "fromPort": "上海", "targetPort": "纽约", "box": "GP", "cutoffTime": "?","其他字段"},{.......}]
使用ptuning微调效果不明显

### Steps To Reproduce

大佬们有解决思路吗

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by runzhi214** [comment]
浅见，我不认为这算自然语言。
这么规整的格式为什么不使用编程工具

**Comment by wenChingzhou** [comment]
> 

这只是个例子，实际输入会很不规范，需要解析的字段很多，用正则表达式提取只能满足50%左右

**Comment by ningchaoar** [comment]
prompt工程足矣，前提是语言模型足够强大。
参考https://github.com/yzfly/LangGPT随便改了一个
```
# Role: 实体提取员

## Profile
- Language: 中文
- Description: 可以提取文本中的关键信息和命名实体

## Rules
1. 定义以下实体类型: 
  a. shippingCompany
  b. fromPort: 出发地地名或城市名，例如"北京"
  c. targetPort: 目的地地名或城市名，例如"上海"
  d. box: 仓位等级
  e. cutoffTime: 截止时间
2. 如果文本中存在以上实体，则进行抽取后返回json字符串
3. 如果文本只存在以上实体中的一部分，则只返回存在的实体
4. 如果文本中不存在以上实体，则返回"{}"

## Workflow
1. 用户以[输入]的形式给定输入文本
2. 针对用户给定的文本，根据<Rules>输出相应文本
3. 准备接收下一条文本

## Initialization
作为角色 <Role>, 严格遵守 <Rules>, 使用默认 <Language> 与用户对话，友好的欢迎用户。然后介绍自己，并告诉用户 <Workflow>。
```

chatgpt的输出：
![chatgpt-test](https://github.com/THUDM/ChatGLM-6B/assets/39253972/152bea4e-d3c4-4657-8063-942082c9123c)

**Comment by wenChingzhou** [comment]
> 

这种方式是可以的  但是有很多识别不了，需要喂语料，  语料应该是啥格式呢
