### ISSUE TITLE
[Help] <PTuning训练参数设置问题>

### ISSUE THREAD

**Issue by hongshuo-wang** [THUDM/ChatGLM-6B#1149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

文档原文如下：
在默认配置 quantization_bit=4、per_device_train_batch_size=1、gradient_accumulation_steps=16 下，INT4 的模型参数被冻结，一次训练迭代会以 1 的批处理大小进行 16 次累加的前后向传播，等效为 16 的总批处理大小，此时最低只需 6.7G 显存。若想在同等批处理大小下提升训练效率，可在二者乘积不变的情况下，加大 per_device_train_batch_size 的值，但也会带来更多的显存消耗，请根据实际情况酌情调整。

这里的二者乘积不变是指per_device_train_batch_size * gradient_accumulation_steps=16不变的意思吗，为什么需要保证乘积不变呢？

### Steps To Reproduce

ptuning微调参数

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by vs0533** [comment]
batch_size 是每次输入模型多少样本 这个值如果太大 会占用非常多的显存；accumulation_steps 是进行指定次数的匹数才进行前后传播（更新参数） 也就是相当于调高bachsize了 所以你将batchsize的值设置为1 累计16批次再进行更新参数 相当于设置了batchsize为16 但是显存没有直接设置batchsize高了

**Comment by hongshuo-wang** [comment]
> batch_size 是每次输入模型多少样本 这个值如果太大 会占用非常多的显存；accumulation_steps 是进行指定次数的匹数才进行前后传播（更新参数） 也就是相当于调高bachsize了 所以你将batchsize的值设置为1 累计16批次再进行更新参数 相当于设置了batchsize为16 但是显存没有直接设置batchsize高了

那是否accumulation_steps越高越好？还是说这个16是官方调试出来的较优解

**Comment by vs0533** [comment]
梯度累积就是一种方法可以减少显存 你调高这个参数应该会导致显存有所上升 但比调高batchsize要省，你可以跑一下试试，超参设置都比较玄学 还是得式

**Comment by hongshuo-wang** [comment]
> 梯度累积就是一种方法可以减少显存 你调高这个参数应该会导致显存有所上升 但比调高batchsize要省，你可以跑一下试试，超参设置都比较玄学 还是得式

谢谢
