### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by wanglaichao** [THUDM/ChatGLM-6B#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

执行脚本：
path="/data1/ChatGLM-6B/ptuning/output_chat_nofb16/adgen-chatglm-6b-pt-128-1e-2/checkpoint-1000"
tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
model = AutoModel.from_pretrained(path, trust_remote_code=True)
model = model.half().cuda()
model = model.eval()
while True:
        qs = input("请输入你的问题。\n")
        if qs:
             response, history = model.chat(tokenizer, qs, [],  temperature=0.1)
             print(response)

 错误如下：
 Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data1/ChatGLM-6B/ptuning/output_chat_nofb16/adgen-chatglm-6b-pt-128-1e-2/checkpoint-1000 and are newly initialized: ['transformer.layers.23.mlp.dense_h_to_4h.weight', 'transformer.layers.18.attention.query_key_value.bias', 'transformer.layers.10.post_attention_layernorm.weight', 'transformer.layers.26.pos。。。
 1
请输入你的问题。
The dtype of attention mask (torch.int64) is not bool
nTraceback (most recent call last):
  File "/data1/ChatGLM-6B/ptuning/run_ptuning_brand.py", line 28, in <module>
    response, history = model.chat(tokenizer, qs, [],  temperature=0.1)
  File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tuangouadmin/.cache/huggingface/modules/transformers_modules/checkpoint-1000/modeling_chatglm.py", line 1285, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/transformers/generation/utils.py", line 2504, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### Steps To Reproduce

我们用的chatglm-6b测试的微调ptuning测试数据就是Git主业提供的数据，下面是链接
https://cloud.tsinghua.edu.cn/f/b3f119a008264b1cabd1/?dl=1
运行脚本也是官网提供的命令如下：
PRE_SEQ_LEN=128
LR=2e-2

CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/dev.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm-6b \
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4
环境是单卡 A100 torch==2.0.1 Python==Python 3.10.9

### Environment

```markdown
- OS: Linux ecs-e128 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Python:3.10.9
- Transformers:4.27.1
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :TURE
```

**Comment by duzx16** [comment]
使用p-tuning微调的模型部署请参考 https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2

**Comment by wanglaichao** [comment]
> 使用p-tuning微调的模型部署请参考 https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2

就是按照Git上的数据微调的，出错了，但是用之前的版本chatglm微调可以成功。

**Comment by king21guns** [comment]
+1 我也遇到这个问题了；不是ptuing，是全量参数finetune

**Comment by whsqjss** [comment]
+1

**Comment by wanglaichao** [comment]
> 我们用的chatglm-6b测试的微调ptuning测试数据就是Git主业提供的数据，下面是链接

太应付了，不知为不知
