### ISSUE TITLE
[BUG/Help] OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by kyangconn** [THUDM/ChatGLM-6B#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

这个在我等待下载完之后就会报错，但报错信息因为它把Windows的\.cache路径认成了/.cache。完整报错如图，我并不知道该如何解决这个斜杠问题。还是说这个是必要在linux中运行？
![1](https://user-images.githubusercontent.com/104826731/225793224-e32d1a56-40ca-4c85-99d5-8cdedc346d99.jpg)

### Steps To Reproduce

1.下载仓库。
2.pip install -r requirements.txt.
3.pip install gradio.
4.python web_demo.py.
5.等待web_demo.py把所有模型下载至默认位置。
6.报错。

### Environment

```markdown
- OS: Windows 10 22H2
- Python:3.10.9
- Transformers: 4.26.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by brad999** [comment]
I had this issue as well. I believe this happens when one of the shards doesn't download properly. Delete the .bin file listed in the error message and then rerun web_demo.py. It should redownload and start successfully.

**Comment by kyangconn** [comment]
It seems really related to the download, it work well after download again completely.
