### ISSUE TITLE
实体提取任务做微调，语料应该用啥格式呢

### ISSUE THREAD

**Issue by wenChingzhou** [THUDM/ChatGLM-6B#1188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

6.2 青岛-- 伊斯坦布尔 40HQ 现舱有意来询
提取 (起始港,目标港,离港时间,箱型大小)类型的实体，仅输出JSON格式

### Expected Behavior

{
"起始港": "青岛",
"目标港": "伊斯坦布尔",
"离港时间": "6.2",
"箱型大小": "40HQ"
}

语料应该用啥格式呢 该咋微调呢
### Steps To Reproduce

/

### Environment

```markdown
/
```

**Comment by chenyiwan** [comment]
我感觉就跟问答格式一样的，微调得你准备这样的数据集吧。问这样的内容，回答就是你准备好的，大量的数据集加以训练。看看能不能得到你要的效果。
