### ISSUE TITLE
[Help] chatglm启动失败

### ISSUE THREAD

**Issue by meowrain** [THUDM/ChatGLM-6B#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行：web_demo.py

报错如图
![image](https://github.com/THUDM/ChatGLM-6B/assets/107172084/ff5aa4d7-9316-4c89-9c96-4efaf56b9ad5)

```txt
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:07<00:00,  1.09it/s]
Failed to load cpm_kernels:[WinError 267] 目录名称无效。: 'C:\\Users\\meowr\\AppData\\Local\\Programs\\PicGo\\PicGo.exe'
Traceback (most recent call last):
  File "D:\chatglm\ChatGLM-6B\web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained(".\\model", trust_remote_code=True).quantize(4).half().cuda()
  File "C:\Users\meowr/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 1434, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "C:\Users\meowr/.cache\huggingface\modules\transformers_modules\model\quantization.py", line 157, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "C:\Users\meowr/.cache\huggingface\modules\transformers_modules\model\quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "C:\Users\meowr/.cache\huggingface\modules\transformers_modules\model\quantization.py", line 76, in compress_int4_weight
    blockDim = (min(round_up(m, 32), 1024), 1, 1)
NameError: name 'round_up' is not defined
```

### Expected Behavior

可以正常运行

### Steps To Reproduce

1.安装完所有依赖，包括pytorch
2.下载模型，放在了目录下的model文件夹内
3.修改`web_demo.py` 
 tokenizer = AutoTokenizer.from_pretrained(".\\model", trust_remote_code=True)
model = AutoModel.from_pretrained(".\\model", trust_remote_code=True).quantize(4).half().cuda()
4.打开conda powershell，cd到目录，执行 `python web_demo.py`
![image](https://github.com/THUDM/ChatGLM-6B/assets/107172084/07653df9-5c38-45c5-a348-93f73fc37ced)
![image](https://github.com/THUDM/ChatGLM-6B/assets/107172084/f3a5df1c-38dd-4f48-ab50-1059282671f2)

### Environment

```markdown
- OS: Windows 11 Insider
- Python: 3.10.10
- Transformers: 4.27.1
- PyTorch: 2.0.1
- CUDA Support True:
```

**Comment by sliontc** [comment]
我也出现这样的错误，请问你解决了吗？

**Comment by Icarusiaz** [comment]
可能是你的环境变量PATH有PicGo.exe所在的目录，Python在`os.environ.get("PATH", "").split(os.pathsep)`时将该目录转换成了该文件。
经过测试发现`import cpm_kernels`会失败，产生`NotADirectoryError: [WinError 267] 目录名称无效。`的错误，定位到`Anaconda3\envs\XXX\Lib\site-packages\cpm_kernels\library\base.py，line11，def lookup_dll(prefix)`，其中的`if not os.path.exists(path) continue`判断不全面，变量path是文件时不会`continue`，导致错误，改为`if not os.path.exists(path) or not os.path.isdir(path): continue`。
已跑通

**Comment by meowrain** [comment]
> 可能是你的环境变量PATH有PicGo.exe所在的目录，Python在`os.environ.get("PATH", "").split(os.pathsep)`时将该目录转换成了该文件。 经过测试发现`import cpm_kernels`会失败，产生`NotADirectoryError: [WinError 267] 目录名称无效。`的错误，定位到`Anaconda3\envs\XXX\Lib\site-packages\cpm_kernels\library\base.py，line11，def lookup_dll(prefix)`，其中的`if not os.path.exists(path) continue`判断不全面，变量path是文件时不会`continue`，导致错误，改为`if not os.path.exists(path) or not os.path.isdir(path): continue`。 已跑通。 cpm_kernels已经存在相关[PR](https://github.com/OpenBMB/cpm_kernels/pull/7/commits/dbcc14e5f276b27f754845811b4fb429e4157bac)。

@Icarusiaz 好的，谢谢！
