### ISSUE TITLE
非常惊艳的效果！想问下为什么对同样的输入，生成的结果是不同的呢？（有时候差别还很大）是因为解码用的top p吗？

### ISSUE THREAD

**Issue by canghongjian** [THUDM/ChatGLM-6B#12]
我看了代码，chat不带history应该就不会用到历史信息？但我使用的时候不带这个参数，连续两次generate1500的文本就提示超过2048了，这是怎么回事呢

**Comment by duzx16** [comment]
是的，生成结果不同是因为解码用的是top p sampling。你可以修改`.chat`方法的参数来使用`transformers`支持的采样方法，但是一般来说top p sampling能比较好地兼顾效率和效果。

关于生成长度的问题，你能提供一个可复现的样例吗？

**Comment by canghongjian** [comment]
这是我调用的方式
```
response, history = model.chat(tokenizer, content) # len(content) 大约1500
response, history = model.chat(tokenizer, content)
```
我调试了下，chat代码最后三行
![image](https://user-images.githubusercontent.com/34473193/224970274-dd4c3cb2-732d-40bb-b1c6-052d917ace4b.png)
第二次进chat的时候history保留了上次append的query和response，调用的时候指明history=[]才可以不受之前history影响
```
response, history = model.chat(tokenizer, content, history=[]) # len(content) 大约1500
response, history = model.chat(tokenizer, content, history=[])
```

**Comment by duzx16** [comment]
> 这是我调用的方式
> 
> ```
> response, history = model.chat(tokenizer, content) # len(content) 大约1500
> response, history = model.chat(tokenizer, content)
> ```
> 
> 我调试了下，chat代码最后三行 ![image](https://user-images.githubusercontent.com/34473193/224970274-dd4c3cb2-732d-40bb-b1c6-052d917ace4b.png) 第二次进chat的时候history保留了上次append的query和response，调用的时候指明history=[]才可以不受之前history影响
> 
> ```
> response, history = model.chat(tokenizer, content, history=[]) # len(content) 大约1500
> response, history = model.chat(tokenizer, content, history=[])
> ```

这是我们代码里的bug，history这个参数的默认参数用的是`[]`，会导致修改的时候永久修改了默认参数的值。谢谢指出，已经修复了。

**Comment by canghongjian** [comment]
再次祝贺你们能推出并开源如此强大的工作！
