### ISSUE TITLE
[BUG/Help] cpu推理速度过慢

### ISSUE THREAD

**Issue by WuTianyi321** [THUDM/ChatGLM-6B#121]
### Current Behavior

由于显存不足，使用cpu推理，模型加载代码
`model = AutoModel.from_pretrained("..\ChatGLMModel\ChatGLM6B", trust_remote_code=True).float()`
其中，"..\ChatGLMModel\ChatGLM6B"为我将https://huggingface.co/THUDM/chatglm-6b下载到本地后的路径。

在模型加载完成，输入【你好】进行测试时，等待很久很久依然没有任何响应。

### Expected Behavior

希望cpu推理加速

### Steps To Reproduce

model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()

### Environment

```markdown
- OS: Win 10 21H2，操作系统内部版本19044.2728
- Python: 3.9.16
- Transformers: 4.27.1
- PyTorch: 1.13.1
- CPU：AMD Ryzen 7 4800H
- RAM：16G*2 DDR4
```

**Comment by yaleimeng** [comment]
显存不足——>CPU推理。。。搞笑呢。。
6B的大模型，GPU跑都够呛，还想CPU推理。。算了吧。直接访问官网的API体验就行了。。

**Comment by xxllp** [comment]
应该有办法

**Comment by yaleimeng** [comment]
我的意思是，难道没有意识到算力是最基本的门槛吗。。搞个CPU就想跑大模型，做梦呢？ 
当然如果你愿意一个响应跑10分钟，那也行。

**Comment by WuTianyi321** [comment]
> 

当然能跑，我跑rwkv的14B模型纯CPU都不慢，当然也可能是rwkv架构优势。

**Comment by WuTianyi321** [comment]
> 我的意思是，难道没有意识到算力是最基本的门槛吗。。搞个CPU就想跑大模型，做梦呢？ 当然如果你愿意一个响应跑10分钟，那也行。

当然能跑，我跑rwkv的14B模型纯CPU都不慢，当然也可能是rwkv架构优势。

**Comment by yuan-er** [comment]
应该是单线程的原因，LLaMA 7B 4bit使用8个线程在CPU(5800x)上跑基本能达成200-300ms/token的速度，在GPU(2070s)上是20-30ms/token，大约是10倍的性能差异。

**Comment by tong-ge** [comment]
我这边大概跑3-5分钟，CPU是满的，应该不是单线程的问题
