### ISSUE TITLE
[BUG/Help] <title>能否给一个可以跑通的colab部署脚本

### ISSUE THREAD

**Issue by WeiWenxing** [THUDM/ChatGLM-6B#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

部署总是出现各种问题，能否给出一个可以跑通的colab部署代码？

### Expected Behavior

部署总是出现各种问题，能否给出一个可以跑通的colab部署代码？

Traceback (most recent call last):
  File "/content/ChatGLM-6B/web_demo.py", line 1, in <module>
    from transformers import AutoModel, AutoTokenizer
ModuleNotFoundError: No module named 'transformers'

### Steps To Reproduce

%cd /content
!git clone https://github.com/THUDM/ChatGLM-6B
%cd ChatGLM-6B
!pip install gradio
!python web_demo.py

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

### Anything else?

部署总是出现各种问题，能否给出一个可以跑通的colab部署代码？

**Comment by WeiWenxing** [comment]
按照这个方案运行正确了： 但是什么结果都没有，说好的输出一个网址，网址在哪里？？？
%cd /content
!git clone https://github.com/THUDM/ChatGLM-6B
%cd ChatGLM-6B
!python3 -m venv venv
!source .\venv\Scripts\activate
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
!pip install -r requirements.txt
!pip install gradio
!python web_demo.py

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  62% 5/8 [00:45<00:27,  9.28s/it]^C

**Comment by evshiron** [comment]
https://github.com/THUDM/ChatGLM-6B/issues/69#issuecomment-1472427924

**Comment by M1saka10010** [comment]
> 按照这个方案运行正确了： 但是什么结果都没有，说好的输出一个网址，网址在哪里？？？ %cd /content !git clone https://github.com/THUDM/ChatGLM-6B %cd ChatGLM-6B !python3 -m venv venv !source .\venv\Scripts\activate !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 !pip install -r requirements.txt !pip install gradio !python web_demo.py
> 
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision. Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Loading checkpoint shards: 62% 5/8 [00:45<00:27, 9.28s/it]

你的checkpoint都还没加载完

**Comment by PengZiqiao** [comment]
亲测可以在colab跑，内存占用3.5G左右，显存占用5.5G左右

!pip install --upgrade protobuf icetk cpm_kernels

from transformers import AutoTokenizer, AutoModel

# 指定缓存位置
os.environ["TRANSFORMERS_CACHE"] = "/content/models_cache" 

# 加载模型
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True).half().cuda()
model = model.eval()

# 推理
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

**Comment by evshiron** [comment]
> Loading checkpoint shards: 62% 5/8 [00:45<00:27, 9.28s/it]

这是加载到第五个shard，内存不足，进程被kill，所以结束了。

我的colab链接里对`web_demo.py`做了一些修改，优化了加载方式，就不会爆内存了，你感兴趣可以看看里边注释掉的内容。

现在提供了`chatglm-6b-int4`模型以后，在colab上不需要上述修改也可以随便跑了。

**Comment by sherlock1987** [comment]
问一下大家，用INT4的模型来跑的话，在colab上执行一次对话要多久？我这边显示是10秒左右，但是检查了代码，发现GPU显存是有的，5.5G。这个正常吗？
