### ISSUE TITLE
GLM的词表有开源吗，在哪个目录下

### ISSUE THREAD

**Issue by Bob-Annette** [THUDM/ChatGLM-6B#1226]
GLM的词表有开源吗，在哪个目录下，没有找到

**Comment by Gio-2020** [comment]
我尝试打印tokenizer.vocab_files_names显示{'vocab_file': 'ice_text.model'}，可以用tokenizer.get_vocab()获取

**Comment by thincal** [comment]
https://huggingface.co/THUDM/chatglm-6b/blob/main/ice_text.model
