### ISSUE TITLE
[Help] Default process group has not been initialized, please make sure to call init_process_group

### ISSUE THREAD

**Issue by heytong** [THUDM/ChatGLM-6B#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

command: sh train.sh 

Error: RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

thanks.

### Steps To Reproduce

Run: sh train.sh

### Environment

```markdown
- OS:centos 8
- Python: 3.9.6
- Transformers: 4.30.1
- PyTorch: torch                       2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by AriesChen-UPC** [comment]
Have you found the cause? I'm also having this problem. Thank you!

**Comment by 254288008** [comment]
me too

**Comment by AriesChen-UPC** [comment]
Suggest checking the transformers version. 
transformers == 4.27.1 worked for me.

**Comment by luoyinqq** [comment]
已经解决，解决方法： train.sh中，改为

python3 -m torch.distributed.launch  --use_env  main.py

**Comment by ArtificialZeng** [comment]
> 已经解决，解决方法： train.sh中，改为
> 
> python3 -m torch.distributed.launch --use_env main.py

根本就不是train，我跑evaluate.sh也报错
