### ISSUE TITLE
有计划发布更多参数的版本吗？

### ISSUE THREAD

**Issue by TEENN2233** [THUDM/ChatGLM-6B#1238]
### Is your feature request related to a problem? Please describe.

如题

### Solutions

如题

**Comment by duzx16** [comment]
已经推出了新的模型 https://github.com/THUDM/ChatGLM2-6B 。在参数量不变的前提下大幅提高了模型性能。
也可以通过 https://chatglm.cn 体验更大规模的 ChatGLM 模型。
