### ISSUE TITLE
[Help] 作为生成式模型，chat能否实现像openai API一样的Steam模式输出？

### ISSUE THREAD

**Issue by playinlife** [THUDM/ChatGLM-6B#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前chat接口会在模型完成所有字符的生成后一次性返回结果

### Expected Behavior

希望每生成一个内容就触发输出，不知道接口是否有参数可以调整达到这个效果

### Steps To Reproduce

按照官方示例
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)

### Environment

```markdown
- OS:CentOS 7
- Python:3.9
- Transformers:4.26.1
- PyTorch:1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

ChatGLM是目前试用下来最好的开源模型，清华NB，加油！

**Comment by duzx16** [comment]
Duplicate of #78
