### ISSUE TITLE
[Help] <输入token数目有限制吗>

### ISSUE THREAD

**Issue by LebronJames0423** [THUDM/ChatGLM-6B#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问下，chatglm6b和chatglm130b有最大输入token数目限制吗？如果没有的话，是不是超过了某个阈值后效果会下降呢？

### Steps To Reproduce

null

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
ChatGLM-6B 最大支持输入 2048 个字符，超过之后效果会明显下降。需要更长的输入可以使用https://github.com/THUDM/ChatGLM2-6B
