### ISSUE TITLE
本地加载模型报错

### ISSUE THREAD

**Issue by muximuxi** [THUDM/ChatGLM-6B#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在本地下载好模型后，根据demo代码执行：
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(myModelPath, trust_remote_code=True)
然后报错：ValueError：Tokenizer class LlamaTokenizer does not exist or is not currently imported.
请问本地加载模型是需要另外下载LlamaTokenizer吗？

### Steps To Reproduce

报错：ValueError：Tokenizer class LlamaTokenizer does not exist or is not currently imported.
请问本地加载模型是需要另外下载LlamaTokenizer吗？

### Environment

```markdown
- OS: wsl-ubuntu 22.04
- Python: 3.7
- Transformers: 4.27.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
使用的应该不是本仓库的代码。
