### ISSUE TITLE
[BUG/Help] [QUESTION] What are the <Image_n> meaning?

### ISSUE THREAD

**Issue by DongqiShen** [THUDM/ChatGLM-6B#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I print the vocabulary in the tokenizer, I find that there are 20000 tokens named <Image_n>(n is the number) from <image_0> to <image_20000>. Just want to know the meaning of these tokens. Does anyone know?  Thanks a lot

### Steps To Reproduce

vocab_dict = tokenizer.get_vocab()

### Environment

```markdown
- OS:Mac M1 Pro
```

**Comment by duzx16** [comment]
These are image tokens in [icetk](https://github.com/THUDM/icetk). Icetk is designed to be a multimodal tokenizer that can handle both images and texts, but we only use the text part.

**Comment by FeiWard** [comment]
> These are image tokens in [icetk](https://github.com/THUDM/icetk). Icetk is designed to be a multimodal tokenizer that can handle both images and texts, but we only use the text part.

咨询一下，如何修改这个词表，比如这些image的token，在文本中根本不需要，但是这么大的词表对推理速度影响比较大，有没有删除的办法？

**Comment by FeiWard** [comment]
@duzx16
