### ISSUE TITLE
后续可以在huggingface上可以提供Torchscript格式的模型么

### ISSUE THREAD

**Issue by paw-zhao** [THUDM/ChatGLM-6B#1290]
### Is your feature request related to a problem? Please describe.

你好，后续可以在huggingface上可以提供Torchscript格式的模型么

### Solutions

你好，后续可以在huggingface上可以提供Torchscript格式的模型么

**Comment by alanzhai219** [comment]
+onnx模型

**Comment by zhangch9** [comment]
Duplicate of [#92](https://github.com/THUDM/ChatGLM-6B/issues/92)
