### ISSUE TITLE
[Help] <title>为什么chatglm每次chat的回答结果都不同？

### ISSUE THREAD

**Issue by soultrans** [THUDM/ChatGLM-6B#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我使用[huggingface模型仓库中提供的demo](https://www.huggingface.co/THUDM/chatglm-6b)进行阅读的理解验证，每次chat过程中ChatGLM的response都不一样，请问这是为什么？有什么方式可以是回答的答案固定吗？

### Steps To Reproduce

代码示例如下：

```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()

QA = """已知信息：{context} 根据上述已知信息，简洁和专业的回答问题。只允许根据原文已知信息进行回答，不允许在答案中添加编造成分，答案请使用中文。 问题是：{question}"""

response, history = model.chat(tokenizer, QA, history=[])
print(response)
```

其中{context} 每次会被替为我需要询问的文本信息；{question}则会被替换为相应的问题

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by soultrans** [comment]
从#1114 找到了相关的处理方案，除此之外，想问下如何使用[THUDM/chatglm2-6b](https://www.huggingface.co/THUDM/chatglm2-6b)进行阅读问答？替换模型后每次都是提示
`Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.`

**Comment by invado** [comment]
这是大语言模型的底层原理决定的

我们目前采用的办法是一个问题让模型回答多次，采纳多个结果中最多出现的那个。

**Comment by SCAUapc** [comment]
> 这是大语言模型的底层原理决定的
> 
> 我们目前采用的办法是一个问题让模型回答多次，采纳多个结果中最多出现的那个。

这个跟大语言模型底层没有关系吧。是因为生成的时候是依照下个token的所有概率进行随机采样得到结果的。楼主可以把do_sample这个设置成False试试。

**Comment by zhangch9** [comment]
Duplicate of [#12](https://github.com/THUDM/ChatGLM-6B/issues/12)
