### ISSUE TITLE
[BUG/Help] <Windows CPU 无法启用多核并行运算 --> quantization_kernels_parallels.so>

### ISSUE THREAD

**Issue by YifuLiu-uk** [THUDM/ChatGLM-6B#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Log 如下：

Failed to load cpm_kernels:name 'CPUKernel' is not defined

Load parallel cpu kernel failed C:\Users\admin\ .cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization.py", line 138, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\admin\anaconda3\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\admin\anaconda3\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)

FileNotFoundError: Could not find module 'C:\Users\admin\ .cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

### Expected Behavior

Activating CPU-based kernels parallel computing / 启动CPU多核并行运算

### Steps To Reproduce

1. 已经按照教程将模型下载至本地并使用本地路径
2. 已按教程改用.float()使用cpu -->  model = AutoModel.from_pretrained("local_address",trust_remote_code=True).float()
3. 已安装[TDM-GCC](https://jmeubank.github.io/tdm-gcc/) --> TDM-GCC 10.3.0 与 openmp
4. 已注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
5. 已将“kernels = Kernel(****)”改成“kernels = CPUKernel()”
6. 主要参考ChatGLM-6B中的：[Issue 166](https://github.com/THUDM/ChatGLM-6B/issues/166)和[Issue 529](https://github.com/THUDM/ChatGLM-6B/issues/529)
7. quantization_kernels_parallel.so 手动载入失败，quantization_kernels.so载入正常
![image](https://github.com/THUDM/ChatGLM-6B/assets/59554407/f736ce0c-25db-4702-9384-d46da16e320b)

### Environment

```markdown
- OS: Windows
- Python: 3.8.16
- Transformers: 4.30.2
- PyTorch: 2.0.1+cpu
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

### Anything else?

目前报错:
1. NameError: name 'CPUKernel' is not defined 
2. Load parallel cpu kernel failed --> quantization_kernels_parallel.so

可以运行quantization_kernels.so，但无法运行quantization_kernels_parallel.so
希望多核心并行运算，有啥好办法吗，谢谢大家

**Comment by YifuLiu-uk** [comment]
模型为**Chatglm2-6b-int4**，不好意思发错项目了

**Comment by mmxstar** [comment]
同问，可以运行quantization_kernels.so，但无法运行quantization_kernels_parallel.so
