### ISSUE TITLE
多轮对话问题

### ISSUE THREAD

**Issue by foreverxujiahuan** [THUDM/ChatGLM-6B#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问这个模型支持像chatgpt一样支持进行多轮对话之后输出下一个答案吗？

这是chatgpt的demo

```
# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

content = response['choices'][0]['message']['content']

print(content)
```

### Steps To Reproduce

None

### Environment

```markdown
- OS: linux
- Python: 3.8.5
- Transformers: 4.27.1
- PyTorch: 1.12.1+cu102
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by 1991Troy** [comment]
支持，你看cli_demo.py里每次调用，都有返回一个response和history，后者记录的就是历史对话信息

**Comment by foreverxujiahuan** [comment]
可是这样只支持一个query和一个response的一一对应的。

我希望能像chatgpt一样，支持多个query在一块的对话

```
messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "请问北京到上海有多远"},
        {"role": "user", "content": "北京和杭州呢"}
        {"role": "assistant", "content": "北京到上海1200公里，北京到杭州1270公里"},
    ]
```

类似这样的效果

**Comment by yuri2peter** [comment]
你要的是连续提问的效果吧，用代码控制一下流程就可以实现。

**Comment by digits122** [comment]
理论上，你将两次提问直接合并到一个提问之中，就可以了，效果是一样的。还可以将自行修改history，移除AI第一次的回复，重新组装，再送给AI进行回复。没有这样试过，但应该是可行的。

**Comment by foreverxujiahuan** [comment]
> 

如果连续发送两句效果和两句直接拼接在一起效果是一样的话确实可以。可能中间得加个分隔符什么的。具体的得做下实验才知道。

**Comment by foreverxujiahuan** [comment]
查看了一下他的chat接口，他的history就是简单的将上文拼接到了当前的query重组成了一个新的prompt。

```
if not history:
    prompt = query
else:
    prompt = ""
    for i, (old_query, response) in enumerate(history):
        prompt += "[Round {}]\n问：{}\n答：{}\n".format(i, old_query, response)
    prompt += "[Round {}]\n问：{}\n答：".format(len(history), query)
```
因此多轮对话和一个长的query效果应该是一样的。

**Comment by Lemondogdog** [comment]
> 理论上，你将两次提问直接合并到一个提问之中，就可以了，效果是一样的。还可以将自行修改history，移除AI第一次的回复，重新组装，再送给AI进行回复。没有这样试过，但应该是可行的。



> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> 请问这个模型支持像chatgpt一样支持进行多轮对话之后输出下一个答案吗？
> 
> 这是chatgpt的demo
> 
> ```
> # Note: you need to be using OpenAI Python v0.27.0 for the code below to work
> import openai
> 
> openai.ChatCompletion.create(
>   model="gpt-3.5-turbo",
>   messages=[
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": "Who won the world series in 2020?"},
>         {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
>         {"role": "user", "content": "Where was it played?"}
>     ]
> )
> 
> content = response['choices'][0]['message']['content']
> 
> print(content)
> ```
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> None
> 
> ### Environment
> ```gfm
> - OS: linux
> - Python: 3.8.5
> - Transformers: 4.27.1
> - PyTorch: 1.12.1+cu102
> - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
> ```
> 
> ### Anything else?
> _No response_
我试了下不知道哪里问题 我是加在历史记录里面然后类似数组那要每一轮对话都把历史记录追加上一次的结果上在新的依次提问题一起发送过去。但是 失败了没成功希望有人能解答下如何实现。多轮对话让它有上下文的记忆啊。

**Comment by xumeng** [comment]
同遇到这个问题，感觉是个很小的bug，为何没有处理🤔️
