### ISSUE TITLE
[BUG/Help] KoboldAI或text-generation-webui可以支持运行这个模型吗？

### ISSUE THREAD

**Issue by coyude** [THUDM/ChatGLM-6B#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如题，KoboldAI或text-generation-webui可以支持运行这个模型吗？两个UI都尝试过，无法加载，不清楚是否是我的步骤有问题。

### Steps To Reproduce

channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - colorama
  - flask-socketio=5.3.2
  - flask-session=0.4.0
  - python-socketio=5.7.2
  - pytorch=1.11.*
  - python=3.8.*
  - cudatoolkit=11.1
  - eventlet=0.33.3
  - dnspython=2.2.1
  - markdown
  - bleach=4.1.0
  - pip
  - git=2.35.1
  - sentencepiece
  - protobuf
  - marshmallow>=3.13
  - apispec-webframeworks
  - loguru
  - termcolor
  - psutil
  - pip:
    - flask-cloudflared==0.0.10
    - flask-ngrok
    - lupa==1.10
    - transformers==4.24.0
    - huggingface_hub==0.12.1
    - safetensors
    - accelerate
    - git+https://github.com/VE-FORBRYDERNE/mkultra

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by cmradix** [comment]
你应当去你所说的两个项目下提问

**Comment by cmradix** [comment]
> 我也在text-generation-webui试过了，行不通，报错 text-generation-webui的作者对于chatglm-6b是这么说的 "Apparently this is a text2text model and not an autoregressive model. So it's more like FLAN than GPT-J or other currently supported models."

你可以尝试官方自带的webui demo或者Akegarasu的ChatGLM-webui，我个人推荐后者。

**Comment by zentlemanx** [comment]
哈哈，我现在也是用的后者
