### ISSUE TITLE
[CPU] <CPU基本上跑不动>

### ISSUE THREAD

**Issue by xmlv** [THUDM/ChatGLM-6B#132]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/6244925/225863951-79018cfa-1335-4796-93c6-735fb0bf652b.png)

低压I7，32G内存，跑了40分钟没结果。

### Solutions

消费GPU大部分8G显存，只能用最低一级的量化比较尴尬， CPU则完全没法用。

**Comment by is** [comment]
试试，4bit模型，然后一定用stream方式，每个token出来都能有反馈。慢不过可以接受吧.
