### ISSUE TITLE
[Help]怎么让每次对话不带history

### ISSUE THREAD

**Issue by lkp1985** [THUDM/ChatGLM-6B#1323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前我的应用场景是自己训练了数据，采用web_demo.py运行后，在对话框给出问题，模型给出答案。发现第一次的答案都是准的，对问题稍作修改后继续问答，会发现它会拿第一次问题进行作答，从而影响了本次答案。所以希望每次提问，不要带history的内容。需要对web_demo.py的代码做哪些修改？

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by heyLinsir** [comment]
可以在web_demo.py中第95行将输入的history参数设置为空：
```
# 原始代码
submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],
                    show_progress=True)
# 修改后代码
submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, gr.State([])], [chatbot, history],
                    show_progress=True)
```

**Comment by lkp1985** [comment]
> 可以在web_demo.py中第95行将输入的history参数设置为空：
> 
> ```
> # 原始代码
> submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],
>                     show_progress=True)
> # 修改后代码
> submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, gr.State([])], [chatbot, history],
>                     show_progress=True)
> ```

这样不行，因为这行代码之前，它已经做了赋值history = gr.State([])。不过我已经解决，在这行代码之前，加一行：
 submitBtn.click(reset_state, outputs=[chatbot, history], show_progress=True)。相当于在predict前调用一次clear history的按钮事件。

**Comment by lkp1985** [comment]
已解决：
在submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],
                    show_progress=True)之前，加一行代码，用于清空历史记录：
submitBtn.click(reset_state, outputs=[chatbot, history], show_progress=True)
submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],
                    show_progress=True)
