### ISSUE TITLE
[Help] <How to train it in huggingface>

### ISSUE THREAD

**Issue by Mr-IT007** [THUDM/ChatGLM-6B#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to train it in huggingface. How to do it

### Steps To Reproduce

I want to train it in huggingface. How to do it

### Environment

```markdown
- OS: Ubuntu 20.04
- Python:3.8
- Transformers:4.26.1
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by mengzhangjian** [comment]
we havee same question

**Comment by aihaidong** [comment]
I have same question.

**Comment by Mingxiangyu** [comment]
I have same question.
