### ISSUE TITLE
python web_demo.py cannot see the answer,but streamlit can

### ISSUE THREAD

**Issue by zhanghui-china** [THUDM/ChatGLM-6B#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i run python web_demo.py, in explorer, I can only see the question ,but cannot see the answer
when i change to run streamlit run web_demo2.py, I can see the question and the answer.

### Steps To Reproduce

python web_demo.py
![image](https://github.com/THUDM/ChatGLM-6B/assets/63148804/520711c1-9947-4dcb-9b2e-1a22ced25472)

streamlit run web_demo2.py

![image](https://github.com/THUDM/ChatGLM-6B/assets/63148804/15cc1fe5-ff95-4e3d-bd45-5c84a17c5e72)

### Environment

```markdown
- OS:windows 11
- Python:3.8 conda 
- Transformers:4.26.1
- PyTorch:1.11
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by YangChun6** [comment]
I also had this problem

**Comment by zhanghui-china** [comment]
> downgrade your gradio version to 3.44.x

this is the answer。
