### ISSUE TITLE
模型预测无报错，但是返回的内容为空

### ISSUE THREAD

**Issue by baibaiw5** [THUDM/ChatGLM-6B#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

模型预测无报错，但是返回的内容为空

### Steps To Reproduce

运行以下命令，打印的response是空字符串。
`from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
response, history = model.chat(tokenizer, "你好", history=[])
print('response',response)
`

### Environment

```markdown
环境：
protobuf                 3.19.5
transformers             4.26.1
icetk   尝试了0.0.4/0.0.5两个版本，这些版本需要 protobuf 3.18，需要强制安装protobuf 3.19
cpm-kernels              1.0.11
torch                    1.13.1
Python 3.10.9
```

**Comment by baibaiw5** [comment]
![image](https://user-images.githubusercontent.com/233871/226082221-6dd63ac2-9211-4d02-af3d-cf98bc195e96.png)

**Comment by baibaiw5** [comment]
经过测试，下载的模型文件有问题，导致无输出

**Comment by JohnHwangzn** [comment]
我也遇到这个问题了额. 请问你是如何解决的呢? 我重新下载了模型, 还是不行.

**Comment by liebkne** [comment]
在cli下同样问题，直接运行cli_demo.py输入并无输出。

**Comment by lwh9346** [comment]
> 在cli下同样问题，直接运行cli_demo.py输入并无输出。

这一项目在几小时前添加了stream output，你可能需要更新一下【本代码仓库】的代码，并且确保模型文件和huggingface上的最新版一致，再重新运行模型。

**Comment by xixiaoyao** [comment]
> 
这个方法也不行，报错

OSError: [Errno 38] Function not implemented: '/root/.cache/huggingface/hub/models--THUDM--ChatGLM-6B/blobs/fe5bac6bfa5b5404ddfe3fabe04862b785e013afd7b308b7beca08239f9489fa' -> '/mnt/models/pytorch_model-00001-of-00008.bin'

**Comment by MichaelToLearn** [comment]
看来是不能用清华云盘上的那个权重了，那个估计是有些老了。

**Comment by jilaqi-le-gao** [comment]
我也是碰到的同样问题。用的是清华云盘上的权重和cli_demo。
