### ISSUE TITLE
改成能在colab下跑起来就好了，colab内存最大13G，跑不起来

### ISSUE THREAD

**Issue by younggggger** [THUDM/ChatGLM-6B#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 62%
5/8 [00:52<00:30, 10.28s/it]

到这里colab就内存爆掉重启了

### Steps To Reproduce

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 62%
5/8 [00:52<00:30, 10.28s/it]

### Environment

```markdown
colab
```

**Comment by evshiron** [comment]
可以尝试搜一下相关issue。

**Comment by PerezFan** [comment]
readme里面低成本部署中有个调整，
就是改下web_demo.py的代码，
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()
我是能跑起来了，但回答问题以后马上又内存不够了

**Comment by duzx16** [comment]
可以直接使用量化后的模型`THUDM/chatglm-6b-int4`
