### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by gitfans5** [THUDM/ChatGLM-6B#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

File "web_demo.py", line 19 SyntaxError: Non-ASCII character '\xe7' in file web_demo.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### Expected Behavior

How to fix the error:

File "web_demo.py", line 19 SyntaxError: Non-ASCII character '\xe7' in file web_demo.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

when running "python web_demo.py"? Thanks.

### Steps To Reproduce

When running "python web_demo.py"

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :

OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
```

**Comment by evanho** [comment]
This error message usually occurs when a Python file contains non-ASCII characters (here is Chinese characters), but the encoding format has not been specified at the top of the file. In Python 3.x, the default encoding format is UTF-8. However, it is still recommended to add a coding declaration at the top of the file if non-ASCII characters are included in the code, to avoid similar errors. For example:

`# -*- coding: utf-8 -*-`

Or you can replace the Chinese characters with English.
