### ISSUE TITLE
[Feature] m系列的mac启用gpu

### ISSUE THREAD

**Issue by kingzeus** [THUDM/ChatGLM-6B#152]
### Is your feature request related to a problem? Please describe.

mac下cpu运行非常慢
pytorch 在m系列的mac上可以支持GPU加速

### Solutions

可以通过以下函数判断
torch.backends.mps.is_available()

修改 `.half().cuda()` 成 `float().to("mps")`

运行返回
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/2177109/226155235-19b4e201-d34a-4131-b59a-4c5d5929ee75.png">

有解决办法么？

**Comment by chaucerling** [comment]
https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1474260291

`int64` is supported on MacOS 13.3 Βeta, and you should also use the nightly build of pytorch.

I tried to use mps backend to run on gpu, but it seems to have a bug when calling the `generate` function.

**Comment by kingzeus** [comment]
> [#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1474260291)
> 
> `int64` is supported on MacOS 13.3 Βeta, and you should also use the nightly build of pytorch.
> 
> I tried to use mps backend to run on gpu, but it seems to have a bug when calling the `generate` function.

it seems to work! !
1. 修改 .half().cuda() 成 float().to("mps")
2. 修改 modeling_chatglm.py line33-37
```python
# flags required to enable jit fusion kernels
# torch._C._jit_set_profiling_mode(False)
# torch._C._jit_set_profiling_executor(False)
# torch._C._jit_override_can_fuse_on_cpu(True)
# torch._C._jit_override_can_fuse_on_gpu(True)
``` 
3. 修改 modeling_chatglm.py line 268
```python
 dtype = attention_scores.dtype
``` 
4. run
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/2177109/226171947-1c5afeec-0983-4dcf-8ac0-7d87d6d373ca.png">

cpu模式下大概300s左右，经过以上修改，仅需5s左右

**Comment by kingzeus** [comment]
> [#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1474260291)
> 
> `int64` is supported on MacOS 13.3 Βeta, and you should also use the nightly build of pytorch.
> 
> I tried to use mps backend to run on gpu, but it seems to have a bug when calling the `generate` function.

it seems to work! !
1. 修改 .half().cuda() 成 float().to("mps")
2. 修改 modeling_chatglm.py line33-37
```python
# flags required to enable jit fusion kernels
# torch._C._jit_set_profiling_mode(False)
# torch._C._jit_set_profiling_executor(False)
# torch._C._jit_override_can_fuse_on_cpu(True)
# torch._C._jit_override_can_fuse_on_gpu(True)
``` 
3. 修改 modeling_chatglm.py line 268
```python
 dtype = attention_scores.dtype
``` 
4. run
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/2177109/226171947-1c5afeec-0983-4dcf-8ac0-7d87d6d373ca.png">

目前会有些警告，但是似乎不影响使用
cpu模式下大概300s左右，
经过以上修改，仅需5-8s左右即可，多1轮回答，内存大概增加2G左右

**Comment by imClumsyPanda** [comment]
@kingzeus 您好 请问您测试环境的pytorch版本和macOS版本分别是多少呢？

**Comment by kingzeus** [comment]
> @kingzeus 您好 请问您测试环境的pytorch版本和macOS版本分别是多少呢？

macOS           13.2.1
torch              2.0.0
torchaudio         2.0.0.dev20230313
torchvision        0.15.1

**Comment by LeeeSe** [comment]
@kingzeus 请问如何绕过 cpm_kernels 的 RuntimeError: Unknown platform: darwin 报错？

**Comment by kingzeus** [comment]
> @kingzeus 请问如何绕过 cpm_kernels 的 RuntimeError: Unknown platform: darwin 报错？

目前来看，最简单的方法不要调用量化函数/不使用int4模型

**Comment by duzx16** [comment]
> > [#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1474260291)
> > `int64` is supported on MacOS 13.3 Βeta, and you should also use the nightly build of pytorch.
> > I tried to use mps backend to run on gpu, but it seems to have a bug when calling the `generate` function.
> 
> it seems to work! !
> 
> 步骤：
> 
> 1. 修改 .half().cuda() 成 float().to("mps")
> 2. 修改 modeling_chatglm.py line33-37
> 
> ```python
> # flags required to enable jit fusion kernels
> # torch._C._jit_set_profiling_mode(False)
> # torch._C._jit_set_profiling_executor(False)
> # torch._C._jit_override_can_fuse_on_cpu(True)
> # torch._C._jit_override_can_fuse_on_gpu(True)
> ```
> 
> 3. 修改 modeling_chatglm.py line 268
> 
> ```python
>  dtype = attention_scores.dtype
> ```
> 
> 4. 运行
> 
> <img alt="image" width="1289" src="https://user-images.githubusercontent.com/2177109/226171947-1c5afeec-0983-4dcf-8ac0-7d87d6d373ca.png">
> 
> 目前会有些警告，但是似乎不影响使用 cpu模式下大概300s左右， 经过以上修改，仅需5-8s左右即可，多1轮回答，内存大概增加2G左右
> 
> 需要改进的地方： 模型需要下载到本地，才能修改 modeling_chatglm.py。现有代码结构下，似乎没有很好的解决办法

感谢你提供的方法。我们已经修改了HF hub上的 `modeling_chatglm.py`，现在可以直接运行。另外将`.float()`改为`.half()`可以节省内存。

**Comment by Yif1999** [comment]
> > > [#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1474260291)
> > > `int64` is supported on MacOS 13.3 Βeta, and you should also use the nightly build of pytorch.
> > > I tried to use mps backend to run on gpu, but it seems to have a bug when calling the `generate` function.
> > 
> > 
> > it seems to work! !
> > 步骤：
> > 
> > 1. 修改 .half().cuda() 成 float().to("mps")
> > 2. 修改 modeling_chatglm.py line33-37
> > 
> > ```python
> > # flags required to enable jit fusion kernels
> > # torch._C._jit_set_profiling_mode(False)
> > # torch._C._jit_set_profiling_executor(False)
> > # torch._C._jit_override_can_fuse_on_cpu(True)
> > # torch._C._jit_override_can_fuse_on_gpu(True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 修改 modeling_chatglm.py line 268
> > 
> > ```python
> >  dtype = attention_scores.dtype
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. 运行
> > 
> > <img alt="image" width="1289" src="https://user-images.githubusercontent.com/2177109/226171947-1c5afeec-0983-4dcf-8ac0-7d87d6d373ca.png">
> > 目前会有些警告，但是似乎不影响使用 cpu模式下大概300s左右， 经过以上修改，仅需5-8s左右即可，多1轮回答，内存大概增加2G左右
> > 需要改进的地方： 模型需要下载到本地，才能修改 modeling_chatglm.py。现有代码结构下，似乎没有很好的解决办法
> 
> @kingzeus 感谢你提供的方法。我们已经修改了HF hub上的 `modeling_chatglm.py`，现在可以直接运行。另外将`.float()`改为`.half()`可以节省内存。

使用.half()输入语句并回车后报错：
loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0aa643d0-625a-11ed-b319-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x3x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      /usr/bin/python3 /Volumes/T7/Dev/ChatGLM/cli_demo.py
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown         
  warnings.warn('resource_tracker: There appear to be %d '

改回.float()正常，但是内存占用大

**Comment by tedyyu** [comment]
但是直接运行 `python web_demo.py` 就会遇到这个错，请问怎么避免？

> > @kingzeus 请问如何绕过 cpm_kernels 的 RuntimeError: Unknown platform: darwin 报错？
> 
> 目前来看，最简单的方法不要调用量化函数/不使用int4模型
