### ISSUE TITLE
[BUG/Help] Load from local stored model failed every time

### ISSUE THREAD

**Issue by clarkchen900** [THUDM/ChatGLM-6B#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have saved the model in a local directory as "../models/chatglm-6b"
Then I changed the demo_web.py script here to load the model from this directory. 

However when I run it, it gives errors like the following: What could be wrong here? 

Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/clark/transformer/ChatGLM-6B/web_demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("../models/chatglm-6b", trust_remote_code=True)
  File "/home/clark/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 708, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm-6b.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

### Expected Behavior

it should be able to load model from the saved directory.

### Steps To Reproduce

After saving the model with model.save_pretrained(PATH),
change the web_demo_py lines 4 and 5 to the following:

tokenizer = AutoTokenizer.from_pretrained("../models/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("../models/chatglm-6b", trust_remote_code=True).half().cuda()

Then run python3 web_demo.py

### Environment

```markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers:4.28.0
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

It runs OK when I load it from Huggingface.

**Comment by duzx16** [comment]
Because you only call `save_pretrained` of the model, not the tokenizer. Therefore it failed when you load the tokenizer.

**Comment by musicfish1973** [comment]
I have encountered the same problem, and it runs OK when I load it from Huggingface.

**Comment by leiqing1** [comment]
@clarkchen900 Download the complete configuration file from huggingface： https://huggingface.co/THUDM/chatglm-6b/tree/main 
Because Tsinghua Park is missing some configuration files ：https://cloud.tsinghua.edu.cn/d/fb9f16d6dc8f482596c2/
