### ISSUE TITLE
[BUG/Help] <title> 量化后的模型可以fine-tuning吗？ 我尝试时出错。

### ISSUE THREAD

**Issue by cs-liangchen-work** [THUDM/ChatGLM-6B#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当我加载原始模型：
output正常输出，且loss.backward()正常运行？
当我加载量化后的模型：
发现output可以正常输出，但是loss.backward()出错，如下：
RuntimeError: shape '[4096, 8192]' is invalid for input of size 67108864

看样子是模型的结构发生了变化？ 是不是量化后的模型不能正常fine-tuning呢？求助！！！

### Steps To Reproduce

output = model(input_ids=data.cuda(), labels=label.cuda())
loss = output.loss.mean()
loss.backward()
加载量化后的模型出错。

### Environment

```markdown
使用的是相同的环境，不存在环境问题
```

**Comment by duzx16** [comment]
量化后直接finetune比较困难，我们目前实现了量化 + P-Tuning的方法，欢迎体验
https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning
