### ISSUE TITLE
[BUG/Help] <title>请问fine-tuning后，需要怎么保存模型 以及加载自己fine-tune后的模型

### ISSUE THREAD

**Issue by cs-liangchen-work** [THUDM/ChatGLM-6B#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我按照这个保存模型：
torch.save(model.state_dict(), './model_E_commerce/static_dict' + str(epoch) + '.pkl')
保存成功，
按照这个加载模型：
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
出现以下错误：
OSError: It looks like the config file at 'model_E_commerce/static_dict2.pkl' is not a valid JSON file.

### Steps To Reproduce

torch.save(model.state_dict(), './model_E_commerce/static_dict' + str(epoch) + '.pkl')
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()

### Environment

```markdown
环境依据给的安装的哦
```

**Comment by duzx16** [comment]
使用`model.save_pretrained`来保存
