### ISSUE TITLE
输入长度异常，应该是2048吧？

### ISSUE THREAD

**Issue by yaleimeng** [THUDM/ChatGLM-6B#17]
Input length of input_ids is 2084, but `max_length` is set to 2048.   This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

**Comment by duzx16** [comment]
报错信息的意思是输入的长度是2084，但是模型设置的最大长度是2048，这是模型训练的时候使用的最大长度。因为使用了相对位置编码，理论上模型可以支持无限长的输入长度，但是超过2048之后模型的性能会逐渐下降。
如果你想尝试支持更长的长度的话，可以在调用`model.chat`传入更长的`max_length`，比如`max_length=4096`，但是生成结果的质量无法保证。

**Comment by yaleimeng** [comment]
我测试是一句一句的，并不长，可能系统当成一个多轮对话了。把所有历史带上就比较长了。
这就又涉及到一个会话管理的事情。
谢谢您的回复。

**Comment by MaiziXiao** [comment]
> 报错信息的意思是输入的长度是2084，但是模型设置的最大长度是2048，这是模型训练的时候使用的最大长度。因为使用了相对位置编码，理论上模型可以支持无限长的输入长度，但是超过2048之后模型的性能会逐渐下降。 如果你想尝试支持更长的长度的话，可以在调用`model.chat`的时候传入更长的`max_length`，比如`max_length=4096`，但是生成结果的质量无法保证。

![image](https://github.com/THUDM/ChatGLM-6B/assets/24979986/3f1ab2da-0b33-43fb-bfee-75d1a7f20ac3)
我把模型读取出来看到输入输出是4096的，请教下为啥max_length是2048呢

**Comment by maxusheng123** [comment]
> 我测试是一句一句的，并不长，可能系统当成一个多轮对话了。 把所有历史带上就比较长了。 这就又涉及到一个会话管理的事情。 谢谢您的回复。

你好，请问这个有什么好的解决方法吗，我猜测是因为每次都把历史记录全部给模型了，叠加下来就超出max_length了。

**Comment by thsno02** [comment]
用  ChatGLM2-6B，最长支持 32k。

**Comment by maxusheng123** [comment]
> input_ids的输入长度为 2084，但设置为 2048。这可能会导致意外行为。您应该考虑增加 .`max_length``max_new_tokens`

你好，请问那个max_new_tokens参数是做什么的。

**Comment by DRZbjut** [comment]
> > 我测试是一句一句的，并不长，可能系统当成一个多轮对话了。 把所有历史带上就比较长了。 这就又涉及到一个会话管理的事情。 谢谢您的回复。
> 
> 你好，请问这个有什么好的解决方法吗，我猜测是因为每次都把历史记录全部给模型了，叠加下来就超出max_length了。

你好，请问这个问题解决了吗

**Comment by DRZbjut** [comment]
> 我测试是一句一句的，并不长，可能系统当成一个多轮对话了。把所有历史带上就比较长了。 这就又涉及到一个会话管理的事情。 谢谢您的回复。

你好，请问这个问题解决了吗
