### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by sofa-li** [THUDM/ChatGLM-6B#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i ran the "model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()"
It stopped at "Loading checkpoint shards:  38%|█████████               | 3/8 [00:08<00:14,  2.91s/it]Killed"

### Steps To Reproduce

ubuntu22 with cuda and python38

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
The process is killed because your spare memory is not enough. It takes about 13GB CPU memory to load the model. If your CPU memory is not enough, you can try with `THUDM/chatglm-6b-int4`.

**Comment by sanjaymarison** [comment]
I have 24gb vram and my process gets killed, I also have 16gb ram with my cpu so it might be causing the problem but why doesnt it load on vram?
