### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'

### ISSUE THREAD

**Issue by WangChenxu21** [THUDM/ChatGLM-6B#18]
raise "google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'"

protobuf==3.20.0

**Comment by duzx16** [comment]
Could you please give the full error log. Specifically, I need to know which line this error occurs on.

**Comment by WangChenxu21** [comment]
Alright.

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 214, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file)
  File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 35, in __init__
    self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)
  File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 67, in _build_text_tokenizer
    tokenizer = TextTokenizer(self.vocab_file)
  File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/icetk/text_tokenizer.py", line 26, in __init__
    self.proto.ParseFromString(proto_str)
google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'

**Comment by duzx16** [comment]
> Alright.
> 
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Traceback (most recent call last): File "web_demo.py", line 4, in tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained return cls._from_pretrained( File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 214, in **init** self.sp_tokenizer = SPTokenizer(vocab_file) File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 35, in **init** self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False) File "/home/users/chenxu.wang/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 67, in _build_text_tokenizer tokenizer = TextTokenizer(self.vocab_file) File "/home/users/chenxu.wang/anaconda3/envs/hdflow/lib/python3.8/site-packages/icetk/text_tokenizer.py", line 26, in **init** self.proto.ParseFromString(proto_str) google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'

Are you sure you correctly downloaded the `ice_text.model` file? The correct file size should be about 2.7MB.

**Comment by jamestch** [comment]
> 
I have the same error. I have downloaded model files from huggingface, model files as followed

![image](https://user-images.githubusercontent.com/6100838/225171925-11cc3abc-014d-4cb6-b667-6d9185bbea41.png)

**Comment by WangChenxu21** [comment]
I think it's correct.

![image](https://user-images.githubusercontent.com/63109208/225233208-20b14724-db52-4650-bb85-95c2fbf9f965.png)

**Comment by duzx16** [comment]
> > 
> 
> I have the same error. I have downloaded model files from huggingface, model files as followed
> 
> ![image](https://user-images.githubusercontent.com/6100838/225171925-11cc3abc-014d-4cb6-b667-6d9185bbea41.png)

@jamestch You also need to download the `ice_text.model ` file.

**Comment by OedoSoldier** [comment]
You need to install `git lfs` to download large models from hf.

**Comment by jamestch** [comment]
> You need to install `git lfs` to download large models from hf.
![image](https://user-images.githubusercontent.com/6100838/225323679-c2f11d27-c423-40e8-91b7-9079b30fd68a.png)

I have installed **git lfs**, model files showed above is downloaded from huggingface by command 
**git clone https://huggingface.co/THUDM/chatglm-6b**

**Comment by jamestch** [comment]
> > > 
> > 
> > 
> > I have the same error. I have downloaded model files from huggingface, model files as followed
> > ![image](https://user-images.githubusercontent.com/6100838/225171925-11cc3abc-014d-4cb6-b667-6d9185bbea41.png)
> 
> @jamestch You also need to download the `ice_text.model ` file.

I have downloaded the ice_text.model file correctly since the SHA256 is right. But it did not work

**Comment by ShunLu91** [comment]
I met the same error when loading the pre-trained LLaMA-2-7b model using the function AutoTokenizer.from_pretrained(). 
After setting `use_fast=True`, this error was fixed.

**Comment by ShunLu91** [comment]
Finally, I re-downloaded the tokenizer-relevant files and solved this issue. Take the LLaMA-2-7b-hf as an example, update the files as below:
* special_tokens_map.json
* tokenizer_config.json
* tokenizer.json
* tokenizer.model
