### ISSUE TITLE
[BUG/Help] An error when running `tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)`

### ISSUE THREAD

**Issue by cloudhzc** [THUDM/ChatGLM-6B#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

>>> tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.

### Steps To Reproduce

run `tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)`

### Environment

```markdown
- OS: Windows 10
- Python: 3.7.5
- Transformers: 4.26.1
- PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by kenneth104** [comment]
It's no error
This is only warning level

Should not affect your next steps
