### ISSUE TITLE
[BUG/Help] <title>window,cpu版本使用chatglm-6b-int4提示错误：AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

### ISSUE THREAD

**Issue by zuuuuuuuuuuu** [THUDM/ChatGLM-6B#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

### Steps To Reproduce

![aa](https://user-images.githubusercontent.com/128494304/226632556-4108b31e-0457-4f4f-ae90-27e47d40e31a.jpg)

### Environment

```markdown
- OS:windows 10
- Python:3.9
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by dragononly** [comment]
解决了吗
