### ISSUE TITLE
有考虑加入微调功能吗？

### ISSUE THREAD

**Issue by teanhow** [THUDM/ChatGLM-6B#188]
体验了一下，效果比我预期的好。如果能加入微调模型的功能就更棒了。

**Comment by aoirusann** [comment]
Maybe try these repos: 
- [mymusise/ChatGLM-Tuning](https://github.com/mymusise/ChatGLM-Tuning)
- [ssbuild/chatglm_finetuning](https://github.com/ssbuild/chatglm_finetuning)
- [lich99/ChatGLM-finetune-LoRA](https://github.com/lich99/ChatGLM-finetune-LoRA)

**Comment by duzx16** [comment]
Duplicate of #3
