### ISSUE TITLE
[Feature] 预测结果的标点还是部分是英文的

### ISSUE THREAD

**Issue by lixiang1991** [THUDM/ChatGLM-6B#189]
### Is your feature request related to a problem? Please describe.

关闭的issue里说这个怎么修复了？
我用最新的[tokenization_chatglm.py]跑的结果还是中文的，：；（）都会输出成英文符号。
我更新了tokenization_chatglm.py和modeling_chatglm.py以后跑出来的结果还是这样
![image](https://user-images.githubusercontent.com/11677440/226798649-0b5d260c-938e-4df3-ab8f-6819a41e611d.png)
![image](https://user-images.githubusercontent.com/11677440/226798676-08ae6889-e1f1-4189-b592-8ec339119614.png)

看了下Hugging Face Hub上的改动记录，就改了两行：ids = [_id for _id in ids if _id >= 0]和self.vocab_files_names["vocab_file"]。比较了ice_text.model的md5和一周前我下载的md5都是9733ffa2cf070e0b78718747ea6a32a7cfc151b9

### Solutions

请问是还有别的地方需要改动才能修复这个问题吗？

**Comment by duzx16** [comment]
之前的更新没有同步到仓库里， 现在已经修复了
