### ISSUE TITLE
[Help] 离线部署的问题

### ISSUE THREAD

**Issue by rogerBridge** [THUDM/ChatGLM-6B#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题: 如何在离线环境下使用 chatglm-6b?
步骤: 在已经下载好了模型文件之后, 然后断开网络环境, 发现: 
         在执行这一步时: `tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)`
         报错, 请求接口: https://huggingface.co/api/models/THUDM/chatglm-6b 时报错
想到的方法:
        1. 修改 cached_file 这个函数, 直接从本地读取json文件
        2. 本地修改 /etc/hosts, 起一个https server, 然后对这个接口请求返回响应
求助:  有没有办法通过修改 transformers.AutoTokenizer 的一些配置来保存接口请求结果?

### Expected Behavior

离线部署后, 程序可以正常运行

### Steps To Reproduce

1. 环境: ubuntu 20.04, 安装的 requirements.txt 里面的依赖, 使用的cpu方法
2. 联网, 制作一个docker镜像, 下载好依赖, 并且正常执行一次输入输出
3. 断网, 打包docker镜像, 离线部署到别的服务器上
4. 执行时报错, 请求接口: https://huggingface.co/api/models/THUDM/chatglm-6b 时报错

### Anything else?
没有

**Comment by evanho** [comment]
from_pretrained 函数的第一个参数可以是本地路径（绝对路径）。

例如，模型在容器中的路径为 '/container/model/root/path/chatgml-6b'，则模型加载语句如下：
`tokenizer = AutoTokenizer.from_pretrained("/container/root/path/chatgml-6b", trust_remote_code=True)`

之后在 docker run 的时候利用 -v 参数将宿主机的实际模型存储路径映射到容器的模型路径，如：
`docker run -v  /host/model/root/path/chatgml-6b:/container/model/root/path/chatgml-6b my-container`

**Comment by rogerBridge** [comment]
> from_pretrained 函数的第一个参数可以是本地路径（绝对路径）。
> 
> 例如，模型在容器中的路径为 '/container/model/root/path/chatgml-6b'，则模型加载语句如下： `tokenizer = AutoTokenizer.from_pretrained("/container/root/path/chatgml-6b", trust_remote_code=True)`
> 
> 之后在 docker run 的时候利用 -v 参数将宿主机的实际模型存储路径映射到容器的模型路径，如： `docker run -v /host/model/root/path/chatgml-6b:/container/model/root/path/chatgml-6b my-container`

你好, 我找到下 模型的路径: /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/d2bbc82a2cdd04522ad340bdd464379808676950/, 然后将 `tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)` 中的path替换掉, 在容器里面执行了以下, 仍然会报错: 请求接口失败

之后我又尝试了新方法: `tokenizer.save_pretrained("/root/tokenizer")`, 然后 `tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)`, 将path替换为 "/root/tokenizer", 仍然会报错: 请求接口失败

**Comment by evanho** [comment]
> 

不客气，解决了就好~模型文件可以直接在 huggingface上下载：[THUDM/chatglm-6b](https://huggingface.co/THUDM/chatglm-6b/tree/main)
