### ISSUE TITLE
执行的时候在Loading checkpoint shards到50%的时候报Killed退出[BUG/Help] <title>

### ISSUE THREAD

**Issue by 13398808159** [THUDM/ChatGLM-6B#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

环境python 3.8.10，torch 1.11.0或者2.0.0。
按文档一路安装后执行web_demo.py，执行到Loading checkpoint shards到50%的时候退出，提示”Killed“。求助。

aitrain3@aitrain3:~/chatglm-6b/ChatGLM-6B$ python3 web_demo.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  50%|███████████████████████████████████████████████████████████████████▌                                                                   | 4/8 [02:10<02:22, 35.73s/it]Killed

### Steps To Reproduce

no

### Environment

```markdown
- OS:Ubuntu
- Python:3.8.10
- Transformers:4.26.1
- PyTorch:1.11.0 or 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
电脑内存不足，需要大概13GB的空余内存。如果不够的话可以使用量化后的版本，将`THUDM/chatglm-6b`替换成`THUDM/chatglm-6b-int`

**Comment by dashan-cht** [comment]
@13398808159 你好,我也遇到这个问题,请问你的解决了吗. 换成量化后的版本也不行

**Comment by geolvr** [comment]
> @13398808159 你好,我也遇到这个问题,请问你的解决了吗. 换成量化后的版本也不行

请问解决了吗？直接加载int4模型，依然需要十几个g内存。
