### ISSUE TITLE
[Help] Loading checkpoint shards:   0% 出现Killed 

### ISSUE THREAD

**Issue by maxadc** [THUDM/ChatGLM-6B#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

各位大佬好，我是菜鸡。
我在python web_demo.py时 出现 
Loading checkpoint shards:   0% 。。。。。.
Killed 
这是什么问题  是不是需要显卡 我是第一次允许,测试
如果是的话 我的GTX980 可以使用吗 我看了一下 是4G内存

### Steps To Reproduce

正常使用 conda创建环境
pip install -r requirements.txt 安装环境 无报错
python web_demo.py

### Environment

```markdown
- OS: debian
- Python: python3.10
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by 13990008036** [comment]
各位大佬，我在推理codegen25-7b-mono时也遇到这个问题，但是我是V100 32G的GPU，torch也是GPU版本的，一直shards 0% 然后kill

**Comment by 1181000705** [comment]
> 各位大佬，我在推理codegen25-7b-mono时也遇到这个问题，但是我是V100 32G的GPU，torch也是GPU版本的，一直shards 0% 然后kill

可以试试重新开个终端

**Comment by WXLJZ** [comment]
> 已解决，是虚拟机内存分配错误导致，增加内存后已正常。

如何增加虚拟机内存呢？我用的是购买的云服务器。

**Comment by WXLJZ** [comment]
> > 各位大佬，我在推理codegen25-7b-mono时也遇到这个问题，但是我是V100 32G的GPU，torch也是GPU版本的，一直shards 0% 然后kill
> 
> 可以试试重新开个终端

重新开个终端也不行欸，我的GPU配置跟你一样。大佬你具体是怎么解决的呢？
