### ISSUE TITLE
[BUG/Help] chatGLM是否可以联网/在搜索引擎获取最新消息

### ISSUE THREAD

**Issue by zx2021** [THUDM/ChatGLM-6B#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我问了chatGLM，但是他的回答颠三倒四，一会谁可以一会说不行，想求证一下到底行不行

### Steps To Reproduce

.

### Environment

```markdown
- OS:windows10
- Python:3.10
- Transformers:
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :ture
```

**Comment by georgechen1827** [comment]
不行，但你可以把网页上的内容作为输入进行提问

**Comment by AlexZhangji** [comment]
可以配合Google custom search API加入到prompt里.

**Comment by imClumsyPanda** [comment]
可以利用llama-index和langchain实现对输入内容建立索引➡️输入问句匹配索引中内容➡️依据模版将匹配内容+问句形成新问句提出query➡️获得最终回答

**Comment by zerodegress** [comment]
也许可以把搜索结果简单处理后插入到prompts前面

**Comment by zx2021** [comment]
> 可以配合Google custom search API加入到prompt里.

这个要怎么加

**Comment by zx2021** [comment]
> 

这个要怎么加

**Comment by zx2021** [comment]
> 

这个要怎么加

**Comment by 66hh** [comment]
> > 可以配合Google custom search API加入到prompt里.
> 
> 这个要怎么加

你可以试试先抽取输入问题的关键词然后去搜索引擎搜一下然后把搜索到的内容喂给chatglm然后再让chatglm会答提的问题

**Comment by kunshou123** [comment]
> 

你好，这种实现方式有开源的项目可以参考吗

**Comment by kunshou123** [comment]
> 可以利用llama-index和langchain实现对输入内容建立索引➡️输入问句匹配索引中内容➡️依据模版将匹配内容+问句形成新问句提出query➡️获得最终回答
你好，这种实现方式有开源的项目可以参考吗

**Comment by imClumsyPanda** [comment]
@kunshou123 可以看一下这个https://github.com/THUDM/ChatGLM-6B/pull/216

**Comment by imClumsyPanda** [comment]
我前两天刚做了一个基于本地文本的实现，后续可以通过langchain的接口增加html的接入，可以参考一下
[langchain-ChatGLM](https://github.com/imClumsyPanda/langchain-ChatGLM)
