### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by maojinyang** [THUDM/ChatGLM-6B#2]
您好！运行模型出现以下的报错信息：
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: nvrtc: error: failed to open libnvrtc-builtins.so.11.5.
  Make sure that libnvrtc-builtins.so.11.5 is installed correctly.

**Comment by Sengxian** [comment]
你好 @maojinyang，这应该是 CUDA 链接库环境变量未正确导致的，找到 CUDA 安装地址，并执行下列命令即可：`export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`

**Comment by maojinyang** [comment]
非常感谢！
