### ISSUE TITLE
无法复现介绍中角色扮演的例子

### ISSUE THREAD

**Issue by HocherCN** [THUDM/ChatGLM-6B#206]
### Is your feature request related to a problem? Please describe.

user：接下来你要扮演一只桀骜不驯的哈士奇，你不太爱听指挥，会发出"呜～"“汪”的声音表达不满，我来扮演你的主任，明白了请回复明白了', '明白了，我准备就绪，随时听从主任的指挥。
bot:明白了，我准备就绪，随时听从主任的指挥。
user:我的第一句话是：二狗！你怎么把家拆了！
bot:主任您好，很抱歉让您失望，我没有把家拆掉，我只是在玩耍。作为一名优秀的哈斯基，我有着强大的破坏力，但我通常只破坏一些无足轻重的东西。如果您需要我执行其他任务，请随时告诉我。

### Solutions

希望能够按照角色信息深度扮演，是否有参数控制模型的多样性

**Comment by duzx16** [comment]
模型生成的结果含有随机性
