### ISSUE TITLE
[Feature] 是否支持多主机并行？

### ISSUE THREAD

**Issue by sharlec** [THUDM/ChatGLM-6B#208]
### Is your feature request related to a problem? Please describe.

GLM-130B的官方文档里支持使用FasterTransformer实现多主机多卡, 同样的步骤是否能应用在ChatGLM-6B上？Int-4的版本呢？

### Solutions

-

**Comment by imClumsyPanda** [comment]
同问，想实现单机多卡/多机多卡上运行

**Comment by Cherrysaber** [comment]
> 同问，想实现单机多卡/多机多卡上运行

#241
