### ISSUE TITLE
是否可以将chatglm 6b版本或者其finetune版本用于已有互联网产品上

### ISSUE THREAD

**Issue by yanchaoguo** [THUDM/ChatGLM-6B#209]
### Solutions

模型效果很好，请问能否和自家产品相结合提升用户体验

**Comment by zx2021** [comment]
同问

**Comment by markthree** [comment]
有协议描述 👉 [LICENSE](https://github.com/THUDM/ChatGLM-6B/blob/main/LICENSE)，可结合 [GPL、MIT、Apache...一文讲清楚开源协议间的区别](https://zhuanlan.zhihu.com/p/457278398) 来看。

**Comment by duzx16** [comment]
模型的权重使用需要遵守[Model License](https://github.com/THUDM/ChatGLM-6B/blob/main/MODEL_LICENSE)。简单来说，在没有授权的情况下模型禁止商业化应用。

**Comment by liangtongt** [comment]
如何获得授权呢？
