### ISSUE TITLE
如何启动的时候绑定在0.0.0.0上，以便于局域网内访问

### ISSUE THREAD

**Issue by bugxzhu** [THUDM/ChatGLM-6B#210]
### Is your feature request related to a problem? Please describe.

如何启动的时候绑定在0.0.0.0上，以便于局域网内访问

### Solutions

如题

**Comment by Roycent** [comment]
web_demo.py的最后一行加一个listen0.0.0.0的参数
`demo.queue().launch(share=True, inbrowser=True, server_name="0.0.0.0")`

**Comment by guillaumexu** [comment]
单机版的时候能正常用，加了server_name="0.0.0.0"后局域网能访问网页，但是对话的时候会报错：
Something went wrong
Expecting value: line 1 column 1 (char 0)

**Comment by guillaumexu** [comment]
> 

问题解决了，是开了代理
