### ISSUE TITLE
关于chatGLM-6B的embedding API接口

### ISSUE THREAD

**Issue by yumianhuli2** [THUDM/ChatGLM-6B#211]
### Is your feature request related to a problem? Please describe.

请问可以提供将问题或者描述转换成embedding向量的API吗？

### Solutions

通过这个repo提供的chatGLM-6B embedding api可以获取
1、问题或者描述对应的向量
2、向量之间可以提供相似度的计算公式和结果并进行返回

**Comment by cableyang** [comment]
OpenAI's ADA model can be used to represent sentences, and if ChatGLM can also be used for sentence embedding, it would be great

**Comment by georgechen1827** [comment]
我尝试了直接使用ChatGLM的transformer部分输出文本的embedding，感觉效果不是很好，可能需要微调模型或者是找一个好用的prompt

**Comment by zhys513** [comment]
我尝试了直接使用ChatGLM的transformer部分输出文本的embedding，输出4096位embedding，使用相似度算法，实测效果不及chatyuan-v2和chinese_roberta_wwm_ext_large

**Comment by duzx16** [comment]
embedding 一般需要使用专门的模型，用生成模型的 embedding 结果不会太好。

**Comment by datalee** [comment]
mark

**Comment by dinfer** [comment]
@duzx16 如果非常需要embedding API的功能，有哪个模型支持的比较好呢？

**Comment by czhcc** [comment]
我用text2vec-large-chinese模型，使用langchain的HuggingFaceEmbeddings加载调用
