### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### ISSUE THREAD

**Issue by wccccp** [THUDM/ChatGLM-6B#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    model = AutoModel.from_pretrained("/mnt1/wcp/chatglm-6b/model/CHATGLM6.2B", trust_remote_code=True).half().cuda()
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### Expected Behavior

运行web_demo.py

### Steps To Reproduce

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    model = AutoModel.from_pretrained("/mnt1/wcp/chatglm-6b/model/CHATGLM6.2B", trust_remote_code=True).half().cuda()
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by georgezouq** [comment]
same problem, any solution?

**Comment by happy-yu1** [comment]
Have you solved this problem yet

**Comment by happy-yu1** [comment]
> Are you sure you have `configuration_chatglm.py` under `/mnt1/wcp/chatglm-6b/model/CHATGLM6.2B`?

Have you solved this problem yet

**Comment by happy-yu1** [comment]
> same problem, any solution?

Have you solved this problem yet

**Comment by chenwenfeng** [comment]
同问

**Comment by georgezouq** [comment]
> > same problem, any solution?
> 
> Have you solved this problem yet

yes, by replace all config file

**Comment by pengan1987** [comment]
I've compared the `modeling_chatglm.py` from ModelScope and HuggingFace, the only different is line 33:

HuggingFace:
`from .configuration_chatglm import ChatGLMConfig`

ModelScope:
`from configuration_chatglm import ChatGLMConfig`

the extra `.` makes HuggingFace version load `configuration_chatglm.py` from same folder, which is correct behavior.
So if you downloaded model from ModelScope and have this error occurred, just change that line of code in `modeling_chatglm.py`

**Comment by munDane117** [comment]
thanks a lot !!! it do works for me

**Comment by munDane117** [comment]
> I've compared the `modeling_chatglm.py` from ModelScope and HuggingFace, the only different is line 33:
> 
> HuggingFace: `from .configuration_chatglm import ChatGLMConfig`
> 
> ModelScope: `from configuration_chatglm import ChatGLMConfig`
> 
> the extra `.` makes HuggingFace version load `configuration_chatglm.py` from same folder, which is correct behavior. So if you downloaded model from ModelScope and have this error occurred, just change that line of code in `modeling_chatglm.py`

thanks a lot !!! it do works for me

**Comment by houhang1005** [comment]
> I've compared the `modeling_chatglm.py` from ModelScope and HuggingFace, the only different is line 33:
> 
> HuggingFace: `from .configuration_chatglm import ChatGLMConfig`
> 
> ModelScope: `from configuration_chatglm import ChatGLMConfig`
> 
> the extra `.` makes HuggingFace version load `configuration_chatglm.py` from same folder, which is correct behavior. So if you downloaded model from ModelScope and have this error occurred, just change that line of code in `modeling_chatglm.py`

so cool
