### ISSUE TITLE
[Help] model.chat和model.stream_chat有什么区别，使用两种方式同一个问题会得出不一样的答案

### ISSUE THREAD

**Issue by twwch** [THUDM/ChatGLM-6B#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用model.chat
![7ec9c5c5-5415-4e5e-9f02-aa59e59d3eed](https://user-images.githubusercontent.com/44161003/227704554-08f6eed0-66a5-43f4-86e2-e71a2113fca1.jpeg)
![img_v2_55fd8e60-9744-406f-868b-ee174ea8becg](https://user-images.githubusercontent.com/44161003/227704566-11b90aab-da7c-4ac5-bb2b-29c8dbf45374.jpg)

使用model.stream_chat
![3d9b7d95-ff1c-424e-87d0-d8c533ef93ff](https://user-images.githubusercontent.com/44161003/227704597-83223900-3f02-458c-acca-fa8b4b64cbeb.jpeg)
![img_v2_41c1aeb7-e7c5-4a27-9df1-a17a8068608g](https://user-images.githubusercontent.com/44161003/227704604-6c7492b8-25cf-45e2-8221-04f044d260b8.jpg)

或者说界面上的三个参数，model.chat和model.stream_chat有什么区别？

### Steps To Reproduce

使用model.chat
![7ec9c5c5-5415-4e5e-9f02-aa59e59d3eed](https://user-images.githubusercontent.com/44161003/227704554-08f6eed0-66a5-43f4-86e2-e71a2113fca1.jpeg)
![img_v2_55fd8e60-9744-406f-868b-ee174ea8becg](https://user-images.githubusercontent.com/44161003/227704566-11b90aab-da7c-4ac5-bb2b-29c8dbf45374.jpg)

使用model.stream_chat
![3d9b7d95-ff1c-424e-87d0-d8c533ef93ff](https://user-images.githubusercontent.com/44161003/227704597-83223900-3f02-458c-acca-fa8b4b64cbeb.jpeg)
![img_v2_41c1aeb7-e7c5-4a27-9df1-a17a8068608g](https://user-images.githubusercontent.com/44161003/227704604-6c7492b8-25cf-45e2-8221-04f044d260b8.jpg)

或者说界面上的三个参数，model.chat和model.stream_chat有什么区别？

### Environment

```markdown
- OS:Ubuntu 16.04.7 LTS
- Python:3.8.13
- Transformers:4.26.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
模型的生成结果本来就有随机性，跟调用什么接口没有关系。
chat只返回最后的生成结果，而stream_chat是流式生成接口，会返回每一步的生成结果

**Comment by blue-q** [comment]
model.chat在哪个分支里
