### ISSUE TITLE
[BUG/Help] 输入【你好】，回复的是英文结果

### ISSUE THREAD

**Issue by Honei** [THUDM/ChatGLM-6B#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

加载模型之后，输入【你好】之后，回复的是英文结果，和README.MD中响应的结果有差异
<img width="571" alt="image" src="https://user-images.githubusercontent.com/11361692/227705156-a68a5b2b-70d6-4b48-aa26-849171a16648.png">

### Expected Behavior

期望输出的结果【你好👋!我是人工智能助手 ChatGLM-6B,很高兴见到你,欢迎问我任何问题。】

### Steps To Reproduce

1. 加载模型
2. 输入【你好】

### Environment

```markdown
- OS: centos 7.5
- Python: 3.9
- Transformers:
- PyTorch: 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
模型的回复有一定的随机性，可以多试几次
