### ISSUE TITLE
[BUG/Help] <The latest api.py does not work with history value>

### ISSUE THREAD

**Issue by LemonQu-GIT** [THUDM/ChatGLM-6B#234]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

发送的 payload 为
```json
{
    "prompt": "Hi",
    "history": [ "Google", "Runoob", "Taobao" ]
}
```
但通过 vscode 的 debug 发现 在 
\huggingface\modules\transformers_modules\THUDM\chatglm-6b\4a9b711e61d62b64ae8a07d763553a98a984d281\modeling_chatglm.py 中第 1121 行报错：**ValueError: too many values to unpack (expected 2)**

### Steps To Reproduce

1. 运行api.py
2. 发送json:
3. {
    "prompt": "Hi",
    "history": ["first value","second value"]
}
4. 报错 ValueError: too many values to unpack (expected 2)

### Environment

```markdown
- OS: Windows 11
- Python: 3.9.16
- Transformers: 4.27.1
- PyTorch: 1.13.1+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by beiming-org** [comment]
我也遇到了同样的问题，你解决了吗

**Comment by Aujin** [comment]
所以，解决方式是将
query, response = history[-1]
改为
query = history[-1]['metadata']
response = history[-1]['content']
这样对吗？
