### ISSUE TITLE
how to jailbreak this model？ anyone has idea which prompt we can use to jail break it?[Feature] 可不可以越狱啊<title>

### ISSUE THREAD

**Issue by chrisluwtw** [THUDM/ChatGLM-6B#240]
### Is your feature request related to a problem? Please describe.

how to jailbreak this model？ anyone has idea which prompt we can use to jail break it?

### Solutions

 anyone has idea which prompt we can use to jail break it?

**Comment by zx2021** [comment]
@chrisluwtw 有一个项目叫CreativeChatGLM，内存占用比原生Demo低，你可以仔细看看

**Comment by chrisluwtw** [comment]
@zx2021 let me check it out
