### ISSUE TITLE
cpu情况下载使用：THUDM/chatglm-6b 报如下错

### ISSUE THREAD

**Issue by gg22mm** [THUDM/ChatGLM-6B#247]
# 测试 - cpu
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("./chatglm", trust_remote_code=True)
model = AutoModel.from_pretrained("./chatglm",trust_remote_code=True).float()

model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

cpu情况下载使用：THUDM/chatglm-6b 报如下错：
![图片](https://user-images.githubusercontent.com/6648329/227845784-1d4b4269-33c5-4baf-8494-f187c824b960.png)

![图片](https://user-images.githubusercontent.com/6648329/227846562-8448cbbc-4d37-4a93-9636-8b57e1dd6a22.png)

**Comment by ZanoZ** [comment]
志强e5 2650芯片的机器，就别折腾了，算力有点不够看

**Comment by gg22mm** [comment]
> 志强e5 2650芯片的机器，就别折腾了，算力有点不够看

我知道是怎么回事了，我用虚拟机，换用linux系统 就成功了，windos有点不兼容
