### ISSUE TITLE
[BUG/Help] <title>请问有联系方式吗？我这里是中国石油大庆油田勘探开发研究院，能否做个技术交流？

### ISSUE THREAD

**Issue by WangShunzhiDQ** [THUDM/ChatGLM-6B#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我这边想跟您chatglm团队做个技术交流，谢谢

### Expected Behavior

我这边想跟您chatglm团队做个技术交流，谢谢

### Steps To Reproduce

我这边想跟您chatglm团队做个技术交流，谢谢

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
我这边想跟您chatglm团队做个技术交流，谢谢
```

### Anything else?

我这边想跟您chatglm团队做个技术交流，谢谢

**Comment by ZanoZ** [comment]
题主，你们不去看他们的博客吗
