### ISSUE TITLE
我如何使用gpu:0 +  gpu:1 两块卡来运行

### ISSUE THREAD

**Issue by gg22mm** [THUDM/ChatGLM-6B#249]
我有两个卡： 每个分别11G这样，如果单个运行小于13G， 如何能同时使用，因为我两个卡加起来是有23G这样的。
![图片](https://user-images.githubusercontent.com/6648329/227876748-5292a57c-15db-4248-aa80-81040d2438e6.png)

**Comment by duzx16** [comment]
可以尝试在创建模型的 `from_pretrained` 调用加上 `device_map='auto'` 。 这个是transformers提供的功能，你可能需要安装Accelerate库。

**Comment by gg22mm** [comment]
好的谢谢~~

**Comment by sxk000** [comment]
>加载不模型时 用device_map='auto'，可以使用两张卡微调，但是微调训练时的loss='0.0'，一直到训练完还是0。测试微调后的模型，没有内容输出。

CUDA_VISIBLE_DEVICES=0,1 
这样微调时也是使用一个GPU，报GPU资源不足。

有解决的办法吗？或者  如何正确使用多个GPU呢？

谢谢！
