### ISSUE TITLE
The answer is mixed English-Chinese

### ISSUE THREAD

**Issue by waterhorse1** [THUDM/ChatGLM-6B#25]
When I ask some questions, the answer is a mixture of English and Chinese, any solution to this problem?

For example:

I ask: let us play chess! I will take the first step. my move is e4.
ChatGLM-6B: Sure, let's play! Your move is e4, and I'll go with d4 as my first move. It's always good to start with a pawn升变, and d4 is a good choice because it升变后可以攻击对手的中车, which is a weakness in many players' plans.

**Comment by duzx16** [comment]
As we claimed in README, the model is optimized for Chinese QA and dialogue. Most prompts we used for training was Chinese, which might cause the problem.
In our tokenizer, the id range of Chinese tokens is `[83823, 145653)`. One temporary solution is to ban these tokens during sampling,  via the `bad_words_ids` argument of the  `generate` method.

**Comment by waterhorse1** [comment]
thanks for your answer, I find another thing in the prompt design, it seems that you will add some prompts like 【问】and 【答】it is in Chinese so I think it might influence the result
