### ISSUE TITLE
[BUG/Help] <为什么GPU的ChatGLM-6B的性能好于ChatGLM-6B-int4？>

### ISSUE THREAD

**Issue by FdyCN** [THUDM/ChatGLM-6B#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我的设备是 Tesla-V100-32G
给了同样的4个问题：
`question = ["介绍下你自己","晚上睡不着怎么办","小明爸爸抱不起小明，因为他太胖了，请问这里的他是指谁","小明爸爸抱不起小明，因为他太瘦了，请问这里的他是指谁"]`

其中ChatGLM-6B的性能如下：
![image](https://user-images.githubusercontent.com/80800417/228122244-93162c33-d7c1-42fa-ba10-df67dd4815de.png)

而ChatGLM-6B-int4的性能如下：
![image](https://user-images.githubusercontent.com/80800417/228122373-e37e4da9-033d-41be-ad23-5cc2a5a7cb0d.png)

为什么量化之后省了i\o性能还会差这么多呢？ （我理解应该是伪量化，在gpu kernel内部还是convert to float来进行计算的吧，所以计算量应该是差不多的）难道说是因为weights fp32 to int4引入的耗时增加？

PS：另外发现，对于第3、4个小脑筋急转弯的问题，ChatGLM-6B-int4的回答竟然好于ChatGLM-6B。

### Steps To Reproduce

none

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch: 1.12.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zx2021** [comment]
确实在某些情况下int4回答的比原生fp16要强，具体体现在网络工程的专业课大题上面，int4准确性比比fp16高

**Comment by duzx16** [comment]
只量化了模型参数，activation还是有超出int4表示范围的所以没法直接量化
