### ISSUE TITLE
请问输入最长支持多少？

### ISSUE THREAD

**Issue by yc930401** [THUDM/ChatGLM-6B#256]
### Solutions

请问输入最长支持多少？

**Comment by zlh-source** [comment]
输入我试了 感觉没有限制？默认是2048，但是超过后也没进行截断，也没报错

**Comment by terrifyzhao** [comment]
配置里默认是2048，position是rotary ，理论上来说支持无限长，我猜训练的时候设置的最长是2048，超过也能用，但是可能效果有影响？
