### ISSUE TITLE
web_demo

### ISSUE THREAD

**Issue by guhao17** [THUDM/ChatGLM-6B#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我已经在服务器上成功部署并且运行出来，但是试了试网页demo
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app报了这个错误，请问一下该怎么解决呢

### Steps To Reproduce

我已经在服务器上成功部署并且运行出来，但是试了试网页demo
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app报了这个错误，请问一下该怎么解决呢

### Environment

```markdown
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

### Anything else?

no

**Comment by duzx16** [comment]
你的服务器是不是不能联网？可以运行`curl https://status.gradio.app`看下是否有返回结果
如果服务器不能联网的话，你要用ssh隧道把demo运行的端口转发到本地

**Comment by ArlanCooper** [comment]
> curl https://status.gradio.app



> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> 我已经在服务器上成功部署并且运行出来，但是试了试网页demo Could not create share link. Please check your internet connection or our status page: [https://status.gradio.app报了这个错误，请问一下该怎么解决呢](https://status.gradio.app%E6%8A%A5%E4%BA%86%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%80%E4%B8%8B%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> 我已经在服务器上成功部署并且运行出来，但是试了试网页demo Could not create share link. Please check your internet connection or our status page: [https://status.gradio.app报了这个错误，请问一下该怎么解决呢](https://status.gradio.app%E6%8A%A5%E4%BA%86%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%80%E4%B8%8B%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2)
> 
> ### Environment
> ```gfm
> Python: 3.8
> Transformers: 4.26.1
> PyTorch: 1.12
> CUDA Support: True
> ```
> 
> ### Anything else?
> no



> 

请问这个问题解决了吗，我现在也是这个问题，但是可以联网的

**Comment by 12lxr** [comment]
> 

有返回结果，结果是一大段html，请问是什么意思呢？我的问题是运行web_demo脚本后，一直没有反应，没有结果
