### ISSUE TITLE
position_ids 的获取是不是有问题？

### ISSUE THREAD

**Issue by songyingxin** [THUDM/ChatGLM-6B#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/13884292/228162842-113ef298-dd8d-41e0-a2cf-f465de2956c7.png)

### Expected Behavior

这行代码是不是应该改为：context_length = len(seq)

因为如果输入进行padding的话， 比如假设输入长度最大为 50， 当前输入文本为40的话，42个字符是bos_token，之后都是 pad_token 进行填充。
那么此时，context_length 的长度就不是50了，而是42，这会导致后面的计算出错

### Steps To Reproduce

输入数据的处理为：
text_token = self.tokenizer(
            text, 
            truncation=True,
            max_length=self.max_length,
            padding="max_length" )

### Environment

```markdown
无
```

### Anything else?

无

**Comment by duzx16** [comment]
感谢指出。之前没有考虑batch生成的情况，所以没有考虑padding
