### ISSUE TITLE
请问huggingface中00002系列和00008系列模型有什么区别？

### ISSUE THREAD

**Issue by rayvzn119** [THUDM/ChatGLM-6B#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/85482204/228163524-0af69a5c-a875-4fc5-9d84-dd7f62346cbe.png)
![image](https://user-images.githubusercontent.com/85482204/228163583-9b68c8b4-c174-437c-b6c2-745967e51e38.png)

ru如图，发现有一个00002模型和一个00008模型，请问这两个有啥区别呢？加载哪一个合适？

### Expected Behavior

如上

### Steps To Reproduce

如上

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

如上

**Comment by duzx16** [comment]
没有区别。只是把checkpoint切分成了不同数量的片段
