### ISSUE TITLE
[Feature] <如何更改下载目录>

### ISSUE THREAD

**Issue by ShiroNYami** [THUDM/ChatGLM-6B#263]
### Is your feature request related to a problem? Please describe.

如何更改下载目录

### Solutions

我之前没有用过Python,出于兴趣跟着文档搭了一个项目，但是发现项目启动时下载的数据全部默认下载在C盘，导致我C盘几乎爆掉了，请问如何修改下载目录？

![image](https://user-images.githubusercontent.com/23102334/228195848-7606d5d9-d93f-4faa-ad8e-5fd10d80ad47.png)

**Comment by duzx16** [comment]
在代码里的`from_pretrained`调用中增加`cache_dir=your local path`

**Comment by ShiroNYami** [comment]
感谢
