### ISSUE TITLE
[Feature] <隐状态清理>

### ISSUE THREAD

**Issue by junleeee** [THUDM/ChatGLM-6B#273]
### Is your feature request related to a problem? Please describe.

目前部署发现，多用户使用时，不同问题之前可能会出现干扰（不同用户之间history是独立传递的），比如一个用户的内容，可能会出现在另一个用户的回答里

### Solutions

提供一个能清理服务内部隐状态的接口

**Comment by duzx16** [comment]
现在main分支的api.py是没有记录历史信息的，只会通过POST请求的history参数来获取历史

**Comment by junleeee** [comment]
> 现在main分支的api.py是没有记录历史信息的，只会通过POST请求的history参数来获取历史

所以可以理解成如果history为空的话，不同问题之间是不会干扰吗

**Comment by duzx16** [comment]
> > 现在main分支的api.py是没有记录历史信息的，只会通过POST请求的history参数来获取历史
> 
> 所以可以理解成如果history为空的话，不同问题之间是不会干扰吗

是的
