### ISSUE TITLE
[Feature] <关于代码重构>

### ISSUE THREAD

**Issue by Ther-nullptr** [THUDM/ChatGLM-6B#276]
### Is your feature request related to a problem? Please describe.

一个小建议：能否新建一个分支，把模型的前向传播和量化部分的核心代码也放到主仓库里，而不是像现在这样和huggingface checkpoint放在一个文件夹里，这样开发人员debug和重构会方便一些。谢谢！

### Solutions

A simple answer

**Comment by duzx16** [comment]
主要是huggingface repo如果不放代码的话就没法很方便地用AutoModel加载。而如果两边都放的话同步起来会比较麻烦。
你可以把huggingface repo clone到本地然后修改代码，然后from_pretrained的时候从本地加载
