### ISSUE TITLE
[Help] How to fix the seed to get deterministic response  

### ISSUE THREAD

**Issue by weimingzha0** [THUDM/ChatGLM-6B#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For performance test purpose, how to make it always return the same response for the same input and history?

Thanks

### Steps To Reproduce

NA

### Environment

```markdown
Ubuntu
```

**Comment by duzx16** [comment]
Add the following code
```
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.backends.cudnn.deterministic = True
```

**Comment by Maggiebj** [comment]
It still fail to get reproducible results after add these seed settings above.
