### ISSUE TITLE
[BUG/Help] <模型微调，做行业大模型训练微调如何做啊>

### ISSUE THREAD

**Issue by luieswww** [THUDM/ChatGLM-6B#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

无

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
- OS:windows
- Python:3.10
- Transformers:4.26
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

### Anything else?

无

**Comment by hscspring** [comment]
LoRA微调方案：
https://github.com/hscspring/hcgf

**Comment by luieswww** [comment]
好的谢谢

**Comment by duzx16** [comment]
仓库里已经实现了P-Tuning微调 https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning
