### ISSUE TITLE
[BUG/Help] Tokenizer Can't be hashed when num_proc >1

### ISSUE THREAD

**Issue by dumpmemory** [THUDM/ChatGLM-6B#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting num_proc >1 for dataset.map function ，the map processing can't continue due to tokenizer object can't be hashed. 

### Steps To Reproduce

1. init tokenizer
2. datasets.fingerprint.Hasher.hash(tokenizer)

### Environment

```markdown
- OS:docker centos 7
- Python: 3.8
- Transformers: 4.27.1
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by robert-weiqian** [comment]
你的问题解决了吗？我目前是同样的问题，我实在windows10下面的wsl2里面操作出现的，主要问题是evaluate.sh运行时出现这个错误。
