### ISSUE TITLE
想咨询一个结论: 自己准备文本，通过ptuning微调、可以使chatglm“掌握”文本中的知识，对吗？(如，全程一张3080ti 12G显存)

### ISSUE THREAD

**Issue by jiaozn** [THUDM/ChatGLM-6B#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

以前12g显存训练是不够的

### Steps To Reproduce

使用ptuning-v2

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by hscspring** [comment]
理论上如此。

**Comment by jiaozn** [comment]
> 理论上如此。

Thax!
Inspiring! I can't wait to take a shot!
