### ISSUE TITLE
[Help] 微调之后该如何应用

### ISSUE THREAD

**Issue by xuguozhi** [THUDM/ChatGLM-6B#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ptuning之后的模型该怎么应用呢，比如应用于web_demo2.py中

### Steps To Reproduce

python3 web_demo2.py

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
只要将web_demo2.py中`AutoModel.from_pretrained`的第一个参数改成ptuning之后的checkpoint的地址（在示例中是./output/adgen-chatglm-6b-pt-8-1e-2/checkpoint-3000）
注意，因为目前的微调还不支持多轮数据，所以只有对话的第一轮的回复是经过微调的

**Comment by doublexxking** [comment]
之前对话的内容不是会cache下来，理论上ptuning只是更新了模型参数没改变这个功能，为什么说“只有对话的第一轮的回复是经过微调的”。
