### ISSUE TITLE
[BUG/Help] 推理的时候怎么设置，来让模型输出的结果有随机性

### ISSUE THREAD

**Issue by puppet101** [THUDM/ChatGLM-6B#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 推理的时候怎么设置，来让模型输出不同的结果，现在让讲个笑话，每次都讲同一个笑话

### Steps To Reproduce

求助

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zhaodice** [comment]
温度拉高

**Comment by puppet101** [comment]
试过了，改成0.9，连续输入讲一个笑话，很大概率连续讲同一个笑话。和chatgpt比起来重复度有点太高了，还有别的策略增加随机性吗？

**Comment by zhaodice** [comment]
> 试过了，改成0.9，连续输入讲一个笑话，很大概率连续讲同一个笑话。和chatgpt比起来重复度有点太高了，还有别的策略增加随机性吗？

也可能是模型本身就很小，所以它学的笑话就这么点，自己微调吧！

**Comment by duzx16** [comment]
> 试过了，改成0.9，连续输入讲一个笑话，很大概率连续讲同一个笑话。和chatgpt比起来重复度有点太高了，还有别的策略增加随机性吗？

temperature是越高随机性越强的，默认的temperature是0.95
另外就是像“讲一个笑话”这种general的指示确实有可能随机性就是比较弱的
