### ISSUE TITLE
[BUG/Help] _no_split_modules = ["GLM6BBlock"] setting need to be changed to _no_split_modules = ["GLMBlock"]

### ISSUE THREAD

**Issue by dumpmemory** [THUDM/ChatGLM-6B#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

there is a typo in model_chatglm.py which should be fixed. 

 _no_split_modules = ["GLM6BBlock"] setting need to be changed to _no_split_modules = ["GLMBlock"]

### Steps To Reproduce

1. change name

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
Merged. Thanks for your contribution.
