### ISSUE TITLE
[BUG/Help] <title>hugging face chatglm-6b似乎缺少某个属性`enable_input_require_grads`

### ISSUE THREAD

**Issue by WhisperChi** [THUDM/ChatGLM-6B#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

基于当前最新代码 [7e84262ddc342798a04ad034fee75ad3432d75e3](https://github.com/THUDM/ChatGLM-6B/commit/7e84262ddc342798a04ad034fee75ad3432d75e3)

基于当前最新模型[2e1be30ac40990739f608f1b186e72bfd8ff4ed6](https://huggingface.co/THUDM/chatglm-6b/commit/2e1be30ac40990739f608f1b186e72bfd8ff4ed6)

下载模型到本地，train.sh修改为本地路径，执行
```shell
bash train.sh
```
报错如下：
`AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'`
查了下huggingface最新提交，似乎确实没有该属性。[2e1be30ac40990739f608f1b186e72bfd8ff4ed6](https://huggingface.co/THUDM/chatglm-6b/commit/2e1be30ac40990739f608f1b186e72bfd8ff4ed6)

### Steps To Reproduce

1. clone本项目代码，git reset 7e84262ddc342798a04ad034fee75ad3432d75e3
2. clone model，git reset 2e1be30ac40990739f608f1b186e72bfd8ff4ed6
3. 修改train.sh，执行本地模型
4. 运行tarin.sh
按照此步骤，就会报错。看了下模型代码（2e1be30ac40990739f608f1b186e72bfd8ff4ed6），`ChatGLMForConditionalGeneration`中确实无`enable_input_require_grads`属性

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Python:Python 3.10.6
- Transformers:transformers             4.26.1
- PyTorch:    torch                    2.0.0   ; torchvision              0.15.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True;  NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0  
```

**Comment by duzx16** [comment]
这个方法是在4.27版本的transformers库里实现的，已经更新了README里的版本要求。

**Comment by huangtao36** [comment]
我将transformers 升级到了4.27.1， 但还是出现AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'的错误

**Comment by WhisperChi** [comment]
> 更新transformers 库 就行, 这个在4.27 应该就有了 peft那移植过来的

谢谢，已经成功运行。

**Comment by WhisperChi** [comment]
> 这个方法是在4.27版本的transformers库里实现的，已经更新了README里的版本要求。

谢谢，已经成功运行。

**Comment by xiao-huichen** [comment]
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'float32'
请问一下各位牛人，这个bug怎么解决呢？
