### ISSUE TITLE
[BUG/Help] bash train.sh后报错 TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by JulyFinal** [THUDM/ChatGLM-6B#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在ptuning目录下执行bash train.sh后报错TypeError: quote_from_bytes() expected bytes
模型是正常运行的，只有在训练时候才出现这个问题

日志如下：
```
03/31/2023 14:53:22 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
03/31/2023 14:53:22 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.01,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=passive,
log_on_each_node=True,
logging_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev/runs/Mar31_14-53-22_NLP,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=output/adgen-chatglm-6b-pt-8-1e-2-dev,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
03/31/2023 14:53:22 - WARNING - datasets.builder - Found cached dataset json (/home/final/.cache/huggingface/datasets/json/default-23a7d84e1000a33e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 438.00it/s]
[INFO|configuration_utils.py:660] 2023-03-31 14:53:43,884 >> loading configuration file config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/config.json
[WARNING|configuration_auto.py:861] 2023-03-31 14:53:43,884 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:660] 2023-03-31 14:58:37,535 >> loading configuration file config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/config.json
[INFO|configuration_utils.py:712] 2023-03-31 14:58:37,536 >> Model config ChatGLMConfig {
  "_name_or_path": "THUDM/chatglm-6b",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 20003,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.26.1",
  "use_cache": true,
  "vocab_size": 150528
}

[WARNING|tokenization_auto.py:631] 2023-03-31 14:58:48,477 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file ice_text.model from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/ice_text.model
[INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file special_tokens_map.json from cache at None
[INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file tokenizer_config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/tokenizer_config.json
Traceback (most recent call last):
  File "/data/workspace/ChatGLM-6B/ptuning/main.py", line 389, in <module>
    main()
  File "/data/workspace/ChatGLM-6B/ptuning/main.py", line 113, in main
    model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, revision=True, trust_remote_code=True)
  File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 261, in get_cached_module_file
    commit_hash = model_info(pretrained_model_name_or_path, revision=revision, token=token).sha
  File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1616, in model_info
    else (f"{self.endpoint}/api/models/{repo_id}/revision/{quote(revision, safe='')}")
  File "/home/final/miniforge3/envs/py3/lib/python3.10/urllib/parse.py", line 869, in quote
    return quote_from_bytes(string, safe)
  File "/home/final/miniforge3/envs/py3/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

```

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS: Ubuntu18.04LTS
- Python: 3.10
- Transformers: 4.26.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by WhisperChi** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> 在ptuning目录下执行bash train.sh后报错TypeError: quote_from_bytes() expected bytes 模型是正常运行的，只有在训练时候才出现这个问题
> 
> 日志如下：
> 
> ```
> 03/31/2023 14:53:22 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
> 03/31/2023 14:53:22 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
> _n_gpu=1,
> adafactor=False,
> adam_beta1=0.9,
> adam_beta2=0.999,
> adam_epsilon=1e-08,
> auto_find_batch_size=False,
> bf16=False,
> bf16_full_eval=False,
> data_seed=None,
> dataloader_drop_last=False,
> dataloader_num_workers=0,
> dataloader_pin_memory=True,
> ddp_bucket_cap_mb=None,
> ddp_find_unused_parameters=None,
> ddp_timeout=1800,
> debug=[],
> deepspeed=None,
> disable_tqdm=False,
> do_eval=False,
> do_predict=False,
> do_train=True,
> eval_accumulation_steps=None,
> eval_delay=0,
> eval_steps=None,
> evaluation_strategy=no,
> fp16=False,
> fp16_backend=auto,
> fp16_full_eval=False,
> fp16_opt_level=O1,
> fsdp=[],
> fsdp_min_num_params=0,
> fsdp_transformer_layer_cls_to_wrap=None,
> full_determinism=False,
> generation_max_length=None,
> generation_num_beams=None,
> gradient_accumulation_steps=16,
> gradient_checkpointing=False,
> greater_is_better=None,
> group_by_length=False,
> half_precision_backend=auto,
> hub_model_id=None,
> hub_private_repo=False,
> hub_strategy=every_save,
> hub_token=<HUB_TOKEN>,
> ignore_data_skip=False,
> include_inputs_for_metrics=False,
> jit_mode_eval=False,
> label_names=None,
> label_smoothing_factor=0.0,
> learning_rate=0.01,
> length_column_name=length,
> load_best_model_at_end=False,
> local_rank=-1,
> log_level=passive,
> log_level_replica=passive,
> log_on_each_node=True,
> logging_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev/runs/Mar31_14-53-22_NLP,
> logging_first_step=False,
> logging_nan_inf_filter=True,
> logging_steps=10,
> logging_strategy=steps,
> lr_scheduler_type=linear,
> max_grad_norm=1.0,
> max_steps=3000,
> metric_for_best_model=None,
> mp_parameters=,
> no_cuda=False,
> num_train_epochs=3.0,
> optim=adamw_hf,
> optim_args=None,
> output_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev,
> overwrite_output_dir=True,
> past_index=-1,
> per_device_eval_batch_size=1,
> per_device_train_batch_size=1,
> predict_with_generate=True,
> prediction_loss_only=False,
> push_to_hub=False,
> push_to_hub_model_id=None,
> push_to_hub_organization=None,
> push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
> ray_scope=last,
> remove_unused_columns=True,
> report_to=[],
> resume_from_checkpoint=None,
> run_name=output/adgen-chatglm-6b-pt-8-1e-2-dev,
> save_on_each_node=False,
> save_steps=1000,
> save_strategy=steps,
> save_total_limit=None,
> seed=42,
> sharded_ddp=[],
> skip_memory_metrics=True,
> sortish_sampler=False,
> tf32=None,
> torch_compile=False,
> torch_compile_backend=None,
> torch_compile_mode=None,
> torchdynamo=None,
> tpu_metrics_debug=False,
> tpu_num_cores=None,
> use_ipex=False,
> use_legacy_prediction_loop=False,
> use_mps_device=False,
> warmup_ratio=0.0,
> warmup_steps=0,
> weight_decay=0.0,
> xpu_backend=None,
> )
> 03/31/2023 14:53:22 - WARNING - datasets.builder - Found cached dataset json (/home/final/.cache/huggingface/datasets/json/default-23a7d84e1000a33e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
> 
>   0%|          | 0/2 [00:00<?, ?it/s]
> 100%|██████████| 2/2 [00:00<00:00, 438.00it/s]
> [INFO|configuration_utils.py:660] 2023-03-31 14:53:43,884 >> loading configuration file config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/config.json
> [WARNING|configuration_auto.py:861] 2023-03-31 14:53:43,884 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
> [INFO|configuration_utils.py:660] 2023-03-31 14:58:37,535 >> loading configuration file config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/config.json
> [INFO|configuration_utils.py:712] 2023-03-31 14:58:37,536 >> Model config ChatGLMConfig {
>   "_name_or_path": "THUDM/chatglm-6b",
>   "architectures": [
>     "ChatGLMModel"
>   ],
>   "auto_map": {
>     "AutoConfig": "configuration_chatglm.ChatGLMConfig",
>     "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
>     "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
>   },
>   "bos_token_id": 150004,
>   "eos_token_id": 150005,
>   "hidden_size": 4096,
>   "inner_hidden_size": 16384,
>   "layernorm_epsilon": 1e-05,
>   "max_sequence_length": 2048,
>   "model_type": "chatglm",
>   "num_attention_heads": 32,
>   "num_layers": 28,
>   "pad_token_id": 20003,
>   "position_encoding_2d": true,
>   "pre_seq_len": null,
>   "prefix_projection": false,
>   "quantization_bit": 0,
>   "torch_dtype": "float16",
>   "transformers_version": "4.26.1",
>   "use_cache": true,
>   "vocab_size": 150528
> }
> 
> [WARNING|tokenization_auto.py:631] 2023-03-31 14:58:48,477 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> [INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file ice_text.model from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/ice_text.model
> [INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file added_tokens.json from cache at None
> [INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file special_tokens_map.json from cache at None
> [INFO|tokenization_utils_base.py:1802] 2023-03-31 15:01:10,453 >> loading file tokenizer_config.json from cache at /home/final/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/2e1be30ac40990739f608f1b186e72bfd8ff4ed6/tokenizer_config.json
> Traceback (most recent call last):
>   File "/data/workspace/ChatGLM-6B/ptuning/main.py", line 389, in <module>
>     main()
>   File "/data/workspace/ChatGLM-6B/ptuning/main.py", line 113, in main
>     model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, revision=True, trust_remote_code=True)
>   File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
>     model_class = get_class_from_dynamic_module(
>   File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
>     final_module = get_cached_module_file(
>   File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 261, in get_cached_module_file
>     commit_hash = model_info(pretrained_model_name_or_path, revision=revision, token=token).sha
>   File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/data/workspace/ChatGLM-6B/.venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1616, in model_info
>     else (f"{self.endpoint}/api/models/{repo_id}/revision/{quote(revision, safe='')}")
>   File "/home/final/miniforge3/envs/py3/lib/python3.10/urllib/parse.py", line 869, in quote
>     return quote_from_bytes(string, safe)
>   File "/home/final/miniforge3/envs/py3/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
>     raise TypeError("quote_from_bytes() expected bytes")
> TypeError: quote_from_bytes() expected bytes
> ```
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> bash train.sh
> 
> ### Environment
> ```gfm
> - OS: Ubuntu18.04LTS
> - Python: 3.10
> - Transformers: 4.26.1
> - PyTorch: 2.0.0
> - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
> ```
> 
> ### Anything else?
> _No response_

试试升级下 transformers，参照最新的 requirements.txt ，升级到 4.27

**Comment by 13665832220** [comment]
升级到最新的后，还是会报错啊。TypeError: expected string or bytes-like object

**Comment by JulyFinal** [comment]
> 抱歉原来的代码加载huggingface repo的模型存在bug，已修复
hah 我也说，终于跑起来了，谢谢
