### ISSUE TITLE
[Feature] Supports llama.cpp

### ISSUE THREAD

**Issue by linouxis9** [THUDM/ChatGLM-6B#296]
### Solutions

Provide instructions on how your models might be converted to ggml and used with https://github.com/ggerganov/llama.cpp

### Additional context

llama.cpp is a fast CPU-optimized inference tool which supports various (LLaMa and non-LLaMa based models)

**Comment by fishfree** [comment]
+1

**Comment by PenutChen** [comment]
There might be more information in [ggml](https://github.com/ggerganov/ggml), since they have conversion scripts that can convert model weights from HuggingFace format to ggml format, located in [examples/gpt-j](https://github.com/ggerganov/ggml/blob/master/examples/gpt-j/convert-h5-to-ggml.py) and [examples/gpt-2](https://github.com/ggerganov/ggml/blob/master/examples/gpt-2/convert-h5-to-ggml.py).

**Comment by lindeer** [comment]
hey @PenutChen, did you have a successful try?  some keys in `config.json` required for gpt-j did not exist in  `config.json` of chatglm, so error occured when writing data info into `ggml-model-f16.bin`:
```
fout.write(struct.pack("i", hparams["n_embd"]))
fout.write(struct.pack("i", hparams["n_head"]))
fout.write(struct.pack("i", hparams["n_layer"]))
fout.write(struct.pack("i", hparams["rotary_dim"]))
```
do you know what are coresponding keys in `config.json` of chatglm? seems the model format is not h5...

**Comment by chenqy4933** [comment]
this feature has supported in https://github.com/MegEngine/InferLLM

**Comment by zhaohb** [comment]
Now llama.cpp has gpu support, will chatglm-6b continue to be updated to support gpu inference？

**Comment by JACKHAHA363** [comment]
+1 I think it's useful because I find that the current quantization int4 somehow decrease the inference speed on my GPU, while I always see speed improvement with llama.cpp quantization

**Comment by li-plus** [comment]
Maybe you can try https://github.com/li-plus/chatglm.cpp. It's written in the same way as llama.cpp based on GGML. Quantization does help to improve inference speed.

**Comment by zhaohb** [comment]
@li-plus  Great thing, is there a plan to support gpu inference？

**Comment by li-plus** [comment]
> @li-plus Great thing, is there a plan to support gpu inference？

Sure there is. I'll make it infer-able on a consumer GPU.
