### ISSUE TITLE
请问会开放训练代码么？

### ISSUE THREAD

**Issue by zjcanjux** [THUDM/ChatGLM-6B#3]
还是说，transformers加载模型后，后续训练代码，用rlhf，自行实现，再在自己语料上，继续训练即可？

**Comment by Sengxian** [comment]
模型已经开源至 [Hugging Face Hub](https://huggingface.co/THUDM/chatglm-6b)，可以直接利用 HF Trainer 等进行训练；RLHF 部分，亦可以直接利用 [trlx](https://github.com/CarperAI/trlx) 等库进行实现。

**Comment by zjcanjux** [comment]
好的，谢谢

**Comment by XingLuxi** [comment]
您发给我的信件已经收到，我会尽快查收并回复您。Your e-mail has been received, I will reply as soon as possible.邢璐茜

**Comment by zhangsanfeng86** [comment]
> 模型已经开源至 [Hugging Face Hub](https://huggingface.co/THUDM/chatglm-6b)，可以直接利用 HF Trainer 等进行训练；RLHF 部分，亦可以直接利用 [trlx](https://github.com/CarperAI/trlx) 等库进行实现。

-------------------------------------------
Hi @Sengxian 
使用hf的trainer可以跑训练，不过，在保存模型时候，报错了：
VOCAB_FILES_NAMES  not found

**Comment by fotomxq** [comment]
可以参考：https://github.com/yuanzhoulvpi2017/zero_nlp

**Comment by zhangtaochn** [comment]
> 可以参考：https://github.com/yuanzhoulvpi2017/zero_nlp

感谢，已经成功train起来了，python3.8上没有包不兼容的错误

**Comment by RRRoger** [comment]
> > 可以参考：https://github.com/yuanzhoulvpi2017/zero_nlp
> 
> 感谢，已经成功train起来了，python3.8上没有包不兼容的错误

请问训练是否达到预期效果？

**Comment by zhangtaochn** [comment]
> > > 可以参考：https://github.com/yuanzhoulvpi2017/zero_nlp
> > 
> > 
> > 感谢，已经成功train起来了，python3.8上没有包不兼容的错误
> 
> 请问训练是否达到预期效果？

不达预期，能跑通，但是我测试发现训练没产生效果。我用了另一个项目，https://github.com/ssbuild/chatglm_finetuning  ，亲测可用。
