### ISSUE TITLE
[BUG/Help] [BUG/Help] 使用最新的ptuning下的train.sh脚本进行finetune时出错 AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### ISSUE THREAD

**Issue by mzh1996** [THUDM/ChatGLM-6B#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/data/mzh/nlp/ChatGLM_dev/ChatGLM-6B-main/ptuning/main.py", line 389, in <module>
    main()
  File "/data/mzh/nlp/ChatGLM_dev/ChatGLM-6B-main/ptuning/main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/data/mzh/tf423/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Steps To Reproduce

sh ./train.sh

### Environment

```markdown
- OS:red het
- Python:3.9.12
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by panxb833** [comment]
需要更新最新的代码，https://huggingface.co/THUDM/chatglm-6b/tree/main

**Comment by mzh1996** [comment]
> 

我看您的模型文件都是18天前的
是不是我把除了.bin文件以外的其它文件都更新为最新版的即可？

**Comment by mzh1996** [comment]
> 需要更新最新的代码，https://huggingface.co/THUDM/chatglm-6b/tree/main

我看您的模型文件都是18天前的
是不是我把除了.bin文件以外的其它文件都更新为最新版的即可？

**Comment by jiaozn** [comment]
> > > 需要更新最新的代码，https://huggingface.co/THUDM/chatglm-6b/tree/main
> > 
> > 
> > 我看您的模型文件都是18天前的 是不是我把除了.bin文件以外的其它文件都更新为最新版的即可？
> 
> 所以，结论是？

——结论：是的，bin不用重新下载；其他文件更新即可

**Comment by 4IK1d** [comment]
Actually, a `git pull` will save you all efforts.

**Comment by lunar333** [comment]
> Actually, a `git pull` will save you all efforts.

你好，我也遇到了这个问题，git pull过了，transfoemer版本4.27.4，还是有这个报错，求指点
(glm) zhonghuihang@kdf-B660-AORUS-MASTER-DDR4:~/ChatGLM-6B/ptuning$ git pull
已经是最新的。


Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Loading prefix_encoder weight from /home/zhonghuihang/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.36it/s]
Traceback (most recent call last):
  File "/home/zhonghuihang/ChatGLM-6B/ptuning/web_demo.py", line 166, in <module>
    main()
  File "/home/zhonghuihang/ChatGLM-6B/ptuning/web_demo.py", line 147, in main
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
  File "/home/zhonghuihang/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
