### ISSUE TITLE
当不设置 pre_seq_len 参数时候，prefix_encoder就无法初始化，我认为这点需要改动

### ISSUE THREAD

**Issue by songyingxin** [THUDM/ChatGLM-6B#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当不设置pre_seq_len 时候，会报错：AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'， 
仔细看了下是 modeling_chatglm.py 第798行的判断导致的。

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

无

**Comment by hyoau** [comment]
请问一下您是怎么解决这个报错的呢？

**Comment by duzx16** [comment]
已支持 full finetune
