### ISSUE TITLE
[Feature] 基于本地知识的 chatglm 应用，利用 langchain，可私有部署、全开源模型

### ISSUE THREAD

**Issue by imClumsyPanda** [THUDM/ChatGLM-6B#307]
### Solutions

项目地址：[langchain-ChatGLM](https://github.com/imClumsyPanda/langchain-ChatGLM)

受 [GanymedeNil](https://github.com/GanymedeNil) 的项目 [document.ai](https://github.com/GanymedeNil/document.ai) 和 [AlexZhangji](https://github.com/AlexZhangji) 创建的 [ChatGLM-6B Pull Request](https://github.com/THUDM/ChatGLM-6B/pull/216) 启发，建立了全部基于开源模型实现的本地知识问答应用。

Embedding 选用的是 [GanymedeNil/text2vec-large-chinese](https://huggingface.co/GanymedeNil/text2vec-large-chinese/tree/main)，LLM 选用的是 [ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B)。依托上述模型，本项目可实现全部使用**开源**模型**离线私有部署**。

**Comment by l15y** [comment]
我这个除你的功能，还基于vue实现了webui。https://github.com/l15y/wenda

**Comment by imClumsyPanda** [comment]
@l15y 被您这个项目碾压了😢

**Comment by l15y** [comment]
> @l15y 被您这个项目碾压了😢

也不完善，精力有限。
欢迎提建议

**Comment by imClumsyPanda** [comment]
@ZanoZ 谢谢🙏🙏 我会继续努力完善的

**Comment by duzx16** [comment]
已加入README中
