### ISSUE TITLE
是否可以增加持续学习的功能？

### ISSUE THREAD

**Issue by Stupid-Ai** [THUDM/ChatGLM-6B#308]
### Is your feature request related to a problem? Please describe.

最近也是使用了ChatGLM-6B来进行微调，虽然可以让他成功记住新的内容但是整个过程是非常漫长的，并且当需要微调的数据不多但需要一直更新时这个过程坑定是非常痛苦的。是否可以通过反馈学习以及增量学习的方式来实现模型的持续学习微调？

### Solutions

最近我也研究了很多持续学习的开源库、但是还不知道能否在ChatGLM-6B上实现。以下是我了解的一两个开源库：
https://github.com/online-ml/river
https://github.com/GMvandeVen/continual-learning
https://github.com/G-U-N/PyCIL

**Comment by ZanoZ** [comment]
我的观点，不一定正确：
持续学习是个很有诱惑力的topic，利用这个功能，貌似我们就可以更懒，更省力。。。
但是，在我们可以更懒的反面，机器的能力会更加突出，嗯，换个词来说，更加失控，可能更准确一点。

我们在爬越高山的时候，要清醒地意识到，对我们来说，那也不是高山，而是深渊

**Comment by ZanoZ** [comment]
嗯，BlenderBot3我没了解过。回头我去看看
对于你说的第二段。我保持谨慎。算法现在已经接近或者已经进入到作者也无法预测算法输出结果的程度。只不过我们国家的公开模型还没有达到量变质变的临界点而已。
对于智能的产生过程，人脑本身也是类似的量变到质变，从简单的逻辑推理能力，发展到有认知能力，忽然有一天，人脑就有自我意识了。我们对此要保持警惕和自我了解。也许，在这个维度方面，也许我们需要其他学科的人来介入，而我们要退后一步以扩展我们的视野，不能局限在技术本身。否则，我们和疯狂科学家就没什么2样了。

呃，乱七八糟写了一堆，见笑了，希望担心的不会成为现实吧。也希望更多的人能意识到这一点，在埋头技术努力推进的时候，能有所调整和留意。

**Comment by zhangxiaoyuan1988** [comment]
我最近也再研究用强化学习ppo，看看能不能优化glm模型，大佬有进展吗？

**Comment by jerry1993-tech** [comment]
我感觉 chatGLM-6B 已经是rlhf后chat化了，是不是可以在 glm-10B得模型上做一些强化学习增强的尝试，我们也在做这方面的尝试，感兴趣的可以交流一下。

10B的地址： https://github.com/THUDM/GLM
