### ISSUE TITLE
Error When ptuning

### ISSUE THREAD

**Issue by zhangsanfeng86** [THUDM/ChatGLM-6B#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi ,
When try to ptuning, Run trian.sh, then get Error:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/73547638/229144453-f72c8a02-2100-4cb8-a330-b82e38f7418a.png">

### Expected Behavior

Get Error

### Steps To Reproduce

Run train.sh

### Environment

```markdown
- OS: Ununtu20.04
- Python:3.8
- Transformers:4.27.0
- PyTorch:1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

None

**Comment by duzx16** [comment]
Are you using the latest model from huggingface repo?

**Comment by pootow** [comment]
The same here.
@duzx16 I've just run the `train.sh` script. How can we use the latest model?

**Comment by zhangsanfeng86** [comment]
yes, should update the latest model
@duzx16 Thank U!

**Comment by pootow** [comment]
@zhangsanfeng86 how do you update the model?
