### ISSUE TITLE
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### ISSUE THREAD

**Issue by wly-thu** [THUDM/ChatGLM-6B#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[INFO|trainer.py:511] 2023-04-01 00:09:18,357 >> max_steps is given, it will override any value given in num_train_epochs
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    main()
  File "main.py", line 328, in main
    model.enable_input_require_grads()
  File "/home/.conda/envs/chatglm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by natureLanguageQing** [comment]
'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'
我也遇到了这个问题

**Comment by wly-thu** [comment]
solve

**Comment by pootow** [comment]
升级transformer，注意看readme里面的版本
