### ISSUE TITLE
[BUG/Help] 不加此选项:quantization_bit,  报错

### ISSUE THREAD

**Issue by zhangsanfeng86** [THUDM/ChatGLM-6B#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="861" alt="image" src="https://user-images.githubusercontent.com/73547638/229286293-115270f2-9aa1-4295-bf15-14a1e26c0ce5.png">

### Steps To Reproduce

./train.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
不太理解，你能更详细的说明一下你对代码做了哪些改动吗？

**Comment by zhangsanfeng86** [comment]
> 不太理解，你能更详细的说明一下你对代码做了哪些改动吗？

@duzx16 您好！
我注释掉了以下，代码：
<img width="931" alt="image" src="https://user-images.githubusercontent.com/73547638/229323453-484d9c5f-e3ac-466f-a142-4bdc2ee46b83.png">

**Comment by zhangsanfeng86** [comment]
我想使用没有经过量化的模型，进行finetune

**Comment by duzx16** [comment]
> 我想使用没有经过量化的模型，进行finetune

不想量化的话在脚本里把`--quantization_bit 4`去掉就行了
