### ISSUE TITLE
[BUG/Help] padding_side is not consistent with p-turning-v2 main.py

### ISSUE THREAD

**Issue by dumpmemory** [THUDM/ChatGLM-6B#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found that the recently change of tokenization_chatglm.py make padding_side to left again. but from https://github.com/THUDM/ChatGLM-6B/blob/4371f7a57285d94f6c22827418f7cebe2983c0b5/ptuning/main.py#L188 which is right setting. so i have try to make a pr for this. 

### Steps To Reproduce

1. should be "right" setting?

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
For training, both right and left paddings are OK. For inference, the input must be left padded.

**Comment by duzx16** [comment]
> would u mind giving the reason for this ? i can't directly follow up, thanks.

Because during inference we need to take the output of the last valid token to predict the next token. If the input is right padded, `transformers` cannot find the correct position of the last valid token.
