### ISSUE TITLE
[BUG/Help] ValueError: 150004 is not in list

### ISSUE THREAD

**Issue by wac81** [THUDM/ChatGLM-6B#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

│ /home/wac/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/e1494f222d3d7f507633e │
│ 49cdd6dba130e7401f4/tokenization_chatglm.py:401 in _pad                                          │
│                                                                                                  │
│   398 │   │                                                                                      │
│   399 │   │   # Initialize attention mask if not present.                                        │
│   400 │   │   if return_attention_mask:                                                          │
│ ❱ 401 │   │   │   context_length = required_input.index(bos_token_id)                            │
│   402 │   │   │   attention_mask = np.ones((1, seq_length, seq_length))                          │
│   403 │   │   │   attention_mask = np.tril(attention_mask)                                       │
│   404 │   │   │   attention_mask[:, :, :context_length] = 1                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: 150004 is not in list

### Steps To Reproduce

1.python38
2.follow your readme ptune
3.and get the error

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
Fixed. Please use the latest model implementation from huggingface repo.
