### ISSUE TITLE
per_device_train_batch_size改大后训练时间成倍增加

### ISSUE THREAD

**Issue by qq31682216** [THUDM/ChatGLM-6B#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

参数默认1，跑1个小时。
改成16，要13个小时。
我理解batch大时间应该缩短一些吧。

### Steps To Reproduce

1.环境按照示例
2.bash train.sh

### Environment

```markdown
- OS:Ubuntu 22.04
- Python:3.8
- Transformers:4.26.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :12.0
```

**Comment by duzx16** [comment]
可能是GPU的性能不支持同时计算这么大的batch
