### ISSUE TITLE
[BUG/Help] <title>显示词表中没有150004，重新下载的模型。

### ISSUE THREAD

**Issue by af-74413592** [THUDM/ChatGLM-6B#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![1680411801863](https://user-images.githubusercontent.com/74224119/229332418-d84cb7a7-f0c0-4a7c-9ebb-50ade895e677.png)

### Steps To Reproduce

使用的是puningv2的train.sh

### Environment

```markdown
- OS: ubuntu
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : 11.8
```

**Comment by duzx16** [comment]
需要更新`tokenization_chatglm.py`
