### ISSUE TITLE
[BUG/Help] 没有回复

### ISSUE THREAD

**Issue by mxtilx** [THUDM/ChatGLM-6B#338]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

![捕获](https://user-images.githubusercontent.com/96869052/229336495-1dbb0a1e-eed0-40eb-9bf5-2dc95adcfb9b.PNG)
![捕获1](https://user-images.githubusercontent.com/96869052/229336496-d7a5aa6f-cc7f-440e-9d42-9168f4f8c883.PNG)
![捕获3](https://user-images.githubusercontent.com/96869052/229336499-65d8f01f-2f2d-4f62-9c84-2bba3cddfcc5.PNG)
用cpu跑起来了，但当我点击generate时没反应

### Expected Behavior

能正常回复

### Steps To Reproduce

在Anaconda中，运行了此项目

### Environment

```markdown
- OS:win10 企业版 LTSC
- Python: 3.10
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :false
```

### Anything else?

无

**Comment by duzx16** [comment]
用CPU确实很慢，你可以看一下资源管理器里CPU占用来确认模型是否在运行

**Comment by mxtilx** [comment]
> 用CPU确实很慢，你可以看一下资源管理器里CPU占用来确认模型是否在运行
![捕获5](https://user-images.githubusercontent.com/96869052/229338005-72aa232d-f3ba-48c0-954b-f71c3b483aba.PNG)

已经在正常工作了
 set `share=True` in `launch()`
这个我没能在文件中找到可以提供一下具体路径吗
