### ISSUE TITLE
是否只支持英伟达的显卡

### ISSUE THREAD

**Issue by jiangbinbin-code** [THUDM/ChatGLM-6B#339]
### Is your feature request related to a problem? Please describe.

是否只支持英伟达的显卡，其他显卡不支持

### Solutions

是否只支持英伟达的显卡，其他显卡不支持

**Comment by duzx16** [comment]
能够运行PyTorch的都可以

**Comment by jiangbinbin-code** [comment]
有个AMD的显卡，运行一直报Could not find module 'nvcuda.dll ，然后换cpu模式也是报这个错，按照https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1470060041 这个issue去修改了 也还是不行，请问还有什么思路可以修改吗？？
&nbsp;


?è
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhengxiao ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 下午3:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] 是否只支持英伟达的显卡 (Issue #339)





 
能够运行PyTorch的都可以

**Comment by Looong01** [comment]
> 有个AMD的显卡，运行一直报Could not find module 'nvcuda.dll ，然后换cpu模式也是报这个错，按照[#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1470060041) 这个issue去修改了 也还是不行，请问还有什么思路可以修改吗？？ &nbsp; ?è ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhengxiao ***@***.***&gt;; 发送时间: 2023年4月2日(星期天) 下午3:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [THUDM/ChatGLM-6B] 是否只支持英伟达的显卡 (Issue #339) 能够运行PyTorch的都可以 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

需要装Linux、ROCm、hip。虚拟机和wsl是不行的

**Comment by yichengming** [comment]
> > 有个AMD的显卡，运行一直报Could not find module 'nvcuda.dll ，然后换cpu模式也是报这个错，按照[#6 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1470060041) 这个issue去修改了 也还是不行，请问还有什么思路可以修改吗？？   ?è _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Zhengxiao _**@**_._**>; 发送时间: 2023年4月2日(星期天) 下午3:46 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [THUDM/ChatGLM-6B] 是否只支持英伟达的显卡 (Issue #339) 能够运行PyTorch的都可以 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 需要装Linux、ROCm、hip。虚拟机和wsl是不行的

感谢。 已经跑起来了

**Comment by NaMoCv** [comment]
> 

怎么跑起来的，不量化？
我报这个：RuntimeError: Library cudart is not initialized

**Comment by yichengming** [comment]
> 

rocm跑起来了。我的测试代码能调用a卡计算了。但是… 这个起不来。可能是我5700xt显卡兼容性问题，第二天买了个2080ti

**Comment by Looong01** [comment]
> > 
> 
> rocm跑起来了。我的测试代码能调用a卡计算了。但是… 这个起不来。可能是我5700xt显卡兼容性问题，第二天买了个2080ti

你得把你的报错信息发一下啊，不然没法帮你

**Comment by Looong01** [comment]
> > 
> 
> 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized

是不是物理机的Linux？

**Comment by NaMoCv** [comment]
> > > 
> > 
> > 
> > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> 
> 是不是物理机的Linux？
> 
> 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> 
> ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)

物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。

**Comment by Looong01** [comment]
> > > > 
> > > 
> > > 
> > > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> > 
> > 
> > 是不是物理机的Linux？
> > 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> > ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)
> 
> 物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。

你可以考虑用cpu导出量化模型，然后不用运行时量化，直接加载量化后的checkpoint到a卡

**Comment by OneiroXL** [comment]
> 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized

我也是报这个错误

**Comment by OneiroXL** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> > > 
> > > 
> > > 是不是物理机的Linux？
> > > 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> > > ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)
> > 
> > 
> > 物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。
> 
> 你可以考虑用cpu导出量化模型，然后不用运行时量化，直接加载量化后的checkpoint到a卡

直接选择作者提供的量化好的模型是不是也可以

**Comment by Looong01** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> > > > 
> > > > 
> > > > 是不是物理机的Linux？
> > > > 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> > > > ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)
> > > 
> > > 
> > > 物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。
> > 
> > 
> > 你可以考虑用cpu导出量化模型，然后不用运行时量化，直接加载量化后的checkpoint到a卡
> 
> 直接选择作者提供的量化好的模型是不是也可以

是这个道理，但是作者只提供了int4和int4q的量化）

**Comment by guoqingkong** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> > > > > 
> > > > > 
> > > > > 是不是物理机的Linux？
> > > > > 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> > > > > ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)
> > > > 
> > > > 
> > > > 物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。
> > > 
> > > 
> > > 你可以考虑用cpu导出量化模型，然后不用运行时量化，直接加载量化后的checkpoint到a卡
> > 
> > 
> > 直接选择作者提供的量化好的模型是不是也可以
> 
> 是这个道理，但是作者只提供了int4和int4q的量化）

直接load int4的模型还是出现cudart 缺失的错误，不晓得怎么绕过去。

**Comment by NaMoCv** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 怎么跑起来的，不量化？ 我报这个：RuntimeError: Library cudart is not initialized
> > > > > > 
> > > > > > 
> > > > > > 是不是物理机的Linux？
> > > > > > 如果是，是否按照pytorch官网按照rocm版本的？（ROCm版本的pytorch无法按照conda方式安装
> > > > > > ![image](https://user-images.githubusercontent.com/69568351/230705090-6f15170b-243d-4f82-b5ce-186fd435acdd.png)
> > > > > 
> > > > > 
> > > > > 物理机linux，rocm；我看过代码了，量化依赖cudart的，没有提供hiprt的调用方法，所以量化用amd显卡跑不起来（cpu可以正常跑）。
> > > > 
> > > > 
> > > > 你可以考虑用cpu导出量化模型，然后不用运行时量化，直接加载量化后的checkpoint到a卡
> > > 
> > > 
> > > 直接选择作者提供的量化好的模型是不是也可以
> > 
> > 
> > 是这个道理，但是作者只提供了int4和int4q的量化）
> 
> 直接load int4的模型还是出现cudart 缺失的错误，不晓得怎么绕过去。

https://github.com/agrocylo/bitsandbytes-rocm 这好像是指出rocm的量化包，b站上有视频用这跑了，我还没试。
