### ISSUE TITLE
下载好的模型，可以修改模型地址么？

### ISSUE THREAD

**Issue by ucas010** [THUDM/ChatGLM-6B#34]
原本是model="THUDM/chatglm-6b"
可以改为model="/data/models--THUDM--chatglm-6b/" ?
另外这个表示啥意思啊？
trust_remote_code=True
去掉后怎么解决bug啊？感谢

**Comment by skirodev** [comment]
You can modify it to a local model path after downloading the model and use `trust_remote_code=True` to skip the security check of Hugging Face on the code in the pre-training model code library.

**Comment by AndersonBY** [comment]
增加cache_dir="本地路径"

**Comment by ucas010** [comment]
trust_remote_code=True
这个不要会报错，咋能去掉啊？总感觉模型被远程控制，会不会哪天就不能用了呢？
