### ISSUE TITLE
[Help]在NVIDIA CMP 50HX系列计算卡上运行ChatGLM-6B

### ISSUE THREAD

**Issue by chenshaoju** [THUDM/ChatGLM-6B#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/515763/229346720-3eb6f6bd-bc64-4594-a3e1-a4338292a13b.png)

运行 python cli_demo.py 后，提示 Torch not compiled with CUDA enabled，搜了一下，这意味着可能找不到CUDA支持的设备：https://blog.csdn.net/qq_40329272/article/details/105727722 。

尝试设置环境变量 `set CUDA_VISIBLE_DEVICES=0`，但是没有作用。

但是相同的设备，是可以运行Stable Diffusion的：
![Snipaste_2023-04-02_18-14-51](https://user-images.githubusercontent.com/515763/229346803-2cfe0278-e11d-43f5-96a1-a08a9f02bd27.png)

设备本身也是支持CUDA的：
![image](https://user-images.githubusercontent.com/515763/229347426-f33b84ae-e46c-4dd5-aede-c52dd7ef565a.png)

我猜测有没有可能是在判断或检测CUDA设备的方式不太一样？

### Expected Behavior

正常工作

### Steps To Reproduce

python cli_demo.py

### Environment

```markdown
- OS: Windows 10
- Python: Python 3.10.9
- Transformers:4.27.1
- PyTorch:1.9.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

### Anything else?

没有使用WSL，和Stable Diffusion共用一个Python环境。

**Comment by duzx16** [comment]
你运行`python -c "import torch; print(torch.cuda.is_available())"`返回的是False说明安装的PyTorch不支持CUDA。请参考PyTorch官网的提示安装支持CUDA的

**Comment by chenshaoju** [comment]
感谢回应，我刚研究了一下Stable Diffusion的环境（venv），返回的是True，我进一步研究一下，有进一步情况再更新：

![image](https://user-images.githubusercontent.com/515763/229347662-d770308f-e6ce-47f3-a7e3-44e17438e612.png)
