### ISSUE TITLE
[BUG/Help] 'Logger' object has no attribute 'warning_once'

### ISSUE THREAD

**Issue by raywongstudy** [THUDM/ChatGLM-6B#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i run the command get the error : "logger.warning_once(f"The dtype of attention mask ({attention_mask.dtype}) is not bool") AttributeError: 'Logger' object has no attribute 'warning_once'"
```
>>> response, history = model.chat(tokenizer, "你好", history=[])
```
error message:
```
logger.warning_once(f"The dtype of attention mask ({attention_mask.dtype}) is not bool")
AttributeError: 'Logger' object has no attribute 'warning_once'
```

### Steps To Reproduce

```
>>> response, history = model.chat(tokenizer, "你好", history=[])
```

### Environment

```markdown
- OS:linux 
- Python: 3.8.5
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
Please upgrade the version of `transformers` to 4.27.1

**Comment by raywongstudy** [comment]
that is success to solve my issue , thank so much !!!

**Comment by yungangwu** [comment]
已经更新transformers版本为4.27.1但仍然报这个错误
