### ISSUE TITLE
[BUG/Help] <RuntimeError: Tensors must have same number of dimensions: got 4 and 2>

### ISSUE THREAD

**Issue by lqcao** [THUDM/ChatGLM-6B#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/srv/local/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:717: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  tensor = as_tensor(value)
Traceback (most recent call last):
  File "/home/lqcao/projects/ai/ChatGLM-6B/cli_demo.py", line 59, in <module>
    main()
  File "/home/lqcao/projects/ai/ChatGLM-6B/cli_demo.py", line 44, in main
    for response, history in model.stream_chat(tokenizer, query, history=history):
  File "/srv/local/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/lqcao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/4ebf106fbcd496d7e3f93418f4ec1ca7dbed4456/modeling_chatglm.py", line 1163, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "/srv/local/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/lqcao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/4ebf106fbcd496d7e3f93418f4ec1ca7dbed4456/modeling_chatglm.py", line 1262, in stream_generate
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/srv/local/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 733, in _update_model_kwargs_for_generation
    model_kwargs["attention_mask"] = torch.cat(
RuntimeError: Tensors must have same number of dimensions: got 4 and 2

### Steps To Reproduce

1. 使用 THUDM/chatglm-6b-int4-qe
2. python cli_demo.py

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
The code of THUDM/chatglm-6b-int4-qe was not synced with the main model. Fixed now.

**Comment by shenshouer** [comment]
RuntimeError: Tensors must have same number of dimensions: got 4 and 2
问题依然存在

**Comment by duzx16** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/sope/.local/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/home/sope/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
>     result = await self.call_function(
>   File "/home/sope/.local/lib/python3.9/site-packages/gradio/blocks.py", line 929, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/home/sope/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/home/sope/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/home/sope/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "/home/sope/.local/lib/python3.9/site-packages/gradio/utils.py", line 490, in async_iteration
>     return next(iterator)
>   File "/home/sope/workspaces/ChatGLM-6B/web_demo.py", line 15, in predict
>     for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
>   File "/home/sope/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/sope/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/7458231b5ac7f19cc49496c35617a4ea66f0533e/modeling_chatglm.py", line 1163, in stream_chat
>     for outputs in self.stream_generate(**input_ids, **gen_kwargs):
>   File "/home/sope/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/sope/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/7458231b5ac7f19cc49496c35617a4ea66f0533e/modeling_chatglm.py", line 1262, in stream_generate
>     model_kwargs = self._update_model_kwargs_for_generation(
>   File "/home/sope/.local/lib/python3.9/site-packages/transformers/generation/utils.py", line 733, in _update_model_kwargs_for_generation
>     model_kwargs["attention_mask"] = torch.cat(
> RuntimeError: Tensors must have same number of dimensions: got 4 and 2
> ```
> 
> 问题依然存在

已经更新了，可以重新运行一下
