### ISSUE TITLE
[Feature] <能否提供INT8量化模型文件？>

### ISSUE THREAD

**Issue by Looong01** [THUDM/ChatGLM-6B#349]
### Is your feature request related to a problem? Please describe.

因为在开发DirectML分支，使其能够运行在Windows上任意支持DirectX12的显卡，包括但不限于Nvidia、AMD、Intel、高通、国产显卡等。但是transformer库并不支持dml后端上的量化函数

我的开发环境为AMD Radeon RX 6700XT

int4性能较差，float16显存不足，int8对市面上大多数的消费级显卡来说正好

因此希望能够提供INT8量化后的model.bin

### Solutions

例如在huggingface上提供chatglm-6b-int8

**Comment by shibing624** [comment]
设置quantization_bit为8后，加载model后save为pkl即可，下次直接load pkl的模型。

**Comment by Looong01** [comment]
> 设置quantization_bit为8后，加载model后save为pkl即可，下次直接load pkl的模型。

请问你们官方的保存方法是保存整个模型还是仅仅保存模型的参数state_dict()？因为我的工程涉及到通用版本的开发，因此不能只给我一个人用就行了的

**Comment by kiranosora** [comment]
请问一下，使用int8量化后，模型性能相较int4有感觉到提升吗？

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm-6b-int8
