### ISSUE TITLE
启动失败 Symbol cudaLaunchKernel not found 

### ISSUE THREAD

**Issue by wuzhipeng7cc** [THUDM/ChatGLM-6B#35]
下面是报错信息
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll

**Comment by wuzhipeng7cc** [comment]
重启后ok了

**Comment by ipengx1029** [comment]
请问怎么解决的啊，我依旧这样，是12G的3060加载不了吗，已经.half().quantize(4).cuda() 了

**Comment by ChanningWong** [comment]
遇到同样的问题，torch.cuda.is_available()是True，cuda版本12.1、torch 2.0

**Comment by frankghe1977** [comment]
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll  ,环境为2.0.0+cu118
True  ，如何处理？

**Comment by frankghe1977** [comment]
我知道，重新安装一便

**Comment by frankghe1977** [comment]
我知道，重新安装一便

**Comment by frankghe1977** [comment]
哟出现另外问题,现在一直没有反应,卡死了.

**Comment by frankghe1977** [comment]
![微信图片_20230427171522](https://user-images.githubusercontent.com/128656744/234817377-ba40dc6a-5143-4b02-8f15-8c8abf60b21f.png)

**Comment by frankghe1977** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory ,如何处理

**Comment by liuguangrui123** [comment]
你的这些问题我都遇到了 尴尬
