### ISSUE TITLE
模型预测程序启动卡住

### ISSUE THREAD

**Issue by xxllp** [THUDM/ChatGLM-6B#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

为啥启动后程序一直卡了，很久也进不去预测呢，单卡预测。
cpu没有飙升，gpu也没有显存占用

### Steps To Reproduce

直接运行cli

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
提供的信息太少，至少应该说明log卡在哪里。如果是网络问题的话可以参考 https://github.com/THUDM/ChatGLM-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B

**Comment by xxllp** [comment]
就是启动的时候卡住了，后面我测试cpu下是可以启动的，但是gpu下是启动失败了。模型已经保存本地了
