### ISSUE TITLE
每次启动API都要更新好烦啊[BUG/Help] <title>

### ISSUE THREAD

**Issue by ding567** [THUDM/ChatGLM-6B#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

每天打开都要下载pytorch.model.bin，已经下载N次了，每次都要崩，第二天打开居然还要重新下载，已经无语住了，本地已经下载N次了，天天下载什么意思啊（哭），怎么样才能不天天下载

### Steps To Reproduce

1

### Environment

```markdown
- OS:win10
- Python:3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by xuguozhi** [comment]
设置成本地路径不行吗？

**Comment by yzho0907** [comment]
先通过git clone huggingface上的模型文件，然后本地加载即可

**Comment by ding567** [comment]
感谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月3日(周一) 中午11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THUDM/ChatGLM-6B] 每次启动API都要更新好烦啊[BUG/Help] <title&gt; (Issue #352)




 
先通过git clone huggingface上的模型文件，然后本地加载即可
 
&mdash;

**Comment by ding567** [comment]
> 设置成本地路径不行吗？

感谢

**Comment by ding567** [comment]
谢谢大家，问题解决了
