### ISSUE TITLE
[BUG/Help] <title>怎么评价微调的效果

### ISSUE THREAD

**Issue by expresschen** [THUDM/ChatGLM-6B#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用ptuning微调时，在1000step时，loss下降到4.0左右，但是再往下训练loss就不下降了，这样是否正常呢？看epoch还没有训练一个epoch的呢，想问一下官方的ptuning效果

### Steps To Reproduce

*

### Environment

```markdown
- OS:centos7
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.17.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
cuda 11.5
```

### Anything else?

no

**Comment by duzx16** [comment]
已添加evaluation结果
https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E8%AF%84%E4%BC%B0%E7%BB%93%E6%9E%9C
