### ISSUE TITLE
ptuning时报错： AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### ISSUE THREAD

**Issue by RileyShe** [THUDM/ChatGLM-6B#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "**/ChatGLM-6B/ptuning/main.py", line 392, in <module>
    main()
  File ""**/ChatGLM-6B/ptuning/main.py", line 120, in main
    model.transformer.prefix_encoder.float()
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Steps To Reproduce

sh train.sh过程中

### Environment

```markdown
- OS: linux
- Python: python3.9.13
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by yangzhipeng1108** [comment]
https://huggingface.co/THUDM/chatglm-6b/tree/main      download the latest

**Comment by RileyShe** [comment]
> > https://huggingface.co/THUDM/chatglm-6b/tree/main download the latest
> 
> 您好，我就是下载的最新的，还报这个错误

@yangzhipeng1108 更新了最新模型 还是同样的错误
![60BD047B](https://user-images.githubusercontent.com/13896613/229456153-da9feddd-9feb-4c12-a9bd-6f6113058ef4.png)

**Comment by yinshipeng** [comment]
我的模型每次都是从仓库里获取的，肯定也都是最新的，同样也报这个错误。

**Comment by kiranosora** [comment]
我也遇到过这个问题，看起来是模型载入方式不对。
你似乎是直接复用了api.py里载入模型的方式而不是main.py里的吧。我改成main.py里那种载入方式就没有报这个错了。
![1](https://user-images.githubusercontent.com/15158210/233020576-cddcc317-6934-41ef-92ca-5735341afb6b.PNG)

**Comment by TuDaCheng** [comment]
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) 这行 预测时需要模型config中含有 pre_seq_len， 模型才会定义prefix_encoder
