### ISSUE TITLE
模型列表里的8个模型都有什么区别吗？

### ISSUE THREAD

**Issue by Chenny0808** [THUDM/ChatGLM-6B#36]
pytorch_model-00001-of-00008.bin
pytorch_model-00002-of-00008.bin
pytorch_model-00003-of-00008.bin
pytorch_model-00004-of-00008.bin
pytorch_model-00005-of-00008.bin 
pytorch_model-00006-of-00008.bin
pytorch_model-00007-of-00008.bin
pytorch_model-00008-of-00008.bin

**Comment by skirodev** [comment]
This is simply a large model being split into 8 parts for uploading and storage.

**Comment by assassinliujie** [comment]
这不显然是同一个模型的八个部分

**Comment by SGL647** [comment]
它们是同一个模型

**Comment by datalee** [comment]
哈哈哈哈哈

**Comment by helloxz** [comment]
手动下载的模型放到哪个位置呢？

**Comment by dalei2019** [comment]
看一下 `pytorch_model.bin.index.json` 描述问题就明白了

**Comment by Suqier** [comment]
![R](https://github.com/THUDM/ChatGLM-6B/assets/18082255/241f7675-60f6-4fc5-9c3c-896791705a79)
