### ISSUE TITLE
[BUG/Help] Ptuning 方式下可以 实施 数据并行 或者模型并行的方式吗

### ISSUE THREAD

**Issue by RileyShe** [THUDM/ChatGLM-6B#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

单卡 训练还是太慢，想用多卡训练，若是实施数据并行的方式，需要怎么改动？

### Steps To Reproduce

单卡 训练还是太慢，想用多卡训练，若是实施数据并行的方式，需要怎么改动？

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.9
- Transformers: 4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by huangxd-** [comment]
我看这里已经实现了
https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel_ptuning

**Comment by duzx16** [comment]
直接修改`train.sh`的 `CUDA_VISIBLE_DEVICES` 到你需要用的显卡就可以数据并行

**Comment by summer-silence** [comment]
@duzx16 这样修改之后实际上我，我的运行时间远远大于单卡运行的时间，这是为什么呢
