### ISSUE TITLE
打开页面错位

### ISSUE THREAD

**Issue by homeyone** [THUDM/ChatGLM-6B#369]
### Is your feature request related to a problem? Please describe.

程序整体都没问题，就是EDGE打开显示的页面都是错位的。

### Solutions

请帮助我

**Comment by duzx16** [comment]
可能是gradio或者EDGE的问题，与本仓库无关。
本仓库提供的web demo只是一个简单的示例，不保证对各种浏览器的兼容性。

**Comment by iris-qq** [comment]
![image](https://github.com/THUDM/ChatGLM-6B/assets/32732041/90d0742b-1aae-43e7-a46c-700b51e2a873)
