### ISSUE TITLE
ValueError: Unrecognized configuration class <class 'transformers_modules.local.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.

### ISSUE THREAD

**Issue by wizd** [THUDM/ChatGLM-6B#37]
got error running the model:

<pre>
D:\chatglm6b\ChatGLM-6B>python web_demo.py
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "D:\chatglm6b\ChatGLM-6B\web_demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "C:\Users\wizard\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 686, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.local.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, BloomConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2TextConfig, Speech2Text2Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, YosoConfig.

D:\chatglm6b\ChatGLM-6B></pre>

**Comment by wizd** [comment]
need to download source code either

**Comment by duzx16** [comment]
Can you check your `transformers` version? The repo requires `transformers>=4.23.1`.

**Comment by musicfish1973** [comment]
(OpenChatKit) root@aca2869c8358:~/ChatGLM-6B-main# conda list | grep transformers
transformers              4.26.1                   pypi_0    pypi
(OpenChatKit) root@aca2869c8358:~/ChatGLM-6B-main# python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/root/ChatGLM-6B-main/cli_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("./model", trust_remote_code=True)#("THUDM/chatglm-6b", trust_remote_code=True)
  File "/root/anaconda3/envs/OpenChatKit/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 686, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.local.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, BloomConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2TextConfig, Speech2Text2Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, YosoConfig.

**Comment by younghuvee** [comment]
==Did somebody fix it? I have same question, my tranformers's version is 4.26.1==

**Comment by musicfish1973** [comment]
It runs ok when I load it from Huggingface.

**Comment by musicfish1973** [comment]
also see the reply in issue 153.

**Comment by alberic-tct** [comment]
I have successfully solved this problem.
Problem cause: The model is not configured correctly. Part of the configuration file is missing
Solution: Download all the configuration files from Hugging Face.
Website: https://huggingface.co/THUDM/chatglm-6b/tree/main

**Comment by codingfun2022** [comment]
model.save_pretrained 保存的模型有问题，缺少 tokenizer 的相关文件：tokenizer_config.json、special_tokens_map.json、tokenization_chatglm.py 和 ice_text.model。

同时调 model.save_pretrained 和 tokenizer.save_pretrained 可以解决。类似：

model.save_pretrained('./models/chatglm-6b')
tokenizer.save_pretrained('./models/chatglm-6b')

**Comment by johnny-richards** [comment]
I encountered the same problem while using chatglm2 to do some inference, and just as @codingfun2022 said, the trainer of huggingface tends to save only the model rather than both model with tokenizer. Therefore such problem was solved by just copying tokenizer_config.json and tokenizer.model to the new checkpoint path so that you could load the model and tokenizer successfully without and problem :)

**Comment by usstq** [comment]
In my case, change `"AutoModel"` in config.json into `"AutoModelForCausalLM"` solves the issue

**Comment by buptzyf** [comment]
> In my case, change `"AutoModel"` in config.json into `"AutoModelForCausalLM"` solves the issue

解救了我，必须点个赞

**Comment by DengNingyuan** [comment]
你好，请问是修改 "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"这里的 "AutoModel":吗


> > In my case, change `"AutoModel"` in config.json into `"AutoModelForCausalLM"` solves the issue
> 
> 解救了我，必须点个赞

**Comment by Reve75** [comment]
> AutoModelForCausalLM

this saved me too
