### ISSUE TITLE
摘要和阅读理解MRC的prompt应该怎么写？

### ISSUE THREAD

**Issue by fancyerii** [THUDM/ChatGLM-6B#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前的效果不好

### Steps To Reproduce

  请问怎么优化

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

我想用ChatGLM做文本摘要以及生成式的阅读理解(MRC)，我试了一下如下的prompt但是效果不太好，请问对于这两个任务，比较好的prompt是什么？

摘要：请对下面的文章进行摘要，100字以内。

MRC：请根据下面的文字回答问题，如果找不到答案请回答不知道。

context

问题：xxxx

**Comment by leonall** [comment]
试试 few shot，看能否教会它

[chatGLM怎么应用于的下游任务？也许你该看看这个（附源码）](https://mp.weixin.qq.com/s/50UvPJ9oLBekxeRSCYZtOA)
