### ISSUE TITLE
[BUG/Help] web_demo.py处理对话报错 RuntimeError: Tensors must have same number of dimensions: got 4 and 2

### ISSUE THREAD

**Issue by owliz** [THUDM/ChatGLM-6B#374]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 步骤  
- 使用[该镜像](https://www.codewithgpu.com/i/THUDM/ChatGLM-6B/ChatGLM)启动容器  
-  调用镜像自带chatglm模型并联网下载tokenizer  
- 启动web_demo.py后在对话框进行对话  
![图片](https://user-images.githubusercontent.com/20179943/229577975-3e322ec6-bb84-46ac-94f3-5d7c98e8aa47.png)
  
### 错误现象
模型可以正常加载，但执行对话报错。
![图片](https://user-images.githubusercontent.com/20179943/229578048-cdecbba5-4474-44a5-a1cd-d1c026e8eced.png)
- 主要错误    
File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 733, in _update_model_kwargs_for_generation
    model_kwargs["attention_mask"] = torch.cat(
RuntimeError: Tensors must have same number of dimensions: got 4 and 2  
- 措施：升级transformer仍无效      
![图片](https://user-images.githubusercontent.com/20179943/229578206-4802e9ef-9e76-47a1-9963-36cece8c67d3.png)

### Expected Behavior

正常对话

### Steps To Reproduce

- 使用[该镜像](https://www.codewithgpu.com/i/THUDM/ChatGLM-6B/ChatGLM)启动容器  
-  调用镜像自带chatglm模型并联网下载tokenizer  
- 启动web_demo.py后在对话框进行对话  

### Environment

```markdown
- [镜像](https://www.codewithgpu.com/i/THUDM/ChatGLM-6B/ChatGLM)   
- GPU: RTX3080
```

**Comment by duzx16** [comment]
镜像里的模型文件不是最新的，需要更新一下modeling_chatglm.py

**Comment by frog-painter** [comment]
> 镜像里的模型文件不是最新的，需要更新一下modeling_chatglm.py

怎么更新镜像里的modeling_chatglm.py。
我之前打算直接修改modeling_chatglm来自定义部分函数，修改之后出现了类似错误。
整个文件删除再重新下载并不work

**Comment by heguancong** [comment]
我也遇到了一样的问题

**Comment by duzx16** [comment]
> > 镜像里的模型文件不是最新的，需要更新一下modeling_chatglm.py
> 
> 怎么更新镜像里的modeling_chatglm.py。 我之前打算直接修改modeling_chatglm来自定义部分函数，修改之后出现了类似错误。 整个文件删除再重新下载并不work

这个镜像并不是官方提供的，应该问镜像的提供者吧。
