### ISSUE TITLE
[BUG/Help] <title>AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### ISSUE THREAD

**Issue by zhangzai666** [THUDM/ChatGLM-6B#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### Expected Behavior

AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### Steps To Reproduce

AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'
```

### Anything else?

AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

**Comment by duzx16** [comment]
Please install transformers 4.27.1

**Comment by zhangzai666** [comment]
> Please install transformers 4.27.1

OK可以了，十分感谢
