### ISSUE TITLE
Any Inference Acceleration Solution Based on C++?

### ISSUE THREAD

**Issue by submartingales** [THUDM/ChatGLM-6B#376]
### Is your feature request related to a problem? Please describe.

Does this project provide any weight checkpoint or code that can be leveraged to accelerate inference (typically, on cpu server) based on C++ ?

### Solutions

I hope the maintainers can at least provide some C++ interfaces that are used for deployment or inference acceleration.

**Comment by lvcaiping** [comment]
> ### Is your feature request related to a problem? Please describe.
> Does this project provide any weight checkpoint or code that can be leveraged to accelerate inference (typically, on cpu server) based on C++ ?
> 
> ### Solutions
> I hope the maintainers can at least provide some C++ interfaces that are used for deployment or inference acceleration.
> 
> ### Additional context
> _No response_

can support a faster transformer version？

**Comment by duzx16** [comment]
https://github.com/wangzhaode/ChatGLM-MNN This project provides a C++ implementation based on MNN. The maintainer also provides ONNX export that can be used on other frameworks.
