### ISSUE TITLE
[BUG/Help] <title>大佬，能基于infer_lora_finetuning.py 的lora微调版本，提供一个flask的部署代码吗

### ISSUE THREAD

**Issue by cristianohello** [THUDM/ChatGLM-6B#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from fastapi import FastAPI, Request
from transformers import AutoTokenizer, AutoModel
import uvicorn, json, datetime
import torch

DEVICE = "cuda"
DEVICE_ID = "0"
CUDA_DEVICE = f"{DEVICE}:{DEVICE_ID}" if DEVICE_ID else DEVICE

def torch_gc():
    if torch.cuda.is_available():
        with torch.cuda.device(CUDA_DEVICE):
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()

app = FastAPI()

@app.post("/")
async def create_item(request: Request):
    global model, tokenizer
    json_post_raw = await request.json()
    json_post = json.dumps(json_post_raw)
    json_post_list = json.loads(json_post)
    prompt = json_post_list.get('prompt')
    history = json_post_list.get('history')
    max_length = json_post_list.get('max_length')
    top_p = json_post_list.get('top_p')
    temperature = json_post_list.get('temperature')
    response, history = model.chat(tokenizer,
                                   prompt,
                                   history=history,
                                   max_length=max_length if max_length else 2048,
                                   top_p=top_p if top_p else 0.7,
                                   temperature=temperature if temperature else 0.95)
    now = datetime.datetime.now()
    time = now.strftime("%Y-%m-%d %H:%M:%S")
    answer = {
        "response": response,
        "history": history,
        "status": 200,
        "time": time
    }
    log = "[" + time + "] " + '", prompt:"' + prompt + '", response:"' + repr(response) + '"'
    print(log)
    torch_gc()
    return answer

if __name__ == '__main__':
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
    model.eval()
    uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)

### Expected Behavior

from fastapi import FastAPI, Request
from transformers import AutoTokenizer, AutoModel
import uvicorn, json, datetime
import torch

DEVICE = "cuda"
DEVICE_ID = "0"
CUDA_DEVICE = f"{DEVICE}:{DEVICE_ID}" if DEVICE_ID else DEVICE

def torch_gc():
    if torch.cuda.is_available():
        with torch.cuda.device(CUDA_DEVICE):
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()

app = FastAPI()

@app.post("/")
async def create_item(request: Request):
    global model, tokenizer
    json_post_raw = await request.json()
    json_post = json.dumps(json_post_raw)
    json_post_list = json.loads(json_post)
    prompt = json_post_list.get('prompt')
    history = json_post_list.get('history')
    max_length = json_post_list.get('max_length')
    top_p = json_post_list.get('top_p')
    temperature = json_post_list.get('temperature')
    response, history = model.chat(tokenizer,
                                   prompt,
                                   history=history,
                                   max_length=max_length if max_length else 2048,
                                   top_p=top_p if top_p else 0.7,
                                   temperature=temperature if temperature else 0.95)
    now = datetime.datetime.now()
    time = now.strftime("%Y-%m-%d %H:%M:%S")
    answer = {
        "response": response,
        "history": history,
        "status": 200,
        "time": time
    }
    log = "[" + time + "] " + '", prompt:"' + prompt + '", response:"' + repr(response) + '"'
    print(log)
    torch_gc()
    return answer

if __name__ == '__main__':
    tokenizer = AutoTokenizer.from_pretrained("应该怎么修改？？？", trust_remote_code=True)
    model = AutoModel.from_pretrained("应该怎么修改？？？", trust_remote_code=True).half().cuda()
    model.eval()
    uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)

### Steps To Reproduce

no

### Environment

```markdown
- OS:
- Python:Python 3.10.9
- Transformers:transformers             4.27.1
- PyTorch:torch                    2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : true
```

### Anything else?

no

**Comment by cristianohello** [comment]
@chenyiwan 
大佬，能提供代码参考吗？最近在生产中部署多轮对话模型服务

**Comment by songsa1** [comment]
> 根本不建议直接在文本生成上面封装http请求的api,高并发下你的显存直接爆，根本无法使用。
> 
> 你应该考虑将问题输入队列，这里直接从队列里一个一个的获取问题，得到输出。前端使用websocket 获取响应文本，或者简单点采用轮循的方式获取。

可是这样做的话，就不是多轮对话了呀

**Comment by chenyiwan** [comment]
> > 根本不建议直接在文本生成上面封装http请求的api,高并发下你的显存直接爆，根本无法使用。
> > 你应该考虑将问题输入队列，这里直接从队列里一个一个的获取问题，得到输出。前端使用websocket 获取响应文本，或者简单点采用轮循的方式获取。
> 
> 可是这样做的话，就不是多轮对话了呀

多轮对话跟这个关系不大，你仔细看看chat方法。
