### ISSUE TITLE
显示权重不对

### ISSUE THREAD

**Issue by PeiZhangNEU** [THUDM/ChatGLM-6B#38]
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

**Comment by taoztw** [comment]
我们也遇到了这个问题！！！

**Comment by PeiZhangNEU** [comment]
已经解决了，是因为pytorch和服务器cuda版本不同导致的，他这个pip 安装的requirement是1.13.0的torch。nvidia11.7以上才可用。

只需要使用conda按照pytorch官网的指令把pytorch重装为自己服务器对应的nvidia cuda版本即可
