### ISSUE TITLE
可以把两块GPU同时用起来吗？一块只有16GB，容易出现torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by musicfish1973** [THUDM/ChatGLM-6B#381]
### Solutions

可以把两块GPU同时用起来吗？一块只有16GB，容易出现torch.cuda.OutOfMemoryError: CUDA out of memory.

**Comment by ChinaGPT** [comment]
int8

**Comment by musicfish1973** [comment]
对话轮数越长显存需求越大，所以想把两块都用起来。看样子目前还做不到

**Comment by hechuanlong** [comment]
> 对话轮数越长显存需求越大，所以想把两块都用起来。看样子目前还做不到

试下用accelerate可不可以？方法参考这里 https://github.com/THUDM/ChatGLM-6B/issues/347
有结果分享一下，谢谢~

**Comment by zhangch9** [comment]
推理可以参考[多卡部署](https://github.com/THUDM/ChatGLM-6B#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2)的说明。
