### ISSUE TITLE
关于p_tuning效果的疑问

### ISSUE THREAD

**Issue by rayvzn119** [THUDM/ChatGLM-6B#386]
### Is your feature request related to a problem? Please describe.

请问为什么选择p_tuning而不是lora或者prefix_tuning，这三者孰优孰劣？然后就是，我使用glm6b原版模型，对广告生成数据集做了测试，发现效果本来就非常好，是不是原版模型已经加了这个数据集？导致微调看不出效果？下面图片是我用原版glm6b做的测试：
![image](https://user-images.githubusercontent.com/85482204/229725350-20bd52c5-0bd1-45ae-be89-3b2fe6b6ee79.png)

### Solutions

见上

**Comment by liaoweiguo** [comment]
我这用ptuning2失败

Traceback (most recent call last):
  File "main.py", line 393, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by maojinyang** [comment]
> 我这用ptuning2失败
> 
> Traceback (most recent call last): File "main.py", line 393, in main() File "main.py", line 119, in main model.transformer.prefix_encoder.float() File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

更新transformers版本就可以了

**Comment by liaoweiguo** [comment]
调优是个玄学

**Comment by Tungsong** [comment]
我就没觉得微调之后生成的广告词有多大提升，原版的模型生成的广告词看着也不错

**Comment by xuguozhi** [comment]
> 我就没觉得微调之后生成的广告词有多大提升，原版的模型生成的广告词看着也不错

+1

**Comment by liucongg** [comment]
https://github.com/liucongg/ChatGLM-Finetuning
我这边做了三元组抽取的实验，仅在embbeding上训练，效果不行，还是得在每一层上加参数

**Comment by Leawnn** [comment]
我这边用自己的问答数据微调，回复效果就是：在一本正经的胡说八道（虽然挺流畅的，也跟微调数据相关的，但是胡说八道）

**Comment by liucongg** [comment]
> 

可能存在数据泄露的问题

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E8%AF%84%E4%BC%B0%E7%BB%93%E6%9E%9C
