### ISSUE TITLE
为什么不能用共享GPU内存呢[Feature] <title>

### ISSUE THREAD

**Issue by ding567** [THUDM/ChatGLM-6B#388]
### Is your feature request related to a problem? Please describe.

为什么不能用共享GPU内存呢
专用6G都满了但是共享GPU内存一点都没动

### Solutions

emm

**Comment by KissMyLady** [comment]
我的显卡只有8G, 也=跑不了大模型, 只能用CPU+内存的方式运行. 我其实也想, ==让内存作为GPU的虚拟显存, 就像RAM不够用后, 可以用磁盘作为虚拟内存临时用一下.==

**Comment by duzx16** [comment]
因为内存和显存之间的数据交换速度很慢，用这种方式推理的延迟会很高。如果想用的话 https://github.com/Jittor/JittorLLMs 里面实现了

**Comment by ding567** [comment]
谢谢


---原始邮件---
发件人: &quot;Zhengxiao ***@***.***&gt;
发送时间: 2023年4月7日(周五) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THUDM/ChatGLM-6B] 为什么不能用共享GPU内存呢[Feature] <title&gt; (Issue #388)




 
因为内存和显存之间的数据交换速度很慢，用这种方式推理的延迟会很高。如果想用的话 https://github.com/Jittor/JittorLLMs 里面实现了
 
&mdash;

**Comment by KissMyLady** [comment]
谢谢分享🎈🎈
