### ISSUE TITLE
[BUG/Help] <ptuning train.sh failed>

### ISSUE THREAD

**Issue by liaoweiguo** [THUDM/ChatGLM-6B#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[INFO|modeling_utils.py:2690] 2023-04-04 08:04:26,681 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
Traceback (most recent call last):
  File "main.py", line 393, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Expected Behavior

training with gpu

### Steps To Reproduce

1. ubuntu docker huggingface/transformers-pytorch-gpu
2. python 3.8
3. transformers              4.27.1
4. torch                     2.0.0+cu117
5. a100 * 2

git clone
cd ptuning
bash train.sh

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8
- Transformers: 4.27.1
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by EnHuiPug** [comment]
去hugging face上把更新的一些文件下下来替换一下本地文件

**Comment by liaoweiguo** [comment]
> 去hugging face上把更新的一些文件下下来替换一下本地文件

谢谢。具体哪些文件，不是那八个大bin文件吧

**Comment by duzx16** [comment]
> > 去hugging face上把更新的一些文件下下来替换一下本地文件
> 
> 谢谢。具体哪些文件，不是那八个大bin文件吧

modeling_chatglm.py和tokenization_chatglm.py

**Comment by liaoweiguo** [comment]
> > > 去hugging face上把更新的一些文件下下来替换一下本地文件
> > 
> > 
> > 谢谢。具体哪些文件，不是那八个大bin文件吧
> 
> modeling_chatglm.py和tokenization_chatglm.py

谢谢，花一晚上重新下载了所有文件。果然好了。
讽刺的是，在一个双A100（这个卡现在要20万一张了）的机器上，训练速度还不如自己装的4090单卡。当然游戏卡跑不动大模型

**Comment by liaoweiguo** [comment]
哪天能有效灌入自己的知识，这个模型就可以在某些场合落地了。现在几种fine tune都不是太理想

**Comment by duzx16** [comment]
> > > > 去hugging face上把更新的一些文件下下来替换一下本地文件
> > > 
> > > 
> > > 谢谢。具体哪些文件，不是那八个大bin文件吧
> > 
> > 
> > modeling_chatglm.py和tokenization_chatglm.py
> 
> 只换了这两个文件还是报同样的错 ![image](https://user-images.githubusercontent.com/24979986/232433675-1366d8f7-92a6-44d0-af4b-57db4a49cb41.png)

换到 `MODEL_PATH` 下面

**Comment by MaiziXiao** [comment]
> > > > > 去hugging face上把更新的一些文件下下来替换一下本地文件
> > > > 
> > > > 
> > > > 谢谢。具体哪些文件，不是那八个大bin文件吧
> > > 
> > > 
> > > modeling_chatglm.py和tokenization_chatglm.py
> > 
> > 
> > 只换了这两个文件还是报同样的错 ![image](https://user-images.githubusercontent.com/24979986/232433675-1366d8f7-92a6-44d0-af4b-57db4a49cb41.png)
> 
> 换到 `MODEL_PATH` 下面
是换到MODEL_PATH下面了，是只要这两个py 文件嘛？
![image](https://user-images.githubusercontent.com/24979986/232442029-89a96621-81fa-4272-8362-95d9734a82dc.png)

**Comment by duzx16** [comment]
> > > > > > 去hugging face上把更新的一些文件下下来替换一下本地文件
> > > > > 
> > > > > 
> > > > > 谢谢。具体哪些文件，不是那八个大bin文件吧
> > > > 
> > > > 
> > > > modeling_chatglm.py和tokenization_chatglm.py
> > > 
> > > 
> > > 只换了这两个文件还是报同样的错 ![image](https://user-images.githubusercontent.com/24979986/232433675-1366d8f7-92a6-44d0-af4b-57db4a49cb41.png)
> > 
> > 
> > 换到 `MODEL_PATH` 下面
> > 是换到MODEL_PATH下面了，是只要这两个py 文件嘛？
> > ![image](https://user-images.githubusercontent.com/24979986/232442029-89a96621-81fa-4272-8362-95d9734a82dc.png)

你创建模型的代码不对
```python
config = AutoConfig.from_pretrained(MODEL_PATH, trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained(MODEL_PATH, config=config, trust_remote_code=True)
```

**Comment by MaiziXiao** [comment]
> 



> > > > > > > 去hugging face上把更新的一些文件下下来替换一下本地文件
> > > > > > 
> > > > > > 
> > > > > > 谢谢。具体哪些文件，不是那八个大bin文件吧
> > > > > 
> > > > > 
> > > > > modeling_chatglm.py和tokenization_chatglm.py
> > > > 
> > > > 
> > > > 只换了这两个文件还是报同样的错 ![image](https://user-images.githubusercontent.com/24979986/232433675-1366d8f7-92a6-44d0-af4b-57db4a49cb41.png)
> > > 
> > > 
> > > 换到 `MODEL_PATH` 下面
> > > 是换到MODEL_PATH下面了，是只要这两个py 文件嘛？
> > > ![image](https://user-images.githubusercontent.com/24979986/232442029-89a96621-81fa-4272-8362-95d9734a82dc.png)
> 
> 你创建模型的代码不对
> 
> ```python
> config = AutoConfig.from_pretrained(MODEL_PATH, trust_remote_code=True, pre_seq_len=128)
> model = AutoModel.from_pretrained(MODEL_PATH, config=config, trust_remote_code=True)
> ```

可以了，感谢
