### ISSUE TITLE
6GB显卡提示显存不足

### ISSUE THREAD

**Issue by zhaoyilun** [THUDM/ChatGLM-6B#39]
显卡：3060laptop 6GB
报错：RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 6.00 GiB total capacity; 5.27 GiB already allocated; 0 bytes free; 5.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by zerodegress** [comment]
在web_demo.py或cli_demo.py里面改一下model行
'model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()'

**Comment by yaleimeng** [comment]
6GB显卡很勉强的。
即便量化到INT4，刚开始占5.33GB左右，后续对话过程中随着对话轮次增多，可以增加到8GB甚至10GB以上。
总之10GB以下显存的GPU需要限制一下轮次、长度等参数才能跑。

**Comment by zhaoyilun** [comment]
> 在web_demo.py或cli_demo.py里面改一下model行 'model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()'

已经按照此方法解决，我将关闭本issue，谢谢！

**Comment by willey2020** [comment]
RuntimeError: Library cudart is not initialized
