### ISSUE TITLE
[BUG/Help] <title>微调后推理结果异常，出现很多不想关的字符

### ISSUE THREAD

**Issue by zhangzai666** [THUDM/ChatGLM-6B#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

微调后推理结果异常，出现很多不想关的字符
![image](https://user-images.githubusercontent.com/94370914/229733855-f75d5034-3569-4e8d-9324-38fcf4881791.png)

### Expected Behavior

微调后推理结果异常，出现很多不想关的字符

### Steps To Reproduce

微调后推理结果异常，出现很多不想关的字符

### Environment

```markdown
- OS:
- Python:
- Trans微调后推理结果异常，出现很多不想关的字符formers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
微调后推理结果异常，出现很多不想关的字符
```

### Anything else?

微调后推理结果异常，出现很多不想关的字符

**Comment by 976311200** [comment]
我也出现相似的情况，不过我用的是提供的广告数据集，我初步觉得可能是我微调的权重采用的非量化的，然后微调时候默认的是int4的原因

**Comment by zhangzai666** [comment]
> 微调

我微调的时候没有量化int4也就是没有指定quantization_bit参数，因为制定后量化应该需要cuda，我docker 环境没装原始的cuda而是用的pytorch-gpu带的cuda有关库。这个原因是量化的原因吗

**Comment by 976311200** [comment]
> 

那我是默认用了quantization_bit 4的参数，我的推理结果都是一些异常符号例如<unk>等

**Comment by zhangzai666** [comment]
> 默认用了quantization_bit 4的参数，我的推理结果都是一
