### ISSUE TITLE
[Help] <bash evaluate.sh 执行失败>

### ISSUE THREAD

**Issue by manyuehefeng** [THUDM/ChatGLM-6B#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![1680599210611](https://user-images.githubusercontent.com/61301696/229745552-6f5e2130-da9f-4e4b-9731-84c58fd23f3a.png)

bash evaluate.sh 执行失败请问怎么处理呀~是哪里有问题嘛

### Environment

```markdown
- OS:linux
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请用仓库中最新的代码。这个问题已经修复了

**Comment by manyuehefeng** [comment]
> 请用仓库中最新的代码。这个问题已经修复了
好的谢谢
