### ISSUE TITLE
[BUG/Help] 在Google Colab 上内存爆满导致无法运行

### ISSUE THREAD

**Issue by hutianyu2006** [THUDM/ChatGLM-6B#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在加载Checkpoint切片的时候RAM爆满导致强制停止运行，显存一点动静没有，如图。
RAM got full when loading checkpoint shards and caused a hard exiting while the GPU RAM wasn't moving at all, just as the image shows.
![image](https://user-images.githubusercontent.com/52768188/229970941-e8b1512f-3d5d-4d78-a7c9-f27df43c04e1.png)
运行nvidia-smi正常，截图如下：
Everything normal when running nvidia-smi, as the screenshot shows:
![image](https://user-images.githubusercontent.com/52768188/229971814-20b0bf76-8078-4917-9741-77aeba2b680d.png)

如果这是正常RAM用量，请在README中注明加载checkpoint所需的最低内存；否则，请想办法解决这个问题。
If it is a usual RAM usage, please specify the minimum memory required to load the checkpoint in the README.md; otherwise, please figure out how to fix this.

### Expected Behavior

当加载第五个切片，也就是终端输出`Loading checkpoint shards:  62% 5/8 [00:51<00:30, 10.18s/it]`时，后端自动输出`^C`并停止运行。
When loading the fifth shard, which means the terminal shows `Loading checkpoint shards:  62% 5/8 [00:51<00:30, 10.18s/it]`, the backend hits a `^C` and stops working.

### Steps To Reproduce

1. 打开Colab笔记本 https://colab.research.google.com/drive/11MgDAgYXdLCo-0zMuKotXdndz12pLsDY?usp=sharing
2. 代码执行程序 --> 全部运行
3. 等待第二个代码窗格运行完成，即可看到对应错误

1. Open the Colab Notebook https://colab.research.google.com/drive/11MgDAgYXdLCo-0zMuKotXdndz12pLsDY?usp=sharing
2. Runtime --> Run all
3. Wait for the "complete" of the second code window, when the excepted behavior shows up.

### Environment

```markdown
- OS:Python 3 Google Compute Engine
- Python: 3.9.16
- Transformers:latest
- PyTorch:latest
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
可以直接加载量化后的版本https://huggingface.co/THUDM/chatglm-6b-int4

**Comment by hutianyu2006** [comment]
我吃完饭再试一下，多谢（毕竟显存够用，瓶颈在RAM让我有点吃惊）



---原始郵件---
寄件人： "Zhengxiao ***@***.***&gt;
傳送時間： 2023年4月5日(週三) 中午11:35
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [THUDM/ChatGLM-6B] [BUG/Help] 在Google Colab 上内存爆满导致无法运行 (Issue #398)




 
可以直接加载量化后的版本https://huggingface.co/THUDM/chatglm-6b-int4

**Comment by hutianyu2006** [comment]
Solved.
(p.s. 这个“琐事”是什么情况啊😂)
![image](https://user-images.githubusercontent.com/52768188/229979738-b558ab2c-8529-447a-8d54-c4be310baa3a.png)
