### ISSUE TITLE
[Feature] <title> Can Chatglm provide relevant APIs?

### ISSUE THREAD

**Issue by xuji755** [THUDM/ChatGLM-6B#399]
### Is your feature request related to a problem? Please describe.

We want to use Chatglm to train a database intelligent operation and maintenance model. Can Chatglm provide relevant APIs?

### Solutions

We have some database operation and maintenance knowledge automation data, and we want to use CHATGLM to build a knowledge base. Can CHATGLM provide relevant APIs?

**Comment by duzx16** [comment]
I can't understand what you mean. Since ChatGLM is open sourced, you can use it to build any APIs except for commercial usage.
