### ISSUE TITLE
想问下是否可以支持cpu的部署

### ISSUE THREAD

**Issue by joebnb** [THUDM/ChatGLM-6B#4]
如题，是否支持cpu部署

**Comment by duzx16** [comment]
可以，将demo中的.cuda()去掉即可。但是推理速度可能会比较慢。

**Comment by duzx16** [comment]
可以。将demo中的`.half().cuda()`换成`.float()`，即可，但是推理速度会比较慢

**Comment by joebnb** [comment]
好的，谢谢啦，建议文档中更新下。

**Comment by brealisty** [comment]
> 可以。将demo中的`.half().cuda()`换成`.float()`，即可，但是推理速度会比较慢

@duzx16 cpu模式下运行，内存占用24G左右，是否合理？
