### ISSUE TITLE
[Help] <关于train.sh的配置项目>

### ISSUE THREAD

**Issue by liaoweiguo** [THUDM/ChatGLM-6B#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

readme中这样说的
在默认配置 quantization_bit=4、per_device_train_batch_size=1、gradient_accumulation_steps=16 下，INT4 的模型参数被冻结，一次训练迭代会以 1 的批处理大小进行 16 次累加的前后向传播，等效为 16 的总批处理大小，此时最低只需 6.7G 显存。若想在同等批处理大小下提升训练效率，可在二者乘积不变的情况下，加大 per_device_train_batch_size 的值，但也会带来更多的显存消耗，请根据实际情况酌情调整。

这里二者乘积不变，是指哪两个参数？per_device_train_batch_size 和gradient_accumulation_steps 吗？我有80G显存，可以配per_device_train_batch_size=8、gradient_accumulation_steps=16 还是per_device_train_batch_size=8、gradient_accumulation_steps=2 

### Expected Behavior

加快训练速度

### Steps To Reproduce

1. ptuning
2. wait

### Environment

```markdown
- OS: ubuntu20.04
- Python: 3.8
- Transformers: 4.27.1
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
这里的意思是如果你想保持训练的batch size不变的话，应该保持per_device_train_batch_size和gradient_accumulation_steps的乘积不变。
