### ISSUE TITLE
不考虑给个清华源么？墙内往下模型太慢太慢太慢了，你一更新前面的模型又没法用了

### ISSUE THREAD

**Issue by Timaos123** [THUDM/ChatGLM-6B#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如题

### Expected Behavior

如题

### Steps To Reproduce

。。。。

### Environment

```markdown
。。。
```

### Anything else?

。。。

**Comment by duzx16** [comment]
已经提供了https://cloud.tsinghua.edu.cn/d/fb9f16d6dc8f482596c2
huggingface repo上我们只更新过代码。模型文件我们目前没有更新过，如果以后更新的话也会同步。在git pull的时候前面加上`GIT_LFS_SKIP_SMUDGE=1`就会跳过模型文件了
