### ISSUE TITLE
[Help] <title将 `prompt_column` 和 `response_column` 改为 JSON 文件中输入文本和输出文本对应的 KEY是指什么？

### ISSUE THREAD

**Issue by jlliushi** [THUDM/ChatGLM-6B#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在Readme的“使用自己的数据集”中说：
修改 `train.sh` 和 `evaluate.sh` 中的 `train_file`、`validation_file`和`test_file`为你自己的 JSON 格式数据集路径，并将 `prompt_column` 和 `response_column` 改为 JSON 文件中输入文本和输出文本对应的 KEY。
其中的 `train_file`、`validation_file`和`test_file`在 ADGEN(广告生成) 数据集 AdvertiseGen 中分别是指哪个文件？将 `prompt_column` 和 `response_column` 改为 JSON 文件中输入文本和输出文本对应的 KEY是指什么？
是将“--prompt_column content \”和“--response_column summary \”中的 content 和 summary 改成两个数值吗？他们对应的  KEY 值在哪里？

### Steps To Reproduce

无

### Environment

```markdown
- OS:windows10
- Python:3.10
- Transformers:4.26.1
- PyTorch:1.14
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.7
```

**Comment by ish505** [comment]
就是你的json文件里面的问和答字段的名称啊，比如{"q" : "问问题。。。", "a" : "回答一下"}，那对应的就是q和a作为参数值了。
