### ISSUE TITLE
[Help] <使用量化模型进行推理无输出>

### ISSUE THREAD

**Issue by wwb306** [THUDM/ChatGLM-6B#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用量化模型，不管是从源模型使用quantize(4)的方法进行量化，还是直接下载hf上的已经量化好的模型，在推理时，均提示
```
The dtype of attention mask(torch.int64) is not bool
```
但去掉量化方法，使用原模型进行推理时，可以正常输入，证明原模型、环境等应该没有问题。

### Expected Behavior

正常推理输出

### Steps To Reproduce

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).quantize(4).half().cuda()

response, history = model.chat(tokenizer, "你好“,history=[])

### Environment

```markdown
- OS:ubuntu
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.13
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

没有具体的代码行报错，同时还在运行文件夹下生成了一个core.xxxxx的文件

**Comment by shibing624** [comment]
+1, 运行正常结束，依然产生core dump文件

**Comment by chenyiwan** [comment]
in8 是可以输出的。只是慢了一点。int 4我也试了。慢是太多了。简直无法用。。

**Comment by wwb306** [comment]
找到原因了，应该是我的torch是1.13导致的，改为1.11后，依旧有提示，但是能正常输出结果了。
