### ISSUE TITLE
[BUG/Help] <执行evaluate.sh 推理过程中报错>

### ISSUE THREAD

**Issue by manyuehefeng** [THUDM/ChatGLM-6B#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![ccb19bc7981e836c886302530015ae5](https://user-images.githubusercontent.com/61301696/230265592-70cc46d9-2b27-46a4-9b0c-e7945abfe430.png)
请问推理过程中出现这个报错是什么意思呢

### Steps To Reproduce

请问推理过程中出现这个报错是什么意思呢

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zbbwss** [comment]
i have the  same problem,.
do you  have addressed this?

**Comment by manyuehefeng** [comment]
> i have the same problem,. do you have addressed this?

I haven't received a response yet.

**Comment by manyuehefeng** [comment]
> i have the same problem,. do you have addressed this?

![1680759651595](https://user-images.githubusercontent.com/61301696/230281922-03c59425-65cf-488e-8d3d-18147bd59c91.png)
After replacing these two files, it seems that the execution was successful.

**Comment by jingtian11** [comment]
微调的时候报错：ValueError: Need either a dataset name or a training/validation file.应该怎么修改啊

**Comment by manyuehefeng** [comment]
> 微调的时候报错：ValueError: Need either a dataset name or a training/validation file.应该怎么修改啊

https://github.com/THUDM/ChatGLM-6B/issues/391#issue-1653499049 使用最新的代码&最新的模型配置文件

**Comment by jingtian11** [comment]
> > 微调的时候报错：ValueError: Need either a dataset name or a training/validation file.应该怎么修改啊
> 
> [#391 (comment)](https://github.com/THUDM/ChatGLM-6B/issues/391#issue-1653499049) 使用最新的代码&最新的模型配置文件

好的，我试一下

**Comment by jingtian11** [comment]
报错   OSError: Can't load the configuration of './output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000' is the correct path to a directory containing a config.json file 是什么意思哇~各位大佬有会的嘛
