### ISSUE TITLE
[BUG/Help] <The website is beautiful,Could you please share the sources?>

### ISSUE THREAD

**Issue by Axbros** [THUDM/ChatGLM-6B#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

url:https://chatglm.cn/login?redirect=%2F
The website is beautiful,Could you please share the sources?
Thanks a lot!

### Steps To Reproduce

1.I want to study this webui

### Environment

```markdown
- OS:Macos
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
Of course ... not.
