### ISSUE TITLE
[BUG/Help] <通过广告词训练之后感觉其他的回答认知出现了问题~>

### ISSUE THREAD

**Issue by manyuehefeng** [THUDM/ChatGLM-6B#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![1680761544592](https://user-images.githubusercontent.com/61301696/230287458-3a2ec908-13f2-4840-a750-a0442b0e8206.png)
![1680761823941](https://user-images.githubusercontent.com/61301696/230287791-c94d96bb-b5c8-4dd8-9b2e-acca16236a4c.png)

通过广告词训练之后感觉其他的回答认知出现了问题，请问这是正常的吗

### Steps To Reproduce

通过广告词训练之后感觉其他的回答认知出现了问题，请问这是正常的吗

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by 976311200** [comment]
这是正常的  因为我微调后也这样了

**Comment by dragononly** [comment]
> 这是正常的 因为我微调后也这样了
这显然不正常。

**Comment by JaheimLee** [comment]
> > 这是正常的 因为我微调后也这样了
> > 这显然不正常。

如果你理解ptuning在干什么，这显然正常。
本来一个对话模型，现在把输入变成非流畅文本语言，每层还额外加入prompt，怎么可能保留之前的能力。
如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。ptuning这种引入额外结构的根本不能用。

**Comment by dragononly** [comment]
> > > 这是正常的 因为我微调后也这样了
> > > 这显然不正常。
> 
> 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。
如果这样的话微调法，没有任何意义了。

**Comment by smartparrot** [comment]
全量或lora微调输入是问题和答案拼起来吗，输出仅仅是答案？

**Comment by 336655asd** [comment]
> > > 这是正常的 因为我微调后也这样了
> > > 这显然不正常。
> 
> 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。

没错，直观理解起来就是你通过p-tuning之后，等于在基座模型之上加了一层全连接，现在它只支持当前的任务了。

**Comment by dragononly** [comment]
> > > > 这是正常的 因为我微调后也这样了
> > > > 这显然不正常。
> > 
> > 
> > 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。
> 
> 没错，直观理解起来就是你通过p-tuning之后，等于在基座模型之上加了一层全连接，现在它只支持当前的任务了。

那如何解决这个问题呢。

**Comment by suc16** [comment]
> > > > > 这是正常的 因为我微调后也这样了
> > > > > 这显然不正常。
> > > 
> > > 
> > > 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。
> > 
> > 
> > 没错，直观理解起来就是你通过p-tuning之后，等于在基座模型之上加了一层全连接，现在它只支持当前的任务了。
> 
> 那如何解决这个问题呢。

改成lora。。

**Comment by chenyiwan** [comment]
> 



> > > > > > 这是正常的 因为我微调后也这样了
> > > > > > 这显然不正常。
> > > > 
> > > > 
> > > > 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。
> > > 
> > > 
> > > 没错，直观理解起来就是你通过p-tuning之后，等于在基座模型之上加了一层全连接，现在它只支持当前的任务了。
> > 
> > 
> > 那如何解决这个问题呢。
> 
> 改成lora。。

lora在我这里也一样影响 之前的回答，以前的回答内容都 乱了。。

**Comment by suc16** [comment]
> > > > > > > 这是正常的 因为我微调后也这样了
> > > > > > > 这显然不正常。
> > > > > 
> > > > > 
> > > > > 如果你理解ptuning在干什么，这显然正常。 本来一个对话模型，现在把输入变成非流畅文本，每层还额外加入prompt，怎么可能保留之前的能力。 如果你需要保留对话能力，肯定要把输入指令全部改写成人话，并且用lora的方式仅微调q、v来减少影响。我理解ptuning这种引入额外结构的根本不适用在这种场景下。
> > > > 
> > > > 
> > > > 没错，直观理解起来就是你通过p-tuning之后，等于在基座模型之上加了一层全连接，现在它只支持当前的任务了。
> > > 
> > > 
> > > 那如何解决这个问题呢。
> > 
> > 
> > 改成lora。。
> 
> lora在我这里也一样影响 之前的回答，以前的回答内容都 乱了。。

lora在我这边试没这个问题。而且lora的有效性，搞alpaca-lora的人都验证过了。

**Comment by suc16** [comment]
> 
推荐友情链接里的 chatglm-tuning

**Comment by yangliuIOC** [comment]
> @songsa1 推荐友情链接里的 chatglm-tuning

请问，你用过lora跑过 这个广告数据集么，

**Comment by suc16** [comment]
> > @songsa1 推荐友情链接里的 chatglm-tuning
> 
> 请问，你用过lora跑过 这个广告数据集么，

肯定没啊。。。不过lora也会有复读机情况发生。

**Comment by qq446840178** [comment]
修改下train.sh 的学习率 LR=1e-4  广告词的应该就可以跑起来了。

**Comment by SZ-ing** [comment]
> 修改下train.sh 的学习率 LR=1e-4 广告词的应该就可以跑起来了。

好玄学，我自己跑法律问题，1e-4，完全学不到东西，用原本的2e-2，效果才比较好。
