### ISSUE TITLE
[BUG/Help] 我的rasa机器人是基于tensorflow的，有支持tensorflow的方案吗

### ISSUE THREAD

**Issue by huanglx27** [THUDM/ChatGLM-6B#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 目前huggingface上提供的是pytorch的预训练模型，请问有提供tensorflow版的计划吗
2. 如果没有，有没有推荐的模型转换方法呢。

### Steps To Reproduce

略

### Environment

```markdown
略
```

**Comment by duzx16** [comment]
1. 没有
2. 没有相关经验
