### ISSUE TITLE
[BUG/Help] 按照微调的文档进行，但是运行时遇到了 AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads' 错误

### ISSUE THREAD

**Issue by ceven2010** [THUDM/ChatGLM-6B#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我按照文档描述的流程进行处理，并没有做过任何调整，但是执行过程中却遇到了这个错误

[INFO|trainer.py:511] 2023-04-06 16:06:03,597 >> max_steps is given, it will override any value given in num_train_epochs
Traceback (most recent call last):
  File "/home/xxx/workspace/text/ChatGLM-6B/ptuning/main.py", line 393, in <module>
    main()
  File "/home/xxx/workspace/text/ChatGLM-6B/ptuning/main.py", line 331, in main
    model.enable_input_require_grads()
  File "/home/xxx/anaconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### Steps To Reproduce

1. 下载 AdvertiseGen 数据集并放到项目根目录
2. 直接运行命令 `bash train.sh`

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.10.9
- Transformers:4.26.1
- PyTorch: 2.0.0+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by ceven2010** [comment]
> 在[Hugging Face](https://huggingface.co/THUDM/chatglm-6b/tree/main)下载并更新模型权重之外的其他文件（.bin文件之外的其他文件）后，重新运行 _train.sh_

感谢您的回复，但是我按照您的指导，重新下载了所有的文件，依旧是同样的问题

**Comment by ceven2010** [comment]
@Jaren1907 感谢您的指导，已经顺利解决了这个问题，是我环境配置缺点组件，重新调整了一下就可以了。

**Comment by maxfeng1979** [comment]
> @Jaren1907 感谢您的指导，已经顺利解决了这个问题，是我环境配置缺点组件，重新调整了一下就可以了。

我也遇到同样问题，请问下具体怎么解决？

**Comment by duzx16** [comment]
需要更新 transformers `4.27.1` 版本

**Comment by wk-955** [comment]
> @Jaren1907 感谢您的指导，已经顺利解决了这个问题，是我环境配置缺点组件，重新调整了一下就可以了。

请问是缺什么组件，我也是报 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'错误
