### ISSUE TITLE
[Help] model.stream_chat方法有办法支持多个问题同时推理吗？

### ISSUE THREAD

**Issue by LikeNeko** [THUDM/ChatGLM-6B#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前我这边测试只要开个线程多个问题一起推理就会报错

### Steps To Reproduce

1

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
据我所知PyTorch model应该是没法被并行调用的吧，除非你自己写一个调度器打成batch

**Comment by LikeNeko** [comment]
> 据我所知PyTorch model应该是没法被并行调用的吧，除非你自己写一个调度器打成batch

知道了谢谢
