### ISSUE TITLE
[Feature] <Embedding Layer Gradient Shrink 在哪一行呀？>

### ISSUE THREAD

**Issue by weizhenzhao** [THUDM/ChatGLM-6B#421]
### Solutions

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/13706689/230400130-5b8dbbd5-a17d-44ab-a840-980c9d301388.png">

- 看过CHATGLM的论文，里面说在预训练的时候，为了使得训练的过程更加稳定，
- 采用了DeepNorm 和 Emedding Layer Gradient Shrink两种Trick。
- 然后我在代码里面找到了 DeepNorm的公式。
- 但是没有找到Embedding Layer Gradient Shrink的代码。
- 想问下EGS这个实现是在哪几行代码呀？

谢谢

**Comment by duzx16** [comment]
这个方法是预训练的时候加的。公开的代码中没有

**Comment by jiezhangGt** [comment]
> > 这个方法是预训练的时候加的。公开的代码中没有
> 
> 您好 看您的回复，我能理解为，预训练时的代码和公开的代码不一致，所以我如果基于chatGLM来在领域内大量无监督文本上继续训练，这条路是走不通的 是吗

兄弟，你这个问题解决了吗？
