### ISSUE TITLE
[BUG/Help] <title>KeyError: 'lm_head.weight'

### ISSUE THREAD

**Issue by deuterium11** [THUDM/ChatGLM-6B#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

报错：KeyError: 'lm_head.weight'

### Expected Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ChatGLM-6B-main\cli_demo.py", line 7, in <module>
    model = AutoModel.from_pretrained(r"C:\Users\Administrator\Downloads\ChatGLM-6B-main\model",trust_remote_code=True,ignore_mismatched_sizes=True).half().quantize(4).cuda()
  File "C:\Program Files\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Program Files\Python310\lib\site-packages\transformers\modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Program Files\Python310\lib\site-packages\transformers\modeling_utils.py", line 2959, in _load_pretrained_model
    mismatched_keys += _find_mismatched_keys(
  File "C:\Program Files\Python310\lib\site-packages\transformers\modeling_utils.py", line 2882, in _find_mismatched_keys
    and state_dict[checkpoint_key].shape != model_state_dict[model_key].shape
KeyError: 'lm_head.weight'

### Steps To Reproduce

报错：KeyError: 'lm_head.weight'

### Environment

```markdown
- OS:windows 10
- Python:3.10
- Transformers:4.27.1
- PyTorch:cu118
- CUDA Support True
```

**Comment by gongfuchang** [comment]
it seems someone push a ['commit '](https://huggingface.co/THUDM/chatglm-6b/commit/63ce1bac4a7a7da57c67448bab39ddbe0e115a19) says 'Update code for slim' on HF repo, which changed the vocab_size and others, without updating the model fine.

**Comment by duzx16** [comment]
Please update your model file `pytorch_model-00001-of-00008.bin` and `pytorch_model-00008-of-00008.bin`

**Comment by duzx16** [comment]
> it seems someone pushed a ['commit '](https://huggingface.co/THUDM/chatglm-6b/commit/63ce1bac4a7a7da57c67448bab39ddbe0e115a19) says 'Update code for slim' on HF repo, which changed the vocab_size and others, without updating the model files.

@gongfuchang The model files are updated in the following commits.

**Comment by gongfuchang** [comment]
> 

seen it now. thank u.
