### ISSUE TITLE
[Feature]  支持视觉信息输入和理解，类似于GPT-4

### ISSUE THREAD

**Issue by feizc** [THUDM/ChatGLM-6B#425]
### Is your feature request related to a problem? Please describe.

通过微调模型，支持视觉信息输入，类似于GPT-4。

目前已经在LLaMA语言模型上进行尝试，且结果不错。
参考：https://github.com/feizc/Visual-LLaMA 

在迁移到chatglm的时候遇到问题，是否有计划让chatglm支持视觉理解？

也欢迎大家提供和讨论可行的方案。

**Comment by zx2021** [comment]
这个不错

**Comment by ZhengQinLai** [comment]
@feizc 你好！可以分享一下遇到了什么问题吗？

**Comment by zhangch9** [comment]
[VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B)支持图像输入，欢迎体验。
