### ISSUE TITLE
[BUG/Help] M2的Mac能够运行，但无法获得正常的输出

### ISSUE THREAD

**Issue by Min9X1n** [THUDM/ChatGLM-6B#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

能够运行，并且没有任何报错，但是无法正常输出内容，如图
已确保模型和代码为最新，且PyTorch为nightly

<img width="847" alt="截屏2023-04-07 08 45 28" src="https://user-images.githubusercontent.com/24851997/230523614-d9eed683-20be-4d4b-b0d1-d8fd286622b9.png">

### Steps To Reproduce

正常运行，无任何报错

### Environment

```markdown
- OS:macOS 13.3
- Python: 3.10.10
- Transformers: 4.27.1
- PyTorch: pytorch-2.1.0.dev20230406
```

**Comment by kingzeus** [comment]
把half()换成float()试试

**Comment by Min9X1n** [comment]
> 把half()换成float()试试

感谢！换成float成功了，但是可能是内存不够，五六百秒才出三四个字
之前macOS 13.2的时候 用half()成功过，速度很快，结果今天更新系统，就不能用了

**Comment by Caleb66666** [comment]
> 

你好，请问下，大约要多大内存才能加载

**Comment by Min9X1n** [comment]
> 你好，请问下，大约要多大内存才能加载

我是24G内存的M2，如果用float()的话，前台只运行ChatGLM和浏览器，用“活动监视器”看内存压力是黄色的，已用22G+，已使用的交换大概在7G左右。half()会好些，但是具体的数值我没有看，至少当时开其他软件不会感觉卡 :(

**Comment by Caleb66666** [comment]
> 

感谢分享。我这16G估计有些吃紧了

**Comment by zbz0425** [comment]
> 

ModuleNotFoundError: No module named 'transformers'
执行遇到这种怎么办，但是已经安装了transformers

**Comment by imClumsyPanda** [comment]
> > 把half()换成float()试试
> 
> 感谢！换成float成功了，但是可能是内存不够，五六百秒才出三四个字 之前macOS 13.2的时候 用half()成功过，速度很快，结果今天更新系统，就不能用了

我这边也是macOS 13.3就不能正常使用了 似乎是macOS新版本和torch兼容性有问题

**Comment by imClumsyPanda** [comment]
我这边也是macOS 13.3就不能正常使用了 重装了conda环境之后 系统也更新到了macOS 13.3.1之后可以用了

**Comment by vvanglro** [comment]
> 我这边也是macOS 13.3就不能正常使用了 重装了conda环境之后 系统也更新到了macOS 13.3.1之后可以用了

跑一下得多长时间才能出结果啊

**Comment by imClumsyPanda** [comment]
我这边是M1 Max 64G内存，第一个问题还比较快 30秒左右差不多

Peanut ***@***.***>于2023年4月8日 周六10:49写道：

**Comment by vvanglro** [comment]
> 我这边是M1 Max 64G内存，第一个问题还比较快 30秒左右差不多 
我32G的  macOS 13.3.1
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/43594924/230701037-fdae82e9-89cf-4e1a-8ce0-1093a69a868a.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/43594924/230701061-e1e68122-d789-4835-b3e8-443cb1224a7e.png">
就图上的版本和代码得140s

**Comment by kingzeus** [comment]
可以看下我的fork https://github.com/kingzeus/ChatGLM-6B  cli_demo.py

**Comment by Min9X1n** [comment]
> 可以看下我的fork https://github.com/kingzeus/ChatGLM-6B cli_demo.py
> 
> 支持mps，回答大概5-8s左右，内存24G

嗯嗯好的，谢谢！！辛苦了
