### ISSUE TITLE
[BUG/Help] <title>参数：do_sample=True, top_p=0.7, temperature=0.95  各是什么意思？？？

### ISSUE THREAD

**Issue by cristianohello** [THUDM/ChatGLM-6B#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

参数：do_sample=True, top_p=0.7, temperature=0.95  各是什么意思？？？

### Expected Behavior

参数：do_sample=True, top_p=0.7, temperature=0.95  各是什么意思？？？

### Steps To Reproduce

参数：do_sample=True, top_p=0.7, temperature=0.95  各是什么意思？？？

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://huggingface.co/docs/transformers/v4.27.2/en/main_classes/text_generation#transformers.GenerationConfig
