### ISSUE TITLE
有大佬实现了传入PDF让模型回答问题的嘛

### ISSUE THREAD

**Issue by zck573693104** [THUDM/ChatGLM-6B#429]
### Solutions

传入PDF让模型回答问题

**Comment by l15y** [comment]
https://github.com/l15y/wenda

**Comment by zck573693104** [comment]
> https://github.com/l15y/wenda

我来试一试

**Comment by imClumsyPanda** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM
