### ISSUE TITLE
[BUG/Help] <RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:>

### ISSUE THREAD

**Issue by zxjhellow2** [THUDM/ChatGLM-6B#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行cli_demo的时候出现问题，实在搞不懂这个问题出现在哪里，关于文件修改，只修改了模型的存储路径，其他没用改动，我尝试按照他的建议修改，也没有效果。

`(pytorch) zhangxj@ubuntu-NF5468M6:~$ /home/zhangxj/miniconda3/envs/pytorch/bin/python3.9 /home/zhangxj/gitspace/ChatGLM-6B/cli_demo.py`

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
/home/zhangxj/miniconda3/envs/pytorch/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.14s/it]
Traceback (most recent call last):
  File "/home/zhangxj/gitspace/ChatGLM-6B/cli_demo.py", line 7, in <module>
    model = AutoModel.from_pretrained("/home/zhangxj/models/chatgpt6b", trust_remote_code=True).half().quantize(4).cuda()
  File "/home/zhangxj/miniconda3/envs/pytorch/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/home/zhangxj/miniconda3/envs/pytorch/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/zhangxj/miniconda3/envs/pytorch/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3019, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")

RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).
	size mismatch for lm_head.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### Expected Behavior

修改问题

### Steps To Reproduce

```python
import os
import platform
import signal
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("/home/zhangxj/models/chatgpt6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/home/zhangxj/models/chatgpt6b", trust_remote_code=True).half().cuda()
model = model.eval()

os_name = platform.system()
clear_command = 'cls' if os_name == 'Windows' else 'clear'
stop_stream = False


def build_prompt(history):
    prompt = "欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序"
    for query, response in history:
        prompt += f"\n\n用户：{query}"
        prompt += f"\n\nChatGLM-6B：{response}"
    return prompt


def signal_handler(signal, frame):
    global stop_stream
    stop_stream = True


def main():
    history = []
    global stop_stream
    print("欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")
    while True:
        query = input("\n用户：")
        if query.strip() == "stop":
            break
        if query.strip() == "clear":
            history = []
            os.system(clear_command)
            print("欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")
            continue
        count = 0
        for response, history in model.stream_chat(tokenizer, query, history=history):
            if stop_stream:
                stop_stream = False
                break
            else:
                count += 1
                if count % 8 == 0:
                    os.system(clear_command)
                    print(build_prompt(history), flush=True)
                    signal.signal(signal.SIGINT, signal_handler)
        os.system(clear_command)
        print(build_prompt(history), flush=True)


if __name__ == "__main__":
    main()

```

### Environment

```markdown
- OS:Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-35-generic x86_64)
- Python: 3.9 
- Transformers:4.27.1
- PyTorch:2.0.0+cu117'
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
需要更新一下 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin`

**Comment by zxjhellow2** [comment]
谢谢，我试试

**Comment by zxjhellow2** [comment]
> 需要更新一下 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin`

我去更新一下

**Comment by zxjhellow2** [comment]
> 需要更新一下 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin`

谢谢提醒，原来昨天更新了好几个文件，终于好了

**Comment by runvyang** [comment]
from_pretrained仍然会下载老的文件，手动下载到目录就可以了

**Comment by zxjhellow2** [comment]
> 这里说的更新一下只是重新下载吗？今天重新下载的版本shape也是(150528, 4096)

是的，总之我是重新下载了最新的版本

**Comment by dalei2019** [comment]
重新从[清华官方网站](https://cloud.tsinghua.edu.cn/d/fb9f16d6dc8f482596c2/)下载模型，这一个报错跳过了！
