### ISSUE TITLE
[BUG/Help] 在bash evaluate.sh的时候报错 <title>OSError: Can't load the configuration of './output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000'. If you were trying to load it from 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![28144e5d5d795b5d6e99b32f52c82f5](https://user-images.githubusercontent.com/123447380/230545439-b72fa51c-f0f7-480f-87eb-2e49ee7bbe93.png)

OSError: Can't load the configuration of './output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000' is the correct path to a directory containing a config.json file

### Expected Behavior

求问各位大佬怎么解决一下啊~~~
![image](https://user-images.githubusercontent.com/123447380/230544989-80e8ea31-a6e6-40b7-80d1-c171553a323b.png)
这里要换成自己的路径嘛

### Steps To Reproduce

train已经完成，在evalute的时候报错

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请确保`./output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000`这个目录是存在的，不然的话要换成你微调后的checkpoint目录

**Comment by jingtian11** [comment]
> 请确保`./output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000`这个目录是存在的，不然的话要换成你微调后的checkpoint目录，在`evaluate.sh`里面

好的好的，已经解决啦~！！！
太感谢了

**Comment by BLAIR-wy** [comment]
> 

请问是怎么解决的呀？我也遇到了这个问题。 是要改train.sh里面的什么参数吗？

**Comment by BLAIR-wy** [comment]
> 请确保`./output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000`这个目录是存在的，不然的话要换成你微调后的checkpoint目录，在`evaluate.sh`里面

你好 我运行 bash train.sh之后 没有生成checkpoint文件夹怎么办呢

**Comment by BLAIR-wy** [comment]
> 请确保`./output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000`这个目录是存在的，不然的话要换成你微调后的checkpoint目录，在`evaluate.sh`里面

请问这个chekpoint是自动生成的吧？ 我运行bash train.sh之后 没有找到checkpoint文件是什么原因呢
