### ISSUE TITLE
[BUG/Help] <Out of range: piece id is out of range.>

### ISSUE THREAD

**Issue by LiuChen19960902** [THUDM/ChatGLM-6B#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

今天早上跟着hf里面更新的一遍模型和几个py文件，然后就开始出这个错误了

### Expected Behavior

今天早上跟着hf里面更新的一遍模型和几个py文件，然后就开始出这个错误了

### Steps To Reproduce

- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by natureLanguageQing** [comment]
![image](https://user-images.githubusercontent.com/37429336/230570138-1bb25723-d981-4839-9994-8db9e34b240a.png)
我也遇到了这个问题

**Comment by duzx16** [comment]
如果是在ptuning里遇到这个问题的话，请重新pull一下本仓库的代码

**Comment by FeiWard** [comment]
重新pull之后还是一样的错误

**Comment by genius0182** [comment]
我发现https://huggingface.co/THUDM/chatglm-6b/blob/main/configuration_chatglm.py上的这里
![image](https://user-images.githubusercontent.com/24863486/231077894-f5e0e59b-09ac-4d44-92f0-d751adbca1f4.png)
和https://huggingface.co/THUDM/chatglm-6b/blob/main/config.json
![image](https://user-images.githubusercontent.com/24863486/231078049-ee62c798-89ce-4d38-8c75-cec333d3e96b.png)
数据不一样。不知道是不是这里的问题。 @duzx16

**Comment by zy86603465** [comment]
@genius0182
我都改成
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "mask_token_id": 130000,
  "gmask_token_id": 130001,
试了一下，还是报原来的错

**Comment by Data2Me** [comment]
我也遇到了这个问题

**Comment by zy86603465** [comment]
这个问题我解决了，把所有的模型文件和配置及代码更新一下就可以了

**Comment by CHJERS** [comment]
> 

想问一下是下到本地运行的嘛？我也更新了，但还是有问题，更新HF里的模型和git里的代码需要改其他参数嘛

**Comment by duzx16** [comment]
> 我发现[https://huggingface.co/THUDM/chatglm-6b/blob/main/configuration_chatglm.py上的这里](https://huggingface.co/THUDM/chatglm-6b/blob/main/configuration_chatglm.py%E4%B8%8A%E7%9A%84%E8%BF%99%E9%87%8C) ![image](https://user-images.githubusercontent.com/24863486/231077894-f5e0e59b-09ac-4d44-92f0-d751adbca1f4.png) 和https://huggingface.co/THUDM/chatglm-6b/blob/main/config.json ![image](https://user-images.githubusercontent.com/24863486/231078049-ee62c798-89ce-4d38-8c75-cec333d3e96b.png) 数据不一样。不知道是不是这里的问题。 @duzx16

图1是默认的值，图2是实际设置的值，不冲突。

**Comment by kingtigerc** [comment]
我今天新拉的代码和模型，也发生这个问题。这是什么原因导致的?

**Comment by kingtigerc** [comment]
重新pull,重新拉模型，重新pip install -r requirements.txt,解决了

**Comment by lrx1213** [comment]
遇到了同样的问题

**Comment by JimXiongGM** [comment]
遇到了同样的问题，应该是tokenizer decode时候有bug，但是再次生成，有时候又不会有问题。

可以尝试加try绕过这个问题：

```python
  retry_cnt=0
  while retry_cnt < 5:
      try:
          response, history = model.chat(
              tokenizer,
              query,
              history=[],
              max_length=512,
              num_beams=5,
              do_sample=True,
              top_p=0.7,
              temperature=0.95,
          )
          break
      except Exception as e1:
          retry_cnt += 1
```

**Comment by zhangyuanscall** [comment]
就是decode源码有问题，我用同一个权重版本的chatglm，尝试多种解码参数，有的解码参数没问题，有的解码参数就有问题

**Comment by ysanimals** [comment]
用的是另外的仓库微调的代码，请问应该如何解决这个decode出现问题

**Comment by Doufanfan** [comment]
+1, decode源码的这个问题要怎么解决。。。

**Comment by godcrying** [comment]
所以，这个issue为什么关闭了？

**Comment by diaojunxian** [comment]
> 所以，这个issue为什么关闭了？

+1 我也遇到了

**Comment by yecphaha** [comment]
参考 https://huggingface.co/THUDM/chatglm3-6b/commit/ea563876364622a0a5c24e6b71db0b93a9861ba0#d2h-069285
在 tokenization_chatglm.py 里新增两行代码
![Snipaste_2023-11-21_17-42-58](https://github.com/THUDM/ChatGLM-6B/assets/32784059/40c4f6ee-6aae-4c0f-bb2a-ce3571fbd7be)

**Comment by ayrnb** [comment]
+1

**Comment by yecphaha** [comment]
> +1

可以参考 https://huggingface.co/THUDM/chatglm3-6b/commit/ea563876364622a0a5c24e6b71db0b93a9861ba0#d2h-069285
在 tokenization_chatglm.py 里新增两行代码

**Comment by greyovo** [comment]
> 参考 https://huggingface.co/THUDM/chatglm3-6b/commit/ea563876364622a0a5c24e6b71db0b93a9861ba0#d2h-069285 在 tokenization_chatglm.py 里新增两行代码 ![Snipaste_2023-11-21_17-42-58](https://private-user-images.githubusercontent.com/32784059/284535170-40c4f6ee-6aae-4c0f-bb2a-ce3571fbd7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTEyMzYsIm5iZiI6MTcwMzA1MDkzNiwicGF0aCI6Ii8zMjc4NDA1OS8yODQ1MzUxNzAtNDBjNGY2ZWUtNmFhZS00YzBmLWJiMmEtY2UzNTcxZmJkN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1NDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzZlZjJlYzQ3NmQwZmUwMTBiN2UzYTFhZmU1YWQxMDc3N2VlNTdhMDcyMmFlZjA0YzMzMDRjYWU1NDE2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuwCJQBUQ9ful3_3WscvmYhZWDxfj4vaoPxbxQh5Zsc)

有用。再明确一些的话，对于ChatGLM-6B来说，则是在 `tokenization_chatglm.py` 中：
```py
class TextTokenizer:
    def __init__(self, model_path):
        self.sp = spm.SentencePieceProcessor()
        self.sp.Load(model_path)
        self.num_tokens = self.sp.vocab_size()
   # .... 省略其他方法

    def convert_id_to_token(self, idx):
        if idx > self.num_tokens:  # 在这里添加判断
            return ""
        return self.sp.IdToPiece(idx)
```
