### ISSUE TITLE
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder

### ISSUE THREAD

**Issue by 1a2cjitenfei** [THUDM/ChatGLM-6B#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transformers是4.27.1呀

### Steps To Reproduce

bash main.sh

### Environment

```markdown
- OS:Ubuntu 18.04
- Python:3.8
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support:True
```

**Comment by 1a2cjitenfei** [comment]
不是bash main.sh是bash train.sh

**Comment by duzx16** [comment]
更新模型目录

**Comment by 1a2cjitenfei** [comment]
> 更新模型目录

好的，非常感谢

**Comment by 1a2cjitenfei** [comment]
> 更新模型目录

更新后还是这个报错
Traceback (most recent call last):
  File "main.py", line 413, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/home/mlamp/miniconda3/envs/chatglm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

是不是修改transformers库了？

**Comment by 1a2cjitenfei** [comment]
> 更新模型目录

我把hugging face上距离上次更新小于24小时的文件都更新了一遍

**Comment by duzx16** [comment]
最新的代码里prefix_encoder的定义在https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L835
没有理由不存在

**Comment by shangkegit** [comment]
我也遇到一样的错误，你是不是也是用的chatglm-6b-int4

**Comment by yinshipeng** [comment]
我也遇见同样的问题，我是在做完训练数据之后，跑测试验证的时候出现的。代码如下：
```
import os
import torch
from transformers import AutoConfig, AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

prefix_state_dict = torch.load(os.path.join("/content/drive/MyDrive/ai/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000", "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
```

**Comment by yinzhang809** [comment]
> 我也遇见同样的问题，我是在做完训练数据之后，跑测试验证的时候出现的。代码如下：
> 
> ```
> import os
> import torch
> from transformers import AutoConfig, AutoModel, AutoTokenizer
> 
> tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
> model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
> 
> prefix_state_dict = torch.load(os.path.join("/content/drive/MyDrive/ai/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000", "pytorch_model.bin"))
> new_prefix_state_dict = {}
> for k, v in prefix_state_dict.items():
>     new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
> model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
> ```

model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
这行 预测时需要模型config中含有 pre_seq_len， 模型才会定义prefix_encoder

参考   
https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L108
https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L109
https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L117

**Comment by laszo** [comment]
> > 我也遇见同样的问题，我是在做完训练数据之后，跑测试验证的时候出现的。代码如下：
> > ```
> > import os
> > import torch
> > from transformers import AutoConfig, AutoModel, AutoTokenizer
> > 
> > tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
> > model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
> > 
> > prefix_state_dict = torch.load(os.path.join("/content/drive/MyDrive/ai/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000", "pytorch_model.bin"))
> > new_prefix_state_dict = {}
> > for k, v in prefix_state_dict.items():
> >     new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
> > model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
> > ```
> 
> model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) 这行 预测时需要模型config中含有 pre_seq_len， 模型才会定义prefix_encoder
> 
> 参考
> 
> https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L108
> 
> 
> https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L109
> 
> 
> https://github.com/THUDM/ChatGLM-6B/blob/8e83083d7fe0dd1a6b7f828b1332bab0d9412ae8/ptuning/main.py#L117

这样就可以了
