### ISSUE TITLE
[BUG/Help] <title>在evalute的时候报错raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}") RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![8e6b6aab0b6ecebb8706141bf80d727](https://user-images.githubusercontent.com/123447380/230558354-ac0471e5-89b9-4813-a7d4-bf95d6bfcbb9.png)

### Steps To Reproduce

![11547087998fec0828b7ef09d631d83](https://user-images.githubusercontent.com/123447380/230558500-e966ad75-50c8-4f0e-a01e-b787561f0e84.png)
前面的都可以正常跑通，这里报错说是RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:，请问有知道为什么嘛
之前运行train.sh之后的output是这样的
![f5ef100eaa6c71d09198e6e21e2d593](https://user-images.githubusercontent.com/123447380/230559465-662f05c7-d6a9-4cf8-80c8-46e7a84918cd.png)
这里的"_name_or_path"是否需要修改
![22c9cd7fb9b1d4e971821d054e9ed74](https://user-images.githubusercontent.com/123447380/230559650-cf84b172-8336-47f8-b102-0dd23d529524.png)

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
保存的pytorch_model.bin是量化过的，但是config.json里没有设置量化。正常来说是不应该出现这种情况下。请确认你训练时使用的transformers是4.27.1版本，并且使用的模型实现是最新的。

**Comment by jingtian11** [comment]
> 

好的，我尝试一下
