### ISSUE TITLE
[requirements.txt] <去除icetk依赖之后requirements.txt的更新问题>

### ISSUE THREAD

**Issue by jc-ryan** [THUDM/ChatGLM-6B#442]
### Solutions

作者你好，此前requirments.txt中的
protobuf>=3.19.5,<3.20.1这一依赖对protobuf版本的限制貌似是针对icetk的，现在不需要icetk了，还需要这条吗，应该可以去掉了吧？因为目前protobuf最新版本已经到4.22.1了，太陈旧会影响其他代码

**Comment by duzx16** [comment]
试了一下没有问题，已经去掉了
