### ISSUE TITLE
[help] 升级transformers到4.27.1后报错

### ISSUE THREAD

**Issue by Kas1o** [THUDM/ChatGLM-6B#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ModuleNotFoundError: No module named 'transformers_modules.THUDM/chatglm-6b'

### Steps To Reproduce

当我尝试升级transformers至4.27.1后出现：
以及我在https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/README.md中看到需要将transformers升级至4.27.1

### Environment

```markdown
- OS: Windows 10 x64
- Python:3.9
- Transformers:4.27.1
- PyTorch:1.10.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by Kas1o** [comment]
是的，我是从相对路径"THUDM/chatglm-6b"中加载模型

**Comment by Kas1o** [comment]
已解决，应采用绝对路径

**Comment by Ikaros-521** [comment]
win下 /换\ 
相对没毛病
