### ISSUE TITLE
[Help]请教有没有方法拓展Chat-GLM-6B在某个学科领域的知识储备？

### ISSUE THREAD

**Issue by piaocn** [THUDM/ChatGLM-6B#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

想借助ChatGLM-6B进行专业领域文本的分析，希望ChatGLM-6B阅读一段专业领域文本后，回答提出的问题。
例如实现这样的效果：
我问：           胃癌是不是恶性肿瘤？
ChatGLM答：是。

这里面需要ChatGPT知晓胃癌是癌症这个知识，请问如何做能让ChatGLM扩充知识内容？
感谢！

### Expected Behavior

None

### Steps To Reproduce

None

### Environment

```markdown
- OS: not needed
- Python: not needed
- Transformers: not needed
- PyTorch: not needed
- CUDA Support not needed
```

### Anything else?

none

**Comment by piaocn** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM 这个项目有帮助吗

**Comment by imClumsyPanda** [comment]
> https://github.com/imClumsyPanda/langchain-ChatGLM 这个项目有帮助吗

有专业知识的本地文档的话，是可以实现的

**Comment by l15y** [comment]
https://github.com/l15y/wenda

**Comment by songsa1** [comment]
上边这些方案，这些都是使用类似chatpdf的方式实现的，都并没有使模型本身拥有领域知识，

**Comment by yuanjie-ai** [comment]
> https://github.com/imClumsyPanda/langchain-ChatGLM 这个项目有帮助吗

https://github.com/yuanjie-ai/ChatLLM也有相关实现

**Comment by zhangch9** [comment]
可以使用领域数据微调，参考[微调说明](https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/README.md)以及[#330](https://github.com/THUDM/ChatGLM-6B/issues/330)。
