### ISSUE TITLE
是否有更大参数的模型发布计划呢？

### ISSUE THREAD

**Issue by cokuehuang** [THUDM/ChatGLM-6B#45]
6B效果已经很惊喜了，是否有训练更大模型的计划呢？

**Comment by yaleimeng** [comment]
官网更大模型的API已经在内测了。估计不会发布更大的模型。因为即使发出来大部分人也没条件正常地跑起来。

**Comment by zx2021** [comment]
6B已经是我这张3060的极限了，所以我更寄希望于官方优化算法，提升推理速度，降低占用，还有改的不要让这个模型嘴这么严（当然这并不可能）

**Comment by yaleimeng** [comment]
虽然我也希望官方能大幅度提高推理速度，但感觉可能性很小。原因就不多说了
