### ISSUE TITLE
为什么运行bash train.sh时一直说我的参数有错？

### ISSUE THREAD

**Issue by z1968357787** [THUDM/ChatGLM-6B#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

main.py: error: the following arguments are required: --model_name_or_path, --output_dir
train.sh: line 4: --do_train: command not found
train.sh: line 5: --train_file: command not found
train.sh: line 6: --validation_file: command not found
train.sh: line 7: --prompt_column: command not found
train.sh: line 8: --response_column: command not found
train.sh: line 9: --overwrite_cache: command not found
train.sh: line 10: --model_name_or_path: command not found
train.sh: line 11: --output_dir: command not found
train.sh: line 12: --overwrite_output_dir: command not found
train.sh: line 13: --max_source_length: command not found
train.sh: line 14: --max_target_length: command not found
train.sh: line 15: --per_device_train_batch_size: command not found
train.sh: line 16: --per_device_eval_batch_size: command not found
train.sh: line 17: --gradient_accumulation_steps: command not found
train.sh: line 18: --predict_with_generate: command not found
train.sh: line 19: --max_steps: command not found
train.sh: line 20: --logging_steps: command not found
train.sh: line 21: --save_steps: command not found
train.sh: line 22: --learning_rate: command not found
train.sh: line 23: --pre_seq_len: command not found
train.sh: line 24: --quantization_bit: command not found

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
与readme一致
```

**Comment by littlerookie** [comment]
你是不是把train.sh脚本里main.py后面的\给删了

**Comment by z1968357787** [comment]
没有的，跟操作系统有关吗？


&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 晚上7:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] 为什么运行bash train.sh时一直说我的参数有错？ (Issue #450)





 
你是不是把train.sh脚本里main.py后面的\给删了

**Comment by littlerookie** [comment]
windows系统吗？要不截下脚本的图

**Comment by z1968357787** [comment]
你好，我用的是Linux操作系统服务器跑的



&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 晚上7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] 为什么运行bash train.sh时一直说我的参数有错？ (Issue #450)





 
windows系统吗？要不截下脚本的图

**Comment by littlerookie** [comment]
另一个报错也是你提的吧，你这个应该是在Windows上下载或修改的代码，然后提交到Linux系统跑的？

**Comment by z1968357787** [comment]
是的，报错都是我提的，不过代码不是在Windows上下载，我是直接在Linux服务器上git clone的
&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 晚上7:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] 为什么运行bash train.sh时一直说我的参数有错？ (Issue #450)





 
另一个报错也是你提的吧，你这个应该是在Windows上下载或修改的代码，然后提交到Linux系统跑的？

**Comment by z1968357787** [comment]
我换了分隔符之后，它又有了一个新的问题





变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/ChatGLM-6B"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUDM/ChatGLM-6B] 为什么运行bash train.sh时一直说我的参数有错？ (Issue #450)





 
另一个报错也是你提的吧，你这个应该是在Windows上下载或修改的代码，然后提交到Linux系统跑的？

**Comment by littlerookie** [comment]
截图看下吧

**Comment by z1968357787** [comment]
&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] 为什么运行bash train.sh时一直说我的参数有错？ (Issue #450)





 
截图看下吧

**Comment by fpolaris** [comment]
我也这个问题，你现在解决了吗

**Comment by nikeaddidaslining** [comment]
换行符格式由CRLF换为LF即可

**Comment by hzauliutingting** [comment]
您好，我遇到了同样的问题，请问你解决了吗

**Comment by Epiphany1536** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by Epiphany1536** [comment]
> 换行符格式由CRLF换为LF即可

确实可能是前面那位xd说的，我把.sh中的代码原封不动复制到一个新的文件中，运行新的文件就不会报错
