### ISSUE TITLE
[BUG/Help] <title>运行evalute.sh的时候报错 RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration: 	size mismatch for transformer.prefix_encoder.embedding.weight: copying a param with shape torch.Size([8, 229376]) from checkpoint, the shape in current model is torch.Size([128, 229376]). 	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![eddaf9a3e38b0d8a8be0c6bd4f5809f](https://user-images.githubusercontent.com/123447380/230601104-c1dc51e7-2d02-4892-880b-3cccc16db832.png)

### Steps To Reproduce

RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.prefix_encoder.embedding.weight: copying a param with shape torch.Size([8, 229376]) from checkpoint, the shape in current model is torch.Size([128, 229376]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
把`evaluate.sh`里的`PRE_SEQ_LEN`改成8
