### ISSUE TITLE
[BUG/Help] <title>在推理阶段报错  UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![9c40e2bf38cb763061c53ca8e7e36ae](https://user-images.githubusercontent.com/123447380/230606051-3b4ed427-38b9-4f65-92fd-08c99bfcccb8.png)

### Steps To Reproduce

UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请使用本仓库最新的代码
