### ISSUE TITLE
[Help] windows的anaconda prompt环境执行train.sh脚本报错：Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by Chalous** [THUDM/ChatGLM-6B#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

到ptuning目录下执行train.sh脚本
![image](https://user-images.githubusercontent.com/13520070/230656979-5d3c6763-32d3-4927-8e75-57db9eb2fef3.png)

### Steps To Reproduce

1. 成功执行web_demo2.py
2. 将官方微调教程放到ptuning中
3. 执行tran.sh

### Environment

```markdown
- OS:Windows 11 Anaconda prompt
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by Chalous** [comment]
解决了，windows不能直接执行这个sh脚本

**Comment by Kino521** [comment]
在windows上布置anaconda，启用conda环境，也可以在windows系统上进行微调
