### ISSUE TITLE
[BUG/Help] <title>想请问一下对模型进行微调的时候执行了train.sh和evalute.sh之后模型保存在哪里

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![a48d09b91eb3889f9d9624e5288c64c](https://user-images.githubusercontent.com/123447380/230704759-f45e8dfc-15f5-4e93-9087-7203bdc86dcd.png)

### Steps To Reproduce

微调的时候执行了train和evalute，下一步应该怎么操作

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by xioozq** [comment]
train.sh里的output_dir就是输出目录
