### ISSUE TITLE
[BUG] <title>微调训练时要用transformers==4.27.1,而推理时却要用transformers==4.26.1

### ISSUE THREAD

**Issue by jlliushi** [THUDM/ChatGLM-6B#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

微调训练时要用transformers==4.27.1的版本，
而推理时却要用transformers==4.26.1的版本，
否则出错，
求统一版本！

### Expected Behavior

求微调训练时和推理时transformers用统一版本4.27.1

### Steps To Reproduce

ModuleNotFoundError: No module named 'transformers_modules.'

(d:\py310) D:\ChatGLM-6B>pip install transformers==4.26.1 -i https://mirrors.aliyun.com/pypi/simple/
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting transformers==4.26.1
  Downloading https://mirrors.aliyun.com/pypi/packages/1e/e2/60c3f4691b16d126ee9cfe28f598b13c424b60350ab339aba81aef054b8f/transformers-4.26.1-py3-none-any.whl (6.3 MB)
     ---------------------------------------- 6.3/6.3 MB 4.3 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in d:\py310\lib\site-packages (from transformers==4.26.1) (4.65.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in d:\py310\lib\site-packages (from transformers==4.26.1) (0.13.2)
Requirement already satisfied: pyyaml>=5.1 in d:\py310\lib\site-packages (from transformers==4.26.1) (6.0)
Requirement already satisfied: numpy>=1.17 in d:\py310\lib\site-packages (from transformers==4.26.1) (1.24.2)
Requirement already satisfied: regex!=2019.12.17 in d:\py310\lib\site-packages (from transformers==4.26.1) (2022.10.31)
Requirement already satisfied: requests in d:\py310\lib\site-packages (from transformers==4.26.1) (2.28.2)
Requirement already satisfied: filelock in d:\py310\lib\site-packages (from transformers==4.26.1) (3.9.1)
Requirement already satisfied: packaging>=20.0 in d:\py310\lib\site-packages (from transformers==4.26.1) (23.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\py310\lib\site-packages (from transformers==4.26.1) (0.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\py310\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.26.1) (4.5.0)
Requirement already satisfied: colorama in d:\py310\lib\site-packages (from tqdm>=4.27->transformers==4.26.1) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\py310\lib\site-packages (from requests->transformers==4.26.1) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\py310\lib\site-packages (from requests->transformers==4.26.1) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in d:\py310\lib\site-packages (from requests->transformers==4.26.1) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\py310\lib\site-packages (from requests->transformers==4.26.1) (1.26.15)
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.27.1
    Uninstalling transformers-4.27.1:
      Successfully uninstalled transformers-4.27.1
Successfully installed transformers-4.26.1

(d:\py310) D:\ChatGLM-6B>python main.py --do_predict --validation_file AdvertiseGen/dev.json --test_file AdvertiseGen/dev.json --overwrite_cache --prompt_column content --response_column summary --model_name_or_path ./output/checkpoint-3000 --output_dir ./output/checkpoint-2000 --overwrite_output_dir --max_source_length 64 --max_target_length 64 --per_device_eval_batch_size 8 --predict_with_generate --pre_seq_len 8 --quantization_bit 8
04/08/2023 18:55:09 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
04/08/2023 18:55:09 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,

### Environment

```markdown
- OS:window10
- Python:3.10
- Transformers:4.27.1/4.26.1
- PyTorch:2.11
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.7
```

### Anything else?

无

**Comment by duzx16** [comment]
在微调和推理的时候都应该使用4.27.1版本

**Comment by chenyiwan** [comment]
不可能，绝对不可能。（曹操）

 都用4.27.1 没问题。。

**Comment by ihuchao** [comment]
理论上，更新的版本应该是向下兼容的，可以尝试都用4.27.1，或者更新的版本
