### ISSUE TITLE
[模型推理速度优化建议] <title>

### ISSUE THREAD

**Issue by wudajun7509** [THUDM/ChatGLM-6B#468]
### Is your feature request related to a problem? Please describe.

首先致敬唐老师以及我们清华可爱的孩子们，这模型真得很棒！
我在实际使用的时候发现一个可能大幅提升模型推理速度的方案。我使用rtx3060+至强4110进行推理的时候发现，GPU负荷很低（几乎为0），CPU32个虚拟核里在推理阶段似乎只有一个核是100%，其他也没有什么负荷。

### Solutions

我认为应该是tokenrizer运行的问题，于是我记录了编码与解码的时间，如下：
{'input_ids': [5, 64351, 119602, 63842, 68901, 6, 70429, 63836, 3346, 53832, 5, 13, 7, 8, 11, 149, 2872, 67077, 63891, 103752, 6, 69383, 70289, 66459, 64507, 78012, 65163, 63823, 103752, 64915, 119671, 65416, 87343, 63944, 6, 63873, 63854, 81570, 64299, 67077, 109990, 68932, 65495, 63823, 130001, 130004]}
耗时：0:00:00.000995秒
利用预处理后的数据,我们将对ERNIE 3.0-xBase模型进行微调,使其更好地适应知识问答任务。微调过程需要大量的计算资源和时间,但将极大地提高模型在特定领域的性能。
耗时：0:00:07.401323秒
一般来说推理输出700字大约90S左右，而这个70字的文本decode用了7S多，如果我们在这一块上进行优化，我估计能够有非常好的效果。

### Additional context

ChatGLM-6B已经是一个非常精致的模型了，如果我提出的建议能有所帮助的话，我将非常荣幸，也希望贡献一些微薄的力量。

**Comment by duzx16** [comment]
我测试decode只需要几毫秒。现在decode是直接使用sentencepiece，应该已经很难优化了
