### ISSUE TITLE
[BUG/Help] 支持low_cpu_mem_usage加载

### ISSUE THREAD

**Issue by digits122** [THUDM/ChatGLM-6B#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当在AutoModel.from_pretrained添加参数low_cpu_mem_usage=True之后，会报错误
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### Expected Behavior

使用low_cpu_mem_usage=True时，一般是想将模型加载到gpu，并且让此过程中最小的cpu内存消耗，以满足在小内存、大显存机器上的加载。无论是否有此特性，不应该加上之后报此错误。

### Steps To Reproduce

AutoModel.from_pretrained增加参数low_cpu_mem_usage=True

### Environment

```markdown
- OS:ubuntu22.04
- Python:3.10.6
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
你加载的是int4量化的模型吗？

**Comment by digits122** [comment]
> 你加载的是int4量化的模型吗？

对，用的是int4量化模型

**Comment by duzx16** [comment]
> > 你加载的是int4量化的模型吗？
> 
> 对，用的是int4量化模型

应该是 `accelerate` 库的问题。量化后的权重是以int8的格式保存的，对于int8的权重pytorch不能设置 `requires_grad=True`（默认值）。我们的代码里已经设置了 `requires_grad=False`，但是 `accelerate` 并没有正确地传进去。因为我没法改库里的代码所以暂时没法解决。
