### ISSUE TITLE
[BUG/Help] <title>train的时候报错DataTrainingArguments object has no attribute "history column

### ISSUE THREAD

**Issue by jingtian11** [THUDM/ChatGLM-6B#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![71c03ce156f21be8dfc527d0226a66e](https://user-images.githubusercontent.com/123447380/230724881-d72a90a8-b84b-42eb-b239-6a0378ed0f9e.png)

### Steps To Reproduce

train的时候报错

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/arguments.py#L83
应该是你没有使用最新的代码
