### ISSUE TITLE
请问能加个友情链接吗？

### ISSUE THREAD

**Issue by StarRing2022** [THUDM/ChatGLM-6B#473]
### Solutions

我们基于贵方的ChatGLM，发现一种可以使用交叉Lora融合的微调方法，可见https://github.com/StarRing2022/ChatGlm-Uni
我们希望能够被官方所接纳，感谢！

**Comment by ZanoZ** [comment]
show it please.

**Comment by StarRing2022** [comment]
Codes is shown

**Comment by duzx16** [comment]
可以提PR，要有一句简短的介绍

**Comment by StarRing2022** [comment]
> 
非常感谢，工程介绍为：基于一种lora交换融合的方法，即使用如LLAMA7B Alpaca微调的lora权值，镶嵌进ChatGLM-6B，以此提升模型的能力，并为大模型权值增强小模型效果提供了可能参考。
