### ISSUE TITLE
网页打不开

### ISSUE THREAD

**Issue by HonestyBrave** [THUDM/ChatGLM-6B#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在A100服务器上运行运行 python web_demo.py ，两个问题：

1.运行时出现：
“Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration 
with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.”

**以上内容是啥意思？**

2.接着出现：http://127.0.0.1:7860
于是我就把网址在我本地浏览器输入网址后，就显示：127.0.0.1 拒绝了我们的连接请求。
打不开网址，请问这个怎么解决？谢谢！

运行打印信息如下：
![1681016121723](https://user-images.githubusercontent.com/16200506/230755166-e6908fdb-c4b9-4808-b9e3-8702aab43b84.jpg)

### Steps To Reproduce

python web_demo.py

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10.10
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

none

**Comment by duzx16** [comment]
https://baike.baidu.com/item/127.0.0.1/4563698
应该用public URL

**Comment by Swag-Wang** [comment]
请问解决了吗，我也存在这个问题

**Comment by HonestyBrave** [comment]
> 请问解决了吗，我也存在这个问题

后来没关注，你试试1.0版本

**Comment by zx2021** [comment]
你只有在本机部署中才能使用127.0.0.1，因为127.0.0.1只是本地环回口，只能用来访问本机，是一个十分经典的梗

**Comment by Swag-Wang** [comment]
> 

您好，请问该如何处理这个问题，我在xshell上登录服务器还是访问不了
