### ISSUE TITLE
[Feature] Only Saving (and Loading) the Prompt Encoder when using P-Tuning v2

### ISSUE THREAD

**Issue by jeffchy** [THUDM/ChatGLM-6B#476]
### Is your feature request related to a problem? Please describe.

When I use p-tuning v2 code, the saved checkpoint of chatglm6b is still huge, it consumes 12+G hard disk mem compared to LORA which only needs to save checkpoints less than 20MB.
Does the checkpoint of the whole chatglm6B is saved during P-tuning v2?

### Solutions

Support Only Saving (and Loading) the Prompt Encoder when using P-Tuning v2

**Comment by duzx16** [comment]
Implemented now.
