### ISSUE TITLE
MacBookPro:intel CPU + eGPU(AMD RX6800 16G) can load model, failed when input, error:input types 'tensor<1x3x1xf16>' and 'tensor<1xf32>' are not broadcast compatible

### ISSUE THREAD

**Issue by FreeBlues** [THUDM/ChatGLM-6B#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error log:

```
(ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:13<00:00,  1.70s/it]
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：hello
loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x3x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      python cli_demo.py
(ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % /Users/ppt/miniconda/envs/ChatGLM/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

(ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % 
```

### Expected Behavior

work normally

### Steps To Reproduce

The line:7 in cli_demo.py modified to below:

```
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().to('mps')
```

### Environment

```markdown
- OS:macOS Ventura 13.2.1
- Python:3.10.10
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : no CUDA

MBP intel CPU, 32G mem,  eGPU(RX6800 16G)
```

**Comment by duzx16** [comment]
根据 https://developer.apple.com/metal/pytorch ，mps后端需要Mac computers with Apple silicon or AMD GPUs

**Comment by cat-fishing** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Error log:
> 
> ```
> (ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % python cli_demo.py
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:13<00:00,  1.70s/it]
> 欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序
> 
> 用户：hello
> loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x3x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
> LLVM ERROR: Failed to infer result type(s).
> zsh: abort      python cli_demo.py
> (ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % /Users/ppt/miniconda/envs/ChatGLM/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '
> 
> (ChatGLM) ppt@pptdeMacBook-Pro ChatGLM-6B % 
> ```
> 
> ### Expected Behavior
> work normally
> 
> ### Steps To Reproduce
> The line:7 in cli_demo.py modified to below:
> 
> ```
> model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().to('mps')
> ```
> 
> ### Environment
> ```gfm
> - OS:macOS Ventura 13.2.1
> - Python:3.10.10
> - Transformers:4.26.1
> - PyTorch:2.0.0
> - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : no CUDA
> 
> MBP intel CPU, 32G mem,  eGPU(RX6800 16G)
> ```
> 
> ### Anything else?
> _No response_

<img width="386" alt="image" src="https://github.com/THUDM/ChatGLM-6B/assets/42529011/fd49b357-ff24-4ada-a160-7a0d99a70344">
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
更换为
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()  回复速度可以
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float().to(''mps)回复速度不能忍

**Comment by yetrun** [comment]
> 我也刚遇到，其实文档里面有说要用pytorch nightly版本，不能用默认的2.0.0版本 pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

现在默认不是安装 2.0.0 版本了，安装 2.2-dev2023xxxx 版本
