### ISSUE TITLE
/mingw32/bin/ld.exe: cannot find -lpthread

### ISSUE THREAD

**Issue by zqq-nuli** [THUDM/ChatGLM-6B#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当我使用 chatglm-6b-int4-qe的模型时 .quantize(4).half().cuda() 出现如下报错 似乎是.cuda()函数出现异常 当我不写  .quantize(4) 时 结果是一样的  请问有人遇到过类似的问题嘛 可以麻烦告诉一下解决方案吗？ 我将模型存放的位置为当前目录下的 model位置 目录为 G:\ChatGLM-6B-main>

/mingw32/bin/ld.exe: cannot find -lpthread

Failed to load cpm_kernels: [WinError 267] 目录名称无效。 ："路径+xxx.ps1"

c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
Compile failed, using default cpu kernel code.

collect2.exe: error: ld returned 1 exit status
Compile failed, using default cpu kernel code.

Cannot load cpu kernel, don't use quantized model on cpu.
Cannot load cuda kernel, quantization failed.

### Steps To Reproduce

python .\api.py

### Environment

```markdown
python 3.11
windows 10 64x
cpu 15-10代
gpu rtx2060
```

**Comment by songxxzp** [comment]
链接时没有找到pthread库。另外使用了32位gcc。
请确保使用64位gcc编译，windows建议使用TDM-GCC（安装时确认pthread和openmp勾选）：https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release
正确安装后应该可在cpu上运行。
cuda的错误看起来像cpm_kernels没有安装好，请再检查一下。
