### ISSUE TITLE
[BUG/Help] <bash train.sh 运行后找不到checkpoint文件>

### ISSUE THREAD

**Issue by BLAIR-wy** [THUDM/ChatGLM-6B#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

想问下 checkpoint文件怎么没有呢？ 
没有对owner的代码做修改后直接运行

### Steps To Reproduce

train.sh的参数都没改，只修改了数据集的路径。训练后 在output中找不到checkpoint

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请不要针对同一个问题重复开issue，可以编辑之前的issue
