### ISSUE TITLE
[BUG/Help] 自己数据集训练报错

### ISSUE THREAD

**Issue by janglichao** [THUDM/ChatGLM-6B#488]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

我用自己的数据集作训练，json文件格式
{"instruction":"这是一个问题"，
"input":"",
"output":" 这是问题答案 ",
"id":1}
**报错：**
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

===================================
顺便再问一个问题：train.sh里面的--model_name_or_path 我是不是不能修改，我改成本地模型地址会报错找不到路径好像加了huggingface的路径。

### Steps To Reproduce

1.修改train.sh文件修改json文件路径
2.运行train.sh

### Environment

```markdown
- OS: ubuntu22
- Python:
- Transformers:
- PyTorch:
- CUDA Support:true :
```

**Comment by janglichao** [comment]
补充一些报错信息：
Traceback (most recent call last):
  File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 413, in <module>
    main()
  File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 333, in main
    trainer = Seq2SeqTrainer(
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer.py", line 519, in __init__
    self.callback_handler = CallbackHandler(
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 296, in __init__
    self.add_callback(cb)
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 313, in add_callback
    cb = callback() if isinstance(callback, type) else callback
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/integrations.py", line 662, in __init__
    import wandb
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 5, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 45, in <module>
    from ..lib import retry
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by duzx16** [comment]
> 补充一些报错信息： Traceback (most recent call last): File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 413, in main() File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 333, in main trainer = Seq2SeqTrainer( File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer.py", line 519, in **init** self.callback_handler = CallbackHandler( File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 296, in **init** self.add_callback(cb) File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 313, in add_callback cb = callback() if isinstance(callback, type) else callback File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/integrations.py", line 662, in **init** import wandb File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/**init**.py", line 26, in from wandb import sdk as wandb_sdk File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/**init**.py", line 5, in from .wandb_artifacts import Artifact # noqa: F401 File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in from wandb.apis import InternalApi, PublicApi File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/**init**.py", line 42, in from .internal import Api as InternalApi # noqa File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/internal.py", line 1, in from wandb.sdk.internal.internal_api import Api as InternalApi File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 45, in from ..lib import retry File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 17, in from .mailbox import ContextCancelledError File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 10, in from wandb.proto import wandb_internal_pb2 as pb File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in from wandb.proto.v3.wandb_internal_pb2 import * File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2 File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in from wandb.proto.v3.wandb_base_pb2 import * File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo'] AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

这个应该是依赖安装的问题吧。你可以运行`python -c "import wandb"`试试

**Comment by janglichao** [comment]
> > 补充一些报错信息： Traceback (most recent call last): File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 413, in main() File "/home/kidd/projects/llms/chatGLM-6B/ChatGLM-6B/ptuning/main.py", line 333, in main trainer = Seq2SeqTrainer( File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer.py", line 519, in **init** self.callback_handler = CallbackHandler( File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 296, in **init** self.add_callback(cb) File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 313, in add_callback cb = callback() if isinstance(callback, type) else callback File "/home/kidd/anaconda3/lib/python3.10/site-packages/transformers/integrations.py", line 662, in **init** import wandb File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/**init**.py", line 26, in from wandb import sdk as wandb_sdk File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/**init**.py", line 5, in from .wandb_artifacts import Artifact # noqa: F401 File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in from wandb.apis import InternalApi, PublicApi File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/**init**.py", line 42, in from .internal import Api as InternalApi # noqa File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/apis/internal.py", line 1, in from wandb.sdk.internal.internal_api import Api as InternalApi File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 45, in from ..lib import retry File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 17, in from .mailbox import ContextCancelledError File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 10, in from wandb.proto import wandb_internal_pb2 as pb File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in from wandb.proto.v3.wandb_internal_pb2 import * File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2 File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in from wandb.proto.v3.wandb_base_pb2 import * File "/home/kidd/anaconda3/lib/python3.10/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo'] AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
> 
> 这个应该是依赖安装的问题吧。你可以运行`python -c "import wandb"`试试
搞定了，就是wandb的问题，谢谢

**Comment by caixiaomao** [comment]
安装了 wandb 还是会报错，请问您是如何解决的？
