### ISSUE TITLE
[BUG/Help] 关于商业化的问题

### ISSUE THREAD

**Issue by xuguozhi** [THUDM/ChatGLM-6B#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

根据自身的私有数据进行微调，是否可以将模型用于商业化？如果可以，那么该如何授权？

### Steps To Reproduce

happy finetuning

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
根据私有数据对模型进行微调仍然属于使用了模型，因此需要遵守model license不能商用。要获得商业化授权请联系yiwen.xu@zhipuai.cn（Iven徐一文）
