### ISSUE TITLE
[BUG/Help] 求助大佬，预测的结果混乱

### ISSUE THREAD

**Issue by ct4131** [THUDM/ChatGLM-6B#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我使用chatGLM-6b-int4模型在cpu上进行对话预测，但预测的结果混乱，是否与我的环境有关，还是我其他地方弄错了？
`from transformers import AutoTokenizer,AutoModel

tokenizer = AutoTokenizer.from_pretrained(".\model",trust_remote_code=True)
model = (
        AutoModel.from_pretrained(
            ".\model",
            trust_remote_code=True, ignore_mismatched_sizes=True, from_tf=False).float()
        #.half()
        #.cuda()
    )
model = model.quantize(bits=4, kernel_file="./model/quantization_kernels.so")
#model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[], max_length=50, top_p=0.9,
                                               temperature=0.1)
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)`
上面这段代码返回的结果如图：
![image](https://user-images.githubusercontent.com/11604587/230879886-5b00072e-b78b-4935-933e-133131762201.png)

### Steps To Reproduce

无

### Environment

```markdown
- OS:windows
- Python:3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
是否是你的 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin` 这两个文件没有更新？最新的 `sha256` 值应该是 `be79e2b22d99b3d76184f83f266cc764275220b66da6c4d0217176c8f8f6af27` 和 `607d08dd09074840c5f4603d4959a5c6789790955181c7253a2c14d38c1801d2`

**Comment by ct4131** [comment]
> 是否是你的 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin` 这两个文件没有更新？最新的 `sha256` 值应该是 `be79e2b22d99b3d76184f83f266cc764275220b66da6c4d0217176c8f8f6af27` 和 `607d08dd09074840c5f4603d4959a5c6789790955181c7253a2c14d38c1801d2`

hi，我是用的是int4 量化后的模型

**Comment by duzx16** [comment]
> > 是否是你的 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin` 这两个文件没有更新？最新的 `sha256` 值应该是 `be79e2b22d99b3d76184f83f266cc764275220b66da6c4d0217176c8f8f6af27` 和 `607d08dd09074840c5f4603d4959a5c6789790955181c7253a2c14d38c1801d2`
> 
> hi，我是用的是int4 量化后的模型

那应该是 `35828b49cf23cbae4c27788d4b04fc68c79a276300e09f14d72a49b0b738b4a9`

**Comment by ct4131** [comment]
> > > 是否是你的 `pytorch_model-00001-of-00008.bin` 和 `pytorch_model-00008-of-00008.bin` 这两个文件没有更新？最新的 `sha256` 值应该是 `be79e2b22d99b3d76184f83f266cc764275220b66da6c4d0217176c8f8f6af27` 和 `607d08dd09074840c5f4603d4959a5c6789790955181c7253a2c14d38c1801d2`
> > 
> > 
> > hi，我是用的是int4 量化后的模型
> 
> 那应该是 `35828b49cf23cbae4c27788d4b04fc68c79a276300e09f14d72a49b0b738b4a9`

![image](https://user-images.githubusercontent.com/11604587/231105955-39095716-b2fe-44f4-ab57-3a3c94913e28.png)
非常感谢，没有注意到更新的模型文件
