### ISSUE TITLE
[BUG/Help] <title>能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练

### ISSUE THREAD

**Issue by zhangzai666** [THUDM/ChatGLM-6B#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练

### Expected Behavior

能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练

### Steps To Reproduce

能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练
```

### Anything else?

能否用glm_10B_chinese模型的预训练方式来对chatglm进行预训练

**Comment by duzx16** [comment]
代码无法直接兼容。如果你自己写的话是可以的
