### ISSUE TITLE
[BUG/Help] <多轮对话效果提升>

### ISSUE THREAD

**Issue by LebronJames0423** [THUDM/ChatGLM-6B#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/33833521/230909494-95ce71f1-058c-4b13-a99a-d6b49defd31e.png)
请问下，上图中说的意思是，即使我目前有多轮对话数据集的话，p-tuning微调还是只支持对第一轮的对话会有微调，第二轮及以后的对话效果还是无法通过微调得到提升吗？谢谢

### Steps To Reproduce

no

### Environment

```markdown
- OS:linux
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
用对话数据集的话可以通过微调提升第二轮及以后的对话效果

**Comment by a394867798as** [comment]
> 用对话数据集的话可以通过微调提升第二轮及以后的对话效果

对话数据集的验证数据集格式是什么样子的？
validation_file
