### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half

### ISSUE THREAD

**Issue by phellonchen** [THUDM/ChatGLM-6B#5]

**Comment by duzx16** [comment]
请问你是在GPU还是CPU上运行的？PyTorch的LayerNorm实现不支持CPU上的fp16计算，请把`.half()`换成`.float()`。

Are you using the model on GPU or CPU? The PyTorch's implementation of LayerNorm doesn't support fp16 computation on CPU. Please replace `.half()` with `.float()`

**Comment by phellonchen** [comment]
Thanks. And how to finetune ChatGLM for our own datasets? Could you give some examples for the forward function?

**Comment by duzx16** [comment]
We will support that in the future. Currently, since the model implementation is already open on [HuggingFace Hub](https://huggingface.co/THUDM/chatglm-6b)，you can implement training with existing libraries like [HF Trainer](https://huggingface.co/docs/transformers/main_classes/trainer).

**Comment by phellonchen** [comment]
Is it similar to https://github.com/THUDM/GLM?
'''
# Training
inputs = tokenizer(
    ["Tsinghua University is located in [MASK].", "One minus one equals zero, is it correct? Answer: [MASK]"],
    return_tensors="pt", padding=True)
inputs = tokenizer.build_inputs_for_generation(inputs, targets=["Beijing", "No"], max_gen_length=8, padding=False)
inputs = inputs.to('cuda')
outputs = model(**inputs)
loss = outputs.loss
logits = outputs.logits
'''

**Comment by phellonchen** [comment]
Thanks. I have found it.

**Comment by huangjie-nlp** [comment]
我在GPU上run 也遇到了这个问题，有什么解决方案吗

**Comment by Data2Me** [comment]
> 我在GPU上run 也遇到了这个问题，有什么解决方案吗

请问你解决了吗

**Comment by NostalgiaJohn** [comment]
> 我在GPU上run 也遇到了这个问题，有什么解决方案吗

> > 我在GPU上run 也遇到了这个问题，有什么解决方案吗
> 
> 请问你解决了吗

已解决，请修改web_demo.py中的这条语句：
Now sovled, please rewrite the following sentence in web_demo.py:
`model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()`

如，使用INT8量化模型时语句为：
For instance, the sentence shall be as follow if you attempt to use INT8 Quantitative Module:
`model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).quantize(8).half().cuda()`

Hope it helps :-)
