### ISSUE TITLE
[BUG/Help]请教下利用lora+belle的数据微调glm会出现重复的回答和一些无关的qa对。

### ISSUE THREAD

**Issue by chouife** [THUDM/ChatGLM-6B#502]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

你好，我在尝试利用lora+belle的指令数据集微调glm，跑了三个epoch。最后发现回答会出现重复的语句和一些无关的QA对以及回复停不下来的问题，后面看了很多仓库的都出现了这个问题，有人提到了是model和tokenizer中的eos_token_id不一致导致的，我更新了昨天最新的代码，发现两者的eos_token_id还是不一致。请教下会是这个原因导致的吗？

### Steps To Reproduce

你好，我在尝试利用lora+belle的指令数据集微调glm，跑了三个epoch。最后发现回答会出现重复的语句和一些无关的QA对以及回复停不下来的问题，后面看了很多仓库的都出现了这个问题，有人提到了是model和tokenizer中的eos_token_id不一致导致的，我更新了昨天最新的代码，发现两者的eos_token_id还是不一致。请教下会是这个原因导致的吗？

### Environment

```markdown
- OS:ubuntu20.04
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.4
```

**Comment by duzx16** [comment]
你用的是哪个仓库实现的lora？

**Comment by chouife** [comment]
你好，使用的是这个仓库的代码：https://github.com/mymusise/ChatGLM-Tuning

**Comment by chouife** [comment]
![示例](https://user-images.githubusercontent.com/82275696/231044928-bfb2f086-e437-435a-af51-8b140b3b8e9e.png)
这个是示例

**Comment by forgot-glory** [comment]
> ![示例](https://user-images.githubusercontent.com/82275696/231044928-bfb2f086-e437-435a-af51-8b140b3b8e9e.png) 这个是示例

你好，想问一下您是如何将训练出来的lora文件夹挂载到模型中的？
