### ISSUE TITLE
[BUG/Help] <title> Internal: [MASK] is already defined.

### ISSUE THREAD

**Issue by phellonchen** [THUDM/ChatGLM-6B#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Internal: [MASK] is already defined.

### Expected Behavior

no

### Steps To Reproduce

no

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.26.1
- PyTorch:PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by threeRepresents** [comment]
我也遇到了，把chatglm-6里面的py文件重新替换成huggingface里面最新的就好了

**Comment by phellonchen** [comment]
我想使用原来的文件，基于chatglm做了二次训练，但只保存了有梯度的部分参数，还需要加载原来的模型。使用本地的模型会报错google.protobuf.message.DecodeError: Error parsing message

**Comment by MaiziXiao** [comment]
请问有解决嘛？google.protobuf.message.DecodeError: Error parsing message 我也是这个error

> 我想使用原来的文件，基于chatglm做了二次训练，但只保存了有梯度的部分参数，还需要加载原来的模型。使用本地的模型会报错google.protobuf.message.DecodeError: Error parsing message
