### ISSUE TITLE
[BUG/Help] <title>请问有人将ChatGLM与llama_index结合吗

### ISSUE THREAD

**Issue by rjc7011855** [THUDM/ChatGLM-6B#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

希望做一个中文文本搜索库，但是不知道怎么将ChatGLM与llama_index结合，有人做过吗，感谢！

### Steps To Reproduce

OS: Ubuntu 16.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by imClumsyPanda** [comment]
实测llama-index自定义模型过程相对麻烦，而且基本都是对langchain中的类进行二次封装，所以目前有基于langchain和chatglm的本地知识问答应用，可以参考项目 https://github.com/imClumsyPanda/langchain-ChatGLM
