### ISSUE TITLE
[Help]想了解一下目前模型训练所需要的工作量

### ISSUE THREAD

**Issue by ripingit** [THUDM/ChatGLM-6B#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好,因为想自己尝试一下使用咱们的方案训练一个垂直领域的模型,想了解下6B模型训练所需要的硬件资源和数据集情况,比如数据集大小和所需要的算力以及训练一次需要的大概时间,如不方便给出具体数据,给一个范围即可,万份感谢

### Steps To Reproduce

1.数据需求
2.硬件需求
3.训练时常

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by kamimachi** [comment]
同求
