### ISSUE TITLE
[BUG/Help] <title>如何让代码每次运行不刷新

### ISSUE THREAD

**Issue by Jessicamona** [THUDM/ChatGLM-6B#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 f"Loading {pretrained_model_name_or_path} requires you to execute the tokenizer file in that"
ValueError: Loading model_chatglm requires you to execute the tokenizer file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### Expected Behavior

每次加载模型代码不重新刷新，想要自己修改一下推理代码

### Steps To Reproduce

1、在用profile计算模型的计算量的时候报错，发现不能修改/.cache/huggingface/modules/transformers_modules/model_chatglm/modeling_chatglm.py，每次运行会自动刷新这个代码

### Environment

```markdown
- OS: Ubuntu 20.04
- Python:3.7
- Transformers:4.27.1
- PyTorch:1.13.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())")
```

### Anything else?

nothing

**Comment by ErvinSwift** [comment]
为什么model.chat跳转到  .cache\huggingface\modules\transformers_modulesodules\modeling_chatglm.py 执行，而不是跳转到我本地下载的模型 modeling_chatglm.py
