### ISSUE TITLE
请提供一下Linux下运行CPU版本的详细操作步骤 

### ISSUE THREAD

**Issue by fishfree** [THUDM/ChatGLM-6B#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`此外，如果需要在 cpu 上运行量化后的模型，还需要安装 gcc 与 openmp。`

README里有这句说明，还请麻烦提供一下详细的Linux上的操作步骤，多谢！

### Steps To Reproduce

如上

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10
```

**Comment by duzx16** [comment]
不同发行版的安装方式不一样。直接搜索可以找到很多教程。

**Comment by fishfree** [comment]
谢谢各位！
