### ISSUE TITLE
[BUG/Help] 中断训练后，steps保存了2000,重启训练没续而是直接从头开始

### ISSUE THREAD

**Issue by janglichao** [THUDM/ChatGLM-6B#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.默认1000个steps保存一次checkpoint，我在2000个steps的时候停止了训练，重启之后好像每从2000开始，而是又重新开始了

2.如果把quantization_bit 4 这个默认值去掉是不是就能用fp16跑了？

### Steps To Reproduce

1.修改train.sh
2.运行sh脚本

### Environment

```markdown
- OS:ubuntu22
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by littlestone0806** [comment]
> 已解决，打扰了，不好意思

请问如何实现的接着训练，而不是从头开始

**Comment by zhouao0314** [comment]
> 已解决，打扰了，不好意思

请问如何解决
