### ISSUE TITLE
'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by HaoRan98** [THUDM/ChatGLM-6B#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 File "web_demo.py", line 68, in predict
    for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
  File "/home/alphis/anaconda3/envs/chatglm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### Steps To Reproduce

输入文字提交之后报错，程序退出

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.7
- Transformers:4.27.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true  11.4
```

**Comment by duzx16** [comment]
应该是你用的 `modeling_chatglm.py` 文件太旧了

**Comment by jasonbomeng** [comment]
麻烦问一下哪里能找到最新的modeling_chatglm.py？

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm-6b
