### ISSUE TITLE
[BUG/Help] cannot import name 'skip_init' from 'torch.nn.utils'

### ISSUE THREAD

**Issue by JasonChenJC** [THUDM/ChatGLM-6B#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/19702981/231095861-50569f7f-7b8c-4252-a8ee-985976965b49.png)
torch=2.0.0

### Steps To Reproduce

run "cli_demo.py " get import error:cannot import name 'skip_init' from 'torch.nn.utils' (/home/pai/lib/python3.9/site-packages/torch/nn/utils/__init__.py)

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.9.15
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

no

**Comment by duzx16** [comment]
`skip_init` does exist in PyTorch 2.0 (https://pytorch.org/docs/stable/generated/torch.nn.utils.skip_init.html). Are you certain of the PyTorch version you use?

**Comment by unmaned-air** [comment]
Have you solved this problem？

**Comment by unmaned-air** [comment]
> `skip_init` does exist in PyTorch 2.0 (https://pytorch.org/docs/stable/generated/torch.nn.utils.skip_init.html). Are you certain of the PyTorch version you use?

必须要用pytorch2.0版本吗

**Comment by unmaned-air** [comment]
> @unmaned-air PyTorch 1.10 works fine for me!

Thank U!!!! I changed my pytorch version, and now it runs well!!!!

**Comment by jokerlj92** [comment]
> > @unmaned-air PyTorch 1.10 works fine for me!
> 
> Thank U!!!! I changed my pytorch version, and now it runs well!!!!

所以这个需要2.0?  但是pytorch version不是要和cuda一致吗

**Comment by hepingguan** [comment]
pytrch 1.5 版本出现cannot import name 'skip_init' from 'torch.nn.utils

**Comment by frankghe1977** [comment]
1.5.1+cu92
True
不能运行。

**Comment by jokerlj92** [comment]
cuda11.8+pytorch2.0+python3.9  this can run.

**Comment by aleimu** [comment]
https://github.com/THUDM/ChatGLM-6B/issues/629 至今还未有解决低版本的方案

**Comment by aleimu** [comment]
我遇到了这个问题 https://github.com/pytorch/pytorch/issues/67680 ,降低torch==1.8.1后有遇到了本页的问题,真实一波三折

**Comment by unmaned-air** [comment]
其实requirements.txt已经要求了torch的版本
&nbsp;


concentrate
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月10日(星期三) 上午10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] [BUG/Help] cannot import name &#39;skip_init&#39; from &#39;torch.nn.utils&#39; (Issue #517)





 
我遇到了这个问题 pytorch/pytorch#67680 ,降低torch==1.8.1后有遇到了本页的问题,真实一波三折

**Comment by xulunfan** [comment]
> > `skip_init` does exist in PyTorch 2.0 (https://pytorch.org/docs/stable/generated/torch.nn.utils.skip_init.html). Are you certain of the PyTorch version you use?
> 
> 必须要用pytorch2.0版本吗

pip install torch==2.0.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org 亲测可行

**Comment by yyegithub** [comment]
1.13就可以，不用非得2.0

**Comment by nongqiqin** [comment]
直接打补丁

`import sys
import importlib

import inspect
import torch


def skip_init(module_cls, *args, **kwargs):
    r"""
    Given a module class object and args / kwargs, instantiates the module without initializing
    parameters / buffers.  This can be useful if initialization is slow or if custom initialization will
    be performed, making the default initialization unnecessary. There are some caveats to this, due to
    the way this function is implemented:

    1. The module must accept a `device` arg in its constructor that is passed to any parameters
    or buffers created during construction.

    2. The module must not perform any computation on parameters in its constructor except
    initialization (i.e. functions from :mod:`torch.nn.init`).

    If these conditions are satisfied, the module can be instantiated with parameter / buffer values
    uninitialized, as if having been created using :func:`torch.empty`.

    Args:
        module_cls: Class object; should be a subclass of :class:`torch.nn.Module`
        args: args to pass to the module's constructor
        kwargs: kwargs to pass to the module's constructor

    Returns:
        Instantiated module with uninitialized parameters / buffers

    Example::

        >>> # xdoctest: +IGNORE_WANT("non-deterministic")
        >>> import torch
        >>> m = torch.nn.utils.skip_init(torch.nn.Linear, 5, 1)
        >>> m.weight
        Parameter containing:
        tensor([[0.0000e+00, 1.5846e+29, 7.8307e+00, 2.5250e-29, 1.1210e-44]],
               requires_grad=True)
        >>> m2 = torch.nn.utils.skip_init(torch.nn.Linear, in_features=6, out_features=1)
        >>> m2.weight
        Parameter containing:
        tensor([[-1.4677e+24,  4.5915e-41,  1.4013e-45,  0.0000e+00, -1.4677e+24,
                  4.5915e-41]], requires_grad=True)

    """
    if not issubclass(module_cls, torch.nn.Module):
        raise RuntimeError('Expected a Module; got {}'.format(module_cls))
    if 'device' not in inspect.signature(module_cls).parameters:
        raise RuntimeError('Module must support a \'device\' arg to skip initialization')

    final_device = kwargs.pop('device', 'cpu')
    kwargs['device'] = 'meta'
    return module_cls(*args, **kwargs).to_empty(device=final_device)



sys.modules['torch.nn.utils.skip_init'] = skip_init

`
去找到这段代码，然后动态加上去
