### ISSUE TITLE
[BUG/Help] <请问做了广告文案的P-tuning后，对其他意图的响应都乱了，这个问题怎么解决？>

### ISSUE THREAD

**Issue by chk4991** [THUDM/ChatGLM-6B#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

。

### Steps To Reproduce

。

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by yangliuIOC** [comment]
暂时是未解之谜

**Comment by chenyiwan** [comment]
太玄幻了，我用lora 微调后也是这个样子。

**Comment by xingchensong** [comment]
似乎和这里（ https://github.com/THUDM/ChatGLM-6B/issues/413）对lora的实践结论是矛盾的？

**Comment by zhangch9** [comment]
Duplicate of [#403](https://github.com/THUDM/ChatGLM-6B/issues/403)
