### ISSUE TITLE
[BUG/Help] 关于是否使用了所有数据进行了finetune

### ISSUE THREAD

**Issue by AlexanderXuan** [THUDM/ChatGLM-6B#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在进行finetune时，我注意到batch size默认为1，最大训练步数max steps设置为3000，但是训练集中的数据有11w+条，所以是否只用了其中很少一部分进行训练，有许多数据并没有参与训练？

### Steps To Reproduce

--per_device_train_batch_size 1 \\
--per_device_eval_batch_size 1 \\
--max_steps 3000 \\

### Environment

```markdown
- OS: 
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
可以手动设置更长的步数
