### ISSUE TITLE
[Help] 有关多轮对话的疑问

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [THUDM/ChatGLM-6B#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用多轮对话的样例进行了测试，发现几次对话后就不能按照预期回复了，构造的训练数据如下：
```json
[
  {
      "prompt": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线",
      "response": "用电脑能读数据流吗？水温多少",
      "history": []
  },
  {
      "prompt": "95",
      "response": "上下水管温差怎么样啊？空气是不是都排干净了呢？",
      "history": [
          [
              "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线",
              "用电脑能读数据流吗？水温多少"
          ]
      ]
  },
  {
      "prompt": "是的。上下水管都好的",
      "response": "那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！",
      "history": [
          [
              "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线",
              "用电脑能读数据流吗？水温多少"
          ],
          [
              "95",
              "上下水管温差怎么样啊？空气是不是都排干净了呢？"
          ]
      ]
  }
]
```
测试发现，依次使用
- 长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线
- 95
- 是的。上下水管都好的

进行对话是没有问题的，能够得到对应的回复，但是后面继续从第一个问题来回问的时候就不是对应的预期的回复了，意思可能完全不同，是不是上下文对后续的提问产生了影响？还是训练的力度不够？或者构造数据的方式有问题？还是介绍里说的，还不支持多轮对话微调？以后会更新支持吗？还是下一个更大模型才会支持？

我还有个疑问，#413 说到ptuning微调之后就只支持当前任务了，这种同样是对话的任务微调之后之前的对话能力是否也会变差？如果想保留原有的对话能力并增加现有的问题处理对话是不是使用lora更适合？

### Steps To Reproduce

无

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:2.10
- Transformers:4.27.1
- PyTorch:1.12
- CUDA Support : True
```

**Comment by duzx16** [comment]
已经支持多轮微调了。`后面继续从第一个问题来回问`，这个时候你的history不是空的，跟训练数据不一样，所以回复当然不会完全一致。

**Comment by cristianohello** [comment]
@duzx16 
想保留原有的对话能力并增加现有的问题处理对话哪种更适合呢？lora还是ptuning？？？


我还有个疑问，https://github.com/THUDM/ChatGLM-6B/issues/413 说到ptuning微调之后就只支持当前任务了，这种同样是对话的任务微调之后之前的对话能力是否也会变差？如果想保留原有的对话能力并增加现有的问题处理对话是不是使用lora更适合？
