### ISSUE TITLE
[BUG/Help] <title>微调后的模型部署仅修改模型路径显示参数未初始化

### ISSUE THREAD

**Issue by 0LEL0** [THUDM/ChatGLM-6B#536]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

我按照Ad的微调示例微调后，在cli_demo.py中填入了微调模型保存地址，但根据README的描述微调时保存的仅有PrefixEncoder部分，不是完整模型，所以在部署的时候显示模型未初始化以及长时间计算但回复为空。

### Expected Behavior

我想知道如何在微调后使用cli_demo部署时同时导入原始模型和微调后的部分。

### Steps To Reproduce

1.bash train.sh
2.修改模型地址为./ptuning/outpupt/adgen-chatglm-6b-pt-128-1e-4/checkpoint-400（两处）
3.python cli_demo.py

### Environment

```markdown
- OS:Ubuntu 22.04
- Python:3.8
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
Duplicate of #532

**Comment by 0LEL0** [comment]
哦，之前看了，但是我的没有爆显存就感觉可能不太一样😂核对了一下有些地方没改到，现在可以了
