### ISSUE TITLE
生成的 id 带有0，导致无法解码

### ISSUE THREAD

**Issue by Henryflee** [THUDM/ChatGLM-6B#55]
outputs = [0,0]
tokenizer.decode(outputs) 解码报错如下：
*** IndexError: Out of range: piece id is out of range.

**Comment by duzx16** [comment]
0 is not a valid token id for the tokenizer and the model shouldn't predict 0. If you did encounter the problem with our demo, please open a new issue with the "Bug/Help" issue form to provide more information.
