### ISSUE TITLE
[BUG/Help] <微调的时候会把labels放入inputs中>

### ISSUE THREAD

**Issue by Rorschaaaach** [THUDM/ChatGLM-6B#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

似乎微调的时候会把labels放入inputs中
![微信图片_20230412173322](https://user-images.githubusercontent.com/37372729/231417494-e008d1df-b333-48ff-9614-b668f74f37dc.png)
我查看了代码ChatGLM-6B-main/ptuning/main.py，代码里也是这么做的
![26](https://user-images.githubusercontent.com/37372729/231417828-6da0b021-6c68-4016-a7f5-08c37724269a.png)

### Steps To Reproduce

sh train.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
That is expected. You can read papers about autoregressive generation to understand.
