### ISSUE TITLE
Help--P-Tuning V2相关问题-前面加参数的相关代码在哪？

### ISSUE THREAD

**Issue by chenyangjun45** [THUDM/ChatGLM-6B#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我看P-Tuning V2的源码中，是在模型每一层前面加可学习的参数，是在要微调的model上改的，在这个工程里没看到相关代码，有大佬知道是哪部分代码做了这个操作吗？

### Steps To Reproduce

无

### Environment

```markdown
无
```

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py
