### ISSUE TITLE
[Feature] <ptuning微调时 cpu单核占用100%，能否优化>

### ISSUE THREAD

**Issue by zhangxueren9** [THUDM/ChatGLM-6B#554]
### Is your feature request related to a problem? Please describe.

ptuning训练时，cpu占用一直是100%，是否会影响显卡性能，能否优化一下？或者分析一下原因。

### Solutions

希望官方能给个原因

**Comment by duzx16** [comment]
微调本来就是用GPU计算的，CPU大部分时间都是在等待GPU运算

**Comment by zhangxueren9** [comment]
> 微调本来就是用GPU计算的，CPU大部分时间都是在等待GPU运算

可是一直用的是单核  一般是哪个步骤的问题
我推测是python处理的步骤遇到了瓶颈   能够帮忙定位一下 我可以自己解决一下
