### ISSUE TITLE
[BUG/Help] ptuning用half().to('mps')报错 用在chat对话中没问题

### ISSUE THREAD

**Issue by sdhou** [THUDM/ChatGLM-6B#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好 我在mac上用model.half().to('mps')跑ptuning报错：
RuntimeError: "bernoulli_scalar_cpu_" not implemented for 'Half'

改成model.float().to('mps')跑 不会报这错但很慢 不会用到gpu

在跑问答中用model.half().to('mps') 就没问题 也能用到gpu 所以很费解 特此请教 谢谢大家 详细报错和运行环境如下：

mac book pro m1 os 13.3 (22E252)

执行 bash ptuning/train.sh  报上面的错误
ptuning/main.py中已修改
        model = model.half().to('mps')

如果改成         model = model.float().to('mps') 就没问题 但用不上gpu

╰─$ bash train.sh
04/12/2023 18:12:13 - WARNING - __main__ - Process rank: -1, device: cpu, n_gpu: 0distributed training: False, 16-bits training: False
04/12/2023 18:12:13 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=0,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output/adgen-chatglm-6b-pt-128-2e-2/runs/Apr12_18-12-13_sdhoudeMacBook-Pro.local,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/adgen-chatglm-6b-pt-128-2e-2,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=output/adgen-chatglm-6b-pt-128-2e-2,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
04/12/2023 18:12:14 - WARNING - datasets.builder - Found cached dataset json (/Users/sdhou/.cache/huggingface/datasets/json/default-e1b3b1125f416fa2/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 508.77it/s]
[INFO|configuration_utils.py:666] 2023-04-12 18:12:14,782 >> loading configuration file ../../chatglm/config.json
[WARNING|configuration_auto.py:905] 2023-04-12 18:12:14,782 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:666] 2023-04-12 18:12:14,798 >> loading configuration file ../../chatglm/config.json
[INFO|configuration_utils.py:720] 2023-04-12 18:12:14,799 >> Model config ChatGLMConfig {
  "_name_or_path": "../../chatglm",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.27.1",
  "use_cache": true,
  "vocab_size": 130528
}

[WARNING|tokenization_auto.py:652] 2023-04-12 18:12:14,799 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1800] 2023-04-12 18:12:14,816 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1800] 2023-04-12 18:12:14,816 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-04-12 18:12:14,816 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-04-12 18:12:14,816 >> loading file tokenizer_config.json
[WARNING|auto_factory.py:456] 2023-04-12 18:12:14,930 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|modeling_utils.py:2400] 2023-04-12 18:12:14,961 >> loading weights file ../../chatglm/pytorch_model.bin.index.json
[INFO|configuration_utils.py:575] 2023-04-12 18:12:14,962 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.27.1"
}

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.40it/s]
[INFO|modeling_utils.py:3032] 2023-04-12 18:12:18,619 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3034] 2023-04-12 18:12:18,619 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../../chatglm and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2690] 2023-04-12 18:12:18,633 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
input_ids [5, 65421, 61, 67329, 32, 98339, 61, 72043, 32, 65347, 61, 70872, 32, 69768, 61, 68944, 32, 67329, 64103, 61, 96914, 130001, 130004, 5, 87052, 96914, 81471, 64562, 65759, 64493, 64988, 6, 65840, 65388, 74531, 63825, 75786, 64009, 63823, 65626, 63882, 64619, 65388, 6, 64480, 65604, 85646, 110945, 10, 64089, 65966, 87052, 67329, 65544, 6, 71964, 70533, 64417, 63862, 89978, 63991, 63823, 77284, 88473, 64219, 63848, 112012, 6, 71231, 65099, 71252, 66800, 85768, 64566, 64338, 100323, 75469, 63823, 117317, 64218, 64257, 64051, 74197, 6, 63893, 130005, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
inputs 类型#裤*版型#宽松*风格#性感*图案#线条*裤型#阔腿裤 宽松的阔腿裤这两年真的吸粉不少,明星时尚达人的心头爱。毕竟好穿时尚,谁都能穿出腿长2米的效果宽松的裤腿,当然是 遮肉小能手啊。上身随性自然不拘束,面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点,还
label_ids [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 130004, 5, 87052, 96914, 81471, 64562, 65759, 64493, 64988, 6, 65840, 65388, 74531, 63825, 75786, 64009, 63823, 65626, 63882, 64619, 65388, 6, 64480, 65604, 85646, 110945, 10, 64089, 65966, 87052, 67329, 65544, 6, 71964, 70533, 64417, 63862, 89978, 63991, 63823, 77284, 88473, 64219, 63848, 112012, 6, 71231, 65099, 71252, 66800, 85768, 64566, 64338, 100323, 75469, 63823, 117317, 64218, 64257, 64051, 74197, 6, 63893, 130005, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]
labels 宽松的阔腿裤这两年真的吸粉不少,明星时尚达人的心头爱。毕竟好穿时尚,谁都能穿出腿长2米的效果宽松的裤腿,当然是遮肉小能手啊。上身随性自然不拘束,面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点,还
/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|                                                                                                                                      | 0/3000 [00:00<?, ?it/s]04/12/2023 18:12:54 - WARNING - transformers_modules.chatglm.modeling_chatglm - `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/opt/code/ChatGLM-6B/ptuning/main.py", line 430, in <module>
    main()
  File "/opt/code/ChatGLM-6B/ptuning/main.py", line 369, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/code/ChatGLM-6B/ptuning/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/opt/code/ChatGLM-6B/ptuning/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/code/ChatGLM-6B/ptuning/trainer.py", line 2645, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/code/ChatGLM-6B/ptuning/trainer.py", line 2677, in compute_loss
    outputs = model(**inputs)
  File "/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/sdhou/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 1158, in forward
    transformer_outputs = self.transformer(
  File "/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/sdhou/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 909, in forward
    past_key_values = self.get_prompt(batch_size=input_ids.shape[0], device=input_ids.device,
  File "/Users/sdhou/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 857, in get_prompt
    past_key_values = self.dropout(past_key_values)
  File "/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/dropout.py", line 59, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/Users/sdhou/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/functional.py", line 1267, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: "bernoulli_scalar_cpu_" not implemented for 'Half'
  0%|                                                                                                                                      | 0/3000 [00:00<?, ?it/s]

### Steps To Reproduce

1.拉取最新项目代码
2.下载模型到本地
3.conda配置环境
4.修改ptuning/main.py         model = model.half().to('mps')
5.运行 bash train.sh

### Environment

```markdown
- OS:mac book pro m1 os 13.3 (22E252)
- Python:3.10.10
- Transformers:4.27.1
- PyTorch:2.1.0.dev20230411
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

**Comment by duzx16** [comment]
ptuning不支持Mac

**Comment by sdhou** [comment]
知道了 非常感谢
