### ISSUE TITLE
[Help] <推理的时候加载checkpoint报错>

### ISSUE THREAD

**Issue by xiaolinyang2022** [THUDM/ChatGLM-6B#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)

### Steps To Reproduce

错误信息：
RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
	Missing key(s) in state_dict: "embedding.weight". 
	Unexpected key(s) in state_dict: ".weight". 

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
> import os from transformers import AutoTokenizer, AutoModel, AutoConfig import torch
> 
> model_name = "/models" # 模型名 或 模型路径 checkpoint_path = "/workspace/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-300" # 模型checkpoint路径 pre_seq_len = 128 # 模型前缀长度 跟你训练的PRE_SEQ_LEN一致
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> 
> config = AutoConfig.from_pretrained(model_name, trust_remote_code=True) config.pre_seq_len = pre_seq_len model = AutoModel.from_pretrained(model_name, config=config, trust_remote_code=True)
> 
> prefix_state_dict = torch.load(os.path.join(checkpoint_path, "pytorch_model.bin"))
> 
> new_prefix_state_dict = {} for k, v in prefix_state_dict.items(): new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict) print(f"Quantized to 4 bit") model = model.quantize(4) model.half().cuda()
> 
> print(model.chat(tokenizer, "你好"))

旧版的checkpoint（大小在3GB左右）直接用 `checkpoint_path` 替换 `THUDM/chatglm-6b`就行
