### ISSUE TITLE
[Help] ptuning/main.py 数据集问题

### ISSUE THREAD

**Issue by snowkcon** [THUDM/ChatGLM-6B#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

commit： cbb9f44e30944971da5110747dd22618003d6793
ChatGLM-6B/blob/main/ptuning/main.py
194行的i和203行的i会不会相互代替扰乱数据

### Steps To Reproduce

commit： cbb9f44e30944971da5110747dd22618003d6793
ChatGLM-6B/blob/main/ptuning/main.py
194行的i和203行的i会不会相互代替扰乱数据

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by snowkcon** [comment]
eval 和 train 好像都存在这个问题

**Comment by duzx16** [comment]
不会。因为内层的 `i` 赋值之后，外层的 `i` 就没有使用过了。不过这样写确实不太好，我修改一下。

**Comment by snowkcon** [comment]
在 json 数据格式下,外层循环是用到了；
训练数据：
{'prompt':'xxx1','response':'xx1','history':[]}
{'prompt':'xxx2','response':'xx2','history':[('xxx1','xx1')]}

**Comment by duzx16** [comment]
> 在 json 数据格式下,外层循环是用到了； 训练数据： {'prompt':'xxx1','response':'xx1','history':[]} {'prompt':'xxx2','response':'xx2','history':[('xxx1','xx1')]}

在205行之后就没有用到 `i` 了。等回到194的时候i又会被赋予外层循环中正确的值。
anyway，这个地方已经修改了

**Comment by snowkcon** [comment]
嗯嗯；看起来受影响应该只有 eval
eval 在后面 是再次用到了 i；
