### ISSUE TITLE
INT4下报错,size mismatch for lm_head.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]). You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### ISSUE THREAD

**Issue by skyemin** [THUDM/ChatGLM-6B#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我搜之前存在的问题是默认量化等级模型更新了,我的是INT4场景下,
https://huggingface.co/THUDM/chatglm-6b/blob/int4/pytorch_model.bin
本地下载的这个模型,报错 size mismatch for lm_head.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### Steps To Reproduce

INT4

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
用你贴的链接更新一下你本地的文件

**Comment by skyemin** [comment]
> 



> 用 https://huggingface.co/THUDM/chatglm-6b-int4/blob/main/pytorch_model.bin 更新一下你本地的文件 另外，https://huggingface.co/THUDM/chatglm-6b 的 int4 分支只是我们用来测试的，请使用https://huggingface.co/THUDM/chatglm-6b-int4

感谢 我晚上回去试试

**Comment by SuperWTao** [comment]
size mismatch for lm_head.weight: copying a param with shape torch.Size([130528, 4096]) from checkpoint, the shape in current model is torch.Size([150528, 4096]).
我在hugging face上下载下载下来的权重参数，使用的是transformers==4.28.1，请问怎么解决
