### ISSUE TITLE
[Issue/Help] <通过ptuningv2微调之后的模型，加载的时候出现问题。>

### ISSUE THREAD

**Issue by kaileimao1996** [THUDM/ChatGLM-6B#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我使用了以下命令，执行了对600组对话 （prompt, response, history）的微调。

> python.exe main.py --do_train --train_file ..\answers.json --validation_file ..\dev.json --prompt_column prompt --response_column response --overwrite_cache --model_name_or_path ..\model --output_dir ..\output --overwrite_output_dir --max_source_length 256 --max_target_length 256 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 16 --predict_with_generate --max_steps 500 --logging_steps 10 --save_steps 50 --learning_rate 2e-2 --pre_seq_len 128 --quantization_bit 4

然后再跑web_demo.py的时候遇到了这个问题。
![error1](https://user-images.githubusercontent.com/25622072/231531816-140bbf6d-9174-41f1-b4d3-c78a7c01b7cf.png)
![error2_png](https://user-images.githubusercontent.com/25622072/231531832-c2290db2-b422-46cf-ac2e-4dfd08929c28.png)

我查询之后找到可能原因是没有更新1和8这两个模型，我顺带也更新了tokenizer.json 和 tokenization_chatglm.py这两个文件（于北京时间4月12日更新过一次）

但是仍旧报错，且是同样的错误。

这个是web_demo.py的调用模型代码
![微信截图_20230413012500](https://user-images.githubusercontent.com/25622072/231536097-8aabdb1f-aba4-4112-93a4-c6c5c672d052.png)

### Environment

```markdown
- OS: 'Windows-10-10.0.22624-SP0'
- Python:3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
- Transformers:4.27.1
- PyTorch:2.0.0+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
- nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
- graphic card: 3070FE 8GB
- cpu: AMD 5800X
```

**Comment by duzx16** [comment]
根据https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2
config加载的时候用的应该是 `"model"`，而不是 `"output/checkpoint-150"`
