### ISSUE TITLE
如何保证每次生成的结果都保证一致

### ISSUE THREAD

**Issue by archerdong** [THUDM/ChatGLM-6B#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

这个模型有没有哪个可以设置 随机种子的地方，这样能保证 相同的 输入 相同的输出。目前表现来看，生成的结果比较不稳定。

### Steps To Reproduce

...

### Environment

```markdown
- OS: ubuntu
- Python:3.9
- Transformers:
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by chenbohua3** [comment]
```
from transformers import set_seed

set_seed(xxx)

```

**Comment by Leawnn** [comment]
do_sample=False就行了，每次都是固定输出

**Comment by Leawnn** [comment]
概率最大的
