### ISSUE TITLE
[Feature] <title>多个P-tuning如何一起加载，还是得不同的训练数据合在一起生成一个模型

### ISSUE THREAD

**Issue by WanJuWuGo** [THUDM/ChatGLM-6B#571]
### Is your feature request related to a problem? Please describe.

多个P-tuning如何一起加载，还是得不同的训练数据合在一起生成一个模型

### Solutions

.

**Comment by natureLanguageQing** [comment]
不同的数据混合在一起生成一个模型。

**Comment by WanJuWuGo** [comment]
谢谢

**Comment by linghongli** [comment]
> 不同的数据混合在一起生成一个模型。

请问如何生成新模型呢？请问有应用工具脚本吗？谢谢。 类似下面这个，可以将vicuna原始模型和增量模型，合并成新模型
https://github.com/lm-sys/FastChat/blob/main/fastchat/model/apply_delta.py#L19
