### ISSUE TITLE
[BUG/Help] <title> mac Intel Iris Plus Graphics 1536 MB macOs13.2.1 启动 web_demo.py  遇到ReadTimeout

### ISSUE THREAD

**Issue by dragonorant** [THUDM/ChatGLM-6B#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

model = AutoModel.from_pretrained("/path/chatglm-6b", trust_remote_code=True).float()

![image](https://user-images.githubusercontent.com/43945251/231647970-a3dd6664-8a5a-44af-9869-944bea246a3c.png)

### Steps To Reproduce

git clone https://github.com/THUDM/ChatGLM-6B.git
git clone https://huggingface.co/THUDM/chatglm-6b

cd ChatGLM-6B
pip install -r requirements.txt

change from_pretrained
python web_demo.py

### Environment

```markdown
- OS: macOs 13.2.1 
  - 处理器: 2.3 GHz 四核Intel Core i7
  - 图形卡: Intel Iris Plus Graphics 1536 MB
- Python: 3.9
- Transformers: 4.27.1
- torch               2.0.0
- torchaudio          2.0.1
- torchvision         0.15.1
AutoModel.from_pretrained("/path/chatglm-6b", trust_remote_code=True).float()
```

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B
