### ISSUE TITLE
[Help] conda配置的清华的源下载依赖失败

### ISSUE THREAD

**Issue by YanzyUpEveryDay** [THUDM/ChatGLM-6B#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

transformers, cpm_kernels 都不能正常下载

### Steps To Reproduce

install

### Environment

```markdown
- OS: windows11
- Python: 3.11
```

**Comment by ZXStudio** [comment]
换国内镜像
pip3 install transformers==4.27.1 -i http://pypi.douban.com/simple/
pip3 install cpm_kernels  -i http://pypi.douban.com/simple/

**Comment by YanzyUpEveryDay** [comment]
> 换国内镜像 pip3 install transformers==4.27.1 -i http://pypi.douban.com/simple/ pip3 install cpm_kernels -i http://pypi.douban.com/simple/

可以将http://pypi.douban.com/simple/设置给conda吗

**Comment by YanzyUpEveryDay** [comment]
> 换国内镜像 pip3 install transformers==4.27.1 -i http://pypi.douban.com/simple/ pip3 install cpm_kernels -i http://pypi.douban.com/simple/

解决了 谢谢

**Comment by GongZhengMe** [comment]
> > 换国内镜像 pip3 install transformers==4.27.1 -i http://pypi.douban.com/simple/ pip3 install cpm_kernels -i http://pypi.douban.com/simple/
> 
> 解决了 谢谢

请问您是怎么解决的，我也被卡在这里了，使用conda没有下载下来
