### ISSUE TITLE
[Feature] 关于chat和stream_chat的优化建议

### ISSUE THREAD

**Issue by rayvzn119** [THUDM/ChatGLM-6B#577]
### Is your feature request related to a problem? Please describe.

首先感谢作者，为我们提供了如此优秀的模型。在实际使用中，经常会对prompt做改写，但希望展示页面中是用户的原始prompt，目前为了实现这个功能，需要对history中的用户输入做改写，或者记录用户每次的input，不是很方便。因此，为了方便做prompt tuning，建议是否可以增加一个chat函数，它支持传入raw_input和改写后的input，返回raw_history和history。
例子：
raw_input:牙疼吃什么药？ input:基于以下资料，回答用户问题：{context} 牙疼吃什么药？
raw_history:[(牙疼吃什么药？, 牙疼应该吃。。。)]        history:[(基于以下资料，回答用户问题：{context} 牙疼吃什么药？), 牙疼吃。。。)]
目前的history返回的是改写后的prompt，但希望返回的是 用户原始输入，方便展示。
一点拙见，供参考。

### Solutions

1

**Comment by duzx16** [comment]
那直接给model传改写后的input就行了
