### ISSUE TITLE
[BUG/Help] RuntimeError: expected mask dtype to be Bool but got Long

### ISSUE THREAD

**Issue by heccxixi** [THUDM/ChatGLM-6B#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

用chatglm进行模型训练

### Expected Behavior

更新了所有4月6号之后更新的文件还是出现了报错

### Steps To Reproduce

  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 306, in attention_fn
    attention_scores.masked_fill_(attention_mask, -10000.0)
RuntimeError: expected mask dtype to be Bool but got Long

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
具体说一下是怎么进行模型训练的？

**Comment by heccxixi** [comment]
用openprompt带的官方教程，然后新加了chatglm当做一个底座模型。
'chat-glm': ModelClass(**{
        'config': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True),
        # 'tokenizer': T5Tokenizer,
        'tokenizer': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True),
        'model': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True),
        'wrapper': MLMTokenizerWrapper,
    })

**Comment by duzx16** [comment]
> 用openprompt带的官方教程，然后新加了chatglm当做一个底座模型。 'chat-glm': ModelClass(**{ 'config': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True), # 'tokenizer': T5Tokenizer, 'tokenizer': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True), 'model': AutoConfig.from_pretrained('/home/hexinyu/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/thu_chatglm', trust_remote_code=True), 'wrapper': MLMTokenizerWrapper, })

那应该在他们的仓库里提问。

**Comment by heccxixi** [comment]
但是调用的是chatglm的代码报的错呀
