### ISSUE TITLE
AutoModel.from_pretrained() error ,If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by EricHuiK** [THUDM/ChatGLM-6B#58]

**Comment by skirodev** [comment]
You need to rerun the code after **clearing the cached model files of Hugging Face**.

**Comment by duzx16** [comment]
Please make sure you have downloaded all the files in https://huggingface.co/THUDM/chatglm-6b . Specifically, check the SHA256 value of LFS files.
Please open a new issue with the "Bug/Help" issue form if the problem is persistent.

**Comment by EricHuiK** [comment]
Yes, some unknown errors occurred during the upload process of my file, I downloaded it and packaged it into a zip file and uploaded it ok

**Comment by quanpinjie** [comment]
请问如何解决呢，我也遇到了同样的问题
