### ISSUE TITLE
有没有办法显示每次聊天结果的准确率？

### ISSUE THREAD

**Issue by superbigsea** [THUDM/ChatGLM-6B#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2

### Expected Behavior

2

### Steps To Reproduce

2

### Environment

```markdown
- OS:
- Python:2
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
什么是准确率

**Comment by superbigsea** [comment]
比方说我问他一个 上海到爱仕达撒大大市怎么走， 他告诉我坐火车，实际上这个是胡说八道。那么能不能知道这次回答的可信度是比较低的。  我问他中国的首都是哪里，他回答是北京，这个可信度是比较高。能不能显示这个可信度

**Comment by XiaTiaoQAQ** [comment]
> 比方说我问他一个 上海到爱仕达撒大大市怎么走， 他告诉我坐火车，实际上这个是胡说八道。那么能不能知道这次回答的可信度是比较低的。 我问他中国的首都是哪里，他回答是北京，这个可信度是比较高。能不能显示这个可信度

如果能知晓这个可信度，就没必要胡说八道了- -

**Comment by superbigsea** [comment]
> > 比方说我问他一个 上海到爱仕达撒大大市怎么走， 他告诉我坐火车，实际上这个是胡说八道。那么能不能知道这次回答的可信度是比较低的。 我问他中国的首都是哪里，他回答是北京，这个可信度是比较高。能不能显示这个可信度
> 
> 如果能知晓这个可信度，就没必要胡说八道了- -

谢啦
