### ISSUE TITLE
CUDA版本需求

### ISSUE THREAD

**Issue by z1968357787** [THUDM/ChatGLM-6B#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问这个项目的CUDA版本有要求吗，我用的11.3跑起来就报了这个错RuntimeError: CUDA Error: no kernel image is available for execution on the device，网上查了原因就说是CUDA版本不对，换了10.0跑起来的时候就说CUDA没法启动

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
与requirement一致
```

**Comment by XiaTiaoQAQ** [comment]
你看看你的pytorch版本和cuda版本。实测cuda11.3+pytorch 1.11.0可以运行

**Comment by ZXStudio** [comment]
> 你看你的pytorch版本和cuda版本。实测cuda11.3+pytorch 1.11.0可以运行

是在服务器上跑还是pc电脑？

**Comment by z1968357787** [comment]
Linux服务器上跑的


&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hao ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 晚上7:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] CUDA版本需求 (Issue #587)





  
你看你的pytorch版本和cuda版本。实测cuda11.3+pytorch 1.11.0可以运行
  
是在服务器上跑还是pc电脑？

**Comment by speeder179** [comment]
cuda 11.7 运行`python web_demo.py`正常，但是运行ptuning下的`bash train.py`就报错。
`RuntimeError: Library cudart is not initialized`

**Comment by lanss315425** [comment]
CUDA Error: no kernel image is available for execution on the device 我也有这个错误，CUDA Version: 10.2，torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1

**Comment by zhangch9** [comment]
Duplicate of [#119](https://github.com/THUDM/ChatGLM-6B/issues/119)
