### ISSUE TITLE
[BUG/Help] <title>求助，微调，多卡训练，torchrun的时候总会出错

### ISSUE THREAD

**Issue by Coder-nlper** [THUDM/ChatGLM-6B#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/nlp/.cache/huggingface/modules/transformers_modules/chatglm6b/modeling_chatglm.py'
这个文件在cache中明明有
为啥总是报错。。。
跑着跑着就挂了
有没有大神解释下

### Steps To Reproduce

无

### Environment

```markdown
- OS:ubuntu 16.04
- Python:3.9.16
- Transformers:4.27.4
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
11.8
```

**Comment by duzx16** [comment]
尝试一下从本地加载模型 `https://github.com/THUDM/ChatGLM-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B`

**Comment by hrdxwandg** [comment]
我也出现这个问题，我是从本地加载的。单机单卡没问题，单机多卡报这个错，有大神知道啥原因么？为啥单机多卡会走cache呢？

**Comment by Coder-nlper** [comment]
> 尝试一下从本地加载模型 https://github.com/THUDM/ChatGLM-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B

这个好像也不行呀，使用deepspeed训练还是会报错

raceback (most recent call last):
  File "/data/home/nlp/llms/chatglm/ptuning/main.py", line 428, in <module>
    main()
  File "/data/home/nlp/llms/chatglm/ptuning/main.py", line 107, in main
    config = AutoConfig.from_pretrained(model_args.model_name_or_path, cache_dir=model_args.model_name_or_path, trust_remote_code=True)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.9/site-packages/transformers-4.27.4-py3.9.egg/transformers/models/auto/configuration_auto.py", line 911, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.9/site-packages/transformers-4.27.4-py3.9.egg/transformers/dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.9/site-packages/transformers-4.27.4-py3.9.egg/transformers/dynamic_module_utils.py", line 179, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.chatglm6b.configuration_chatglm' has no attribute 'ChatGLMConfig'

这些文件本地下载好的模型里面有，.cache里面也有，就是为啥多卡训练加载不了

**Comment by hrdxwandg** [comment]
> > 我也出现这个问题，我是从本地加载的。单机单卡没问题，单机多卡报这个错，有大神知道啥原因么？为啥单机多卡会走cache呢？
> 
> 单机多卡是时灵时不灵的，有时候加载模型代码都能找见，有时候找不见，这让人很懵逼。。。。

是的，哈哈

**Comment by online2311** [comment]
我多卡也遇到了同样的问题，单卡是正常的。

**Comment by ray-008** [comment]
我用多卡的时候还爆过显存，我是两张A100-40G的卡。

**Comment by Coder-nlper** [comment]
> 我用多卡的时候还爆过显存，我是两张A100-40G的卡。

看有人堆了8张A100，训练成功了😄😄😄

**Comment by hrdxwandg** [comment]
原因找打了，huggingface transformers的bug

**Comment by Coder-nlper** [comment]
> 

> 原因找到了，是huggingface transformers的bug。
> [huggingface/transformers#22506](https://github.com/huggingface/transformers/issues/22506)
> 用main分支重新安装下包就行

刚看到transformers的源码了，准备改，感觉好麻烦。

过来看看issue，看有结果没，看到老哥回答。

亲测有效，目前没有报错了，感谢老哥～

**Comment by 336655asd** [comment]
2*V100-32G成功跑起来了，我建议的步骤是：
1. 拉取最新的chatglm代码和模型，最新的transformers，最新的deepspeed，分别安装好。我的transformers版本为4.28.1，deepspeed版本为0.9.0
2. main.py文件，修改模型读取参数，model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, empty_init=False, trust_remote_code=True)
3. ds_train_finetune.sh，删除quantization_bit参数，per_device_train_batch_size、max_source_length、max_target_length调低
4. 修改deepspeed.json文件，我的配置如下：
```
{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
},
"optimizer": {
  "type": "AdamW",
  "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
  }
},
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
  },
  "offload_param": {
      "device": "cpu",
      "pin_memory": true
  },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "reduce_scatter": true,
    "contiguous_gradients" : true,
    "overlap_comm": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  }
}
```

**Comment by TestNLP** [comment]
> > 
> 
> > 原因找到了，是huggingface transformers的bug。
> > [huggingface/transformers#22506](https://github.com/huggingface/transformers/issues/22506)
> > 用main分支重新安装下包就行
> 
> 刚看到transformers的源码了，准备改，感觉好麻烦。
> 
> 过来看看issue，看有结果没，看到老哥回答。
> 
> 亲测有效，目前没有报错了，感谢老哥～

我也有同样问题，请问你最后安装的transformers是哪个版本？

**Comment by hrdxwandg** [comment]
@TestNLP 直接安装main分支

**Comment by jockeyyan** [comment]
> 

我用4.28.1试了一下，能跑起来。

**Comment by 2088208** [comment]
> 2*V100-32G成功跑起来了，我建议的步骤是：
> 
> 1. 拉取最新的chatglm代码和模型，最新的transformers，最新的deepspeed，分别安装好。我的transformers版本为4.28.1，deepspeed版本为0.9.0
> 2. main.py文件，修改模型读取参数，model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, empty_init=False, trust_remote_code=True)
> 3. ds_train_finetune.sh，删除quantization_bit参数，per_device_train_batch_size、max_source_length、max_target_length调低
> 4. 修改deepspeed.json文件，我的配置如下：
> 
> ```
> {
>   "train_micro_batch_size_per_gpu": "auto",
>   "zero_allow_untested_optimizer": true,
>   "fp16": {
>     "enabled": "auto",
>     "loss_scale": 0,
>     "initial_scale_power": 16,
>     "loss_scale_window": 1000,
>     "hysteresis": 2,
>     "min_loss_scale": 1
>   },
>   "bf16": {
>     "enabled": "auto"
> },
> "optimizer": {
>   "type": "AdamW",
>   "params": {
>       "lr": "auto",
>       "betas": "auto",
>       "eps": "auto",
>       "weight_decay": "auto"
>   }
> },
>   "zero_optimization": {
>     "stage": 3,
>     "offload_optimizer": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>   "offload_param": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>     "allgather_partitions": true,
>     "allgather_bucket_size": 5e8,
>     "reduce_scatter": true,
>     "contiguous_gradients" : true,
>     "overlap_comm": true,
>     "sub_group_size": 1e9,
>     "reduce_bucket_size": "auto",
>     "stage3_prefetch_bucket_size": "auto",
>     "stage3_param_persistence_threshold": "auto",
>     "stage3_max_live_parameters": 1e9,
>     "stage3_max_reuse_distance": 1e9,
>     "stage3_gather_16bit_weights_on_model_save": true
>   }
> }
> ```

大哥 能不能看看你的ds_train_fitune.sh的参数啊
