### ISSUE TITLE
[Feature] 致谢并邀请加入ChatGLM-Uni的评审

### ISSUE THREAD

**Issue by StarRing2022** [THUDM/ChatGLM-6B#599]
### Solutions

非常感谢ChatGLM官方的中文开源大语言模型！ChatGLM-Uni是基于贵方模型作为底座，以Lora交互其他模型为手段，用于迅速使ChatGLM得到较为理想的个性化与适应性能力。初步实验表明，该方法能产生一定效果。我们真诚希望ChatGLM官方参与到评审团之中，以指导和帮助我们下一步的努力方向。我们的工作为：https://github.com/StarRing2022/ChatGlm-Uni

**Comment by duzx16** [comment]
主要是感觉实验的场景有点怪。alpaca 数据集翻译成中文之后覆盖的场景跟 chatglm 本来就是高度类似的，这种迁移我看不出有什么实际意义。应该研究比如怎么把 alpaca 的英文能力迁移到 chatglm，或者把 chatglm的中文能力迁移到 llama。

**Comment by StarRing2022** [comment]
我们解释一下，更多的Lora权值是基于英文或多语言的，我们已分享的权值还是英文的比较多，如victuna，确实增强了ChatGLM英文能力，感谢您的建议！我们也是想如此弥补。

**Comment by duzx16** [comment]
> 我们解释一下，更多的Lora权值是基于英文或多语言的，我们已分享的权值还是英文的比较多，如victuna，确实增强了ChatGLM英文能力，感谢您的建议！我们也是想如此弥补。

我没有同意加入评审，可以不要把我的id放到你们的README上吗
