### ISSUE TITLE
Gradio渲染不全

### ISSUE THREAD

**Issue by Gladiator566** [THUDM/ChatGLM-6B#60]
您好，很棒的工作！我按照readme的步骤，python web_demo.py成功启动了公网服务demo，但是gradio显示的只有如下图一般的界面，只有最下面的generate按钮对话框，并没有像README的demo截图一样出现“提问”及“回复”对话框；
![image](https://user-images.githubusercontent.com/22348637/225265303-877a1bc1-516b-417a-8362-c9af459b8c65.png)
并且有时gradio即使设置了share=True，得到公网地址会非常慢，经常会变成提示No interface is running，请问这是什么原因呢？模型应该是加载完毕的，谢谢！
环境：
  * 系统：Linux，Centos-7
  * 浏览器：Chrome
  * 显卡：3090*1，cuda：11.7
  * Gradio版本：3.21.0

**Comment by duzx16** [comment]
Web demo修改过了，之前的版本不支持markdown语法。
