### ISSUE TITLE
[BUG/Help] <title>您好，请问基座模型GLM的预训练问题，预训练数据格式。

### ISSUE THREAD

**Issue by zhangzai666** [THUDM/ChatGLM-6B#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好，我想基于chatglmd的基座模型GLM-chinese进行预训练，但是我看代码中的数据集是知乎、百科还有五道。数据集格式是.lazy。您能提供这个数据文件示例么

### Expected Behavior

您好，我想基于chatglmd的基座模型GLM-chinese进行预训练，但是我看代码中的数据集是知乎、百科还有五道。数据集格式是.lazy。您能提供这个数据文件示例么

### Steps To Reproduce

您好，我想基于chatglmd的基座模型GLM-chinese进行预训练，但是我看代码中的数据集是知乎、百科还有五道。数据集格式是.lazy。您能提供这个数据文件示例么

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
您好，我想基于chatglmd的基座模型GLM-chinese进行预训练，但是我看代码中的数据集是知乎、百科还有五道。数据集格式是.lazy。您能提供这个数据文件示例么
```

### Anything else?

您好，我想基于chatglmd的基座模型GLM-chinese进行预训练，但是我看代码中的数据集是知乎、百科还有五道。数据集格式是.lazy。您能提供这个数据文件示例么

**Comment by duzx16** [comment]
不能

**Comment by TEENN2233** [comment]
这个肯定没法给你看吧，你自己都说涉及百度知乎之类的产品了
