### ISSUE TITLE
[BUG/Help] 训练相关的问题：我的数据集是PDF,DOCX,HTML的格式，请问如何训练？

### ISSUE THREAD

**Issue by 19245222** [THUDM/ChatGLM-6B#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好。如题。我留意到大部分的数据集都是这种JSON格式的，比如：
"question": "......."
"answer":  "........." 

但如果我的数据集是一个HTML格式的文件呢？
比如：http://app.0359tv.com/agreement/privacy/policy.html 

理想的情况：

    1.question 填 HTML的文字 和 我的问题
    2.answer 填 我预设的答案
    3.然后喂给 CHATGLM-Tuning 这个项目去finetune，最后ChatGLM模型得到增强。

但具体用到哪个工具，我不知道，恳请您指导下。如果您有不一样的思路，请您指教，谢谢！

### Steps To Reproduce

Null

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
可以用 `pandoc` 转化为文本或者markdown

**Comment by chrischjh** [comment]
> 可以用 `pandoc` 转化为文本或者markdown

训练数据不是要以问答的形式？只是转换成文本没用吧

**Comment by moliqingwa** [comment]
+1

> > 可以用 `pandoc` 转化为文本或者markdown
> 
> 训练数据不是要以问答的形式？只是转换成文本没用吧

**Comment by mockyd** [comment]
> > 可以用 `pandoc` 转化为文本或者markdown
> 
> 训练数据不是要以问答的形式？只是转换成文本没用吧

您好，请问这个问题您有解决方法了吗？
