### ISSUE TITLE
[Feature] <有其他平台的代码吗>

### ISSUE THREAD

**Issue by liaoweiguo** [THUDM/ChatGLM-6B#609]
### Is your feature request related to a problem? Please describe.

跨平台： 支持在国产的海光 DCU、华为昇腾 910 和申威处理器及美国的英伟达芯片上进行训练与推理。

想测试一下在申威上的推理性能

### Solutions

部署一个国产平台推理服务

**Comment by zhangch9** [comment]
没有对应的硬件，目前无法测试。
