### ISSUE TITLE
  Something went wrong Expecting value: line 1 column 1 (char 0)  

### ISSUE THREAD

**Issue by laose307** [THUDM/ChatGLM-6B#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

输入文本点击提交就界面就显示如下错误：

Something went wrong
Expecting value: line 1 column 1 (char 0)

看到有人说把 queue去掉，去掉了就会报queue的错误。这个问题如何解决？

### Expected Behavior

能正常返回值出来

### Steps To Reproduce

输入文本点击提交就界面就显示如下错误：

Something went wrong
Expecting value: line 1 column 1 (char 0)

看到有人说把 queue去掉，去掉了就会报queue的错误。这个问题如何解决？

### Environment

```markdown
conda create -n chatglm python=3.10

conda activate chatglm安装pytorch

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
```

### Anything else?

conda create -n chatglm python=3.10

conda activate chatglm安装pytorch

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

**Comment by duzx16** [comment]
你能贴一下完整的报错信息吗

**Comment by laose307** [comment]
非常感谢，问题已经解决了

**Comment by enternityFan** [comment]
> 非常感谢，问题已经解决了

请问是怎么解决的？我也遇到了这个问题。

**Comment by CodingSha** [comment]
一样的问题，同问如何解决

**Comment by LuckyLee333** [comment]
我也遇见了这样的问题，我解决了，但是只能在本地运行的那种。

更改web_demo.py中的最后一行代码：（把share关掉了）
# demo.queue().launch(share=True, inbrowser=True)
import os
os.environ["no_proxy"] = "localhost,127.0.0.1,::1"
demo.queue().launch(server_name="0.0.0.0", server_port=7890)

**Comment by ysun** [comment]
> 我也遇见了这样的问题，我解决了，但是只能在本地运行的那种。
> 
> 更改web_demo.py中的代码：demo.queue().launch(share=True, inbrowser=True)（注释掉这一行，改为下边的代码） import os os.environ["no_proxy"] = "localhost,127.0.0.1,::1" demo.queue().launch(server_name="0.0.0.0", server_port=7890)
> 
> 这样就不会出现这个问题了，不知道对大家有没有用。

@LuckyLee333 厉害！ 竟然解决了，Python大神！哈哈哈。非常感谢~！

**Comment by enternityFan** [comment]
这个问题我解决了，考虑是以下的原因:
1.cmd版本的问题。使用windows自带的cmd是行不通的，我用MobaXterm的话就行。
2.api.py改为uvicorn.run(app, host='192.168.1.XXX', port=8000, workers=1)，通过修改为这个代码，可以实现局域网内调用api.

**Comment by 5211273081** [comment]
> demo.queue().launch(share=True, inbrowser=True)

第几行啊这个
