### ISSUE TITLE
多卡运行clidemo，回答出现问题

### ISSUE THREAD

**Issue by Razliublt** [THUDM/ChatGLM-6B#627]
### Is your feature request related to a problem? Please describe.

我使用的多卡部署的分支，跑的clidemo，我只提问了一次，模型却回答我很多次
![E37L3}$S_V{)(G{BTD03JSB](https://user-images.githubusercontent.com/50354993/232183118-392e64d3-64f1-4e25-b50b-035f989921bf.png)

### Solutions

这是clidemo 的代码
![image](https://user-images.githubusercontent.com/50354993/232183134-f42e9c37-773b-48b9-bb18-60261cec7ac1.png)

**Comment by Razliublt** [comment]
这是因为多卡部署的原因吗？如果我只想要一个回答该怎么做

**Comment by zhangch9** [comment]
感觉是你的terminal没有设置好，`clear`（或`cls` on Windows）命令执行有问题。
