### ISSUE TITLE
[Help] <torch1.7.1版本没有 skip_init 方法 导致加载报错>

### ISSUE THREAD

**Issue by wgfire** [THUDM/ChatGLM-6B#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在自己电脑上部署GPU版本，由于cuda 版本原因， 使用的pytorch为1.7.1，执行web_demo.py 报错，
执行这个modeling_chatglm.py时报错，  在这个版本下要怎么修改呢，能帮忙贴下代码吗，感谢
![image](https://user-images.githubusercontent.com/25904586/232190011-56186e58-161e-4383-b7f0-70f4e34335ce.png)

### Expected Behavior

在torch为1.7.1 时 正常加载模型

### Steps To Reproduce

python  web-demo.py

### Environment

```markdown
- OS:window
- Python:3.9
- Transformers:
- PyTorch:1.7.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : true
```

**Comment by duzx16** [comment]
把`from torch.nn.utils import skip_init` 换成
```python
def skip_init(cls, *args, **kwargs):
    return cls(*args, **kwargs)
```

**Comment by shenjingrong** [comment]
skip_init 方法只在PyTorth版本1.10.0以上才开始有的，如下步骤看看能不能解决你的问题：
1、检查当前你的PyTorth版本：python -c "import torch; print(torch.__version__)"
2、如果是1.10.1以下版本则没有skip_init 方法，需要升级PyTorth版本，升级步骤：
（1）卸载旧的PyTorth版本：pip uninstall torch
（2）安装新的PyTorth版本：pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html
其中新版的PyTorth版本根据你的实际情况安装，官网PyTorth历史下载地址：https://pytorch.org/get-started/previous-versions/

**Comment by wgfire** [comment]
> 把`from torch.nn.utils import skip_init` 换成
> 
> ```python
> def skip_init(cls, *args, **kwargs):
>     return cls(*args, **kwargs)
> ```

有些地方是5个参数，后面两个是删除吗？

**Comment by wgfire** [comment]
> skip_init 方法只在PyTorth版本1.10.0以上才开始有的，如下步骤看看能不能解决你的问题： 1、检查当前你的PyTorth版本：python -c "import torch; print(torch.**version**)" 2、如果是1.10.1以下版本则没有skip_init 方法，需要升级PyTorth版本，升级步骤： （1）卸载旧的PyTorth版本：pip uninstall torch （2）安装新的PyTorth版本：pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html 其中新版的PyTorth版本根据你的实际情况安装，官网PyTorth历史下载地址：https://pytorch.org/get-started/previous-versions/

我是1.7.1，也没有这个方法，需要2.0吧?

**Comment by xxAkuya** [comment]
请问找到解决办法了吗，

**Comment by a729360471** [comment]
1、卸载显卡驱动
sh NVIDIA-Linux-x86_64-525.105.17.run --uninstall
2、重启后安装11.7cuda
sh NVIDIA-Linux-x86_64-515.105.01.run
3、安装torch
pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117

**Comment by YikunHan42** [comment]
同问，这里1.9.1 pytorch
