### ISSUE TITLE
[BUG/Help] 跑微调train时报错 Library cublasLt is not initialized 

### ISSUE THREAD

**Issue by sdhou** [THUDM/ChatGLM-6B#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

大家好 请教：3090 24G的显卡跑demo都没问题 跑ptuning train 报 RuntimeError: Library cublasLt is not initialized

        model = model.quantize(model_args.quantization_bit) 因该是在这步上报的错 可我已经4bit跑了啊 求助

运行环境和报错信息如下

python 3.9
nvidia-smi CUDA Version: 12.1

(glm3) C:\Users\Administrator>conda list
# packages in environment at C:\Users\Administrator\miniconda3\envs\glm3:
#
# Name                    Version                   Build  Channel
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7        py39haa95532_0
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.11.0                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fastapi                   0.95.1                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
gradio                    3.27.0                   pypi_0    pypi
gradio-client             0.1.3                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.17.0                   pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.13.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.3.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
latex2mathml              3.75.2                   pypi_0    pypi
linkify-it-py             2.0.0                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdtex2html                1.2.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
orjson                    3.8.10                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       23.0.1           py39haa95532_0
protobuf                  4.22.3                   pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pydantic                  1.10.7                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.9.16               h6244533_2
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rouge-chinese             1.0.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.98                   pypi_0    pypi
setuptools                65.6.3           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
starlette                 0.26.1                   pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.0+cu118              pypi_0    pypi
torchaudio                2.0.1+cu118              pypi_0    pypi
torchvision               0.15.1+cu118             pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.1                   pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.21.1                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
websockets                11.0.1                   pypi_0    pypi
wheel                     0.38.4           py39haa95532_0
wincertstore              0.2              py39haa95532_2
xxhash                    3.2.0                    pypi_0    pypi
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi

python main.py     --do_train     --train_file train.json     --validation_file dev.json     --prompt_column prompt     --response_column response --history_column history    --overwrite_cache     --model_name_or_path ..\\oye     --output_dir output\\adgen-chatglm-6b-pt-128-2e-2     --overwrite_output_dir     --max_source_length 64     --max_target_length 64     --per_device_train_batch_size 1     --per_device_eval_batch_size 1    --gradient_accumulation_steps 16     --predict_with_generate     --max_steps 3000     --logging_steps 10     --save_steps 1000     --learning_rate 2e-2     --pre_seq_len 128     --quantization_bit 4
04/16/2023 08:47:22 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
04/16/2023 08:47:22 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output\\adgen-chatglm-6b-pt-128-2e-2\runs\Apr16_08-47-22_DESKTOP-TON0688,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output\\adgen-chatglm-6b-pt-128-2e-2,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=output\\adgen-chatglm-6b-pt-128-2e-2,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
04/16/2023 08:47:33 - WARNING - datasets.builder - Found cached dataset json (C:/Users/Administrator/.cache/huggingface/datasets/json/default-33fa19b8d1c0557c/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 178.08it/s]
[INFO|configuration_utils.py:666] 2023-04-16 08:47:33,531 >> loading configuration file ..\\oye\config.json
[WARNING|configuration_auto.py:905] 2023-04-16 08:47:33,531 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:666] 2023-04-16 08:47:33,687 >> loading configuration file ..\\oye\config.json
[INFO|configuration_utils.py:720] 2023-04-16 08:47:33,687 >> Model config ChatGLMConfig {
  "_name_or_path": "..\\\\oye",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.27.1",
  "use_cache": true,
  "vocab_size": 130528
}

[WARNING|tokenization_auto.py:652] 2023-04-16 08:47:33,703 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1800] 2023-04-16 08:47:33,922 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1800] 2023-04-16 08:47:33,922 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-04-16 08:47:33,922 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-04-16 08:47:33,922 >> loading file tokenizer_config.json
[WARNING|auto_factory.py:456] 2023-04-16 08:47:34,296 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|modeling_utils.py:2400] 2023-04-16 08:47:34,562 >> loading weights file ..\\oye\pytorch_model.bin.index.json
[INFO|configuration_utils.py:575] 2023-04-16 08:47:34,562 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.27.1"
}

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.23s/it]
[INFO|modeling_utils.py:3032] 2023-04-16 08:47:44,834 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3034] 2023-04-16 08:47:44,834 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ..\\oye and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2690] 2023-04-16 08:47:44,890 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
04/16/2023 08:47:44 - WARNING - cpm_kernels.library.base - Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
Traceback (most recent call last):
  File "C:\Users\Administrator\code\ChatGLM-6B\ptuning\main.py", line 431, in <module>
    main()
  File "C:\Users\Administrator\code\ChatGLM-6B\ptuning\main.py", line 129, in main
    model = model.quantize(model_args.quantization_bit)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\oye\modeling_chatglm.py", line 1435, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\oye\quantization.py", line 157, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\oye\quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\oye\quantization.py", line 78, in compress_int4_weight
    kernels.int4WeightCompression(
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in __call__
    func = self._prepare_func()
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\kernels\base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\kernels\base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\device\__init__.py", line 152, in use
    self._device.use()
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\device\__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "C:\Users\Administrator\miniconda3\envs\glm3\lib\site-packages\cpm_kernels\library\base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized

### Steps To Reproduce

conda create --name glm python=3.9
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
run train

### Environment

```markdown
- OS:windows
- Python:3.9
- Transformers:4.27.1 
- PyTorch:2.0.0+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by sdhou** [comment]
找到原因了 是我cudatoolkit 没装。。。

**Comment by happybeta** [comment]
> 找到原因了 是我cudatoolkit 没装。。。

你好，如何安装cudatoolkit 有指南吗？

**Comment by liudaoguang** [comment]
ChatGLM2-6B/ptuning/main.py
127     if model_args.pre_seq_len is not None:
128         # P-tuning v2
129         model = model.half()  ===>model = model.half().cuda()    
GPU微调训练：尝试在后面加.cuda()，半精度half是依赖cuda写的需要调用cuda函数；（ubuntu亲测有效）
CPU微调训练：model = model.float() （个人仅在macOS m1上跑通）
130         model.transformer.prefix_encoder.float()

**Comment by chuangfengwang** [comment]
> > 找到原因了 是我cudatoolkit 没装。。。
> 
> 你好，如何安装cudatoolkit 有指南吗？

https://developer.nvidia.com/cuda-toolkit-archive

**Comment by diiiiiiiiiiiiK** [comment]
这些包都太大了，3G
