### ISSUE TITLE
[BUG/Help] <title>请问如何基于之前的Ptuning模型，再次进行微调

### ISSUE THREAD

**Issue by littlestone0806** [THUDM/ChatGLM-6B#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

已经训练了200次，生成了一个模型。再次执行训练时，又从头开始跑了

### Steps To Reproduce

已经训练了200次，生成了一个模型。再次执行训练时，又从头开始跑了

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zx19941234** [comment]
你好  请问你是用的什么配置运行微调的  我运行微调报内存不足   我用的V100 16G

**Comment by littlestone0806** [comment]
> 你好 请问你是用的什么配置运行微调的 我运行微调报内存不足 我用的V100 16G

我用的M40 24G

**Comment by zx19941234** [comment]
这个问题已经解决&nbsp; 谢谢&nbsp; &nbsp;还有一个问题请教
{
&nbsp; &nbsp; "prompt": "请用C#帮我实现",
&nbsp; &nbsp; "response": "using System;using System.Net.Http;using System.Text;using System.Threading.Tasks;using Newtonsoft.Json;class Program{static async Task Main(){string url="http://127.0.0.1/hangbanguanjia";var requestParams=new{safd="111"};string response=await SendRequestAsync(url,requestParams);Console.WriteLine("Response: "+response);}static async Task<string&gt; SendRequestAsync(string url,object requestParams){using(HttpClient client=new HttpClient()){var content=new StringContent(JsonConvert.SerializeObject(requestParams),Encoding.UTF8,"application/json");HttpResponseMessage response=await client.PostAsync(url,content);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync();}}}",
&nbsp; &nbsp; "history": [
&nbsp; &nbsp; &nbsp; &nbsp; [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "航班管家的出票地址是多少?",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "航班管家的出票地址是http://127.0.0.1/hangbanguanjia,请注意，为了数据安全，ip地址为虚拟ip，请替换成实际ip"
&nbsp; &nbsp; &nbsp; &nbsp; ],
&nbsp; &nbsp; &nbsp; &nbsp; [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "航班管家的请求参数是？",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "航管管家的请求参数类型是application/json，参数为{'safd':'111'}"
&nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; ]
}
这个是我微调的数据集&nbsp; 但是当我跑完运行之后&nbsp; &nbsp;问的问题和想要的完全不符，请问知道怎么回事吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月17日(星期一) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] [BUG/Help] <title&gt;请问如何基于之前的Ptuning模型，再次进行微调 (Issue #639)





  
你好 请问你是用的什么配置运行微调的 我运行微调报内存不足 我用的V100 16G
  
我用的M40 24G

**Comment by yaumi123** [comment]
是怎么解决的？

**Comment by grep-w** [comment]
我也遇到了相似的问题，每次都是重新微调，请问有没有在Ptuning过程中可以多次使用之前微调结果的解决方案呢?

**Comment by SHITIANYU-hue** [comment]
我现在又在这里加了一个参数继续finetune 
![image](https://github.com/THUDM/ChatGLM-6B/assets/38762389/4ca578f8-10b8-44a7-b216-47f49d0ebc6b)

**Comment by ufocjm** [comment]
> 

可以看一下你的详细配置吗？

**Comment by ufocjm** [comment]
> 我现在又在这里加了一个参数继续finetune ![image](https://user-images.githubusercontent.com/38762389/242784242-4ca578f8-10b8-44a7-b216-47f49d0ebc6b.png)

可以看一下你的详细配置吗？

**Comment by SHITIANYU-hue** [comment]
https://github.com/SHITIANYU-hue/ChatGLM-6B/blob/main/ptuning/main.py#L113

**Comment by ufocjm** [comment]
> https://github.com/SHITIANYU-hue/ChatGLM-6B/blob/main/ptuning/main.py#L113

对，这段代码我也看到了，通过你上面在`do_train`加上`--ptuning_checkpoint`是可以继续微调的对吗？然后微调的结果又再一次覆盖到`--output_dir`吗？

**Comment by SHITIANYU-hue** [comment]
对的

**Comment by ufocjm** [comment]
> 对的

最后再通过这样运行吗？
```python
MODEL_PATH = "./model/chatglm-6b"
CHECKPOINT_PATH = "./output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-1000"

# 载入Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)

config = AutoConfig.from_pretrained(MODEL_PATH, trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained(MODEL_PATH, config=config, trust_remote_code=True).cuda()

prefix_state_dict = torch.load(os.path.join(CHECKPOINT_PATH, "pytorch_model.bin"))
new_prefix_state_dict = {}

for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
```

**Comment by EXYNOS9825** [comment]
> 
请问下M40 24G运行这个模型的效果怎么样
