### ISSUE TITLE
请问：ChatGLM-6B-INT8跟load(ChatGLM-6B).quantize(8)有什么区别吗？

### ISSUE THREAD

**Issue by ninghongbo123** [THUDM/ChatGLM-6B#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问ChatGLM-6B-INT8跟load(ChatGLM-6B).quantize(8)有什么区别吗？

### Steps To Reproduce

无

### Environment

```markdown
无
```

**Comment by duzx16** [comment]
load(ChatGLM-6B).quantize(8) 是先加载fp16的完整模型再量化，内存占用的峰值等于fp16的模型大小。
ChatGLM-6B-INT8是直接加载INT8量化的模型，内存占用的峰值等于INT8的模型大小。适合内存比较有限的情况。

**Comment by xu-song** [comment]
预测效果哪个好一些呢
