### ISSUE TITLE
[BUG/Help] ptuning running issue

### ISSUE THREAD

**Issue by lawzlo** [THUDM/ChatGLM-6B#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to run `bash` train.sh` , and got this:

`bash` train.sh    
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named `'numpy'`

I've installed numpy, torch, and all dependencies, but it still has the same issue.

Can anyone help?

### Steps To Reproduce

1. activate venv
2. cd to ptuning folder
3. run bash train.sh
4. 

### Environment

```markdown
- OS:Windows
- Python:3.10
- Transformers:
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by MrJungleMonkey** [comment]
So did you solve the problem? Can you share your experience?

**Comment by lawzlo** [comment]
It is env issue in my case, change to python.exe instead of python3 in train.sh.

**Comment by MrJungleMonkey** [comment]
> It is env issue in my case, change to python.exe instead of python3 in train.sh.

thx！I have the same problem and I tried your method successfully.
