### ISSUE TITLE
[BUG/Help] 希望提供 chatglm-6b-int4 的镜像地址

### ISSUE THREAD

**Issue by chenkan** [THUDM/ChatGLM-6B#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

直接从 huggingface 下载网速大概只有几十 K，下载需要 2-3 天，希望提供国内镜像地址

### Steps To Reproduce

同 Current Behavior

### Environment

```markdown
- OS:windows
- Python:3
- Transformers:4.27.1
- PyTorch:2
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.8
```

**Comment by kiron111** [comment]
聞達的懶人包，模型的資料夾，有chatglm-6b-in4:

https://pan.baidu.com/s/105nOsldGt5mEPoT2np1ZoA?pwd=lyqz

**Comment by kiron111** [comment]
百度網盤，cheat engine 加速
