### ISSUE TITLE
微调后的模型大小为24G而非12G，非P-Tuning

### ISSUE THREAD

**Issue by songyingxin** [THUDM/ChatGLM-6B#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当我采用chatglm进行微调的时候，保存的模型大小为24G，而原来的chatglm模型大小为12g， 请问这个是由于你们做了什么保存处理吗？

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

无

**Comment by duzx16** [comment]
因为存的是checkpiont是fp32格式的，这个可以优化，但是还没有做。

**Comment by songyingxin** [comment]
> 因为存的是checkpiont是fp32格式的，这个可以优化，但是还没有做。

ok，了解，感谢回复。感觉后面的各种轻量化的优化才是未来大模型发展的重点
