### ISSUE TITLE
[BUG/Help] <title>chatglm-6b-int4训练和推理都会导致服务器重启，然后显卡无法识别，硬盘丢失挂载

### ISSUE THREAD

**Issue by moon4869** [THUDM/ChatGLM-6B#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

服务器显卡为1080TI，系统为Ubuntu 16.04.5 LTS。
使用P-Tuning v2的微调方式，所有配置和文档中保持一致，修改了模型为chatglm-6b-int4，数据集以及per_device_train_batch_size=4，gradient_accumulation_steps=4
其中一台服务器在训练开始几十分钟后无法连接，待服务器重启后，硬盘丢失挂载，显卡正常识别。
另一台服务器在训练开始几十分钟后也无法连接，服务器自动重启后，发现硬盘丢失挂载，重新挂载后再次启动模型训练，在几十分钟后服务器再次中断连接，等待其重启后，发现NVIDIA显卡驱动丢失，无法识别到NVIDIA显卡，硬盘丢失挂载。
![image](https://user-images.githubusercontent.com/33173163/232421914-1021b37f-6995-4113-9d3f-d533bce39316.png)
第三台服务器成功训练完个人数据集，3000step，然后使用ChatGLM-6B-PT中的部署方式启动ipynb进行推理测试，测试前期一切正常，直到半个小时后，服务器突然中断，待其重启后，硬盘丢失挂载，NVIDIA显卡驱动丢失，但是可以识别到NVIDIA显卡。
![image](https://user-images.githubusercontent.com/33173163/232422204-8e230852-1bbc-4225-a65f-da72f5a26188.png)
上面所有的训练、测试过程中，显存都处于正常状态，并且开始都正常运行，只是突然服务器发生中断。

### Steps To Reproduce

如果有需要的话可以提供完整的复现流程

### Environment

```markdown
- OS:Ubuntu 16.04.5 LTS
- Python:3.10
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

### Anything else?

请问可能是什么原因导致上述情况的出现？可能的排查方式和解决方法？

**Comment by moon4869** [comment]
根据[教程](https://blog.csdn.net/wjinjie/article/details/108997692)的方法，修复了第三台服务器的显卡驱动问题，现在可以正常识别和使用了。但是第二台服务器因为无法识别到NVIDIA显卡，无法修复对应显卡驱动问题。

**Comment by duzx16** [comment]
应该是服务器本身存在的问题，跟本仓库无关
