### ISSUE TITLE
[BUG/Help] 多GPU部署模型依然报错ValueError: `checkpoint` should be the path to a file containing a whole state dict

### ISSUE THREAD

**Issue by guanlinz** [THUDM/ChatGLM-6B#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

完整报错如下：

```
[ec2-user@ip-172-31-10-203 ChatGLM-6B]$ python3 web_demo3.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.19s/it]
Traceback (most recent call last):
  File "web_demo3.py", line 7, in <module>
    model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=2)
  File "/home/ec2-user/ChatGLM-6B/chatglm_parallel.py", line 28, in load_model_on_gpus
    model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/big_modeling.py", line 486, in load_checkpoint_and_dispatch
    offload_buffers=offload_buffers,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 900, in load_checkpoint_in_model
    "`checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded "
ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint, but got THUDM/chatglm-6b.
```

web_app.py：
```
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
# from utils import load_model_on_gpus
from chatglm_parallel import load_model_on_gpus

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=4)
# model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
# model = model.eval()
```

load_model_on_gpus:
```
def load_model_on_gpus(checkpoint_path, num_gpus=2):
    # 总共占用13GB显存,28层transformer每层0.39GB左右
    # 第一层 word_embeddings和最后一层 lm_head 层各占用1.2GB左右
    num_trans_layers = 28
    vram_per_layer = 0.39
    average = 13/num_gpus
    used = 1.2
    device_map = {'transformer.word_embeddings': 0,
                  'transformer.final_layernorm': num_gpus-1, 'lm_head': num_gpus-1}
    gpu_target = 0
    for i in range(num_trans_layers):
        if used > average-vram_per_layer/2 and gpu_target < num_gpus:
            gpu_target += 1
            used = 0
        else:
            used += vram_per_layer
        device_map['transformer.layers.%d' % i] = gpu_target

    model = AutoModel.from_pretrained(
        checkpoint_path, trust_remote_code=True)
    model = model.eval()
    model = load_checkpoint_and_dispatch(
        model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
    return model
```

### Steps To Reproduce

- 根据github issue: https://github.com/ChuangLee/ChatGLM-6B-multiGPU/blob/main/chatglm_parallel.py 进行修改后，依然报错ValueError: `checkpoint` should be the path to a file containing a whole state dict

### Environment

```markdown
- OS: Amazon Linux 2 
- Python: 3.7
- Transformers: 4.27.1
- PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
[刚刚的commit](https://github.com/THUDM/ChatGLM-6B/commit/01e6313abf4122d789d6e68128856af52847b355)修复了，可以再试一下

**Comment by guanlinz** [comment]
Hi @duzx16 

感谢修复，但是问题依然存在。
```
[ec2-user@ip-172-31-10-203 ChatGLM-6B]$ python3 web_demo.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.20s/it]
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.19s/it]
Traceback (most recent call last):
  File "web_demo.py", line 7, in <module>
    model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=4)
  File "/home/ec2-user/ChatGLM-6B/utils.py", line 57, in load_model_on_gpus
    model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/big_modeling.py", line 486, in load_checkpoint_and_dispatch
    offload_buffers=offload_buffers,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 900, in load_checkpoint_in_model
    "`checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded "
ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint, but got THUDM/chatglm-6b.
```



我的web_demo.py 前几行:
```
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
from utils import load_model_on_gpus

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=4)
model = model.eval()
```


utils.py:
```
def load_model_on_gpus(checkpoint_path: Union[str, os.PathLike], num_gpus: int = 2,
                       device_map: Optional[Dict[str, int]] = None, **kwargs) -> Module:
    if num_gpus < 2 and device_map is None:
        model = AutoModel.from_pretrained(
            checkpoint_path, trust_remote_code=True, **kwargs).half().cuda()
    else:
        from accelerate import load_checkpoint_and_dispatch
        from accelerate import dispatch_model

        model = AutoModel.from_pretrained(
            checkpoint_path, trust_remote_code=True, **kwargs)
        model = model.eval()
        model = AutoModel.from_pretrained(
            checkpoint_path, trust_remote_code=True, **kwargs).half()

        if device_map is None:
            device_map = auto_configure_device_map(num_gpus)

        model = load_checkpoint_and_dispatch(
            model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
        model = dispatch_model(model, device_map=device_map)

    return model
```

**Comment by duzx16** [comment]
> Hi @duzx16
> 
> 感谢修复，但是问题依然存在。
> 
> ```
> [ec2-user@ip-172-31-10-203 ChatGLM-6B]$ python3 web_demo.py 
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.20s/it]
> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.19s/it]
> Traceback (most recent call last):
>   File "web_demo.py", line 7, in <module>
>     model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=4)
>   File "/home/ec2-user/ChatGLM-6B/utils.py", line 57, in load_model_on_gpus
>     model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/big_modeling.py", line 486, in load_checkpoint_and_dispatch
>     offload_buffers=offload_buffers,
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 900, in load_checkpoint_in_model
>     "`checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded "
> ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint, but got THUDM/chatglm-6b.
> ```
> 
> 我的web_demo.py 前几行:
> 
> ```
> from transformers import AutoModel, AutoTokenizer
> import gradio as gr
> import mdtex2html
> from utils import load_model_on_gpus
> 
> tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
> model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=4)
> model = model.eval()
> ```
> 
> utils.py:
> 
> ```
> def load_model_on_gpus(checkpoint_path: Union[str, os.PathLike], num_gpus: int = 2,
>                        device_map: Optional[Dict[str, int]] = None, **kwargs) -> Module:
>     if num_gpus < 2 and device_map is None:
>         model = AutoModel.from_pretrained(
>             checkpoint_path, trust_remote_code=True, **kwargs).half().cuda()
>     else:
>         from accelerate import load_checkpoint_and_dispatch
>         from accelerate import dispatch_model
> 
>         model = AutoModel.from_pretrained(
>             checkpoint_path, trust_remote_code=True, **kwargs)
>         model = model.eval()
>         model = AutoModel.from_pretrained(
>             checkpoint_path, trust_remote_code=True, **kwargs).half()
> 
>         if device_map is None:
>             device_map = auto_configure_device_map(num_gpus)
> 
>         model = load_checkpoint_and_dispatch(
>             model, checkpoint_path, device_map=device_map, offload_folder="offload", offload_state_dict=True).half()
>         model = dispatch_model(model, device_map=device_map)
> 
>     return model
> ```

你的 `utils.py` 的文件内容显然不太对
https://github.com/THUDM/ChatGLM-6B/blob/main/utils.py
