### ISSUE TITLE
[BUG/Help]如果token的限制提高到1万2万个汉字的话，会发生什么？

### ISSUE THREAD

**Issue by 19245222** [THUDM/ChatGLM-6B#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好，我的需求是根据大文本来提问的。但是目前大多数的模型，包括 gpt-3.5-tubo 和这个模型都有限制，请问大文本（1万以上的汉字）要选择什么模型呢？

### Steps To Reproduce

1

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
1
```

**Comment by digits122** [comment]
模型的训练内容就是2048，就算你修改让它支持更高的上限，但是它没有训练过，也不会给你更好的答案。要1w~2w字，按照1字≈1token，你唯一的选择只有用GPT4-32K才能满足要求。

**Comment by 19245222** [comment]
那么将模型的训练内容提高到1W～2W字这个做法可行吗？

**Comment by 19245222** [comment]
那么将模型的训练内容提高到1W～2W字这个做法可行吗？

> 模型的训练内容就是2048，就算你修改让它支持更高的上限，但是它没有训练过，也不会给你更好的答案。要1w~2w字，按照1字≈1token，你唯一的选择只有用GPT4-32K才能满足要求。

那么将模型的训练内容提高到1W～2W字这个做法可行吗？
