### ISSUE TITLE
[BUG/Help] <lm_head.weight权重>

### ISSUE THREAD

**Issue by 447428054** [THUDM/ChatGLM-6B#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

为什么模型加载时缺少该权重：lm_head.weight

@mojianhao @AdamBear @jsl9208 @cjld 

不在model.named_pamaters也不在model.named_buffers，这样的权重经过skip_init只有随机初始化，不进行梯度更新吗

### Expected Behavior

为什么模型加载时缺少该权重：lm_head.weight

不在model.named_pamaters也不在model.named_buffers，这样的权重经过skip_init只有随机初始化，不进行梯度更新吗

### Steps To Reproduce

1. 加载模型

### Environment

```markdown
- OS:linux
- Python:3.8
- Transformers:4.27
- PyTorch:1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
lm_head.weight 在 `pytorch_model-00008-of-00008.bin`。你可以手动加载这个文件看一下。

**Comment by 447428054** [comment]
> lm_head.weight 在 `pytorch_model-00008-of-00008.bin`。你可以手动加载这个文件看一下。

@duzx16 想问一下，我看lm_head是skip_init的方式初始化，这种方式并不会被添加到梯度更新的计算参数里面，这个原因是什么呀？这个不是最接近输出的地方嘛，不需要进行更新吗

**Comment by duzx16** [comment]
> > lm_head.weight 在 `pytorch_model-00008-of-00008.bin`。你可以手动加载这个文件看一下。
> 
> @duzx16 想问一下，我看lm_head是skip_init的方式初始化，这种方式并不会被添加到梯度更新的计算参数里面，这个原因是什么呀？这个不是最接近输出的地方嘛，不需要进行更新吗

skip_init 只是会跳过初始化来节约时间，跟梯度是否更新没有关系。https://pytorch.org/tutorials/prototype/skip_param_init.html

**Comment by 447428054** [comment]
> > > lm_head.weight 在 `pytorch_model-00008-of-00008.bin`。你可以手动加载这个文件看一下。
> > 
> > 
> > @duzx16 想问一下，我看lm_head是skip_init的方式初始化，这种方式并不会被添加到梯度更新的计算参数里面，这个原因是什么呀？这个不是最接近输出的地方嘛，不需要进行更新吗
> 
> skip_init 只是会跳过初始化来节约时间，跟梯度是否更新没有关系。https://pytorch.org/tutorials/prototype/skip_param_init.html

@duzx16 我是打印模型named_parameters和named_buffers发现都没有lm_head,查了一下lm_head也没有转成nn.Parameter，这样并不会添加到计算图中，不会参与梯度的更新。我是这样理解的哈～想问一下这块是不是这样的呢
