### ISSUE TITLE
[Help][Documentation Request] In class `InvalidScoreLogitsProcessor`, what's the meaning of tonken_id `5`?

### ISSUE THREAD

**Issue by pootow** [THUDM/ChatGLM-6B#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My model constantly rolling out token id 5, but I can't find any explanation of what token id 5 means.

And btw, what does `image token` mean? I can't find doc anywhere.

### Steps To Reproduce

1. go to file `modeling_chatglm.py`
2. at top of the file
3. you will find the class there.

### Environment

```markdown
Not relevant.
```

**Comment by pootow** [comment]
Oh! The `image token` will be used for multi-modal I guess!!

**Comment by duzx16** [comment]
It is the space token. We use the space token when the output contains `nan` value.

**Comment by pootow** [comment]
Thank you.
