### ISSUE TITLE
Finetune with LoRA

### ISSUE THREAD

**Issue by OedoSoldier** [THUDM/ChatGLM-6B#67]
参考 [LLaMA的LoRA](https://github.com/tloen/alpaca-lora)，如果能用 LoRA 来 finetune，硬件需求会大大减轻。

Finetune 整个 28 层 6B 的大模型，显存消耗太大了。

另外，具体的训练数据组织格式有无参考？

**Comment by OedoSoldier** [comment]
另外 hf 上的 `modeling_chatglm.py` 第 602 行处有误，会造成用 PEFT 训练 LoRA 时报错：
```
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'model_parallel'
```

**Comment by OedoSoldier** [comment]
> modeling_chatglm.py

https://huggingface.co/THUDM/chatglm-6b/blob/0d8b08d1bb16a486554bf1cf373fceb17b8f492e/modeling_chatglm.py#L613

是 613 行，应该是 `False`。

**Comment by duzx16** [comment]
> > modeling_chatglm.py
> 
> https://huggingface.co/THUDM/chatglm-6b/blob/0d8b08d1bb16a486554bf1cf373fceb17b8f492e/modeling_chatglm.py#L613
> 
> 是 613 行，应该是 `False`。

谢谢指出，已经修复了

**Comment by OedoSoldier** [comment]
我测试了直接使用 [LLaMA 的 LoRA 训练脚本](https://github.com/tloen/alpaca-lora/blob/main/finetune.py)，将 `target_modules=["q_proj", "v_proj"]` 改为 `target_modules=["query", "value"]` 即可。目前问题主要出现在 INT-8 量化，ChatGLM 的 INT-8 量化似乎和 (bitsandbytes)[https://github.com/TimDettmers/bitsandbytes] 的 INT-8 量化不兼容，只能以半精度来跑，显存消耗较大（4090跑不动）。

**Comment by ScottishFold007** [comment]
> 

长度多大，input和target各自的length？

**Comment by zhangzuizui** [comment]
> 我测试了直接使用 [LLaMA 的 LoRA 训练脚本](https://github.com/tloen/alpaca-lora/blob/main/finetune.py)，将 `target_modules=["q_proj", "v_proj"]` 改为 `target_modules=["query", "value"]` 即可。目前问题主要出现在 INT-8 量化，ChatGLM 的 INT-8 量化似乎和 [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) 的 INT-8 量化不兼容，只能以半精度来跑，显存消耗较大（4090跑不动）。
> 
> 修改后的设定：
> 
> ```
> tokenizer = AutoTokenizer.from_pretrained("chatglm-6b", trust_remote_code=True, add_eos_token=True)
> model = AutoModel.from_pretrained("chatglm-6b", trust_remote_code=True).half().cuda()
> 
> model = prepare_model_for_int8_training(model)
> 
> config = LoraConfig(
>     r=LORA_R,
>     lora_alpha=LORA_ALPHA,
>     target_modules=["query", "value"],
>     lora_dropout=LORA_DROPOUT,
>     bias="none",
>     task_type="CAUSAL_LM",
> )
> ```

这里有两个问题哈（不是特别确定，但我觉得你的设置不对）
target_modules似乎应该设置为["query_key_value"]？参考https://huggingface.co/THUDM/chatglm-6b/blob/0d8b08d1bb16a486554bf1cf373fceb17b8f492e/modeling_chatglm.py#L341
task_type应该是SEQ_2_SEQ_LM

**Comment by ScottishFold007** [comment]
目前peft只支持Seq2SeqLM、CausalLM，但glm2者都不是

**Comment by siriusctrl** [comment]
目前可以 inject LoRA 的 layers 应该是有四个地方，所以正确的应该是
```
config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=["query_key_value", "dense", "dense_h_to_4h", "dense_4h_to_h"],
    bias="none",
)
```
但是问题是，GLM 是 prefix LM，所有的开源工具对这种 LM 支持都非常差。而且 LLaMa finetune 的代码是直接对整个数据用 LM-loss 进行 finetune，但是实际上应该把 prompt 的部分的 Loss 变成 0

**Comment by ScottishFold007** [comment]
你这个能跑通吗？我跑得模型可以训练了，但是保存的时候出问题了



---Original---
From: "Xinyao (Morry) ***@***.***&gt;
Date: Fri, Mar 17, 2023 10:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [THUDM/ChatGLM-6B] Finetune with LoRA (Issue #67)




 
目前可以 inject LoRA 的 layers 应该是有四个地方，所以正确的应该是
 config = LoraConfig(     r=LORA_R,     lora_alpha=LORA_ALPHA,     lora_dropout=LORA_DROPOUT,     target_modules=["query_key_value", "dense", "dense_h_to_4h", "dense_4h_to_h"],     bias="none", )  
但是问题是，GLM 是 prefix LM，所有的开源工具对这种 LM 支持都非常差。而且 LLaMa finetune 的代码是直接对整个数据用 LM-loss 进行 finetune，但是实际上应该把 prompt 的部分的 Loss 变成 0

**Comment by siriusctrl** [comment]
> 你这个能跑通吗？我跑得模型可以训练了，但是保存的时候出问题了
> […](#)
> ---Original--- From: "Xinyao (Morry) ***@***.***&gt; Date: Fri, Mar 17, 2023 10:28 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [THUDM/ChatGLM-6B] Finetune with LoRA (Issue #67) 目前可以 inject LoRA 的 layers 应该是有四个地方，所以正确的应该是 config = LoraConfig( r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=LORA_DROPOUT, target_modules=["query_key_value", "dense", "dense_h_to_4h", "dense_4h_to_h"], bias="none", ) 但是问题是，GLM 是 prefix LM，所有的开源工具对这种 LM 支持都非常差。而且 LLaMa finetune 的代码是直接对整个数据用 LM-loss 进行 finetune，但是实际上应该把 prompt 的部分的 Loss 变成 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以跑通，需要 hack 一下 Trainer 里面的 loss calculation，我并不确定我写的是正确的

**Comment by nlp4whp** [comment]
> 目前peft只支持Seq2SeqLM、CausalLM，但glm2者都不是

https://github.com/mymusise/ChatGLM-Tuning 这个项目的作者给peft提了PR支持glm：https://github.com/huggingface/peft/pull/180/commits

貌似就是给`TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING`加上chatglm

**Comment by yuanzhoulvpi2017** [comment]
目前，我这边是这么做的：
```python
peft_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM, 
    inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
    target_modules=['query_key_value', 'dense','dense_h_to_4h','dense_4h_to_h']
)
model = get_peft_model(model, peft_config)
accelerator.print(model.print_trainable_parameters())
```
本质上是使用lora来替换linear层。

但是我现在遇到的问题是，模型精度没对齐。奇怪

**Comment by js0316** [comment]
> 目前，我这边是这么做的：
> 
> ```python
> peft_config = LoraConfig(
>     task_type=TaskType.SEQ_2_SEQ_LM, 
>     inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
>     target_modules=['query_key_value', 'dense','dense_h_to_4h','dense_4h_to_h']
> )
> model = get_peft_model(model, peft_config)
> accelerator.print(model.print_trainable_parameters())
> ```
> 
> 本质上是使用lora来替换linear层。
> 
> 但是我现在遇到的问题是，模型精度没对齐。奇怪
> 
> ```shell
> RuntimeError: expected scalar type Half but found Float
> ```

请问目前这个如何解决的呢？

**Comment by zhangzuizui** [comment]
> 



> 目前，我这边是这么做的：
> 
> ```python
> peft_config = LoraConfig(
>     task_type=TaskType.SEQ_2_SEQ_LM, 
>     inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
>     target_modules=['query_key_value', 'dense','dense_h_to_4h','dense_4h_to_h']
> )
> model = get_peft_model(model, peft_config)
> accelerator.print(model.print_trainable_parameters())
> ```
> 
> 本质上是使用lora来替换linear层。
> 
> 但是我现在遇到的问题是，模型精度没对齐。奇怪
> 
> ```shell
> RuntimeError: expected scalar type Half but found Float
> ```

target_modules太多会导致模型很难收敛
这个repo以及把lora的finetune调通了，亲测可行，建议参考https://github.com/mymusise/ChatGLM-Tuning

**Comment by terrifyzhao** [comment]
> 

你好，你的nan问题还存在吗

**Comment by yuanzhoulvpi2017** [comment]
> > 
> 
> 你好，你的nan问题还存在吗

已经更新了，很久直接就可以了。

**Comment by PopRangR** [comment]
可以尝试把pre_seq_len这个参数调小一点，learning_rate也调小一点，并且我没有用量化

**Comment by PopRangR** [comment]
大佬们，有咩有针对6b-int4的lora微调方案，机器显存就8g
