### ISSUE TITLE
[BUG/Help] 请问量化示例中为什么先进行quantize再进行half？

### ISSUE THREAD

**Issue by xingchensong** [THUDM/ChatGLM-6B#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```py
# 按需修改，目前只支持 4/8 bit 量化
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).quantize(8).half().cuda()
```

在官方给定的量化示例代码中，先执行了quantize(8)再执行half()，按照正常的逻辑是否应该反过来，先half再quant？

另外有个现象：先quant再half的话，显存占用上看倒是符合预期，但是推理速度上int8会显著慢于fp16，不知道会不会和上面这个潜在问题有关？

### Steps To Reproduce

None

### Environment

```markdown
None
```

**Comment by duzx16** [comment]
其实没什么区别，权重矩阵默认的精度就是 fp16 的。.half() 是为了转换 LayerNorm的参数。量化之后权重矩阵已经转换成 INT8 类型了，INT8 类型的 tensor 是不会被转换成 half的
