### ISSUE TITLE
请问模型有没有单独可修改的embeddings层，或者我能不能把pre-embedded的数据传入模型？

### ISSUE THREAD

**Issue by zhangchi-thu** [THUDM/ChatGLM-6B#672]
### Is your feature request related to a problem? Please describe.

我希望把一些已经pre-embedded的数据传入模型的来进行训练（不用模型的embedding layer）， 请问有什么方法吗？非常感谢！

### Solutions

希望能有一个方法来调整模型的embedding layer或者绕过embedding layer直接传入数据

**Comment by duzx16** [comment]
传 `input_embeds` 就行
