### ISSUE TITLE
预计何时发布 chatglm 13B

### ISSUE THREAD

**Issue by doublexxking** [THUDM/ChatGLM-6B#673]
现在10B以上的模型越来越多，在上下文理解，英文理解方面chatglm 6B相对较弱，是否可以发布13B模型增加中文大语言模型能力？

**Comment by liaoweiguo** [comment]
只有130B，个人玩不动的

**Comment by doublexxking** [comment]
那个是基础模型，看看有没有计划发布chatglm 13b

**Comment by ZanoZ** [comment]
可以计算一下，单机运行，最合适的多少B的，取效率和性能最佳点。
不会就是6B吧？这个性能弱了点
