### ISSUE TITLE
[BUG/Help] <title>Windows环境下使用GPU加载INT-4模型报错

### ISSUE THREAD

**Issue by OathK1per** [THUDM/ChatGLM-6B#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No compiled kernel found.
Compiling kernels : C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.c -shared -o C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.so
e:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels.c -shared -o C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels.so
Load default cpu kernel failed:
Traceback (most recent call last):
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm\quantization.py", line 167, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Failed to load kernel.
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
No compiled kernel found.
Compiling kernels : C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.c -shared -o C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels_parallel.so
e:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels.c -shared -o C:\Users\admin\.cache\huggingface\modules\transformers_modules\chatglm\quantization_kernels.so
Load default cpu kernel failed:
Traceback (most recent call last):
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm\quantization.py", line 167, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Failed to load kernel.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm\modeling_chatglm.py", line 1430, in quantize
    load_cpu_kernel(**kwargs)
  File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\chatglm\quantization.py", line 430, in load_cpu_kernel
    assert cpu_kernels.load
AssertionError

### Steps To Reproduce

Windows环境下使用GPU加载INT-4模型，前面顺利，使用MingW下载的gcc，无法编译quantization_kernels_parallel

### Environment

```markdown
- OS:Windows10
- Python:3.10.10
- Transformers:4.27.1
- PyTorch:2.0.0+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by zx2021** [comment]
你是不是windows10 32bit的系统？

**Comment by ZhangErling** [comment]
可以换一种部署方式WSL [Windows部署文档](https://github.com/ZhangErling/ChatGLM-6B/blob/main/deployment_windows.md)

**Comment by AllenXiao95** [comment]
同样遇到这个问题，卡了很久，请问题主是使用了lpthread解决的么？
Environment
```
- OS:Windows11
- Python:3.9.0
- Transformers:4.26.1
- PyTorch:2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
- ```
