### ISSUE TITLE
[Feature] <如何能够增加输入的最大长度>

### ISSUE THREAD

**Issue by EasyLuck** [THUDM/ChatGLM-6B#678]
### Is your feature request related to a problem? Please describe.

您好，请问如何能够增加输入的最大长度，现在最大是2048，在算力允许的情况下，如何能够增加这个最大的输出长度限制呢？
期待您的回复，感谢。

### Solutions

您好，请问如何能够增加输入的最大长度，现在最大是2048，在算力允许的情况下，如何能够增加这个最大的输出长度限制呢？
期待您的回复，感谢。

### Additional context

您好，请问如何能够增加输入的最大长度，现在最大是2048，在算力允许的情况下，如何能够增加这个最大的输出长度限制呢？
期待您的回复，感谢。

**Comment by zhangch9** [comment]
可以在调用`model.chat`的时候设置更大的`max_length`，参考[#17](https://github.com/THUDM/ChatGLM-6B/issues/17)
