### ISSUE TITLE
[BUG/Help] Model generates mixture of English and Chinese when it should only respond in English

### ISSUE THREAD

**Issue by NotNANtoN** [THUDM/ChatGLM-6B#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When loading `THUDM/chatglm-6b-int8` or `THUDM/chatglm-6b-int4`, I regularly get outputs like these: 

`
![image](https://user-images.githubusercontent.com/19983153/232739610-79ae3060-10ca-485f-88ac-da9109016834.png)
`

The output is great, but is there any way to restrict the model to only generate in English? This way it is not really usable, as this mixing of languages seems to happen quite often. Maybe there is a way to restrict the tokens the model can use?

I would appreciate any help!

### Expected Behavior

Generation in either English when the question/chat is in English.

### Steps To Reproduce

1. Load the int4 or int8 model
2. Ask questions
3. Model will regularly include Chinese characters in the answer

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8
- Transformers: 4.28.1
- PyTorch: 2.0.0+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by youyanghust** [comment]
+1
