### ISSUE TITLE
[Feature] <关于api调用的上下文问题>求教，如果是调用api的话，是不是要将每一次的对话保存下来并通过history传输过去？

### ISSUE THREAD

**Issue by davidfrz** [THUDM/ChatGLM-6B#684]
### Solutions

求教，如果是调用api的话，是不是要将每一次的对话保存下来并通过history传输过去？

**Comment by lineng-hao-jie** [comment]
首次会话，history=[],以后的每次都将上一次response中history取出，与本次一起作为参数传入即可：
<img width="520" alt="1682089846609" src="https://user-images.githubusercontent.com/58200403/233671832-959eb469-e864-47d8-8179-8a1603701072.png">

**Comment by davidfrz** [comment]
> 首次会话，history=[],以后的每次都将上一次response中history取出，与本次一起作为参数传入即可： <img alt="1682089846609" width="520" src="https://user-images.githubusercontent.com/58200403/233671832-959eb469-e864-47d8-8179-8a1603701072.png">

哦哦 谢谢~
