### ISSUE TITLE
colab内存爆了，显卡没动静

### ISSUE THREAD

**Issue by myrzx** [THUDM/ChatGLM-6B#69]
![image](https://user-images.githubusercontent.com/45350198/225314022-2a76f18c-692a-4c32-a52f-2a97d5a37e9a.png)

**Comment by Brx86** [comment]
上午我就试了，colab内存不够跑不起来，也没法加swapfile。在本地运行的时候启动时最好留有20G空闲内存（加swap也行），不过启动后正常运行的占用内存降到几G的样子

**Comment by digits122** [comment]
电脑16G内存才能正常使用，8G就会爆内存，明明运行起来只占用6G不到显存，加载时却消耗了过量的内存，现在只能用swap空间来解决

**Comment by Xiaobin2333** [comment]
![image](https://user-images.githubusercontent.com/59763071/225419672-cd5a8b26-9a90-4694-84a5-38a9c1396a43.png)
我尝试使用了按块加载的方法，系统内存没爆，GPU内存爆了。

**Comment by evshiron** [comment]
可以自行修改`web_demo.py`以达到在colab中运行的效果。

这是一个可以正常使用的colab链接：

https://colab.research.google.com/drive/1S8w0pbOsUHU1JqJzoWQKNgvG6HBwbI6c#scrollTo=rASYNo8CxFlK

在我的使用过程中，回复速度在30-40s以上，内存占用在7.7G，显存占用维持在12.7G，超过20条消息后达到13.8G，属于一个能用的状态。`quantize()`和`cuda()`因为报错已经移除。

至于如何进一步优化占用或榨取性能，请调整`device_map`中的值，`0`代表在GPU上运行，`cpu`代表在CPU上运行，`disk`将offload到本地存储中。

参考文档：
* https://huggingface.co/docs/accelerate/usage_guides/big_modeling
* https://github.com/THUDM/ChatGLM-6B#%E6%A8%A1%E5%9E%8B%E9%87%8F%E5%8C%96

PS: 感觉傻乎乎的。

**Comment by younggggger** [comment]
> 可以自行修改`web_demo.py`以达到在colab中运行的效果。
> 
> 这是一个可以正常使用的colab链接：
> 
> https://colab.research.google.com/drive/1S8w0pbOsUHU1JqJzoWQKNgvG6HBwbI6c#scrollTo=rASYNo8CxFlK
> 
> 在我的使用过程中，回复速度在30-40s以上，内存占用在7.7G，显存占用维持在12.7G，超过20条消息后达到13.8G，属于一个能用的状态。`quantize()`和`cuda()`因为报错已经移除。
> 
> 至于如何进一步优化占用或榨取性能，请调整`device_map`中的值，`0`代表在GPU上运行，`cpu`代表在CPU上运行，`disk`将offload到本地存储中。
> 
> 参考文档：
> 
> * https://huggingface.co/docs/accelerate/usage_guides/big_modeling
> * https://github.com/THUDM/ChatGLM-6B#%E6%A8%A1%E5%9E%8B%E9%87%8F%E5%8C%96
> 
> PS: 感觉傻乎乎的。
我在本地运行，提示    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

我显卡驱动 nvidia cuda 11.4,安装了conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
cuda_11.4.3_472.50_win10.exe和cudnn-11.4-windows-x64-v8.2.2.26.zip

**Comment by evshiron** [comment]
我没在本地跑过，爱莫能助。

**Comment by duzx16** [comment]
如果内存不够的话，可以加载量化后的模型`THUDM/chatglm-6b-int4`

**Comment by younggggger** [comment]
> 爱莫能助。

colab上跑起来了，但回答问题好久不出来

**Comment by evshiron** [comment]
@younggggger  修好了，之前被我改坏了。现在换成了量化后的模型，不会炸内存，显存也充裕了，回复速度在10s左右。原版模型在注释里，感兴趣也可以拿出来玩玩。

**Comment by younggggger** [comment]
> @younggggger 修好了，之前被我改坏了。现在换成了量化后的模型，不会炸内存，显存也充裕了，回复速度在10s左右。原版模型在注释里，感兴趣也可以拿出来玩玩。

可以了，谢谢啊，简单玩了下：


用户：写出10以内的质数

ChatGLM-6B：10以内的质数有2、3、5、7、11、13、17、19、23、29、31、37、41、43、47、53、59、61、67、71、73、79和83。

用户：写错了

ChatGLM-6B：非常抱歉,我的回答有误。10以内的质数是2、3、5、7、11、13、17、19、23、29、31、37、41、43、47、53、59、61、67、71、73、79和83。再次感谢您的指正。

用户：这是100以内的，不是10以内

ChatGLM-6B：非常抱歉,我的回答又有误。100以内的质数有2、3、5、7、11、13、17、19、23、29、31、37、41、43、47、53、59、61、67、71、73、79、83、89和101。再次感谢您的指正。

**Comment by LiuZhenyan-Wuzhong** [comment]
我采用的 quantize(4)  有人知道显存为什么一直是0吗?
![image](https://user-images.githubusercontent.com/56421773/227878411-6fd0cff5-9fc3-4aaf-930c-881aa197c2d7.png)
