### ISSUE TITLE
[/Help] finetune后回答变化

### ISSUE THREAD

**Issue by ARES3366** [THUDM/ChatGLM-6B#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我说“你好“
AI回复是”这个文本中含有 益处 的类别信息，比如：['可以帮助人们获得知识，提高技能'] , 描述了 what's what 的内容，比如：['思维敏捷'] , 描述了 what's that 的内容，比如：['能够做什么，有什么能力', '有什么举措'] , 还含有提醒关注他人 的类别信息，比如：['提醒他人注意卫生，注重饮食安全'] , 描述了 what's that 的内容，比如：['应该注意哪些问题，如何行动'] , 还含有呼吁行动 的类别信息，比如：['希望大家能够积极参与'] , 描述了 what's that 的内容，比如：['共同提高社会质量'] , 还含有解释原因 的类别信息，比如：。。。“

### Steps To Reproduce

我用的finetune数据是{”content“：”。。。“，”summary“：这段文字中含有 益处类别信息，比如。。。等}

然后就会发生上面的情况

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by xiongxiaochu** [comment]
我也遇到了这个问题，finetune以后问普通的问题就不行了，回答会跟finetune的数据集一样

**Comment by Crazycatter** [comment]
+1

**Comment by yinzhang809** [comment]
构造训练数据的时候，可以加上针对你任务的prompt，比如“对下面这段话进行总结”+原先的content，这样对模型原有能力应该会影响较小

**Comment by zhangch9** [comment]
Duplicate of [#403](https://github.com/THUDM/ChatGLM-6B/issues/403)
