### ISSUE TITLE
ptuning之后api预测

### ISSUE THREAD

**Issue by ZTurboX** [THUDM/ChatGLM-6B#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ptuning-v2微调之后模型是只保存 PrefixEncoder 部分的参数？用api.py预测是要加载原 ChatGLM-6B 模型以及 微调后的权重吗？我用以下代码加载权重，有报错
![image](https://user-images.githubusercontent.com/5669444/232971443-9a0bf8ef-a6db-4a18-bfca-502ca04268c6.png)
![image](https://user-images.githubusercontent.com/5669444/232971476-f968b415-54cf-4719-b98d-8a5f06a2867b.png)

### Steps To Reproduce

ptuning-v2微调之后模型是只保存 PrefixEncoder 部分的参数？用api.py预测是要加载原 ChatGLM-6B 模型以及 微调后的权重吗？我用以下代码加载权重，有报错
![image](https://user-images.githubusercontent.com/5669444/232971443-9a0bf8ef-a6db-4a18-bfca-502ca04268c6.png)
![image](https://user-images.githubusercontent.com/5669444/232971476-f968b415-54cf-4719-b98d-8a5f06a2867b.png)

### Environment

```markdown
- OS:centos 7
- Python:3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by derekzhuo** [comment]
我也有类似的问题，用新的数据（只有一条kv数据）
加载生成的prefix_encoder数据后，原来模型的对话能力丢失了，不知道如何解决。

**Comment by xiongxiaochu** [comment]
> 

请问您加载的时候有遇到“Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']”这个问题吗？

**Comment by duzx16** [comment]
> > 
> 
> 请问您加载的时候有遇到“Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']”这个问题吗？

这是个 warning，可以忽略，后续这个参数会单独加载
