### ISSUE TITLE
请问怎么构建属于自己的数据集，或者CLM可以训练的数据集

### ISSUE THREAD

**Issue by PopRangR** [THUDM/ChatGLM-6B#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

自己按照官方提供的数据集格式，编写了十几条问答数据训练完成之后一点效果没有，想问问大家是怎么实现的

### Steps To Reproduce

自己按照官方提供的数据集格式，编写了十几条问答数据训练完成之后一点效果没有，想问问大家是怎么实现的

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by chenyiwan** [comment]
步数不够。

**Comment by PopRangR** [comment]
> 

请问步数不够是啥意思，是数据太少吗

**Comment by PopRangR** [comment]
> 步数不够。

请问步骤数不够是啥意思，是数据太少吗

**Comment by ysun** [comment]
你好，我是AI小白，也正在研究这些。
求教，有啥官方的文档，可以指导我训练自己的模型。大概做成一个私有的数据集，公司内部数据。

**Comment by PopRangR** [comment]
> > > 步数不够。
> > 
> > 
> > 请问步骤数不够是什么意思，是数据太少吗
> 
> 这种类型的模型训练时，一般都是多少步后保存1次“保存档”或“成绩”到多少后，保存保存档并退出训练。进行推理 。
> 
> **可以理解为数据太少。**

好的，谢谢，请问目前有没有除了 ADGEN 数据集还有别的数据集可以跑的

**Comment by PopRangR** [comment]
> 你好，我是AI小白，也在研究这些。 求教，有什么官方的文档，可以指导我训练自己的模型。大概念做一个私有的数据集，公司满意。

我也刚接触，不是很清楚

**Comment by fireice009** [comment]
> 你好，我是AI小白，也正在研究这些。 求教，有啥官方的文档，可以指导我训练自己的模型。大概做成一个私有的数据集，公司内部数据。

https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning

**Comment by eeric** [comment]
@ysun 
大家有办法创造自己的私有训练集吗？

**Comment by lucifer1004** [comment]
就参考 ADGEN 的格式（一个 JSON 数组，每个记录包含至少一个 Q 字段和一个 A 字段，字段名可以自定义）做就行。但对数量还是有一定的要求。太少了肯定不行。

**Comment by eeric** [comment]
是的，如果能有自动从文本中生成准确的问答，将是更好的方法。

**Comment by zhangch9** [comment]
可参考[#330](https://github.com/THUDM/ChatGLM-6B/issues/330)中提到的方法。

**Comment by SERE026** [comment]
怎么训练自己的模型，而不是微调？
建立私有数据集进行训练，针对特殊场景
