### ISSUE TITLE
我想做这样一件事，不知道是否可以

### ISSUE THREAD

**Issue by chenyiwan** [THUDM/ChatGLM-6B#698]
### Is your feature request related to a problem? Please describe.

我们现在用这个模型做基础模型，训练自己的知识，这就是微调。

同时我想让它忘记原有的内容，相当于清空他的记忆，只回答我微调的内容 ，其它的都说：不清楚或不知道等等。。

大佬们，有没有方案？

### Solutions

我们现在用这个模型做基础模型，训练自己的知识，这就是微调。

同时我想让它忘记原有的内容，相当于清空他的记忆，只回答我微调的内容 ，其它的都说：不清楚或不知道等等。。

大佬们，有没有方案？

**Comment by chenyiwan** [comment]
想过通过过滤问题的方式，在上层应用添加一个过滤器，非微调数据，就直接返回，但感觉太low了。。

**Comment by AlexLiu-C** [comment]
直接把这个需求在每次发送请求的时候都发给他呢? 虽然这样比你的想法更low一些.

**Comment by derekzhuo** [comment]
我是训练完，原来能work的prompt都不能work了

**Comment by starplatinum3** [comment]
请问这个过滤器怎么做呀，也是一个文本处理的，感觉很难，还是只是单纯的过滤一些关键词呀
