### ISSUE TITLE
[BUG/Help]  Mac M设备上通过 quantize(8) 调整精度时报错：AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by exp-sky** [THUDM/ChatGLM-6B#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi 目前在Mac M设备上直接调用没有问题。
model = AutoModel.from_pretrained(model_dir_path, trust_remote_code=True).half().to('mps')

但如果降低精度的话，如下代码会报错。
model = AutoModel.from_pretrained(model_dir_path, trust_remote_code=True).quantize(8).half().to('mps')

raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

简单看了一下，应该是如下两个文件中对quantize功能相关的代码存在兼容性问题？
chatglm-6b/modeling_chatglm.py
chatglm-6b/quantization.py

### Steps To Reproduce

1.mac OS M设备
2.调用示例代码
tokenizer = AutoTokenizer.from_pretrained(model_dir_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_dir_path, trust_remote_code=True).quantize(8).half().to('mps')

### Environment

```markdown
- OS:macOS 13.3.1
- Python:3.11.3
- Transformers:4.28.1
- PyTorch:2.1.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :mac M设备是False
```

**Comment by duzx16** [comment]
MPS 后端不支持量化，因为量化的 kernel 是用 CUDA 写的
