### ISSUE TITLE
[BUG/Help] <Something went wrong Expecting value: line 1 column 1 (char 0)>

### ISSUE THREAD

**Issue by CodingSha** [THUDM/ChatGLM-6B#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用web_demo.py将页面跑起来之后，进页面输入文字，点发送之后，报了这个错误
Something went wrong
Expecting value: line 1 column 1 (char 0)

### Steps To Reproduce

使用web_demo.py将页面跑起来之后，进页面输入文字，点发送之后，报了这个错误
Something went wrong
Expecting value: line 1 column 1 (char 0)

### Environment

```markdown
- OS:ubuntu 22.04
- Python:3.10。10
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.7
```

**Comment by CodingSha** [comment]
好的，我试试，感谢

**Comment by LuckyLee333** [comment]
你好，你的问题解决了吗？我也是这个问题，把翻墙关了也没用。服务器的翻墙也要关了吗？

**Comment by mark342703702** [comment]
我也是这个问题

**Comment by 15klli** [comment]
> 你好，你的问题解决了吗？我也是这个问题，把翻墙关了也没用。服务器的翻墙也要关了吗？

是的，我也是服务器配置了http_proxy/https_proxy，导致我报错，关了之后就行了

**Comment by kobeng** [comment]
unset http_proxy 
unset https_porxy 
一样报错 请问大家如何解决呢？
