### ISSUE TITLE
webui出现一直在推理的状态，即使回答完成也不出现输入框[BUG/Help] <title>

### ISSUE THREAD

**Issue by elcky** [THUDM/ChatGLM-6B#706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/42209617/233085525-b5cbdf70-8b55-4efe-b341-ce55ff55c7e6.png)

### Steps To Reproduce

1. python env
2. pip install -r requirement.txt
3. share=true

### Environment

```markdown
- OS:ubuntu-22.04.2-live-server-amd64
- Python:3.10.6
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
显示是在 `queue`，也就是这个命令根本没有发送给后端去计算而是在排队。应该是网络问题。
