### ISSUE TITLE
PRE_SEQ_LEN参数是什么含义

### ISSUE THREAD

**Issue by ZTurboX** [THUDM/ChatGLM-6B#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PRE_SEQ_LEN参数是什么含义，如何根据自己的数据调整？

### Expected Behavior

PRE_SEQ_LEN参数是什么含义，如何根据自己的数据调整？

### Steps To Reproduce

PRE_SEQ_LEN参数是什么含义，如何根据自己的数据调整？

### Environment

```markdown
- OS:centos7
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by michelleqyhqyh** [comment]
+1

**Comment by duzx16** [comment]
P-Tuning的时候的 soft prompt的长度，越大可微调的参数越多
