### ISSUE TITLE
显存占用增加

### ISSUE THREAD

**Issue by ai25395** [THUDM/ChatGLM-6B#71]
每次对话显存占用都会增加几百Mb，请问除了重启程序有别的解决办法吗？

**Comment by skirodev** [comment]
Don't pass historical dialogue information.
```
model.chat(tokenizer, input, history=[])
```

**Comment by ai25395** [comment]
谢谢，我明白了，history的增加会导致显存占用增加，不过history也是ai理解上下文的能力的来源吧。看来可以根据初始的可用显存量，设置history的maxSize，这样既保留一定的上下文能力，又防止显存不够用。
