### ISSUE TITLE
[BUG/Help] ptuning微调无法运行，显示没有numpy库

### ISSUE THREAD

**Issue by MrJungleMonkey** [THUDM/ChatGLM-6B#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在pycharm中运行train.sh或在shell中bash train.sh，获得如下错误信息：

PS E:\ChatGLM-6B-main_v230419\ptuning> bash train.sh
Traceback (most recent call last):
  File "/mnt/e/ChatGLM-6B-main_v230419/ptuning/main.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

但我的环境中已经安装有numpy，检查未发现异常。
请问问题可能出在哪里？

### Expected Behavior

运行微调代码

### Steps To Reproduce

pycharm下尝试：
1.下载安装GLM-6B代码包并在pycharm打开，配置解释器为python3.9，根据README.md、requirements.txt和ptuning\README.md要求安装所需环境。
2.参数无改动。
3.运行‘train.sh’
4.终端无输出，路径下无output。

shell中尝试：
1.先前在上述步骤中，已安装好环境。
2.参数无改动。
3.bash train.sh
4.输出错误信息：“
PS E:\ChatGLM-6B-main_v230419\ptuning> bash train.sh
Traceback (most recent call last):
  File "/mnt/e/ChatGLM-6B-main_v230419/ptuning/main.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
”

### Environment

```markdown
- OS:windows10
- Python:3.9.13
- Transformers:4.27.1
- PyTorch:torch==1.13.1+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by MrJungleMonkey** [comment]
#653 has solved.

**Comment by 11sarac** [comment]
请问是如何解决的？

**Comment by zzzzzling** [comment]
您好，最后是怎么解决这个问题的

**Comment by zzzzzling** [comment]
> 您好，最后是怎么解决这个问题的

解决了，我是用git环境运行的train.sh，没有在git中激活conda环境，激活conda环境，在配置了numpy的虚拟环境中运行tranin.sh就行了
