### ISSUE TITLE
[BUG/Help] stream_chat接口中max_new_tokens相关报错

### ISSUE THREAD

**Issue by wpydcr** [THUDM/ChatGLM-6B#717]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

在对话时，如果长度超过设定的Maximum length，就会报如下错误：
Input length of input_ids is 138, but `max_length` is set to 118. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

后续会直接报错无法继续使用

### Expected Behavior

超出长度能否截断输出，使用“继续”来续接

### Steps To Reproduce

使用web_demo.py脚本

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by JasonChenJC** [comment]
同样问题，请问解决了吗

**Comment by yxdroid** [comment]
亲,您的邮件已收到!

**Comment by zhangch9** [comment]
可以参考[#17](https://github.com/THUDM/ChatGLM-6B/issues/17)增大`stream_chat`中的`max_length`参数。

**Comment by yxdroid** [comment]
亲,您的邮件已收到!
