### ISSUE TITLE
通过ptuning微调参数加载checkpoint后，推理逻辑不对了

### ISSUE THREAD

**Issue by guarx** [THUDM/ChatGLM-6B#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5118509/233276811-80de2e84-a82c-4e33-9502-f3499c382bc4.png)
这个是不是有问题呢，
加载训练完后的checkpoint后，之前的推理逻辑都没了，这是加载训练checkpoint的代码
![image](https://user-images.githubusercontent.com/5118509/233278042-22c07ba0-46fb-4ef9-b595-30ca9f2171de.png)
这个结果明显不对啊
![image](https://user-images.githubusercontent.com/5118509/233278636-3b93e6c5-5a14-4532-b4bd-254312a1fbf7.png)
训练用的json就是文档里的

### Steps To Reproduce

1. bash ptuning/train.sh
2. bash ptuning/evaluate.sh
3. streamlit run web_demo2.py --server.port 6006

### Environment

```markdown
- OS: ubuntu
- Python: 3.8
- Transformers: 4.27
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by liaoweiguo** [comment]
同样的问题。

感觉这个模型根本不能调

**Comment by waveboy800** [comment]
我的是微调完后只能回答喵喵了

**Comment by sun1092469590** [comment]
> 我的是微调完后只能回答喵喵了

你好，问一下哈，你的微调训练参数有自己调整吗？我的微调完推理时答复是空的，并且推理速度特别慢

**Comment by waveboy800** [comment]
没有

**Comment by xmlv** [comment]
我也遇到了，ptuning v2调过之后就变傻子了。

**Comment by zhangch9** [comment]
Duplicate of [#403](https://github.com/THUDM/ChatGLM-6B/issues/403)
