### ISSUE TITLE
centos上，2个12g显存的显卡如何配置可以同时使用

### ISSUE THREAD

**Issue by feingto** [THUDM/ChatGLM-6B#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

centos上，2个12g显存的显卡，无论是训练还是web，都始终用0号显卡，如何配置可以同时使用

### Steps To Reproduce

Centos7
12G nvida *2

### Environment

```markdown
- OS:Centos7
- Python:3.8
- Transformers:4.26.1
- PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
推理请参考 https://github.com/THUDM/ChatGLM-6B#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2
训练修改 `train.sh` 里面的 `CUDA_VISIBLE_DEVICES` 就行了
