### ISSUE TITLE
[Help] <流式和非流式接口的原理是什么？>

### ISSUE THREAD

**Issue by LebronJames0423** [THUDM/ChatGLM-6B#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问下chat和stream_chat接口在原理上有哪些区别啊？

### Steps To Reproduce

null

### Environment

```markdown
- OS:
- Python:Python: 3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
`chat` 会直接返回最终的生成结果，`stream_chat` 会每生成一个 token 就返回一次，用于实现流式的生成效果

**Comment by LebronJames0423** [comment]
> `chat` 会直接返回最终的生成结果，`stream_chat` 会每生成一个 token 就返回一次，用于实现流式的生成效果

相同的输入，如果入参完全一样的话，生成的内容没有区别是吧，不考虑temperature的影响的话
