### ISSUE TITLE
[Help] <请问chatglm-6b有公开完整的训练代码吗？>

### ISSUE THREAD

**Issue by LebronJames0423** [THUDM/ChatGLM-6B#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问chatglm-6b有公开完整的训练代码吗？而不只是微调的代码？
麻烦解答一下，多谢

### Steps To Reproduce

null

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by mason0510** [comment]
应该没有吧

**Comment by chenyiwan** [comment]
科研成果，不太可能免费开放的。

**Comment by zhuchangjiang** [comment]
同问同求

**Comment by Dragonkingpan** [comment]
给你代码也没用，你没数据，没机器。要站在巨人的肩膀上做事

**Comment by gg22mm** [comment]
微调不能满足吗？

**Comment by 15559003770** [comment]
Transformer？

**Comment by tomcat123a** [comment]
https://github.com/shibing624/MedicalGPT
参考这个项目，预训练，指令微调，rm模型训练，ppo都有现成的

**Comment by zhangch9** [comment]
Duplicate of [#3](https://github.com/THUDM/ChatGLM-6B/issues/3)
