### ISSUE TITLE
[Feature] 有使用一站式微调整训练的吗？

### ISSUE THREAD

**Issue by ZXStudio** [THUDM/ChatGLM-6B#735]
### Is your feature request related to a problem? Please describe.

训练出来的模型可以在训练环境下运行，但无法在标准环境运行。

发生异常: TypeError
argument of type 'WindowsPath' is not iterable
  File "D:\GLM\web_demo.py", line 4, in <module>
    from peft import PeftModel
TypeError: argument of type 'WindowsPath' is not iterable

[https://www.bilibili.com/video/BV1P24y1L7Ge/?spm_id_from=333.880.my_history.page.click&vd_source=82be2a599d5b9b5e4cbfb0c33798b71d](url)

**Comment by littlestone0806** [comment]
整合包作者来了，因为当时我整合时，bitsandbytes这个库，我替换了一些东西，因为不替换的话，bitsandbytes只支持linux，不支持windows，就会出现上述错误。解决办法就是，把我的整合包里的env\Lib\site-packages\bitsandbytes全部替换你的python环境的bitsandbytes包
