### ISSUE TITLE
用deepspeed方式返回错误码-9 啥意思

### ISSUE THREAD

**Issue by guarx** [THUDM/ChatGLM-6B#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5118509/233330566-86d81520-c5f5-4015-908c-a652195ec344.png)

### Steps To Reproduce

./ds_train_finetune.sh

### Environment

```markdown
- OS:ubuntu
- Python:3.8
- Transformers:4.27.1
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
内存占用过大被操作系统 kill 了，或者被其他用户手动 kill 了

**Comment by guarx** [comment]
> 内存占用过大被操作系统 kill 了，或者被其他用户手动 kill 了

收到，嗯应该是显存不够，谢谢
