### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by chaomowangshen** [THUDM/ChatGLM-6B#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

量化模型int-4运行以后报错，显示assert vocab_file is not None，有什么解决方法吗

### Expected Behavior

怎么解决呢

### Steps To Reproduce

assert vocab_file is not None

### Environment

```markdown
- OS:'Windows-10-10.0.22621-SP0'
- Python:3.10
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :12.1
```

**Comment by duzx16** [comment]
应该是你本地的路径里没有 `ice_text.model`

**Comment by xxAkuya** [comment]
我这个文件是有的，但是只能运行一次，运行第二次就找不到了
很奇怪

**Comment by xiaocao-226934** [comment]
> 我这个文件是有的，但是只能运行一次，运行第二次就找不到了 很奇怪

解决了吗，我也遇到了一样的问题

**Comment by chaomowangshen** [comment]
无，换模型呗，这个也很久了
