### ISSUE TITLE
这个模型太犟

### ISSUE THREAD

**Issue by wizd** [THUDM/ChatGLM-6B#74]
![Screenshot 2023-03-15 220627](https://user-images.githubusercontent.com/2835415/225333688-fa8275e4-b46b-4c6d-9ddc-d558f77824cc.png)

**Comment by yaleimeng** [comment]
不是太犟，是理解能力有限，是参与训练对话语料的原因。。很多回答都非常机械，非常违和。
或者说，暂时不太具备角色扮演能力。。需要做对应的微调才行。
