### ISSUE TITLE
可以使用fp32 来微调吗？

### ISSUE THREAD

**Issue by chenyiwan** [THUDM/ChatGLM-6B#744]
### Is your feature request related to a problem? Please describe.

可以使用fp32 来微调吗？

### Solutions

可以使用fp32 来微调吗？

### Additional context

可以使用fp32 来微调吗？

**Comment by duzx16** [comment]
可以，去掉 `train.sh` 里的 `--quantization_bit 4`，把 `main.py` 里的 `.half()` 改成 `.float()` 就行

**Comment by chenyiwan** [comment]
哦，我是直接.cuda()了。
