### ISSUE TITLE
请问大家如何多batch推理呀，用list把问题送进去嘛？

### ISSUE THREAD

**Issue by Jessicamona** [THUDM/ChatGLM-6B#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

query = ['你好','请问如何健康减肥？','请推荐好吃的南京菜']
我想尝试多batch推理，我如何修改cli_demo呢

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

nothing

**Comment by duzx16** [comment]
`chat` 跟 `stream_chat` 都不支持 batch，但是 `generate` 和 `stream_generate` 是支持的
```python
inputs = tokenizer(['你好','请问如何健康减肥？','请推荐好吃的南京菜'], padding=True, return_tensors="pt")
inputs = inputs.to(model.device)
outputs = model.generate(**inputs)
print(tokenizer.batch_decode(outputs))
```

**Comment by thincal** [comment]
> `chat` 跟 `stream_chat` 都不支持 batch，但是 `generate` 和 `stream_generate` 是支持的
> 
> ```python
> inputs = tokenizer(['你好','请问如何健康减肥？','请推荐好吃的南京菜'], padding=True, return_tensors="pt")
> inputs = inputs.to(model.device)
> outputs = model.generate(**inputs)
> print(tokenizer.batch_decode(outputs))
> ```

发现输出会有截断现象：

```
['你好 你好👋!我是人工智能助手 ChatGL', '请问如何健康减肥? 减肥需要综合考虑饮食、运动和生活习惯等方面,以下', '请推荐好吃的南京菜 南京有许多美食,以下是一些值得尝试的:\n']
```

**Comment by EthenZhang** [comment]
> 

outputs = model.generate(**inputs,max_length=2046)
这样就可以了
