### ISSUE TITLE
[BUG/Help]  mac M2核心上运行报错RuntimeError: Internal

### ISSUE THREAD

**Issue by zhengyoutan** [THUDM/ChatGLM-6B#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

各位大佬，帮忙看看是什么原因
只修改了模型加载部分
![image](https://user-images.githubusercontent.com/88961103/233574864-3466658c-225d-47b5-85bc-3ba85c76f747.png)
**下面是报错：**
![image](https://user-images.githubusercontent.com/88961103/233573960-e308c750-b650-493d-aac1-d6c03350187b.png)

### Steps To Reproduce

1.conda 虚拟环境，先配的JittorLLMs的依赖环境，在该虚拟环境基础上又安装了本项目的requirements.txt
2.修改了模型加载部分 model = AutoModel.from_pretrained("your local path", trust_remote_code=True).half().to('mps')
3.执行 cli_demo.py文件，报错

### Environment

```markdown
- OS: Apple M2
- Python: 3.8.16
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
- conda 虚拟环境，先配的JittorLLMs的依赖环境，在该虚拟环境基础上又安装了本项目的requirements.txt
```

**Comment by duzx16** [comment]
这是加载tokenizer 的时候报错了，应该是你的 `ice_text.model` 文件没有下载完整
