### ISSUE TITLE
关于macOS

### ISSUE THREAD

**Issue by Raphtalia-chann** [THUDM/ChatGLM-6B#75]
macOS运行报错未知平台解决方法：
1.  修改web_demo.py/cli_demo.py
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
2.  既然报错sys.platform，那就干脆把linux改成识别到的darwin，反正都是类unix
修改/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cpm_kernels/library/base.py（具体路径因人而异）
<img width="1136" alt="2A537A26F29BD14B735F4C00DE058FB8" src="https://user-images.githubusercontent.com/79193123/225332533-1360a305-f462-4a1f-bd6b-5c32d05bb304.png">
添加elif darwin：
<img width="581" alt="截屏2023-03-15 22 05 56" src="https://user-images.githubusercontent.com/79193123/225333428-0adf98ed-dcee-4a2d-b7c4-f42496e25932.png">

        elif sys.platform.startswith("darwin"):
            lib_path = unix_find_lib(self.__name)
            self.__lib_path = lib_path
            if lib_path is not None:
                self.__lib = ctypes.cdll.LoadLibrary(lib_path)

最终效果双击运行：
<img width="563" alt="截屏2023-03-15 22 08 22" src="https://user-images.githubusercontent.com/79193123/225334103-dbe926c7-df3f-4af1-8d01-ee6d8f7b5507.png">

**Comment by duzx16** [comment]
谢谢你提供的方法。在https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1470060041中我给出了报错的原因和解决方法。
