### ISSUE TITLE
量化后latency变慢了

### ISSUE THREAD

**Issue by frankxyy** [THUDM/ChatGLM-6B#752]
量化后，gpu占用确实减少了，但latency实验后没降。
rtx3090单卡，bs = 1,  latency(生成每个token)结果如下:
fp16: 46.48 ms
int8: 84.32 ms
int4: 73.82 ms

code: https://gist.github.com/frankxyy/f2ed19969d05c7ed718568b4badffc77

**Comment by duzx16** [comment]
Duplicate of #726
