### ISSUE TITLE
[BUG/Help] <title>8-3-5+4=？这样的逻辑问题该怎么训练

### ISSUE THREAD

**Issue by rikeyz** [THUDM/ChatGLM-6B#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5292339/233683249-d0991b51-332b-4942-9ce8-fbe59224f927.png)
结果居然等于3，还一本正经地推理了一遍。

### Expected Behavior

4

### Steps To Reproduce

3090显卡下，启动不带量化的模型，提问 8-3-5+4=?，回答结果为3

### Environment

```markdown
- OS:Centos 7.9
- Python: python 3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by SailNow** [comment]
忘记是不是这个模型了，查找了很多7b左右的模型，记得有大佬说这个模型容量下做逻辑推理(数学计算)是表显比较差且不好训练的，个人认为试试更大的模型或者等创作者大佬来看看

**Comment by chenyiwan** [comment]
我认为 它根本没有学会做加减法，只是记到了一些式子的答案而已。。。

**Comment by JasonChenJC** [comment]
调用api呗？比如eval()

**Comment by zhangch9** [comment]
Duplicate of [#712](https://github.com/THUDM/ChatGLM-6B/issues/712)
