### ISSUE TITLE
[BUG/Help] TypeError: quantize() got an unexpected keyword argument 'empty_init'

### ISSUE THREAD

**Issue by candowu** [THUDM/ChatGLM-6B#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 File "/home/app/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1422, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
TypeError: quantize() got an unexpected keyword argument 'empty_init'

### Steps To Reproduce

1.下载最新的分支代码
2.安装依赖 pip install -r requirement.txt
3.修改train.sh 中模型路径
4.sh train.sh

### Environment

```markdown
- OS:cenos
- Python:3.9.16
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support: True， T4
```

**Comment by duzx16** [comment]
应该是你用的模型实现不是最新的，因为最新的模型实现的1422行 https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L1422 跟你的内容对不上
你可以删掉 `/home/app/.cache/huggingface/modules/transformers_modules/chatglm-6b` 让 transformers 重新下载一下

**Comment by Frankey419** [comment]
> 应该是你用的模型实现不是最新的，因为最新的模型实现的1422行 https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L1422 跟你的内容对不上 你可以删掉 `/home/app/.cache/huggingface/modules/transformers_modules/chatglm-6b` 让 transformers 重新下载一下

File "/home/local_user/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1434, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
TypeError: quantize() got an unexpected keyword argument 'empty_init'

同样遇到了这个问题，按这个方法重新下载了还是不行

**Comment by yaleimeng** [comment]
是啊。新版本代码是1434行，照样是报告同一个错误。。
看另外一个issue，去掉量化这一行可以跑。但是显卡顶不住，OOM了
