### ISSUE TITLE
[BUG/Help] load_model_on_gpus从哪个utils引入的？

### ISSUE THREAD

**Issue by zw81929** [THUDM/ChatGLM-6B#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

多卡模型加载预测的时候，官方说可以用
from utils import load_model_on_gpus
model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=6)

但是这个“from utils import load_model_on_gpus” 从哪里引入的？

### Steps To Reproduce

OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.13
CUDA Support: True

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B/blob/main/utils.py

**Comment by zxcvbn114514** [comment]
> https://github.com/THUDM/ChatGLM-6B/blob/main/utils.py

请问我运行时出现报错：
A:\chatglm_webui-main>python main.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ A:\chatglm_webui-main\main.py:33 in <module>                                                     │
│                                                                                                  │
│    30 │   raise FileNotFoundError('Model not found')                                             │
│    31                                                                                            │
│    32 tokenizer = AutoTokenizer.from_pretrained(args.path, trust_remote_code=True)               │
│ ❱  33 model = load_model_on_gpus(checkpoint_path="./chatglm-6b-int4-slim")                       │
│    34                                                                                            │
│    35 if args.cpu:                                                                               │
│    36 │   model = model.float()                                                                  │
│                                                                                                  │
│ A:\chatglm_webui-main\utils.py:45 in load_model_on_gpus                                          │
│                                                                                                  │
│   42 │   else:                                                                                   │
│   43 │   │   from accelerate import dispatch_model                                               │
│   44 │   │                                                                                       │
│ ❱ 45 │   │   model = AutoModel.from_pretrained(checkpoint_path, trust_remote_code=True, **kwa    │
│   46 │   │                                                                                       │
│   47 │   │   if device_map is None:                                                              │
│   48 │   │   │   device_map = auto_configure_device_map(num_gpus)                                │
│                                                                                                  │
│ C:\Users\Ge                                                                                      │
│ Yunxiang\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto │
│ _factory.py:441 in from_pretrained                                                               │
│                                                                                                  │
│   438 │   │   │   if kwargs_copy.get("torch_dtype", None) == "auto":                             │
│   439 │   │   │   │   _ = kwargs_copy.pop("torch_dtype")                                         │
│   440 │   │   │                                                                                  │
│ ❱ 441 │   │   │   config, kwargs = AutoConfig.from_pretrained(                                   │
│   442 │   │   │   │   pretrained_model_name_or_path,                                             │
│   443 │   │   │   │   return_unused_kwargs=True,                                                 │
│   444 │   │   │   │   trust_remote_code=trust_remote_code,                                       │
│                                                                                                  │
│ C:\Users\Ge                                                                                      │
│ Yunxiang\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\conf │
│ iguration_auto.py:931 in from_pretrained                                                         │
│                                                                                                  │
│   928 │   │   │   │   )                                                                          │
│   929 │   │   │   class_ref = config_dict["auto_map"]["AutoConfig"]                              │
│   930 │   │   │   module_file, class_name = class_ref.split(".")                                 │
│ ❱ 931 │   │   │   config_class = get_class_from_dynamic_module(                                  │
│   932 │   │   │   │   pretrained_model_name_or_path, module_file + ".py", class_name, **kwargs   │
│   933 │   │   │   )                                                                              │
│   934 │   │   │   config_class.register_for_auto_class()                                         │
│                                                                                                  │
│ C:\Users\Ge                                                                                      │
│ Yunxiang\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_u │
│ tils.py:388 in get_class_from_dynamic_module                                                     │
│                                                                                                  │
│   385 │   │   revision=revision,                                                                 │
│   386 │   │   local_files_only=local_files_only,                                                 │
│   387 │   )                                                                                      │
│ ❱ 388 │   return get_class_in_module(class_name, final_module.replace(".py", ""))                │
│   389                                                                                            │
│   390                                                                                            │
│   391 def custom_object_save(obj, folder, config=None):                                          │
│                                                                                                  │
│ C:\Users\Ge                                                                                      │
│ Yunxiang\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_u │
│ tils.py:157 in get_class_in_module                                                               │
│                                                                                                  │
│   154 │   Import a module on the cache directory for modules and extract a class from it.        │
│   155 │   """                                                                                    │
│   156 │   module_path = module_path.replace(os.path.sep, ".")                                    │
│ ❱ 157 │   module = importlib.import_module(module_path)                                          │
│   158 │   return getattr(module, class_name)                                                     │
│   159                                                                                            │
│   160                                                                                            │
│                                                                                                  │
│ C:\Users\Ge Yunxiang\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126 in    │
│ import_module                                                                                    │
│                                                                                                  │
│   123 │   │   │   if character != '.':                                                           │
│   124 │   │   │   │   break                                                                      │
│   125 │   │   │   level += 1                                                                     │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   127                                                                                            │
│   128                                                                                            │
│   129 _RELOADING = {}                                                                            │
│ <frozen importlib._bootstrap>:1050 in _gcd_import                                                │
│ <frozen importlib._bootstrap>:1027 in _find_and_load                                             │
│ <frozen importlib._bootstrap>:992 in _find_and_load_unlocked                                     │
│ <frozen importlib._bootstrap>:241 in _call_with_frames_removed                                   │
│ <frozen importlib._bootstrap>:1050 in _gcd_import                                                │
│ <frozen importlib._bootstrap>:1027 in _find_and_load                                             │
│ <frozen importlib._bootstrap>:992 in _find_and_load_unlocked                                     │
│ <frozen importlib._bootstrap>:241 in _call_with_frames_removed                                   │
│ <frozen importlib._bootstrap>:1050 in _gcd_import                                                │
│ <frozen importlib._bootstrap>:1027 in _find_and_load                                             │
│ <frozen importlib._bootstrap>:1004 in _find_and_load_unlocked                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'transformers_modules.'
是啥情况啊大佬

**Comment by Yif-Liu-Github** [comment]
from utils import load_model_on_gpus
