### ISSUE TITLE
RuntimeError: Library cublasLt is not initialized

### ISSUE THREAD

**Issue by Leader-txt** [THUDM/ChatGLM-6B#76]
An error occurred while startup.

**Comment by Leader-txt** [comment]
solved after rebooting.

**Comment by liudaoguang** [comment]
ChatGLM2-6B/ptuning/main.py
127     if model_args.pre_seq_len is not None:
128         # P-tuning v2
129         model = model.half()  ===>model = model.half().cuda()    
GPU微调训练：尝试在后面加.cuda()，半精度half是依赖cuda写的需要调用cuda函数；（ubuntu亲测有效）
CPU微调训练：model = model.float() （个人仅在macOS m1上跑通）
130         model.transformer.prefix_encoder.float()
