### ISSUE TITLE
[Help] <title> 请问生成的时候temperature和top_p参数有用到吗？目前没有在代码里找到

### ISSUE THREAD

**Issue by xiongxiaochu** [THUDM/ChatGLM-6B#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问生成的时候temperature和top_p参数有用到吗？目前没有在代码里找到

只在代码里看到do_sample=True的时候会有一个多项式sample的操作，temperature和top_p没找到在哪里用的，求问哪里可以找到？

### Steps To Reproduce

无

### Environment

```markdown
- OS: Linux
- Python: 3.9
- Transformers: 4.28.0.dev
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig.temperature
简单来说就是temperature越大，top_p越大，随机性越强

**Comment by xiongxiaochu** [comment]
> https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig.temperature 简单来说就是temperature越大，top_p越大，随机性越强

请问具体在代码的哪里有体现呢？

**Comment by duzx16** [comment]
> > https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig.temperature 简单来说就是temperature越大，top_p越大，随机性越强
> 
> 请问具体在代码的哪里有体现呢？

在 `transforemers` 的代码里面

**Comment by tomFoxxxx** [comment]
> > https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig.temperature 简单来说就是temperature越大，top_p越大，随机性越强
> 
> 请问具体在代码的哪里有体现呢？

/[models](https://github.com/chatchat-space/Langchain-Chatchat/tree/v0.1.17/models)
/chatglm_llm.py

在这个旧版本的此文件内可以找到（点击/model可以直接跳转）。目前langchain-ChatGLM已经更新到了2.0版本
