### ISSUE TITLE
[BUG/Help] <title>好多常识回答不对

### ISSUE THREAD

**Issue by wuxiaobo** [THUDM/ChatGLM-6B#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5646265/233824652-aa93ab1f-665e-4f07-825b-e03cba15296c.png)

### Steps To Reproduce

- OS:linux 
- Python:3.10
- Transformers: 4.27.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
- OS:linux 
- Python:3.10
- Transformers: 4.27.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

![image](https://user-images.githubusercontent.com/5646265/233824611-a6a72130-85cc-49ad-b3f6-67b92b2a326f.png)
![image](https://user-images.githubusercontent.com/5646265/233824628-844648fa-6468-4572-ba5a-3a9c8ddf7a29.png)
![image](https://user-images.githubusercontent.com/5646265/233824643-01e6831d-e8a1-4b11-aaa0-b47144189e91.png)

**Comment by eAtmApp** [comment]
chatgpt 3.5 也答不全我这市里面的区县 -_-

**Comment by duzx16** [comment]
欢迎针对 ChatGLM-6B 的 badcase 提交反馈：https://github.com/THUDM/ChatGLM-6B/tree/main/improve
