### ISSUE TITLE
生成的标点符号中西文标点混杂

### ISSUE THREAD

**Issue by riverscn** [THUDM/ChatGLM-6B#77]
非常降低中文的输出品质……
![300a743f063cd08389fc68dcd031269](https://user-images.githubusercontent.com/555062/225334588-dc8ec947-156d-4163-a365-233fdf703486.png)

**Comment by duzx16** [comment]
已修复。请使用Hugging Face Hub上最新的模型实现。

**Comment by lixiang1991** [comment]
请问下这个怎么修复的？看了下Hugging Face Hub上的改动记录，就改了两行：ids = [_id for _id in ids if _id >= 0]和self.vocab_files_names["vocab_file"]。比较了ice_text.model的md5和一周前我下载的md5都是9733ffa2cf070e0b78718747ea6a32a7cfc151b9

**Comment by riverscn** [comment]
用了HFH上的最新模型，标点符号还是有问题的
