### ISSUE TITLE
[BUG/Help] <title>关于max_source_length 和max_target_length 的一些问题

### ISSUE THREAD

**Issue by Isfate** [THUDM/ChatGLM-6B#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

max_source_length 和max_target_length是输入长度和输出长度么, 如果不是请忽略以下问题
在使用自己的数据集进行训练的时候, max_source_length 和max_target_length的最大支持长度是多少,
多轮对话中, 上轮对话的回答是否计入当前轮次对话的max_source_length 中
在增加了max_source_length 和max_target_length的长度后, 在预测的时候显存的的占用是否会增多

### Steps To Reproduce

无

### Environment

```markdown
无
```

**Comment by exaggerated-dream** [comment]
1. max_source_length、max_target_length是输入输出文本的向量长度，可以自己用tokenizer.encode计算
2. 官方建议不超过2048，可以翻下以前的issues，有说过
3. 计入
4. 会
