### ISSUE TITLE
[Help] 请问在ptuning时，哪一行代码用于冻结全部的模型参数？

### ISSUE THREAD

**Issue by MAxx8371** [THUDM/ChatGLM-6B#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

main.py函数中没有找到关于 冻结全部模型参数 的语句。

### Steps To Reproduce

*

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L852

**Comment by MAxx8371** [comment]
谢谢！
