### ISSUE TITLE
请问下微调数据里面的#和*分别代表什么意思啊？

### ISSUE THREAD

**Issue by Dragonkingpan** [THUDM/ChatGLM-6B#775]
### Is your feature request related to a problem? Please describe.

{"content": "类型#上衣*材质#牛仔布*颜色#白色*风格#简约*图案#刺绣*衣样式#外套*衣款式#破洞", "summary": "简约而不简单的牛仔外套，白色的衣身十分百搭。衣身多处有做旧破洞设计，打破单调乏味，增加一丝造型看点。衣身后背处有趣味刺绣装饰，丰富层次感，彰显别样时尚。"}

### Solutions

请问下微调数据立面的#和*分别代表什么意思啊？看上去似乎是想表示：
类型：上衣；
材质：牛仔裤；
...
是这个意思么？如果我们自己制作数据集，应该有什么规则么？

**Comment by duzx16** [comment]
ADGEN 这个数据集自己用来分隔标签的，对 ChatGLM-6B 来说没有特殊含义。自己制作数据集的话按照人类能够理解的标准就行。
