### ISSUE TITLE
有模型中的13万多token对应分词编码映射关系的说明么？

### ISSUE THREAD

**Issue by zhangjin4415** [THUDM/ChatGLM-6B#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我看模型用了vocab_size=130344，没有找到这13万多词的分词编码关系，不知道有没有具体的说明呢

### Steps To Reproduce

chatglm-6B

### Environment

```markdown
- OS:ubuntu22.04 
- Python: 3.10
```

**Comment by jaweii** [comment]
同问

**Comment by Gio-2020** [comment]
可以用tokenizer.get_vocab()
