### ISSUE TITLE
ptuning运行train.sh脚本没反应

### ISSUE THREAD

**Issue by bookwoods** [THUDM/ChatGLM-6B#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![3308c17ee0259ec2488fba3a4c6fbca](https://user-images.githubusercontent.com/106570410/233840150-33d0afc6-a20e-4642-b011-222c3428f0d0.jpg)

在pycharm下运行train.sh无反应

### Steps To Reproduce

在git bash以及cygwin上运行都是如此，请问这是什么原因呢

### Environment

```markdown
已确定环境和项目完全一致，主程序能正常运行
```

**Comment by Deemol** [comment]
同样的问题，train.sh和train_chat.sh都没反应

**Comment by tingfengwuyou** [comment]
把python3 改为 python

**Comment by bookwoods** [comment]
> 把python3 改为 python

问题已解决，感谢
