### ISSUE TITLE
如何修改监听地址和端口

### ISSUE THREAD

**Issue by amwork2020** [THUDM/ChatGLM-6B#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

python web_demo.py

Running on local URL:  http://127.0.0.1:7860

如何修改监听地址为主机地址，如何修改端口为其他的？

谢谢！

### Steps To Reproduce

python web_demo.py

Running on local URL:  http://127.0.0.1:7860

如何修改监听地址为主机地址，如何修改端口为其他的？

谢谢！

### Environment

```markdown
python web_demo.py

Running on local URL:  http://127.0.0.1:7860

如何修改监听地址为主机地址，如何修改端口为其他的？

谢谢！
```

**Comment by Zombiessss** [comment]
# web_demo最后一行launch添加两个参数
demo.queue().launch(server_name="0.0.0.0", server_port=8080, share=False, inbrowser=True)

**Comment by Lukangkang123** [comment]
> # web_demo最后一行launch添加两个参数
> demo.queue().launch(server_name="0.0.0.0", server_port=8080, share=False, inbrowser=True)

请问web_demo2.py如何修改端口？
