### ISSUE TITLE
[BUG/Help] 模型授权问题

### ISSUE THREAD

**Issue by OathK1per** [THUDM/ChatGLM-6B#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问该模型能够商用吗？如何授权呢

### Steps To Reproduce

礼貌求问

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请联系yiwen.xu@zhipuai.cn（Iven徐一文）
