### ISSUE TITLE
int8量化不能正常运行

### ISSUE THREAD

**Issue by tubiichiorigami** [THUDM/ChatGLM-6B#79]
![QQ截图20230315223901](https://user-images.githubusercontent.com/59564842/225343982-93662331-79af-4aa1-a33f-e83e76d77479.png)
 如图，来个大佬救救

**Comment by tubiichiorigami** [comment]
> 请确定`./model/chatglm-6b`这个目录是存在的，并且里面有完整的模型实现和checkpoint。

目录是存在的，这个包是从b站秋叶那里下的，解压下来有12.8G，应该没问题。
![QQ截图20230315232229](https://user-images.githubusercontent.com/59564842/225357351-019453e7-8efa-4d52-a155-f15bfa81bd30.png)

**Comment by duzx16** [comment]
> > 请确定`./model/chatglm-6b`这个目录是存在的，并且里面有完整的模型实现和checkpoint。
> 
> 目录是存在的，这个包是从b站秋叶那里下的，解压下来有12.8G，应该没问题。 ![QQ截图20230315232229](https://user-images.githubusercontent.com/59564842/225357351-019453e7-8efa-4d52-a155-f15bfa81bd30.png)

@tubiichiorigami 有没有可能图里的目录名是`modle`，不是`model`

**Comment by tubiichiorigami** [comment]
> > > 请确定`./model/chatglm-6b`这个目录是存在的，并且里面有完整的模型实现和checkpoint。
> > 
> > 
> > 目录是存在的，这个包是从b站秋叶那里下的，解压下来有12.8G，应该没问题。 ![QQ截图20230315232229](https://user-images.githubusercontent.com/59564842/225357351-019453e7-8efa-4d52-a155-f15bfa81bd30.png)
> 
> @tubiichiorigami 有没有可能图里的目录名是`modle`，不是`model`

我人傻了，多谢大佬
