### ISSUE TITLE
[BUG/Help] <title>单句推理显存持续增加

### ISSUE THREAD

**Issue by RafaelHuang87** [THUDM/ChatGLM-6B#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/THUDM/ChatGLM-6B/issues/393
根据以上描述是由于要缓存context中的信息，如何才能每次调用后清理缓存，保证不会出现持续增加直至OOM的情况呢？

### Steps To Reproduce

\

### Environment

```markdown
- OS:CentOS
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.12.0+cu102
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by RafaelHuang87** [comment]
@duzx16 辛苦大佬有空的时候看看这个问题

**Comment by duzx16** [comment]
你清空 `history`或者只保留最后几轮的历史就可以了

**Comment by RafaelHuang87** [comment]
> 你清空 `history`或者只保留最后几轮的历史就可以了

不好意思，可是如标题所说，我每次进行的都是单句的推理，传入的history均为[]，但是显存仍旧会从最初的13G逐步增加到14、15G，最终超过16G导致OOM

**Comment by kulina** [comment]
> 仍旧会从最初的13G逐步增

我也遇到了同样的问题，请问您是否找到了合适的解决办法？

**Comment by ianZzzzzz** [comment]
在推理结束后清理缓存就可以了，torch.cuda.empty_cache()
