### ISSUE TITLE
[BUG/Help] 加载数据集一直出现coredumped问题

### ISSUE THREAD

**Issue by shibo950912** [THUDM/ChatGLM-6B#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

load_dataset自己的本地数据集的时候一直出现coredumped，各位大佬又出现过类似问题嘛：
Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-280a26c65343a6bc/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e...
Segmentation fault (core dumped)

### Steps To Reproduce

\\\\

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:4.27.3
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by licy02** [comment]
我也遇到了相同的问题，请问您有解决吗？
