### ISSUE TITLE
Why this model never output a Chinese comma "，" ？

### ISSUE THREAD

**Issue by pandazki** [THUDM/ChatGLM-6B#8]
Just curious.  😏

**Comment by Sengxian** [comment]
Our tokenizer is trained based on sentencepiece and the [NFKC normalization preprocessing step](https://github.com/google/sentencepiece/blob/master/doc/normalization.md) will convert Chinese commas to English ones.

**Comment by pandazki** [comment]
Thanks for your explanation~

**Comment by pandazki** [comment]
https://arxiv.org/pdf/1808.06226.pdf

Further reading.
