### ISSUE TITLE
Symbol cudaLaunchKernel not found

### ISSUE THREAD

**Issue by tubiichiorigami** [THUDM/ChatGLM-6B#80]
![QQ截图20230315234923](https://user-images.githubusercontent.com/59564842/225366463-42a209fc-79e5-4549-8d1e-4a725cd1e55b.png)
翻之前的Issues好多都是重启之后解决，但我重启了多次之后依然还会有该问题。

**Comment by SnownICE** [comment]
我也是Symbol cudaLaunchKernel not found但是web ui能打开,可能是环境变量里有问题,我使用绝对路径就不报错了

**Comment by duzx16** [comment]
这个应该只是Warning，不影响使用
