### ISSUE TITLE
[BUG/Help] 为什么本地部署模型时报错找不到Pytorch_model.bin文件,从云盘里下载的是01-08.bin

### ISSUE THREAD

**Issue by Anekys** [THUDM/ChatGLM-6B#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

python cli_demo.py

### Expected Behavior

py代码:
``` python
tokenizer = AutoTokenizer.from_pretrained("/opt/chatGLM_6B/chatglm-module", trust_remote_code=True)
model = AutoModel.from_pretrained("/opt/chatGLM_6B/chatglm-module", trust_remote_code=True).half().cuda()
model = model.eval()
```
文件内容:
![image](https://user-images.githubusercontent.com/53458682/234168201-b358211d-c8f8-4914-b1ba-10bc2c626a41.png)
报错内容:
``` python
raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory 
```

### Steps To Reproduce

python cli_demo.py

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: Python3.8
- Transformers: 
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :Ture
```

**Comment by Anekys** [comment]
貌似是我呆瓜了,这01-08每一个都是单独的模型嘛?

**Comment by EeyoreLee** [comment]
> 貌似是我呆瓜了,这01-08每一个都是单独的模型嘛?

加一起是整个模型，你缺少一个pytorch_model.bin.index.json文件，其中保存了模型每个矩阵对应的文件名，你把这个下载一下就可以了

**Comment by suoer95** [comment]
> pytorch_model.bin.index.json
我下载了，也报这个错，请问大佬知道是为什么吗？
