### ISSUE TITLE
怎么用单机多卡推理呀

### ISSUE THREAD

**Issue by Siegfried-qgf** [THUDM/ChatGLM-6B#803]
看他默认的代码是单卡的

**Comment by irasin** [comment]
按道理huggingface是可以通过device_map="auto"实现多卡的，但是在模型文件中加一些配置定义，可能需要参考一下其他的模型加一下类似_no_split_modules的定义

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2
