### ISSUE TITLE
根据文档提供的内容进行微调后，丧失了原有的基本对话能力

### ISSUE THREAD

**Issue by jaccborn** [THUDM/ChatGLM-6B#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

根据文档中的方法进行微调后，询问例如“你是谁”  “你叫什么” 
都会回复所训练模型内容中相关的字眼，实际上询问的问题与训练的模型问题是不相关的

是否有其他相关微调参数设置 或者如何改进 可以保留原有的对话能力？

### Steps To Reproduce

1、下载ADGEN 数据集并放入对应目录
2、运行bash train.sh进行训练
3、运行bash evaluate.sh进行推理
4、运行bash web_demo.sh进行测试

### Environment

```markdown
- OS:Windows 11
- Python: 3.10
- Transformers:4.27.1
- PyTorch:2.0
- GPU: 4080 32G
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by waveboy800** [comment]
我也是遇到这个，微调数据就三条，你是谁，喵喵喵那个，从此问它什么问题都是喵喵喵了

**Comment by jaccborn** [comment]
您好 实名认证请联系所属地市旅游局单位管理员(具体联系人我这边也不清楚，请您咨询一下)

**Comment by TEENN2233** [comment]
希望官方能出点什么微调工具

**Comment by dhhcj** [comment]
都一样。。灾难性遗忘问题，等更新或者官方回复吧

**Comment by duzx16** [comment]
灾难性遗忘问题很难解决，最好的方法是把数据和通用域的训练数据一起进行训练。
如果你的数据具有泛用意义的话，可以提交到 https://github.com/THUDM/ChatGLM-6B/tree/main/improve ，我们会将筛选通过的数据加入训练

**Comment by PopRangR** [comment]
请问这个问题目前有解决方案没

**Comment by waveboy800** [comment]
可以使用本地知识库，不走微调的路线就可以了。

**Comment by PopRangR** [comment]
> 可以使用本地知识库，不走微调的线路就可以了。

不使用训练微调之后的数据？

**Comment by SupritYoung** [comment]
个人研究，除了一起训练，还可以使用self-instruct等方法，使得训练数据尽量平滑，符合常规对话的逻辑。

**Comment by cssaudrey** [comment]
> 个人研究，除了一起训练，还可以使用self-instruct等方法，使得训练数据尽量平滑，符合常规对话的逻辑。

有建议的link可以参考吗？
