### ISSUE TITLE
大佬，我用lora 微调完成后，在chekpoint里，挑选了一个比较好的pt， 下次我想基于微调后的这个pt，继续微调，你们一般是怎么弄的？

### ISSUE THREAD

**Issue by chenyiwan** [THUDM/ChatGLM-6B#805]
### Is your feature request related to a problem? Please describe.

大佬，我用lora微调完成后，在chekpoint里，挑选了一个比较好的pt，
下次我想基于微调后的这个pt，继续微调，你们一般是怎么弄的？

### Solutions

大佬，我用lora微调完成后，在chekpoint里，挑选了一个比较好的pt，
下次我想基于微调后的这个pt，继续微调，你们一般是怎么弄的？

### Additional context

大佬，我用lora微调完成后，在chekpoint里，挑选了一个比较好的pt，
下次我想基于微调后的这个pt，继续微调，你们一般是怎么弄的？

**Comment by FrankWhh** [comment]
1. merge原来的lora参数，再继续微调
2. 加载原来的lora ，再继续微调

**Comment by chenyiwan** [comment]
merge怎么操作丶有教程吗

**Comment by ChenWarlock** [comment]
> merge怎么操作丶有教程吗

model = model.merge_and_unload()
