### ISSUE TITLE
[BUG/Help] <title> 8 or 128 ?

### ISSUE THREAD

**Issue by ucas010** [THUDM/ChatGLM-6B#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi,dear
pre_seq_len is 8 in train but 128 when inference
https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/train_chat.sh#L1
**PRE_SEQ_LEN=8**
https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/web_demo.sh#L1
**PRE_SEQ_LEN=128**
why ?

### Steps To Reproduce

no

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by ucas010** [comment]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
	size mismatch for embedding.weight: copying a param with shape torch.Size([8, 229376]) from checkpoint, the shape in current model is torch.Size([128, 229376]).

**Comment by ucas010** [comment]
this is a big bug !!!
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/50656998/234177555-093744ac-0513-47a5-8743-8e46804b73e4.png">

**Comment by ucas010** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/50656998/234178179-14917df5-5296-4432-a855-b519b7e8b1d3.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/50656998/234178227-de4b0502-23d1-482b-b828-9c251d82ae9f.png">

**Comment by SSSSQD** [comment]
i also confused，why in two shell script, PRE_SQL_LEN has two different value

**Comment by duzx16** [comment]
Thanks for pointing out this. Already fixed.
