### ISSUE TITLE
model.chat（）方法的max_length是指回答的response的长度吗

### ISSUE THREAD

**Issue by blue-q** [THUDM/ChatGLM-6B#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

model.chat（）方法的max_length是指回答的response的长度吗

### Steps To Reproduce

model.chat（）方法的max_length是指回答的response的长度吗

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by yuri2peter** [comment]
经测试，是输入（历史）+输出的总长度。但是由于输入是外界传入的，所以最终影响的是输出长度。
