### ISSUE TITLE
A卡不能用嘛？6800显卡部署出错

### ISSUE THREAD

**Issue by zhibinlin1** [THUDM/ChatGLM-6B#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AMD 6800显卡部署出错，AMD显卡是否可以使用该项目？
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### Steps To Reproduce

运行api.py，下载完产生如下错误：
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by lc11235** [comment]
AMD的显卡不支持CUDA吧，只能用CPU方式训练

**Comment by zhibinlin1** [comment]
> 
AMD显卡不能用就白瞎了大显存

**Comment by gg22mm** [comment]
> > 
> 
> AMD显卡不能用就白瞎了大显存

amd只能打游戏 ~~

**Comment by AldarisX** [comment]
用rocm

**Comment by po4920826** [comment]
你好，我用A卡部署成功了，但是在ubuntu系统，理论上其他linux系统也是可以的。
使用这个方法配置的Text generation web UI 
https://rentry.org/eq3hg

**Comment by worm128** [comment]
> 你好，我用A卡部署成功了，但是在ubuntu系统，理论上其他linux系统也是可以的。 使用这个方法配置的Text generation web UI，原作者用的是arch linux https://rentry.org/eq3hg

谢谢分享
