### ISSUE TITLE
请问chatglm用的是什么量化方法？

### ISSUE THREAD

**Issue by frankxyy** [THUDM/ChatGLM-6B#815]
如题，比如是LLM.int8()吗？

**Comment by zx2021** [comment]
拿过去解决隔壁win不能量化的问题是吧（狗头）

**Comment by frankxyy** [comment]
> 拿过去解决隔壁win不能量化的问题是吧（狗头）

不是，学习。。 看代码有点懵。。

**Comment by irasin** [comment]
同问，用的是什么量化方法呢？GPTQ？还是直接对权重对称量化成int8？这样精度损失应该会比较大吧？

**Comment by lonngxiang** [comment]
> 同问，用的是什么量化方法呢？GPTQ？还是直接对权重对称量化成int8？这样精度损失应该会比较大吧？

同问
