### ISSUE TITLE
[Help] 微调之后保存的checkpoint里只有一个pytorch_model.bin而且大小只有7M，这是什么原因呢？

### ISSUE THREAD

**Issue by WuYilin2022** [THUDM/ChatGLM-6B#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

载入模型的时候使用微调后的checkpoint，报错：
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../ptuning/output/AQSH-chatglm-6b-pt-8-1e-2/checkpoint-3000 and are newly initialized: ['transformer.layers.19.attention.query_key_value.weight', 'transformer.layers.9.input_layernorm.bias', 'transformer.layers.10.input_layernorm.bias', 'transformer.layers.17.post_attention_layernorm.bias', 'transformer.layers.27.mlp.dense_4h_to_h.weight', 'transformer.layers.12.mlp.dense_4h_to_h.weight', 'transformer.layers.15.input_layernorm.weight', 'transformer.layers.18.input_layernorm.bias', 'transformer.layers.16.attention.query_key_value.bias', 'transformer.layers.17.mlp.dense_4h_to_h.weight', 'transformer.layers.12.input_layernorm.bias', 'transformer.layers.22.mlp.dense_4h_to_h.weight', 'transformer.layers.16.attention.rotary_emb.inv_freq', 'transformer.layers.5.input_layernorm.weight', 'transformer.layers.25.attention.dense.weight', 'transformer.layers.17.attention.rotary_emb.inv_freq', 'transformer.layers.24.attention.query_key_value.weight', 'transformer.layers.26.mlp.dense_h_to_4h.bias', 'transformer.layers.4.attention.query_key_value.bias', 'transformer.layers.27.attention.query_key_value.weight', 'transformer.layers.13.mlp.dense_4h_to_h.weight', 'transformer.layers.0.mlp.dense_4h_to_h.bias', 'transformer.layers.22.mlp.dense_4h_to_h.bias', 'transformer.layers.8.attention.dense.weight', 'transformer.layers.20.mlp.dense_h_to_4h.weight', 'transformer.layers.26.attention.rotary_emb.inv_freq', 'transformer.layers.2.mlp.dense_4h_to_h.bias', 'transformer.layers.27.attention.dense.weight', 'transformer.layers.2.input_layernorm.weight', 'transformer.layers.26.attention.query_key_value.weight', 'transformer.layers.4.post_attention_layernorm.weight', 'transformer.layers.17.attention.dense.weight', 'transformer.layers.19.attention.dense.bias', 'transformer.layers.5.mlp.dense_4h_to_h.weight', 'transformer.layers.0.mlp.dense_h_to_4h.bias', 'transformer.layers.2.attention.query_key_value.bias', 'transformer.layers.20.attention.dense.bias', 'transformer.layers.9.attention.dense.bias', 'transformer.layers.16.attention.dense.bias', 'transformer.layers.2.post_attention_layernorm.weight', 'transformer.layers.16.attention.query_key_value.weight', 'transformer.layers.24.attention.query_key_value.bias', 'transformer.layers.13.attention.dense.bias', 'transformer.layers.4.attention.dense.bias', 'transformer.layers.7.attention.rotary_emb.inv_freq', 'transformer.layers.23.input_layernorm.bias', 'transformer.layers.10.attention.query_key_value.bias', 'transformer.layers.1.attention.query_key_value.bias', 'transformer.layers.25.mlp.dense_4h_to_h.weight', 'transformer.layers.27.input_layernorm.bias', 'transformer.layers.18.attention.dense.bias', 'transformer.layers.25.mlp.dense_h_to_4h.weight', 'transformer.layers.3.mlp.dense_h_to_4h.bias', 'transformer.layers.4.mlp.dense_h_to_4h.weight', 'transformer.layers.13.mlp.dense_4h_to_h.bias', 'transformer.layers.20.input_layernorm.bias', 'transformer.layers.17.mlp.dense_4h_to_h.bias', 'transformer.layers.17.post_attention_layernorm.weight', 'transformer.layers.24.input_layernorm.bias', 'transformer.layers.27.attention.dense.bias', 'transformer.layers.14.input_layernorm.weight', 'transformer.layers.15.mlp.dense_h_to_4h.bias', 'transformer.layers.8.post_attention_layernorm.bias', 'transformer.layers.27.attention.query_key_value.bias', 'transformer.layers.22.post_attention_layernorm.weight', 'transformer.layers.1.mlp.dense_h_to_4h.weight', 'transformer.layers.5.input_layernorm.bias', 'transformer.layers.15.attention.query_key_value.bias', 'transformer.layers.17.attention.query_key_value.weight', 'transformer.layers.25.mlp.dense_h_to_4h.bias', 'transformer.layers.7.mlp.dense_h_to_4h.bias', 'transformer.layers.19.post_attention_layernorm.bias', 'lm_head.weight', 'transformer.layers.3.input_layernorm.weight', 'transformer.layers.6.attention.query_key_value.bias', 'transformer.layers.18.mlp.dense_4h_to_h.weight', 'transformer.layers.0.input_layernorm.bias', 'transformer.layers.15.mlp.dense_4h_to_h.weight', 'transformer.layers.13.post_attention_layernorm.bias', 'transformer.layers.15.post_attention_layernorm.bias', 'transformer.layers.24.attention.dense.weight', 'transformer.layers.11.mlp.dense_h_to_4h.weight', 'transformer.layers.26.input_layernorm.weight', 'transformer.layers.19.input_layernorm.weight', 'transformer.layers.8.attention.dense.bias', 'transformer.layers.21.input_layernorm.weight', 'transformer.layers.15.input_layernorm.bias', 'transformer.layers.24.mlp.dense_h_to_4h.weight', 'transformer.layers.16.post_attention_layernorm.bias', 'transformer.layers.2.attention.query_key_value.weight', 'transformer.layers.19.mlp.dense_h_to_4h.bias', 'transformer.layers.3.mlp.dense_4h_to_h.weight', 'transformer.layers.9.attention.rotary_emb.inv_freq', 'transformer.layers.20.mlp.dense_h_to_4h.bias', 'transformer.layers.24.input_layernorm.weight', 'transformer.layers.17.mlp.dense_h_to_4h.bias', 'transformer.layers.13.attention.query_key_value.weight', 'transformer.layers.20.attention.rotary_emb.inv_freq', 'transformer.layers.23.attention.query_key_value.weight', 'transformer.layers.22.input_layernorm.bias', 'transformer.layers.8.attention.query_key_value.bias', 'transformer.layers.16.post_attention_layernorm.weight', 'transformer.layers.20.post_attention_layernorm.bias', 'transformer.layers.0.input_layernorm.weight', 'transformer.layers.11.mlp.dense_4h_to_h.weight', 'transformer.layers.10.mlp.dense_h_to_4h.bias', 'transformer.layers.24.post_attention_layernorm.weight', 'transformer.layers.21.mlp.dense_h_to_4h.weight', 'transformer.layers.13.attention.dense.weight', 'transformer.layers.27.attention.rotary_emb.inv_freq', 'transformer.layers.1.attention.rotary_emb.inv_freq', 'transformer.layers.23.post_attention_layernorm.weight', 'transformer.layers.26.attention.dense.bias', 'transformer.layers.13.post_attention_layernorm.weight', 'transformer.layers.10.attention.dense.weight', 'transformer.layers.26.post_attention_layernorm.bias', 'transformer.layers.0.attention.dense.weight', 'transformer.layers.12.mlp.dense_h_to_4h.bias', 'transformer.layers.24.mlp.dense_4h_to_h.weight', 'transformer.layers.15.attention.dense.weight', 'transformer.layers.25.post_attention_layernorm.bias', 'transformer.layers.6.attention.dense.weight', 'transformer.layers.27.post_attention_layernorm.bias', 'transformer.layers.10.input_layernorm.weight', 'transformer.layers.27.mlp.dense_4h_to_h.bias', 'transformer.layers.7.attention.dense.weight', 'transformer.layers.25.attention.rotary_emb.inv_freq', 'transformer.layers.23.mlp.dense_4h_to_h.weight', 'transformer.layers.20.input_layernorm.weight', 'transformer.layers.2.attention.dense.bias', 'transformer.layers.19.mlp.dense_4h_to_h.weight', 'transformer.layers.17.attention.dense.bias', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.4.attention.dense.weight', 'transformer.layers.6.input_layernorm.weight', 'transformer.layers.18.attention.rotary_emb.inv_freq', 'transformer.layers.12.input_layernorm.weight', 'transformer.layers.19.attention.dense.weight', 'transformer.layers.9.attention.query_key_value.weight', 'transformer.layers.23.attention.dense.weight', 'transformer.layers.7.mlp.dense_h_to_4h.weight', 'transformer.layers.13.mlp.dense_h_to_4h.weight', 'transformer.layers.8.mlp.dense_4h_to_h.weight', 'transformer.layers.13.attention.query_key_value.bias', 'transformer.layers.14.attention.rotary_emb.inv_freq', 'transformer.layers.3.mlp.dense_h_to_4h.weight', 'transformer.layers.5.attention.rotary_emb.inv_freq', 'transformer.layers.10.mlp.dense_4h_to_h.weight', 'transformer.layers.11.attention.query_key_value.bias', 'transformer.layers.9.mlp.dense_h_to_4h.weight', 'transformer.layers.7.attention.query_key_value.weight', 'transformer.layers.17.input_layernorm.weight', 'transformer.layers.7.post_attention_layernorm.bias', 'transformer.layers.14.attention.dense.bias', 'transformer.layers.14.mlp.dense_h_to_4h.bias', 'transformer.layers.21.attention.query_key_value.weight', 'transformer.layers.24.post_attention_layernorm.bias', 'transformer.layers.19.mlp.dense_4h_to_h.bias', 'transformer.layers.15.attention.rotary_emb.inv_freq', 'transformer.layers.18.post_attention_layernorm.weight', 'transformer.layers.14.mlp.dense_h_to_4h.weight', 'transformer.layers.1.attention.query_key_value.weight', 'transformer.layers.2.attention.rotary_emb.inv_freq', 'transformer.layers.25.input_layernorm.weight', 'transformer.layers.9.mlp.dense_4h_to_h.weight', 'transformer.layers.11.post_attention_layernorm.weight', 'transformer.layers.5.attention.query_key_value.bias', 'transformer.layers.26.attention.query_key_value.bias', 'transformer.layers.5.mlp.dense_h_to_4h.weight', 'transformer.layers.1.post_attention_layernorm.bias', 'transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.23.mlp.dense_4h_to_h.bias', 'transformer.layers.9.input_layernorm.weight', 'transformer.layers.9.mlp.dense_h_to_4h.bias', 'transformer.layers.2.post_attention_layernorm.bias', 'transformer.layers.23.mlp.dense_h_to_4h.weight', 'transformer.layers.27.input_layernorm.weight', 'transformer.layers.1.post_attention_layernorm.weight', 'transformer.layers.2.mlp.dense_h_to_4h.bias', 'transformer.layers.4.mlp.dense_4h_to_h.bias', 'transformer.layers.22.attention.query_key_value.weight', 'transformer.layers.20.mlp.dense_4h_to_h.bias', 'transformer.layers.10.post_attention_layernorm.bias', 'transformer.layers.13.mlp.dense_h_to_4h.bias', 'transformer.layers.14.mlp.dense_4h_to_h.bias', 'transformer.layers.12.post_attention_layernorm.weight', 'transformer.layers.14.post_attention_layernorm.weight', 'transformer.layers.23.attention.dense.bias', 'transformer.layers.1.mlp.dense_h_to_4h.bias', 'transformer.layers.15.post_attention_layernorm.weight', 'transformer.layers.3.post_attention_layernorm.bias', 'transformer.layers.23.attention.rotary_emb.inv_freq', 'transformer.layers.6.mlp.dense_4h_to_h.weight', 'transformer.layers.27.mlp.dense_h_to_4h.weight', 'transformer.layers.3.input_layernorm.bias', 'transformer.layers.5.mlp.dense_4h_to_h.bias', 'transformer.layers.15.mlp.dense_h_to_4h.weight', 'transformer.layers.15.attention.query_key_value.weight', 'transformer.layers.18.post_attention_layernorm.bias', 'transformer.layers.2.attention.dense.weight', 'transformer.layers.20.post_attention_layernorm.weight', 'transformer.layers.2.input_layernorm.bias', 'transformer.layers.12.attention.dense.bias', 'transformer.layers.16.mlp.dense_h_to_4h.weight', 'transformer.layers.19.attention.rotary_emb.inv_freq', 'transformer.layers.1.attention.dense.bias', 'transformer.layers.0.attention.query_key_value.bias', 'transformer.layers.0.mlp.dense_h_to_4h.weight', 'transformer.layers.16.input_layernorm.bias', 'transformer.layers.5.attention.dense.bias', 'transformer.layers.16.mlp.dense_4h_to_h.bias', 'transformer.layers.7.input_layernorm.bias', 'transformer.layers.25.input_layernorm.bias', 'transformer.layers.11.input_layernorm.bias', 'transformer.layers.3.mlp.dense_4h_to_h.bias', 'transformer.layers.19.input_layernorm.bias', 'transformer.layers.21.mlp.dense_h_to_4h.bias', 'transformer.layers.4.mlp.dense_4h_to_h.weight', 'transformer.layers.11.post_attention_layernorm.bias', 'transformer.layers.9.post_attention_layernorm.bias', 'transformer.layers.5.attention.query_key_value.weight', 'transformer.layers.16.mlp.dense_4h_to_h.weight', 'transformer.layers.13.input_layernorm.bias', 'transformer.layers.26.mlp.dense_4h_to_h.weight', 'transformer.layers.0.attention.dense.bias', 'transformer.layers.6.post_attention_layernorm.bias', 'transformer.layers.7.attention.query_key_value.bias', 'transformer.layers.22.attention.dense.weight', 'transformer.layers.3.attention.query_key_value.weight', 'transformer.layers.21.post_attention_layernorm.weight', 'transformer.layers.25.attention.query_key_value.bias', 'transformer.layers.7.post_attention_layernorm.weight', 'transformer.layers.1.mlp.dense_4h_to_h.bias', 'transformer.layers.17.input_layernorm.bias', 'transformer.layers.26.post_attention_layernorm.weight', 'transformer.layers.21.mlp.dense_4h_to_h.weight', 'transformer.layers.8.mlp.dense_h_to_4h.bias', 'transformer.final_layernorm.weight', 'transformer.layers.7.input_layernorm.weight', 'transformer.layers.5.post_attention_layernorm.weight', 'transformer.layers.23.input_layernorm.weight', 'transformer.layers.23.mlp.dense_h_to_4h.bias', 'transformer.layers.21.attention.dense.weight', 'transformer.layers.18.attention.query_key_value.weight', 'transformer.layers.6.mlp.dense_4h_to_h.bias', 'transformer.layers.9.mlp.dense_4h_to_h.bias', 'transformer.layers.22.attention.query_key_value.bias', 'transformer.layers.12.attention.dense.weight', 'transformer.layers.11.input_layernorm.weight', 'transformer.layers.27.post_attention_layernorm.weight', 'transformer.layers.12.attention.query_key_value.bias', 'transformer.layers.0.mlp.dense_4h_to_h.weight', 'transformer.layers.6.attention.dense.bias', 'transformer.layers.8.mlp.dense_h_to_4h.weight', 'transformer.layers.6.attention.rotary_emb.inv_freq', 'transformer.layers.21.attention.dense.bias', 'transformer.layers.6.post_attention_layernorm.weight', 'transformer.layers.12.attention.query_key_value.weight', 'transformer.layers.20.attention.query_key_value.weight', 'transformer.layers.8.input_layernorm.bias', 'transformer.layers.21.attention.query_key_value.bias', 'transformer.layers.11.attention.dense.bias', 'transformer.layers.3.attention.rotary_emb.inv_freq', 'transformer.layers.22.attention.rotary_emb.inv_freq', 'transformer.layers.13.input_layernorm.weight', 'transformer.layers.11.attention.rotary_emb.inv_freq', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.25.attention.dense.bias', 'transformer.layers.25.post_attention_layernorm.weight', 'transformer.layers.4.mlp.dense_h_to_4h.bias', 'transformer.layers.9.attention.query_key_value.bias', 'transformer.layers.21.post_attention_layernorm.bias', 'transformer.layers.4.input_layernorm.weight', 'transformer.layers.6.mlp.dense_h_to_4h.bias', 'transformer.layers.21.mlp.dense_4h_to_h.bias', 'transformer.layers.23.post_attention_layernorm.bias', 'transformer.layers.7.mlp.dense_4h_to_h.bias', 'transformer.layers.24.mlp.dense_4h_to_h.bias', 'transformer.layers.24.attention.rotary_emb.inv_freq', 'transformer.layers.3.attention.dense.bias', 'transformer.layers.20.mlp.dense_4h_to_h.weight', 'transformer.layers.11.mlp.dense_4h_to_h.bias', 'transformer.layers.6.mlp.dense_h_to_4h.weight', 'transformer.layers.14.post_attention_layernorm.bias', 'transformer.word_embeddings.weight', 'transformer.layers.24.attention.dense.bias', 'transformer.layers.16.attention.dense.weight', 'transformer.layers.8.attention.rotary_emb.inv_freq', 'transformer.layers.12.post_attention_layernorm.bias', 'transformer.layers.2.mlp.dense_4h_to_h.weight', 'transformer.layers.5.attention.dense.weight', 'transformer.layers.7.mlp.dense_4h_to_h.weight', 'transformer.layers.18.mlp.dense_4h_to_h.bias', 'transformer.layers.4.attention.rotary_emb.inv_freq', 'transformer.layers.26.input_layernorm.bias', 'transformer.layers.27.mlp.dense_h_to_4h.bias', 'transformer.layers.10.mlp.dense_h_to_4h.weight', 'transformer.layers.17.mlp.dense_h_to_4h.weight', 'transformer.layers.18.mlp.dense_h_to_4h.weight', 'transformer.layers.1.attention.dense.weight', 'transformer.layers.0.post_attention_layernorm.weight', 'transformer.layers.11.attention.dense.weight', 'transformer.layers.5.mlp.dense_h_to_4h.bias', 'transformer.layers.11.attention.query_key_value.weight', 'transformer.layers.19.attention.query_key_value.bias', 'transformer.layers.19.post_attention_layernorm.weight', 'transformer.layers.12.attention.rotary_emb.inv_freq', 'transformer.layers.26.attention.dense.weight', 'transformer.layers.21.attention.rotary_emb.inv_freq', 'transformer.layers.1.input_layernorm.bias', 'transformer.layers.7.attention.dense.bias', 'transformer.layers.11.mlp.dense_h_to_4h.bias', 'transformer.layers.10.mlp.dense_4h_to_h.bias', 'transformer.layers.14.input_layernorm.bias', 'transformer.layers.20.attention.query_key_value.bias', 'transformer.layers.25.mlp.dense_4h_to_h.bias', 'transformer.layers.22.attention.dense.bias', 'transformer.layers.0.post_attention_layernorm.bias', 'transformer.layers.22.mlp.dense_h_to_4h.weight', 'transformer.final_layernorm.bias', 'transformer.layers.16.input_layernorm.weight', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.10.post_attention_layernorm.weight', 'transformer.layers.3.post_attention_layernorm.weight', 'transformer.layers.17.attention.query_key_value.bias', 'transformer.layers.4.post_attention_layernorm.bias', 'transformer.layers.1.input_layernorm.weight', 'transformer.layers.22.mlp.dense_h_to_4h.bias', 'transformer.layers.23.attention.query_key_value.bias', 'transformer.layers.3.attention.query_key_value.bias', 'transformer.layers.15.attention.dense.bias', 'transformer.layers.8.mlp.dense_4h_to_h.bias', 'transformer.layers.15.mlp.dense_4h_to_h.bias', 'transformer.layers.2.mlp.dense_h_to_4h.weight', 'transformer.layers.26.mlp.dense_h_to_4h.weight', 'transformer.layers.20.attention.dense.weight', 'transformer.layers.4.input_layernorm.bias', 'transformer.layers.10.attention.query_key_value.weight', 'transformer.layers.0.attention.rotary_emb.inv_freq', 'transformer.layers.18.mlp.dense_h_to_4h.bias', 'transformer.layers.1.mlp.dense_4h_to_h.weight', 'transformer.layers.16.mlp.dense_h_to_4h.bias', 'transformer.layers.6.attention.query_key_value.weight', 'transformer.layers.14.mlp.dense_4h_to_h.weight', 'transformer.layers.18.attention.query_key_value.bias', 'transformer.layers.25.attention.query_key_value.weight', 'transformer.layers.18.attention.dense.weight', 'transformer.layers.5.post_attention_layernorm.bias', 'transformer.layers.12.mlp.dense_h_to_4h.weight', 'transformer.layers.9.post_attention_layernorm.weight', 'transformer.layers.12.mlp.dense_4h_to_h.bias', 'transformer.layers.26.mlp.dense_4h_to_h.bias', 'transformer.layers.3.attention.dense.weight', 'transformer.layers.10.attention.dense.bias', 'transformer.layers.22.post_attention_layernorm.bias', 'transformer.layers.8.attention.query_key_value.weight', 'transformer.layers.22.input_layernorm.weight', 'transformer.layers.8.input_layernorm.weight', 'transformer.layers.13.attention.rotary_emb.inv_freq', 'transformer.layers.10.attention.rotary_emb.inv_freq', 'transformer.layers.24.mlp.dense_h_to_4h.bias', 'transformer.layers.21.input_layernorm.bias', 'transformer.layers.8.post_attention_layernorm.weight', 'transformer.layers.6.input_layernorm.bias', 'transformer.layers.18.input_layernorm.weight', 'transformer.layers.9.attention.dense.weight', 'transformer.layers.4.attention.query_key_value.weight', 'transformer.layers.19.mlp.dense_h_to_4h.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The dtype of attention mask (torch.int64) is not bool

### Steps To Reproduce

微调的时候参数用的是：
PRE_SEQ_LEN=8 # 128
LR=1e-2 #2e-2

CUDA_VISIBLE_DEVICES=1 python3.10 main.py \
    --do_train \
    --train_file AQSH/train.json \
    --validation_file AQSH/dev.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm-6b \
    --output_dir output/AQSH-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 512 \
    --max_target_length 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
#    --quantization_bit 4
/

### Environment

```markdown
- OS:Linux
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by runwean** [comment]
我也是遇到了一样的错误
