### ISSUE TITLE
如何開放到公網ip?

### ISSUE THREAD

**Issue by Dfaker-HK** [THUDM/ChatGLM-6B#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

現在在啟動的時候, 他只會顯示 cannot create share link, 並且只能從localhost 訪問, 有辦法可以開放到其他ip嗎?

### Steps To Reproduce

simply run web_demo.py

### Environment

```markdown
- OS: Windows 11
- Python: 3.3
- Transformers: 4.28
- PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by Xiaobin2333** [comment]
你可以对web_demo.py进行以下修改：
`#demo.queue().launch(share=True)
demo.queue().launch(share=True, server_name="0.0.0.0")
#如果需要修改默认端口还可以添加server_port=xxx`

**Comment by Dfaker-HK** [comment]
it worked, thank you very much!

**Comment by Dfaker-HK** [comment]
it worked, thank you very much!
