### ISSUE TITLE
[Help] 请问chatGLM是否可以对同一问句产生多个不同答复，调节num_beams没有效果

### ISSUE THREAD

**Issue by vandarkfan** [THUDM/ChatGLM-6B#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

调用model.chat时，加入参数num_beams无效果，进入model_chatglm.py后发现1285行：
outputs = self.generate(**inputs, **gen_kwargs)
outputs只会生成一个回答

### Steps To Reproduce

代码基本完全为示例：
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

response, history = model.chat(tokenizer, "迪士尼的电影在哪些国家播出过", history=history, num_beams=10)
print(response)

仅仅在倒数第二行改动了num_beams=10

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.28.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by dayL-W** [comment]
大佬，一样的问题，你解决了吗

**Comment by LiuNull** [comment]
mark，同样的问题

**Comment by Joey404** [comment]
同问😭
