### ISSUE TITLE
[Help] 多轮对话数据格式问题

### ISSUE THREAD

**Issue by luolanfeixue** [THUDM/ChatGLM-6B#828]
### Is your feature request related to a problem? Please describe.

将领域内的多轮对话数据按照官网预测的例子进行组织了数据形式，进行全参数 model finetuing。
在ChatGLM6B基础上我们仅使用领域内的多轮对话数据使用全参数 model finetuing（非ptuning方式） 提供的方式进行微调。领域内数据共23万。
我们的对话组织形式
原始多轮对话：问题1->答案1->问题2->答案2
组织训练数据为：input:【round0】\n问：问题1，答：答案1 \n 【round1】\n 问：问题2 答：target:答案2。

现在我们观察到，在领域内数据BLUE是有提升的。但在公开数据集CLUE的阅读理解任务上，会有一部分例子输出会偏向于领域内，预测的输入中加入“【round0】”后更偏向领域内数据。
      
      例子如下：
           原始数据：
                input：阅读文章，回答问题：具体文章xxxx。问题：具体问题xxx。
                label：埼玉县埼玉市南区七丁目
          ChatGLM6B：
                input：阅读文章，回答问题：具体文章xxxx。问题：具体问题xxx。
               output：武藏浦和站是一个位于埼玉县埼玉市南区七丁目，属于东日本旅客铁道（JR东日本）
          模型为我们微调模型（预测时预测input中不加入【round0】）
               input：阅读文章，回答问题：具体文章xxxx。问题：具体问题xxx。
               output：武藏浦和站是一个位于埼玉县埼玉市南区七丁目，属于东日本旅客铁道（JR东日本）埼玉县埼玉市南区七丁目，属于东日本旅客铁道
         模型同上（预测时预测input中加入【round0】）：
               input：【round0】阅读文章，回答问题：具体文章xxxx。问题：具体问题xxx。
               output：亲，请您稍等，正在查询中。谢谢理解呢。
               ps:  ”亲，请您稍等，正在查询中。谢谢理解呢。“是我们训练语料中的内容。

### Solutions

“【round0】”似乎被当成领域内数据的一个强提示了，已经被23万的领域内数据带偏。为什么这么点数据就能产生这种现象呢？想请教下训练ChatGLM6B使用的多轮对话训练数据，其中input的prompt格式是怎么样的？针对多轮对话数据都在开头加上"【round0】问：答："这种prompt吗？【

**Comment by Leawnn** [comment]
我的多轮对话效果不好....

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E5%AF%B9%E8%AF%9D%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by gg22mm** [comment]
> https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E5%AF%B9%E8%AF%9D%E6%95%B0%E6%8D%AE%E9%9B%86

想确认一下是不是这样的？
{"prompt": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "response": "用电脑能读数据流吗？水温多少", "history": []}
{"prompt": "95", "response": "上下水管温差怎么样啊？空气是不是都排干净了呢？", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "用电脑能读数据流吗？水温多少"]]}
{"prompt": "是的。上下水管都好的", "response": "那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "用电脑能读数据流吗？水温多少"], ["95", "上下水管温差怎么样啊？空气是不是都排干净了呢？"]]}

{"prompt": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线22222222", "response": "用电脑能读数据流吗？水温多少22222222", "history": []}
{"prompt": "95", "response": "上下水管温差怎么样啊？空气是不是都排干净了呢？22222222", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线22222222", "用电脑能读数据流吗？水温多少22222222"]]}
{"prompt": "是的。上下水管都好的22222222", "response": "那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！22222222", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线22222222", "用电脑能读数据流吗？水温多少22222222"], ["95", "上下水管温差怎么样啊？空气是不是都排干净了呢？22222222"]]}

{"prompt": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线33333333", "response": "用电脑能读数据流吗？水温多少33333333", "history": []}
{"prompt": "95", "response": "上下水管温差怎么样啊？空气是不是都排干净了呢？33333333", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线33333333", "用电脑能读数据流吗？水温多少33333333"]]}
{"prompt": "是的。上下水管都好的33333333", "response": "那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！33333333", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线33333333", "用电脑能读数据流吗？水温多少33333333"], ["95", "上下水管温差怎么样啊？空气是不是都排干净了呢？33333333"]]}

{"prompt": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线444444444", "response": "用电脑能读数据流吗？水温多少444444444", "history": []}
{"prompt": "95", "response": "上下水管温差怎么样啊？空气是不是都排干净了呢？444444444", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线444444444", "用电脑能读数据流吗？水温多少444444444"]]}
{"prompt": "是的。上下水管都好的444444444", "response": "那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！444444444", "history": [["长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线444444444", "用电脑能读数据流吗？水温多少444444444"], ["95", "上下水管温差怎么样啊？空气是不是都排干净了呢？444444444"]]}

**Comment by dizhenx** [comment]
history 为空，训练行吗？不搞多轮 TypeError: Couldn't cast array of type
list<item: string>
to
null 这个报错啥原因
