### ISSUE TITLE
[BUG/Help] 使用main.py进行全量微调训练后，输出一直为空

### ISSUE THREAD

**Issue by lmx760581375** [THUDM/ChatGLM-6B#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from transformers import AutoModel, AutoTokenizer
import sys

local_model_path = "my_local_checkpoint_path"
# model_path = "THUDM/chatglm-6b"  # You can modify the path for storing the local model
model = AutoModel.from_pretrained(local_model_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(local_model_path, trust_remote_code=True)
response, history = model.chat(tokenizer, "你好", history=[])
print("\033[1;36m" + "chatGLM:{}".format(response) + "\033[0m")

line = input("Human:")
while line:
    response, history = model.chat(tokenizer, str(line), history=[])
    print("\033[1;36m"+"chatGLM:{}".format(response)+"\033[0m")
    # print('\033[42m'+"chatGLM:{}"+'\033[42m'.format(response))
    line = input("Human:")
    # print(line)

我使用main.py进行了全量微调，重新加载模型发现直接不输出了，什么输出都为空。

### Steps To Reproduce

使用了main.py在我自己的数据集上进行了训练，使用trainer.save_model()保存了训练后的模型

### Environment

```markdown
- OS:centos7
- Python:3.8.13
- Transformers:4.28.0.dev0
- PyTorch: 1.13.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : 11.7
```

**Comment by duzx16** [comment]
请按照更改代码 https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2

**Comment by lmx760581375** [comment]
> 请按照更改代码 https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2

？？？我的代码已经贴了，跟你们的readme一样，注意，我是全量微调，并不是ptuning

**Comment by insist93** [comment]
遇到同样的问题，请问有解决方案吗？

**Comment by lmx760581375** [comment]
> 遇到同样的问题，请问有解决方案吗？

或许是数据的格式问题，我之后没有使用chatglm了，在用llama

**Comment by insist93** [comment]
> > 遇到同样的问题，请问有解决方案吗？
> 
> 或许是数据的格式问题，我之后没有使用chatglm了，在用llama

为什么会觉得是数据格式的问题呢？都是参考给定的数据结构，修改了数据集字段做训练的，应该没问题的

**Comment by lmx760581375** [comment]
> > > 遇到同样的问题，请问有解决方案吗？
> > 
> > 
> > 或许是数据的格式问题，我之后没有使用chatglm了，在用llama
> 
> 为什么会觉得是数据格式的问题呢？都是参考给定的数据结构，修改了数据集字段做训练的，应该没问题的

数据格式很重要， 输出空是因为模型认为你的输入以及不需要补充了，建议类似格式，让模型知道你要让他输出结果：

#Human：{你的prompt}
#Asisstant：
