### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by KKinder82** [THUDM/ChatGLM-6B#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

源代码文件：modeling_chatglm.py 的 第 711 行 有一处错误。

方法  get_position_ids(self, input_ids, mask_positions, device, use_gmasks=None):  中 下面代码

      position_ids[context_length:] = mask_positions[i] 

   应该改为：
       position_ids[i, context_length:] = mask_positions[i] 。

### Steps To Reproduce

无

### Environment

```markdown
- OS: Windows11
- Python: 3.10 
- Transformers: 4.27.1
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
感谢指出，已经修复了。不过这块的代码实际并不会执行。
