### ISSUE TITLE
[BUG/Help] p-tuning如何使用多卡进行微调呢？

### ISSUE THREAD

**Issue by tykuyh** [THUDM/ChatGLM-6B#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

readme里只有多卡部署的方法，想咨询一下如何进行多卡微调？
当前单卡微调速度非常之慢，仅50条数据就需要4小时+。如果使用多卡微调速度是否能够上升呢？

### Steps To Reproduce

单卡微调可以成功，但是耗时很长。

### Environment

```markdown
- OS:EulorOS
- Python:3.10
- Transformers:4.26.1
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by tykuyh** [comment]
Transformers 是 4.27.1
多卡部署也失败了，直接按照readme中的操作，报错：

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

**Comment by duzx16** [comment]
修改脚本里的 `CUDA_VISIBLE_DEVICES` 到你想要用的GPU编号（比如 `0,1,2,3`）即可

**Comment by duzx16** [comment]
> Transformers 是 4.27.1 多卡部署也失败了，直接按照readme中的操作，报错：
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

你运行的是哪个模型？

**Comment by tykuyh** [comment]
> > Transformers 是 4.27.1 多卡部署也失败了，直接按照readme中的操作，报错：
> > RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)
> 
> 你运行的是哪个模型？

运行的是非量化的14GB左右的模型，跑的api.py脚本。
也没有改相关脚本和代码，直接跑是正常的，但是在脚本里加上from utils import load_model_on_gpus，然后把
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
改成model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=2).half().cuda()后再运行，报了这个错。

**Comment by tykuyh** [comment]
> 修改脚本里的 `CUDA_VISIBLE_DEVICES` 到你想要用的GPU编号（比如 `0,1,2,3`）即可

是可行的，感谢！
但是有个小疑惑，似乎不能指定 4，而且最多指定四块， 触发其中任意一个情况都会报 ValueError: 130004 is not in list。最终尝试了指定1,2,3,5，是正常的。

完整报错：
ValueError: Caught ValueError in replica 4 on device 4.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/chatGLM/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/chatGLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/chatGLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 936, in forward
    attention_mask = self.get_masks(
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 682, in get_masks
    context_lengths = [seq.tolist().index(self.config.bos_token_id) for seq in input_ids]
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 682, in <listcomp>
    context_lengths = [seq.tolist().index(self.config.bos_token_id) for seq in input_ids]
ValueError: 130004 is not in list

**Comment by sxk000** [comment]
> 修改脚本里的 `CUDA_VISIBLE_DEVICES` 到你想要用的GPU编号（比如 `0,1,2,3`）即可

1，这样是每张卡上 都加载一遍模型，然后之间相互通信，会出现2两卡训练的速度比一张卡慢的情况。

2，如果每张都加载不下一个完整的模型，比如100张11G的显卡，这种情况还会报现存不足的问题，而不能多卡训练，虽然总显存有1100G，但是也无济于事。

3，能不能把模型均匀加载一次到多个显卡上，然后多张卡一起训练一个模型呢？

**Comment by HelixPark** [comment]
我按照如下修改ptuning/train.sh里的0,1,2，就一直报OOM，不过单卡能跑。

PRE_SEQ_LEN=128
LR=2e-2

CUDA_VISIBLE_DEVICES=0,1,2 python3 main.py \
    --do_train \
    --train_file data/PanguData/train.json \
    --validation_file data/PanguData/dev.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path /home/llm_files/chatglm-6b-v1_1 \
    --output_dir output/pangu-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 128 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 200 \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \

**Comment by summer-silence** [comment]
@duzx16 大佬，请问为什么我这样设置多卡微调之后，资源的利用和耗时要远远大于单卡微调时候的状态呢

**Comment by VictoryBlue** [comment]
> @wutingjun CUDA_VISIBLE_DEVICES=0,1 感觉这样去设置多卡是有存在问题的，我这样设置多卡的时候感觉比单卡的时间要多很多，请问这个问题，您解决了吗

我和你遇到了一样的问题，单卡训练1小时半就够了，8张卡跑最简单的demo竟然跑了2天，而且微调效果极差，甚至不如单卡

**Comment by summer-silence** [comment]
@VictoryBlue 请问这个问题解决了吗？

**Comment by coolge** [comment]
> > @wutingjun CUDA_VISIBLE_DEVICES=0,1 感觉这样去设置多卡是有存在问题的，我这样设置多卡的时候感觉比单卡的时间要多很多，请问这个问题，您解决了吗
> 
> 我和你遇到了一样的问题，单卡训练1小时半就够了，8张卡跑最简单的demo竟然跑了2天，而且微调效果极差，甚至不如单卡

我也遇到了多卡训练速度很慢且远低于单卡的情况
