### ISSUE TITLE
[BUG/Help] <title> 全参数finetune需要占用基础显存？

### ISSUE THREAD

**Issue by zwkkk** [THUDM/ChatGLM-6B#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1 batch，A100 80G显存装不下

### Steps To Reproduce

NONE

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
因为Adam optimizer的特点，全参数微调需要的显存大小是 fp16参数大小 + fp32参数大小* 3，应该已经超过了 80GB 显存。你可以在 deepspeed.json 里的 `zero_optimization` 部分增加
```
"offload_optimizer": {
            "device": "cpu",
        }
```

**Comment by ylhou** [comment]
@zwkkk 请问后来1 batch，A100 80G显存 开zero offload训练成功了吗

**Comment by ChenBinfighting1** [comment]
用int4或者int8 模型微调应该可以，我3090 24G int4 batch_size=3刚好能cover住
