### ISSUE TITLE
[BUG/Help] <为什么本地运行网页版的没有报错，但是浏览器>

### ISSUE THREAD

**Issue by GoodmorningChris** [THUDM/ChatGLM-6B#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/58820529/235048897-f3666d03-d2e3-490c-98da-8b5d63d03919.png)
![image](https://user-images.githubusercontent.com/58820529/235048898-9cf86f51-645a-4051-b6ef-4746926c93fd.png)

### Steps To Reproduce

![~`S`TNDF$JV%_4WH7(X6MEI](https://user-images.githubusercontent.com/58820529/235048575-3b98e31e-1cb1-4136-80e6-25581194680c.png)
![3G}POZ$DM%R}HZ10GJ4C3TB](https://user-images.githubusercontent.com/58820529/235048580-5b044558-5da3-4a3b-86ee-6bd1a03faa23.png)
网页没有结果

### Environment

```markdown
- OS:Linux
- Python:3.10
- A100
- 带宽：200M
- 硬盘：1T
```

**Comment by MiXianif** [comment]
你可以把  share参数设置为True，会生成一个公共链接，你试试

**Comment by GoodmorningChris** [comment]
> 你可以把 share参数设置为True，会生成一个公共链接，你试试

我试了！可以的！忘记回复了！谢谢你！感谢！！
