### ISSUE TITLE
[BUG/Help] 网页ws里有报错信息，不展示返回的数据

### ISSUE THREAD

**Issue by szpnygo** [THUDM/ChatGLM-6B#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

终端没有任何报错信息，只有ws返回了一句
Expecting value: line 1 column 1 (char 0)

### Steps To Reproduce

运行web版

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请提供报错截图和你的环境信息

**Comment by szpnygo** [comment]
![WechatIMG579](https://user-images.githubusercontent.com/3326788/225494813-e0ba74cd-8a44-4cde-828f-67fa57db1699.jpeg)

**Comment by szpnygo** [comment]
python版本3.10.8
torch版本'2.0.0+cu118'
gradio版本3.21.0
transformers版本4.26.1

cli命令行运行是没有问题的，表现非常好

**Comment by fichas** [comment]
@szpnygo 我尝试

**Comment by fichas** [comment]
> [gradio-app/gradio#3330](https://github.com/gradio-app/gradio/issues/3330)
> 
> 找到原因了，居然是因为开了代理。我关闭代理后，果然可以了

环境可能不一样 我这个是在同网段下的开发机上 并不是local环境

**Comment by LikaiLiu-lh** [comment]
> 

找了半天更改localURL的方式，感谢，it works!
