### ISSUE TITLE
[Help] </s>不是特殊token为什么写在tokenizer_config.json？

### ISSUE THREAD

**Issue by IamRoBota** [THUDM/ChatGLM-6B#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.模型文件tokenizer_config.json中写了 "end_token": "<\/s>"
![Screenshot 2023-04-28 at 16 44 40](https://user-images.githubusercontent.com/15852871/235100333-75ac6fcd-4e84-4a96-b067-e6d6f43cd7a1.png)

2.调用tokenizer切</s>会被切碎
<img width="115" alt="Screenshot 2023-04-28 at 16 45 35" src="https://user-images.githubusercontent.com/15852871/235100536-d440310d-4444-4459-83d8-42bdd69d807d.png">
<img width="339" alt="Screenshot 2023-04-28 at 16 45 48" src="https://user-images.githubusercontent.com/15852871/235100592-beecb4d2-947d-45e3-8076-2e732b1be844.png">

3.查看了tokenizer中的特殊token，发现居然没有"<\/s>" ????
<img width="637" alt="Screenshot 2023-04-28 at 16 46 39" src="https://user-images.githubusercontent.com/15852871/235100780-06beeb88-31d5-4c15-87b7-1987cdc05ef1.png">

### Steps To Reproduce

Too simple to reproduce

### Environment

```markdown
Environment unrelated
```

**Comment by IamRoBota** [comment]
2. 如果需要一个特殊token来分割开上下两句，应该用哪个？？

感谢🙏

**Comment by duzx16** [comment]
用 `\n` 就可以。

**Comment by IamRoBota** [comment]
> 用 `\n` 就可以。

换行符已经有其他用途了  怕给模型引入歧义

**Comment by IamRoBota** [comment]
@duzx16 
1.换行符已经有其他用途了 怕给模型引入歧义，还能用哪个呢？
2.<\/s>不是特殊token 写在tokenizer_config.json的作用是？
谢谢

**Comment by IamRoBota** [comment]
> 用 `\n` 就可以。

@duzx16
1.换行符已经有其他用途了 怕给模型引入歧义，还能用哪个呢？
2.</s>不是特殊token 写在tokenizer_config.json的作用是？
谢谢

**Comment by GeekDream-x** [comment]
> > 用 `\n` 就可以。
> 
> @duzx16 1.换行符已经有其他用途了 怕给模型引入歧义，还能用哪个呢？ 2.</s>不是特殊token 写在tokenizer_config.json的作用是？ 谢谢

@duzx16

**Comment by IamRoBota** [comment]
> > 用 `\n` 就可以。
> 
> @duzx16 1.换行符已经有其他用途了 怕给模型引入歧义，还能用哪个呢？ 2.</s>不是特殊token 写在tokenizer_config.json的作用是？ 谢谢

@duzx16
