### ISSUE TITLE
[BUG/Help] <显示keyerror 'content' >

### ISSUE THREAD

**Issue by lanchongdashygo** [THUDM/ChatGLM-6B#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行sh train.sh时出现以下错误：
04/29/2023 15:41:21 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
04/29/2023 15:41:21 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output/adgen-chatglm-6b-pt-128-2e-2/runs/Apr29_15-41-21_autodl-container-2888119d3c-1017b742,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/adgen-chatglm-6b-pt-128-2e-2,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=output/adgen-chatglm-6b-pt-128-2e-2,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
04/29/2023 15:41:23 - WARNING - datasets.builder - Using custom data configuration default-8b471e77a485c86e
04/29/2023 15:41:23 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-8b471e77a485c86e/0.0.0/e6070c77f18f01a5ad4551a8b7edfba20b8438b7cad4d94e6ad9378022ce4aab)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 720.55it/s]
[INFO|configuration_utils.py:666] 2023-04-29 15:41:23,041 >> loading configuration file /root/autodl-tmp/modal/chatglm-6b/config.json
[WARNING|configuration_auto.py:905] 2023-04-29 15:41:23,041 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:666] 2023-04-29 15:41:23,090 >> loading configuration file /root/autodl-tmp/modal/chatglm-6b/config.json
[INFO|configuration_utils.py:720] 2023-04-29 15:41:23,094 >> Model config ChatGLMConfig {
  "_name_or_path": "/root/autodl-tmp/modal/chatglm-6b",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.27.1",
  "use_cache": true,
  "vocab_size": 130528
}

[WARNING|tokenization_auto.py:652] 2023-04-29 15:41:23,095 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1800] 2023-04-29 15:41:23,144 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1800] 2023-04-29 15:41:23,144 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-04-29 15:41:23,144 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-04-29 15:41:23,144 >> loading file tokenizer_config.json
[WARNING|auto_factory.py:456] 2023-04-29 15:41:23,390 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|modeling_utils.py:2400] 2023-04-29 15:41:23,491 >> loading weights file /root/autodl-tmp/modal/chatglm-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:575] 2023-04-29 15:41:23,493 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.27.1"
}

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.22s/it]
[INFO|modeling_utils.py:3032] 2023-04-29 15:41:33,544 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3034] 2023-04-29 15:41:33,545 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /root/autodl-tmp/modal/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2690] 2023-04-29 15:41:33,597 >> Generation config file not found, using a generation config created from the model config.
Running tokenizer on train dataset:   0%|                                                                          | 0/16 [00:00<?, ?ba/s]
Traceback (most recent call last):
  File "main.py", line 431, in <module>
    main()
  File "main.py", line 249, in main
    train_dataset = train_dataset.map(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2585, in map
    return self._map_single(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 585, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 552, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/fingerprint.py", line 480, in wrapper
    out = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2982, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2865, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2545, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "main.py", line 195, in preprocess_function_train
    for i in range(len(examples[prompt_column])):
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 149, in __getitem__
    values = super().__getitem__(key)
  File "/root/miniconda3/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: 'content'

### Expected Behavior

no

### Steps To Reproduce

sh train.sh
附上train.sh文件内容
PRE_SEQ_LEN=128
LR=2e-2

CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file ./train.json \
    --validation_file ./dev.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path /root/autodl-tmp/modal/chatglm-6b \
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.11.0+cu113
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.3
requirements里的依赖全部安装完成
```

### Anything else?

no

**Comment by lanchongdashygo** [comment]
请问这是因为自己给定的数据集的格式出错了吗？json文件需要怎么样的格式呢？

**Comment by lanchongdashygo** [comment]
是数据名称没改对，已解决

**Comment by dizhenx** [comment]
> 

我现在也遇到了这个问题，怎么解决？KeyError: 'content'
