### ISSUE TITLE
[BUG/Help] 在有GPU的情况下，推理过程消耗CPU，并且只用CPU的1核

### ISSUE THREAD

**Issue by ljwps** [THUDM/ChatGLM-6B#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用工程中的 api.py启动。
进行推理，推理内容为：
{"prompt": "帮我写一段java招聘信息，要求2年工作经验，会国产数据库，会rabbitmq，能需求分析", "history": []}

返回内容大概有240～270字不等。

用jmeter进行压力测试，结果为如下图，10个并发下吞吐量4.5个每分钟
![image](https://user-images.githubusercontent.com/18318466/235291275-124736ec-4a12-4b0c-a6fa-ad30d5fc28db.png)
过程中，发现有1核CPU使用率为100%，GPU使用率为44%，也就是CPU只使用了1核心，导致不能处理更多的请求，GPU并不能跑满。
![image](https://user-images.githubusercontent.com/18318466/235291431-fc9866ea-ea0a-4ebc-8a96-db1339fef12a.png)
![image](https://user-images.githubusercontent.com/18318466/235291453-1183ca1a-bb5d-482d-b218-d607e93e6d6a.png)

使用postman对项目进行debug，发现在下图代码行处理速度挺慢，并且这行代码执行时CPU中1核跑满，GPU40%～50%
![image](https://user-images.githubusercontent.com/18318466/235292416-15f9f4fc-f56b-4ea2-808e-a52d26b2a024.png)

### Expected Behavior

glm在推理时一定要用cpu么，推理不应该都在GPU上跑的么？如何能把CPU多核心用起来，不然都挤在一个核心上，拖慢推理速度。
还是说 有什么设置不对，导致了用到了CPU，在跑之前代码没动过。

### Steps To Reproduce

用jmeter进行压力测试，结果为如下图，10个并发下吞吐量4.5个每分钟
![image](https://user-images.githubusercontent.com/18318466/235291275-124736ec-4a12-4b0c-a6fa-ad30d5fc28db.png)
过程中，发现有1核CPU使用率为100%，GPU使用率为44%，也就是CPU只使用了1核心，导致不能处理更多的请求，GPU并不能跑满。
![image](https://user-images.githubusercontent.com/18318466/235291431-fc9866ea-ea0a-4ebc-8a96-db1339fef12a.png)
![image](https://user-images.githubusercontent.com/18318466/235291453-1183ca1a-bb5d-482d-b218-d607e93e6d6a.png)

使用postman对项目进行debug，发现在下图代码行处理速度挺慢，并且这行代码执行时CPU中1核跑满，GPU40%～50%
![image](https://user-images.githubusercontent.com/18318466/235292416-15f9f4fc-f56b-4ea2-808e-a52d26b2a024.png)

### Environment

```markdown
- OS: ubuntu 22
- Python: 3.8.16
- Transformers: 4.27.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : 是
```

**Comment by duzx16** [comment]
推理基本用不到CPU。只是 CPU 在等待 GPU 计算完成的时候也是显示占用率 100%。

**Comment by ljwps** [comment]
> 推理基本用不到CPU。只是 CPU 在等待 GPU 计算完成的时候也是显示占用率 100%。

一次提问gpu消耗40~50%的样子，在并发测试的时候，gpu并不能跑满，GLM只能单线程处理请求么？

**Comment by ljwps** [comment]
> 推理基本用不到CPU。只是 CPU 在等待 GPU 计算完成的时候也是显示占用率 100%。


一次提问gpu消耗40~50%的样子，在并发测试的时候，gpu并不能跑满，照道理2个并发GPU应该也能到80~100的样子，GLM只能单线程处理请求么？

**Comment by ljwps** [comment]
> 推理基本用不到CPU。只是 CPU 在等待 GPU 计算完成的时候也是显示占用率 100%。

一次提问gpu消耗40~50%的样子，在并发测试的时候，gpu并不能跑满，照道理2个并发GPU应该也能到80~100的样子，GLM只能单线程处理请求么？

**Comment by lindeer** [comment]
同求CPU多核运行的改进，一旦能充分利用CPU应用的范围和场景也能大大拓宽。或者提供模型转化成gpt格式的脚本也好:pray:

**Comment by Ha2ryZhang** [comment]
有进展吗? 并发起来就全部都慢下来了
