### ISSUE TITLE
onnx export

### ISSUE THREAD

**Issue by irasin** [THUDM/ChatGLM-6B#86]
To deploy the model with onnxruntime or trt, I want to know how can we export this pytorch model to onnx format.

BTW, since the model parameter number is 6255206400, for full float weights, the model should consume 6255206400 * 4 / 1024 / 1024 / 1024 = 23.3 GiB graphics memory. I wander why the graphics memory usage is only 12~13 GiB?

**Comment by duzx16** [comment]
I am not familiar with onnx so I cannot help.
The model only consumes 13GB graphics memory usage because it is in half float precision, not full float.

**Comment by irasin** [comment]
hi, @duzx16, thank you for your quick response~
