### ISSUE TITLE
[BUG/Help] <title>AttributeError: module 'gradio' has no attribute 'Chatbot'

### ISSUE THREAD

**Issue by zilingliyu** [THUDM/ChatGLM-6B#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "D:\IdeaProjects\ChatGLM-6B-main\web_demo.py", line 24, in <module>
    gr.Chatbot.postprocess = postprocess
AttributeError: module 'gradio' has no attribute 'Chatbot'

### Steps To Reproduce

Traceback (most recent call last):
  File "D:\IdeaProjects\ChatGLM-6B-main\web_demo.py", line 24, in <module>
    gr.Chatbot.postprocess = postprocess
AttributeError: module 'gradio' has no attribute 'Chatbot'

### Environment

```markdown
- OS:Windows10 64bit
- Python:3.10.11
- Transformers:4.27.1
- PyTorch:>=1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :CPU 32G
```

**Comment by zilingliyu** [comment]
update gradio

**Comment by nikeaddidaslining** [comment]
pip install --upgrade gradio
