### ISSUE TITLE
[Help] 请问ChatGLM的基座模型对应于GLM项目中的哪个模型呢？

### ISSUE THREAD

**Issue by BrightXiaoHan** [THUDM/ChatGLM-6B#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

原始的GLM模型好像没有6B的大小
![image](https://user-images.githubusercontent.com/25839309/225509682-301aa2b8-ada9-4172-88b3-049d69a0e6e3.png)
请问ChatGLM是以哪个模型作为基座训练出来的呢？

### Expected Behavior

基座模型是否已经开源呢？

**Comment by Sengxian** [comment]
ChatGLM-6B 的基座是我们充分吸取了 GLM-130B 的训练经验训练出来的新基座模型 GLM-6B，目前暂时没有开源计划。您可使用 ChatGLM-6B 进行微调并将其用于学术研究及（非商用）用途。

**Comment by Data2Me** [comment]
> 

怎么微调呢

**Comment by shangzhensen** [comment]
+1

**Comment by iseesaw** [comment]
> ChatGLM-6B 的基座是我们吸取了 GLM-130B 的经验训练出来的新基座模型 GLM-6B，一些细节在[博客](https://chatglm.cn/blog)中有所介绍，目前暂时没有开源计划。您可使用 ChatGLM-6B 进行微调并将其用于学术研究及（非商用）用途。

请问是基于 GLM-130B 还是 ChatGLM-130B 蒸馏（或吸取经验）呢？

**Comment by Sengxian** [comment]
> > ChatGLM-6B 的基座是我们吸取了 GLM-130B 的经验训练出来的新基座模型 GLM-6B，一些细节在[博客](https://chatglm.cn/blog)中有所介绍，目前暂时没有开源计划。您可使用 ChatGLM-6B 进行微调并将其用于学术研究及（非商用）用途。
> 
> 请问是基于 GLM-130B 还是 ChatGLM-130B 蒸馏（或吸取经验）呢？

重新训练
