### ISSUE TITLE
[Help] ptuing的数据集，key必须是content和summary么？还是可以随便自定义？

### ISSUE THREAD

**Issue by louishust** [THUDM/ChatGLM-6B#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

None

### Steps To Reproduce

None

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
可以在 `train.sh` 里修改 `prompt_column` 和 `response_column`

**Comment by Crazycatter** [comment]
> 可以在 `train.sh` 里修改 `prompt_column` 和 `response_column`

能增加其他column么
