### ISSUE TITLE
'gcc' 不是内部或外部命令，也不是可运行的程序 或批处理文件

### ISSUE THREAD

**Issue by ccartermices** [THUDM/ChatGLM-6B#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to run chatGLM-6B-int4 on my machine but it had a bug.
RuntimeError: [enforce fail at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 100663296 bytes.

I change part of the code in web_demo.py:
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("E:\ChatGLM-6B-main\models\chatglm_int4", trust_remote_code=True).quantize(8).half().cuda()
model = model.eval()

### Steps To Reproduce

Run"python web_demo.py"

error:
(E:\minconda_extra_env_folder\ChatGLM6B) E:\ChatGLM-6B-main>python web_demo.py
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 446/446 [00:00<00:00, 157kB/s]
E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\cc\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)enization_chatglm.py: 100%|████████████████████████████████████████| 16.7k/16.7k [00:00<00:00, 1.07MB/s]
Downloading ice_text.model: 100%|██████████████████████████████████████████████████| 2.71M/2.71M [00:03<00:00, 846kB/s]
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.c -shared -o C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels.c -shared -o C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed.
Failed to load kernel.
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
No compiled kernel found.
Compiling kernels : C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.c -shared -o C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels.c -shared -o C:\Users\cc\.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization_kernels.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed.
Failed to load kernel.
Traceback (most recent call last):
  File "E:\ChatGLM-6B-main\web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("E:\ChatGLM-6B-main\models\chatglm_int4", trust_remote_code=True).quantize(8).half().cuda()
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 1430, in quantize
    load_cpu_kernel(**kwargs)
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\quantization.py", line 430, in load_cpu_kernel
    assert cpu_kernels.load
AssertionError

### Environment

```markdown
- OS:win10(32GB memory + 1080ti GPU 11 GB)
- Python:3.9.0
- Transformers:4.27.1
- PyTorch:2
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :cu118
```

**Comment by invado** [comment]
安装个gcc呗。readme中不有嘛https://jmeubank.github.io/tdm-gcc/
