### ISSUE TITLE
[Help] <How to continue pre-training and fine-tuning？>

### ISSUE THREAD

**Issue by acadaiaca** [THUDM/ChatGLM-6B#91]
### ChatGLM how to continue pre-training and fine-tuning？
This is the same question in this issue:
https://github.com/THUDM/ChatGLM-6B/issues/3
But after reading these information I still don't know how to use HF trainer to train or finetune ChatGLM-6B. 

Has anyone successfully implemented it?

**Comment by acadaiaca** [comment]
能否用GLM的pretrain代码和finetune代码来做CahtGLM的continue pretrain和finetune？
https://github.com/THUDM/GLM/blob/main/pretrain_glm.py
https://github.com/THUDM/GLM/blob/main/finetune_glm.py

**Comment by duzx16** [comment]
Already supported now.

**Comment by cxjtju** [comment]
> 哪位同学做过 ，求代码

请问同学找到解决办法了吗
