### ISSUE TITLE
[Feature] <title> Question about pretrain obejct of Chatglm-6b

### ISSUE THREAD

**Issue by DSXiangLi** [THUDM/ChatGLM-6B#925]
### Is your feature request related to a problem? Please describe.

We would like to do continue pretrain on Chatglm-6B model, I was wondering whether the Chatglm-6b has the same pretrain object as in the GLM project. Since they have quite different context length. Could you please help me with this? 

### Solutions

Provide pretrain code of chatglm-6b if possible

**Comment by duzx16** [comment]
Yes. The objective is the same as GLM.
