### ISSUE TITLE
多卡分布式部署推理

### ISSUE THREAD

**Issue by ZTurboX** [THUDM/ChatGLM-6B#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

api.py中如何多卡分布式部署推理

### Steps To Reproduce

api.py中如何多卡分布式部署推理

### Environment

```markdown
- OS:centos
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
是一个模型部署在多卡上吗？请参考 https://github.com/THUDM/ChatGLM-6B#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2
