### ISSUE TITLE
大佬们请问下使用pt微调后，打开窗口前两个问题回答比较正常，之后就开始胡说了，这是为啥

### ISSUE THREAD

**Issue by PopRangR** [THUDM/ChatGLM-6B#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

大佬们请问下使用pt微调后，打开窗口前两个问题回答比较正常，之后就开始胡说了，这是为啥

### Steps To Reproduce

大佬们请问下使用pt微调后，打开窗口前两个问题回答比较正常，之后就开始胡说了，这是为啥

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
因为你微调的时候数据是没有对话历史的。
