### ISSUE TITLE
加载模型错误

### ISSUE THREAD

**Issue by shirwy** [THUDM/ChatGLM-6B#935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

model = AutoModel.from_pretrained("./chatglm-6b", trust_remote_code=True).half().cuda()
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-31-3ad3867071ee> in <module>
----> 1 model = AutoModel.from_pretrained("./chatglm-6b", trust_remote_code=True).half().cuda()

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    444                 trust_remote_code=trust_remote_code,
    445                 **hub_kwargs,
--> 446                 **kwargs_copy,
    447             )
    448         if hasattr(config, "auto_map") and cls.__name__ in config.auto_map:

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    913             )
    914             config_class.register_for_auto_class()
--> 915             return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
    916         elif "model_type" in config_dict:
    917             config_class = CONFIG_MAPPING[config_dict["model_type"]]

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/transformers/configuration_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    551             )
    552 
--> 553         return cls.from_dict(config_dict, **kwargs)
    554 
    555     @classmethod

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/transformers/configuration_utils.py in from_dict(cls, config_dict, **kwargs)
    694             kwargs["_commit_hash"] = config_dict["_commit_hash"]
    695 
--> 696         config = cls(**config_dict)
    697 
    698         if hasattr(config, "pruned_heads"):

~/.cache/huggingface/modules/transformers_modules/chatglm-6b/configuration_chatglm.py in __init__(self, vocab_size, hidden_size, num_layers, num_attention_heads, layernorm_epsilon, use_cache, bos_token_id, eos_token_id, mask_token_id, gmask_token_id, pad_token_id, max_sequence_length, inner_hidden_size, position_encoding_2d, quantization_bit, pre_seq_len, prefix_projection, **kwargs)
    100             bos_token_id=bos_token_id,
    101             eos_token_id=eos_token_id,
--> 102             **kwargs
    103         )

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/transformers/configuration_utils.py in __init__(self, **kwargs)
    334             # from_pretrained's torch_dtype arg convert it to an actual torch.dtype object
    335             if is_torch_available():
--> 336                 import torch
    337 
    338                 self.torch_dtype = getattr(torch, self.torch_dtype)

~/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/torch/__init__.py in <module>
    247     raise  # If __file__ is not None the cause is unknown, so just re-raise.
    248 
--> 249 for name in dir(_C):
    250     if name[0] != '_' and not name.endswith('Base'):
    251         __all__.append(name)

NameError: name '_C' is not defined

### Steps To Reproduce

model = AutoModel.from_pretrained("./chatglm-6b", trust_remote_code=True).half().cuda()

### Environment

```markdown
- Python:3.7
- Transformers:4.27.1
- PyTorch:1.8.1
```

**Comment by duzx16** [comment]
PyTorch 安装有问题。建议按照 pytorch.org 官网的说明用 conda 安装。
