### ISSUE TITLE
Deepspeed finetune需要多大的显存？

### ISSUE THREAD

**Issue by twosnowman** [THUDM/ChatGLM-6B#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

3060 12G显卡deepspeed训练时报显存不够

### Steps To Reproduce

deepspeed训练需要多大显存？

### Environment

```markdown
OS: Ubuntu 22.04
Python: 3.10
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by kjgfjlkj** [comment]
24GB batch size为1 都不够

**Comment by EeyoreLee** [comment]
Finetuning的话，混合精度训练大概需要16*6 约96GB左右的显存，通常我们采用某种peft去微调

**Comment by gawei1995** [comment]
测试 deepspeed zero2   62G /单张

**Comment by TE-Raven** [comment]
看你训练样本，调整一个参数，再搞个量化也许能成，不过12G确实有点少

**Comment by newtonysls** [comment]
> 

请问 显卡吞吐量如何 大概多少tokens/GPU/s

**Comment by gawei1995** [comment]
> 

看你显卡型号

**Comment by zhangch9** [comment]
Duplicate of [#556](https://github.com/THUDM/ChatGLM-6B/issues/556)
