### ISSUE TITLE
[Help] In linux, where is the default download model located?

### ISSUE THREAD

**Issue by CDPDisk** [THUDM/ChatGLM-6B#94]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I used web_demo.py to run it, which downloaded the model parameters using the default path. I now want to move it, where is the default path? I didn't find it in the current folder.

### Steps To Reproduce

Don't need

### Environment

```markdown
Ubuntu 18.04.6 LTS
```

**Comment by Stxr** [comment]
~/.cache/huggingface/hub/

**Comment by CDPDisk** [comment]
> 

I found it, thanks

**Comment by CDPDisk** [comment]
> ~/.cache/huggingface/hub/
I found it, thanks
