### ISSUE TITLE
[BUG/Help] LangChain 接入 ChatGLM 问题

### ISSUE THREAD

**Issue by TJJ120635** [THUDM/ChatGLM-6B#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

由于 LangChain 没有对 ChatGLM 的支持，需要自己将模型封装成LLM或者ChatModel。imClumsyPanda大佬的[langchain-ChatGLM](https://github.com/imClumsyPanda/langchain-ChatGLM) 项目使用的是自行封装CustomLLM类的方式，同时也封装了一个local_doc_qa。

我看到官方文档有对 [Hugging Face Hub](https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_hub.html) 和 [Hugging Face Local Pipelines](https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_pipelines.html) 的支持（不清楚二者区别），而且 [ChatGLM](https://huggingface.co/THUDM/chatglm-6b-int4) 也有对应的 HF 项目。
我的想法是能否让ChatGLM作为hf模型直接加载？这样就不需要自己去封装CustomLLM了。

由于对hf不了解，我不知道LangChain官方的加载方式能否兼容本地ChatGLM模型，需要求助各位

### Steps To Reproduce

无

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 2.0.0

- GPU: Nvidia Tesla P40
- Driver: 515.65.01
- CUDA: 11.7
- CuDNN: cudnn-linux-x86_64-8.9.0.131_cuda11
- CUDA Support: True
```

**Comment by codeman0987** [comment]
有人能回答一下吗

**Comment by TJJ120635** [comment]
@codeman0987 现在LangChain已经加入了ChatGLM的支持了，你可以看一下官方文档的 https://python.langchain.com/docs/integrations/llms/chatglm。
首先你需要参考ChatGLM 1/2/3的官方文档，在服务器上部署一个API服务，然后直接把API的地址，例如是http://127.0.0.1:8000，填到LangChain里。后面调用的方法就跟别的LLM一样

**Comment by codeman0987** [comment]
@TJJ120635 好的，感谢
