### ISSUE TITLE
[BUG/Help] <hf model path 加载报错>

### ISSUE THREAD

**Issue by qingyuan18** [THUDM/ChatGLM-6B#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

执行ds_train_finetuning.sh ， main.py加载Configuration报错：

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/658202d88ac4bb782b99e99ac3adff58b4d0b813/tokenization_chatglm.py'

AttributeError: module 
'transformers_modules.THUDM.chatglm-6b.658202d88ac4bb782b99e99ac3adff58b4d0b813.
tokenization_chatglm' has no attribute 'ChatGLMTokenizer'

前两天都可以跑，这是改了代码么？

### Steps To Reproduce

gitclone后直接执行ptuing目录下的ds_train_finetuning.sh

### Environment

```markdown
- OS:  Ubuntu 20.x
- Python: 3.9
- Transformers: 4.26
- PyTorch: 1.13
- CUDA Support ：True
```

**Comment by JinmingZhao** [comment]
same question

**Comment by crowningwang** [comment]
same question

**Comment by roki1031** [comment]
还没解决吗？

**Comment by qingyuan18** [comment]
已经解决了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月5日(周一) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THUDM/ChatGLM-6B] [BUG/Help] <hf model path 加载报错&gt; (Issue #948)




 
还没解决吗？

**Comment by roki1031** [comment]
> 已经解决了，谢谢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月5日(周一) 晚上6:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [THUDM/ChatGLM-6B] [BUG/Help] <hf model path 加载报错&gt; (Issue #948) 还没解决吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问怎么解决的呀，我也遇到同样问题了

**Comment by GasolSun36** [comment]
我解决了。好像是下载到cache的时候出了问题。大家直接从huggingface上面把模型下载下来，然后用模型绝对路径作为from_pretrained()的路径就好了.
