### ISSUE TITLE
Could not find module "nvcuda.dll"

### ISSUE THREAD

**Issue by lightCraft2020** [THUDM/ChatGLM-6B#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在windows系统上执行，报错：Could not find module "nvcuda.dll"，代码已经修改为：
`model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()`
使用CPU进行执行，结果还是报错，没有找到cuda 相关的dll 还需要修改哪个地方么？

### Steps To Reproduce

在windows系统上执行，报错：Could not find module "nvcuda.dll"，代码已经修改为：
`model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()`
使用CPU进行执行，结果还是报错，没有找到cuda 相关的dll 还需要修改哪个地方么？

### Environment

```markdown
- OS:
- Python: 3.8
- Transformers: 
- PyTorch:  
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False
```

**Comment by duzx16** [comment]
能提供一下截图看看具体报错是在哪一行吗

**Comment by lightCraft2020** [comment]
![cpu_bug](https://user-images.githubusercontent.com/11204164/225559649-67ae53f5-c139-4c52-9e19-40853ca88c89.png)

**Comment by duzx16** [comment]
类似于https://github.com/THUDM/ChatGLM-6B/issues/6#issuecomment-1470060041
先把仓库clone到本地再运行就可以解决这个问题。
