### ISSUE TITLE
fast transformer support for 6B model

### ISSUE THREAD

**Issue by xu78guo6** [THUDM/ChatGLM-6B#956]
### Is your feature request related to a problem? Please describe.

6B在NV卡上性能不是最佳，想了解下是否支持FT后端的运行方式？

### Solutions

130B已经提供了FT版本，基于那个版本可以微调一下跑通6B吗

**Comment by datalee** [comment]
官方大佬可以出手吗

**Comment by zhangch9** [comment]
Duplicate of [#109](https://github.com/THUDM/ChatGLM-6B/issues/109)
