### ISSUE TITLE
[BUG] 本地部署运行web版本运行报错

### ISSUE THREAD

**Issue by tddevrtx4090** [THUDM/ChatGLM-6B#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/125423618/225558084-6bace20e-d473-4297-b0b0-3761155ed02d.png)

### Steps To Reproduce

安装步骤
```shell
git clone https://github.com/THUDM/ChatGLM-6B
cd ChatGLM-6B
python3 -m venv venv
.\venv\Scripts\activate
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
pip install -r requirements.txt
pip install gradio
```

### Environment

```markdown
- OS:Windows 10 专业版
- Python:3.10.9
- Transformers:4.27.1
- PyTorch:2.0.0+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by fichas** [comment]
#105 @tddevrtx4090  可以参考这个配置一下～

**Comment by tddevrtx4090** [comment]
可以了。

> #105 @tddevrtx4090 可以参考这个配置一下～
