### ISSUE TITLE
[BUG/Help] <title>我想将GLM的模型文件转成onnx文件进行推理。结果它除了生成model.onnx 之外，还生成了了一堆相关的文件，请问这个是怎么回事？

### ISSUE THREAD

**Issue by chen1846847163** [THUDM/ChatGLM-6B#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

代码如下所示:
![image](https://user-images.githubusercontent.com/38528436/236761667-ae771160-7c51-4256-ab1c-305c2c864365.png)

理论上应该只会生成 GLM_model.onnx 文件，但实际还生成了一堆 onnx__MatMul_* , 以及transformer.layers.* 等文件，不理解为什么会生成这些文件？ 

有大佬可以帮忙解释一下吗

![image](https://user-images.githubusercontent.com/38528436/236762222-aa3b0b4b-a279-4d5b-9fad-64756209c6f7.png)

![image](https://user-images.githubusercontent.com/38528436/236762192-b6809152-3068-45fa-96f5-cc05976c3a3c.png)

### Expected Behavior

只生成一个 GLM_model.onnx 文件，没有多余文件生成

### Steps To Reproduce

1. Environment as bellow:
  - OS:
  - Python:3.9.13
  - Transformers:4.28.1
  - PyTorch:2.0.0
 2. Run code as bellow:
 

```
from transformers import AutoTokenizer, AutoModel
import torch
tokenizer = AutoTokenizer.from_pretrained("/home/pang/work/chatglm/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/home/pang/work/chatglm/chatglm-6b", trust_remote_code=True).float()

# inputs = tokenizer(["Please tell me what's your real name?","Please tell me what's your real name?"], return_tensors="pt")

model = model.eval()

inputs = tokenizer("Please tell me what's your real name?", return_tensors="pt")

output = model(input_ids=inputs.input_ids)

# print(output.logits)
output_token_ids = torch.argmax(output.logits,dim=-1)
print(output_token_ids)


torch.onnx.export(model, 
                  ({'input_ids':inputs.input_ids,'past_key_values':None}), 
                  "GLM_model.onnx", 
                  verbose=True,
                #   export_params=True,
                  input_names = ['input_ids'] , 
                  output_names = ['output'],
                    # dynamic_axes = { 'input_ids':{0: 'batch',1: 'batch'}, 'lm_logits':{0:'batch'} },
                  )

```

3. see error

### Environment

```markdown
- OS:
- Python:3.9.13
- Transformers:4.28.1
- PyTorch:2.0.0
```

### Anything else?

No

**Comment by zx2021** [comment]
在我的理解里.bin文件就像是一种压缩包，包括.onnx以及其他不常改的小文件，

**Comment by zx2021** [comment]
这是一种正常现象

**Comment by xiaogang-github** [comment]
好大哥，这个模型转换后效果咋样推理会更快吗，有没有demo分享一下

**Comment by lfcxlfcx** [comment]
> 好大哥，这个模型转换后效果咋样推理会更快吗，有没有demo分享一下

+1

**Comment by chen1846847163** [comment]
@zx2021 ok, 理解，谢谢解答。
@xiaogang-github @lfcxlfcx 转 onnx 模型是为了在 CPU，GPU 以外的平台使用，并不是为了更快的速度或更少的内存占用。

**Comment by YueGeek** [comment]
您好，请问即使是生成了很多的文件，是不是也正常可以进行推理？

**Comment by ArtyZe** [comment]
@chen1846847163 兄弟onnx模型分享一下ok吗？我的转的时候报错RuntimeError: _Map_base::at

**Comment by chen1846847163** [comment]
> @chen1846847163 兄弟onnx模型分享一下ok吗？我的转的时候报错RuntimeError: _Map_base::at
1. 文件又大又杂，上传起来比较麻烦，因此无法提供。
2. 你的问题是转换时出的问题，建议在转换过程详细分析问题所在。

**Comment by chen1846847163** [comment]
后续我不会再跟踪维护这个 issue, 各位有问题请在官方 issue list 中新开一个 issue~

**Comment by chen1846847163** [comment]
> 您好，请问即使是生成了很多的文件，是不是也正常可以进行推理？请问您是通过什么方法进行推理的呢？

1. 可以正常推理
2. ONNXRUNTIME

**Comment by xiaogang-github** [comment]
不好意思，模型搞了一段时间不能用之后就删了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月19日 14:11 |
| 收件人 | THUDM/ChatGLM-6B ***@***.***> |
| 抄送人 | xiaogang-github ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [THUDM/ChatGLM-6B] [BUG/Help] <title>我想将GLM的模型文件转成onnx文件进行推理。结果它除了生成model.onnx 之外，还生成了了一堆相关的文件，请问这个是怎么回事？ (Issue #964) |

后续我不会再跟踪维护这个 issue, 各位有问题请在官方 issue list 中新开一个 issue~

**Comment by Franklinlifangcheng** [comment]
请问大佬如何实现将微调后的chatglm模型转换成onnx模型啊
