### ISSUE TITLE
多轮对话微调后的checkpoint

### ISSUE THREAD

**Issue by Godlikemandyy** [THUDM/ChatGLM-6B#966]
### Is your feature request related to a problem? Please describe.

想了解一下多轮对话微调后如何用训练后的checkpoint呢

### Solutions

微调使用的是ptuning下的train_chat.sh;
能不能给出一个加载训练后的示例

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/web_demo.sh
