### ISSUE TITLE
[Help] <使用DeepSpeed的全微调出现线程冲突，导致FileNotFoundError>

### ISSUE THREAD

**Issue by Sparklexs** [THUDM/ChatGLM-6B#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在四卡的物理机和Slurm上（Sbatch --gpus=4 的方式提交作业）都尝试使用repo里的`ds_train_finetune.sh`样例测试DeepSpeed的并行效果，但是发现GPU数量超过1个以后，就会在输出中出现FileNotFoundError，我发现是执行代码`AutoTokenizer.from_pretrained()`和`AutoModel.from_pretrained()`时无法读取缓存中的模型定义python文件（虽然我指定的是本地路径，但是这两个方法还是从缓存中寻找模型的class文件），比如
![image](https://user-images.githubusercontent.com/8364759/236809048-b8b55da4-db21-40d3-87db-af68862cdc93.png)
模型的配置文件确实是在缓存目录下的，经过测试排查我发现是DeepSpeed开启了num_gpus个线程同时调用main.py，这就导致了同时读取缓存的py文件时线程冲突，因为1个GPU从不报错，2个GPU有一定概率不报错，3个以上就肯定会报错。
这个问题在物理机上还好，虽然报错，DeepSpeed并不会主动结束进程，当一个线程读取完文件后，载入模型到四个GPU core上就没事了。但是在基于slurm的云服务器上就麻烦了，slurm会直接关闭进程，导致程序退出。
我找了很久，并没有找到任何一个前例报过线程冲突的bug，包括我们自己使用DeepSpeed微调其他模型也没有遇到过，请问大家有没有在multiGPU的情况下遇到DeepSpeed的FileNotFoundError？

### Steps To Reproduce

这是在slurm下使用sbatch的脚本，相比于原来的`ds_train_finetune.sh`并未做任何修改，无非是尝试过修改GPU的数量验证线程问题
![image](https://user-images.githubusercontent.com/8364759/236816940-0f9352df-da90-4f8e-9896-e8d03b9f1c49.png)

### Environment

```markdown
- OS: CentOS 7
- Python: 3.9.7
- Transformers:4.27.1
- PyTorch: 1.13.1+cu117
- deepspeed: 0.8.1
- CUDA Support: True
```

**Comment by Sparklexs** [comment]
发现是transformer 4.27.1的bug，多进程读取cache文件load class会导致抢占进程，目前已经在Apr.4的版本中已经更新移除了该问题，安装尽量使用在此之后的版本，避免DeepSpeed多节点多GPU时报错。

**Comment by immortal5655** [comment]
> 发现



> 发现是transformer 4.27.1的bug，多进程读取cache文件load class会导致抢占进程，目前已经在Apr.4的版本中已经更新移除了该问题，安装尽量使用在此之后的版本，避免DeepSpeed多节点多GPU时报错。

请问能看一下您的deepspeed以及transformer版本吗

**Comment by jyC23333** [comment]
该问题现在仍然存在，当我在8个节点，每个节点8块卡的集群上训练时，该问题基本是必现的。
请问现在发现更好的解决方案吗？
@Sparklexs
