### ISSUE TITLE
running on ubuntu python3

### ISSUE THREAD

**Issue by haha517** [THUDM/ChatGLM-6B#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  62%|██████████████████████████████                  | 5/8 [00:10<00:06,  2.22s/it]Killed

### Steps To Reproduce

python3 web_demo.py  
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  62%|██████████████████████████████                  | 5/8 [00:10<00:06,  2.22s/it]Killed

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by haha517** [comment]
use a 1080ti GPU,16G memory

**Comment by yaleimeng** [comment]
请对模型进行量化再加载。不量化的话初始占用13GB左右【*.bin模型总大小】，后续可以达到18GB显存。显然你的显存不够。
参考 #39

**Comment by makc-321** [comment]
请问你的问题解决了吗  留个联系方式交流下？
